### ISSUE TITLE
Create Action for adding new users

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#100]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-c8f35a766750cd5bfc49639f3d29cc57d291d7298a4282d03cc68ca647c48e0b.png)

It use de service in : /marlo-web/createUser.do

**Comment by HermesJim** [comment]
Person in charge was on holidays. We will talk whit him this week.

**Comment by htobon** [comment]
We are waiting for the new version of the Authentication library developed by IT.

**Comment by htobon** [comment]
Authentication library was delivered today in the morning.
