### ISSUE TITLE
Deadlocks are occurring when navigating to the project list page

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1006]
Hi Hector and co.

I am getting the following exception dumped to Standard Error console when navigating to the project list page:

pr 21, 2017 3:00:46 PM com.mchange.v2.async.ThreadPoolAsynchronousRunner$DeadlockDetector run
WARNING: com.mchange.v2.async.ThreadPoolAsynchronousRunner$DeadlockDetector@2166564c -- APPARENT DEADLOCK!!! Creating emergency threads for unassigned pending tasks!
Apr 21, 2017 3:00:46 PM com.mchange.v2.async.ThreadPoolAsynchronousRunner$DeadlockDetector run
WARNING: com.mchange.v2.async.ThreadPoolAsynchronousRunner$DeadlockDetector@2166564c -- APPARENT DEADLOCK!!! Complete Status: 
	Managed Threads: 3
	Active Threads: 3
	Active Tasks: 
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@51f9e1f8 (com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#2)
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@6859db64 (com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#1)
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@6f3687ea (com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#0)
	Pending Tasks: 
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@4488b150
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@5a606e18
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@7c441ccb
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@2796dd7e
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@2695eaed
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@7fdc5089
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@23a2b9fd
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@324efdda
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@3b05bbfc
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@26c0ec0d
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@101bd479
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@55fe4b8d
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@43b2d095
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@6233fc6a
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@2cc55449
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@b40d07f
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@5ea39ffa
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@238ef8e8
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@25ef87cc
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@28216826
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@6abf7e97
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@3ea29290
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@672ab36f
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@446997f4
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@55330228
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@7faf3c0c
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@4dac495d
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@45f2b12b
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@89dd9ff
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@ed4cbbc
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@219d8d9a
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@71360b6b
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@17827693
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@3fa3c6f4
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@721f6dc7
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@33b35dbc
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@370193b7
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@16b467c5
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@1f4c4181
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@363bb169
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@d9c1032
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@38a3c40b
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@451ecad7
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@2ec59be4
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@43b5138e
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@6510146f
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@566b3268
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@54f389fa
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@3fb1c989
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@5a67117c
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@5510902a
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@1d646f2b
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@2c28108f
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@4ea61887
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@1f6650b9
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@21456949
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@4d05b986
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@3399f281
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@1ed79fd3
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@1452b261
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@74fbe0e4
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@88a0900
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@2a0136c5
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@2bc1485e
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@167102
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@580cba09
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@7b9808d3
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@5a3a2c46
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@6917c862
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@5476ebbb
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@6f93bf76
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@64c0e6de
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@334376fc
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@500b681c
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@22110564
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@4104e1ee
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@69d89ba4
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@6298450b
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@48084619
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@2ee5d567
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@3cd7ea4
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@235dc3cb
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@296f6137
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@29a1d790
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@4171b45e
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@c7f7420
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@5ecbda41
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@79f19b5f
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@356e037b
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@42c7af82
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@42de6c49
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@37002c2e
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@7230946e
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@df48e15
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@3cf907c6
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@a2e3d2b
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@7ccb5be4
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@5566e64e
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@21550c13
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@5a69aa77
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@7cdbdea5
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@1e6d13e6
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@17d1a1ac
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@7c8b33
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@22f0436f
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@54f496f4
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@4eb29107
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@2af3aef1
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@ab87bfb
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@7a8b1f6e
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@206b9391
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@1758354b
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@5e76e3f8
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@7ca4e737
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@2f0429
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@568b9b0a
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@3f8bdb00
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@644d1e99
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@1c3b5075
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@1662cb33
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@77504124
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@7be52081
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@3d9b6f70
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@3da010a3
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@480c3f52
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@1abffffa
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@7c39f332
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@41a1d11e
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@687e90d7
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@ddbe20d
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@3ec820e7
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@712e3f01
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@6dcae1db
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@3fd3ade5
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@40e36de0
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@403584ca
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@7acb712e
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@58554717
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@382ad90
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@6f7d6afe
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@4e1e343e
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@3c81bf15
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@2a797b38
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@2e57ce13
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@11d7b023
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@209fdc1b
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@41dec38b
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@5169aaf5
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@7d935e53
Pool thread stack traces:
	Thread[com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#2,5,main]
		java.lang.Thread.sleep(Native Method)
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask.run(BasicResourcePool.java:1805)
		com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)
	Thread[com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#1,5,main]
		java.lang.Thread.sleep(Native Method)
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask.run(BasicResourcePool.java:1805)
		com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)
	Thread[com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#0,5,main]
		java.lang.Thread.sleep(Native Method)
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask.run(BasicResourcePool.java:1805)
		com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)

This appears due to c3po connection pool settings.

I was able to fix the issue changing the c3po idle_test_period and the timeout settings to 60 seconds.  Also the max pool size is 7000 which seems rather excessive.  I think a more standard approach would be to change the max_pool_size to 100 and the min_pool_size to 10.  The number of prepared statements that are cached (i.e max_statements) could be increased from 100 to 200 (or higher if need be) if required.

I am happy to submit a fix, but will need to first familiarize myself with your git workflow.

**Comment by htobon** [comment]
Hi @Grant-Lay, are you tackling this issue in #1088?
If so, can you please move it into Milestone v4.1.7 and mark it as fixed when this is done? Otherwise, please let this issue here.

Cheers,

**Comment by Grant-Lay** [comment]
Closing this issue as this is duplicated in #1088
