### ISSUE TITLE
Project locations in funding sources

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1007]

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-34d718fad87dd3d8b9be44b12f1aa2e89d8af1924c9e5c9864b29b9d54d30fa3.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-791404e39eec3b9c5b93f2730d6a715aa6a289ef5683747d4a2c79850a334934.png)

**Comment by htobon** [comment]
@carios1usb please replace "UN standart (M49)" to "United Nations Standard (M.49)"

**Comment by htobon** [comment]
Could we split this development in two sections? 
1. Tracking locations in funding sources; and
2. Suggest locations at project level
