### ISSUE TITLE
Revamp Project partners (Institution countries and other things)

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1008]

**Comment by cgarcia9106** [comment]
![-Blank ERD & Data Flow - Page 1.jpeg](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/-Blank%20ERD%20%26%20Data%20Flow%20-%20Page%201-eefd0cf074f394c49c7f271ee9baf6c7cd856014d0a485f140ec34db7a77009a.jpeg)

**Comment by cgarcia9106** [comment]
@htobon  please check this simple MER

**Comment by cgarcia9106** [comment]
![-Blank ERD & Data Flow - Page 1 (1).jpeg](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/-Blank%20ERD%20%26%20Data%20Flow%20-%20Page%201%20%281%29-156bb67565fd42172e65d6369d86a367f02cfdcb571cb2e6a84538622a852a76.jpeg)

**Comment by sebas932** [comment]
Feedback from @hector 

 - [ ]  Add the HQ by default
 - [ ]  Change message to  "Your request was sent to the MARLO Support Team"
 - [ ]  Remove branch and city from request institution popup
 - [ ]  Fix type "recive"
 - [ ]  Use the same look and feel as request institution in request country office(s)

**Comment by htobon** [comment]
- [ ] Please remove the location from the list if it is already picked.
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-ac2bf0dc7a1fbfb768a64aacb4bca2d773200615a5d6893466da17a84a3c56c2.png)

**Comment by sebas932** [comment]
@AndresFVR please apply the changes made in the reports

**Comment by AndresFVR** [comment]
Project Full PDF Reporting and Planning:
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-8837407b56b58e788d014ebcb32d8cd7dd1b2ab24631a32a7aa74ce7ca3ddf2f.png)

**Comment by htobon** [comment]
Hello all. 
In conversation with PIM and A4NH, we are still discussing when should we release this development into the production environment. Please stay this issue here until we decide exactly a date on this week.
