### ISSUE TITLE
Tag in Funding sources of "W1W2 Cofinancing"

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1010]
Mockup: https://docs.google.com/presentation/d/1qkdWw0mSlk-KHyxxlY84BXBkVPnhZVzMAB4SXWAErxk/edit#slide=id.g22180d15b8_0_5

**Comment by htobon** [comment]
Hi guys,
As per conversation with Pascale, she agreed on the latest Mockup that we proposed.

The main purpose then **is not** to create a new funding source type, but just include a **TAG** where one will be able to indicate which W1/W2 funds are going to be used for co-financing purposes.

And, the idea is to keep the same summary reports as if a new funding-source type was created.

Please refer to the Mockup in the exchanged emails.

**Comment by sebas932** [comment]
Tag Funding Source
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-c346e87b1b9f67e02e13fb5f963a6fe80e8227275a82b3e24b37c7cf6ab77983.png)

Tag Funding Source **popup**
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-1bc432c40399f710ad3b497f4b36df38811a66ebb72e85aad6e1aff563f95355.png)

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-403d9c2926ca18affffc406e324288d8c24803660703d508da711d3b7d41d215.png)

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-8b8d13fc2be6d6c5fbab2b066d55f38d3a47031fac7144fb992ac43adbb7af9a.png)

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-f680badd7cf5f4285d1f8c62651b07d7162d47d9fb093bf9438f26379bc41c03.png)

**Comment by AndresFVR** [comment]
Budget per Partners Summary:
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-730da7cdf9dcfb6733546ee15519998ecf484bdf40a30f78db324f91e13579e1.png)
