### ISSUE TITLE
Update MARLO User manual

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1013]

**Comment by htobon** [comment]
Hi @AndresFVR, here is the new version of the file. Please also note that the name changed.

**Comment by htobon** [comment]
[Introduction_To_MARLO_v2.1.pdf](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Introduction_To_MARLO_v2.1-656de6d5ffac23ea079e8f83a3d911c0b238d709362ab1882bca217960c79570.pdf)

**Comment by htobon** [comment]
Done
