### ISSUE TITLE
Annualization proposal in MARLO

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1015]
- [x] Project description
- [x] Partners 
- [x] Contribution to Flagship Outcomes                
- [x] Impact Pathway Outcomes
- [x] Impact Pathway clusters  
- [x] Activites adjust db migration
- [x] Activities refactor model

Summaries Section:

- [x] Full PDF (Planning)
- [x] Full PDF (Reporting)
- [x] Search Terms
- [x] Contribution to Flagship Outcomes and Milestones            
- [x] Outcome Case Studies
- [x] Project Highlights  
- [x] Project Leverages

- [x] Partners 

- [x] Expected Deliverables
- [x] Reporting Deliverables

- [x] Budgets

**Comment by sebas932** [comment]
We meet and talk the annually process of MARLO

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-5d69d46926666c2c49d8704e7e755af7a595bb686c9f4ec0a3d31a8c56b30e62.png)

**Comment by cgarcia9106** [comment]
![projects_annuality.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/projects_annuality-1068c4649488d6d0b417cd98c2d41500fb56f0b0a7cbecca3902a12906140352.png)

**Comment by cgarcia9106** [comment]
@htobon

**Comment by htobon** [comment]
May you please come to my office and explain it in detail? Thank you in advance

**Comment by cgarcia9106** [comment]
Project Description
Project Partners
Impact Pathway Outcomes
Impact Patwhay Clusters

**Comment by cgarcia9106** [comment]
Now that the permissions are going to depend on the annuality, the operation with the view was very heavy for which it was decided to carry out a store procedure to be able to call these permissions: "

The call is
Call getPermissions (USER_ID);

**Comment by cgarcia9106** [comment]
-[x] Contribution to CRP Outcome 
-[x] Project Activites

**Comment by cgarcia9106** [comment]
-[x] Project Locations

**Comment by cgarcia9106** [comment]
![Data.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Data-ca41e3a7ff36e6bf67117c9ad91a246c0154953c1822e95cbf94d6367a48d24d.png)

Deliverables annuality
