### ISSUE TITLE
PROPOSAL: Develop an automated backup process that goes to dapadfs

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1016]
Currently, we are generating backups of the database every 4 hours. However they are placed in the hosting server. 
The idea here would be to also make an automated process that allows the system to send the backups to CIAT, or any other place in order to improve the security of the site.

**Comment by cgarcia9106** [comment]
https://goo.gl/YlLOAP

@htobon

**Comment by htobon** [comment]
As per our discussion, please elaborate an issue statement with at least 2 or 3 alternatives.

**Comment by HermesJim** [comment]
Update.

Work with Angela to establish and execute the MARLO backups process.
