### ISSUE TITLE
Enable Projects for Phases (Interface)

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#1023]
- Flagship leaders and project leaders can't edit the disabled projects .
- Review list of projects in summaries
- Change year en cycle

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-abe8dbf760e85f6a07c73de55b6e98117561085dbc70696fb5256ff3d7044a16.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-e81d61ceddaeca480ed0165b5c26a49553cdbfcfc3937384d18eb1383067af49.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-570806544fcc2173e0fc3d4be9e61f07e5d3827f7ad3210b949f1a192f982beb.png)

**Comment by htobon** [comment]
This will be parked until we finalize the annualization mockup.

**Comment by sebas932** [comment]
@htobon and @cgarcia9106, we need to discuss how to go forward with this issue, i think is useful for enabling projects.
BTW, its already enabled in MARLO Dev
