### ISSUE TITLE
For the W1-2 FS donor; status of funding source should not include "pipeline" or "informally confirmed

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1024]

**Comment by sebas932** [comment]
**W1W2 type selected**
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-33d8526f865e233fb0b13663bdf4141b967156101f984dcefd2f738f1bb77069.png)

**Different type to W1W2**
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-e6c37b4f542017eea4c8c885e2d1ca34831619e5e4fee23492b72baa266e3e6f.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-4b38fecf469de696a7b2a759b16a4eb8c88ca0d32c2b0482319458f6a81b4cd0.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-ef41f4a6fc6c9edaefd8aa96d3ae3dadffa4ad6c89015152f6235386de0b685c.png)

**Comment by carios1usb** [comment]
In funding sources popUp:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-1cf0ee674c3ece836ad7f755f47b218efd08193641893df80acb73b8012daddc.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-8e58b24b1d273da9bfce72b87f1f34901291da15df6a28b39aea325a415d3848.png)

**Comment by sebas932** [comment]
Thank you Carlos
