### ISSUE TITLE
Review compare history function

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1028]
- [x]  IP: Outcomes 
- [x]  IP: Cluster Of Activities
- [x]  Project: Description
- [x]  Project: Partners
- [x]  Project: Locations
- [x]  Project: Contribution to CRP Outcomes
- [x]  Project: Deliverable
- [x]  Project: Activities
- [x]  Project: Budget By Partners
- [x]  Project: Budget by CoA
- [x]  Funding Source

**Comment by sebas932** [comment]
@cgarcia9106 please check the following revisions 

**IP: Outcomes**
	Missing outcomes[0].subIdos[0].srfSubIdo.id
	Missing assumptions
**IP: Clustes of Activities**
	Missing CoA > KeyOutput > Outcome Contribution

**Project: Description**
	OK	

**Project: Partners**
	OK

**Project: Locations**
	Not implemented compare function yet

**Project: Contribution to CRP Outcomes**
	Not implemented compare function yet

**Project: Deliverable**
	Missing Funding sources
	Missing Gender dimensions and levels
	Missing Responsible and other contact persons

**Project: Activities**
	Missing new activities
	Missing new start date, end date, leader, status.
	Missing deliverables added

**Project: Budget By Partners**
	Not implemented compare function yet

**Project: Budget by CoA**
	Not implemented compare function yet

**Funding Source**
	Missing contract / proposal
	Missing Budget Amount per year
	Does not load {fundingSource} modifiedBy and ActiveSince

**Comment by htobon** [comment]
What is the status of this issue?

**Comment by htobon** [comment]
Not a priority at the moment. Since this has been done and just need a reviewing process. I'm going to close this issue.
