### ISSUE TITLE
TOTAL budget per year

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1030]
Please include a total budget per year
W1/W2 + W3 + Bilateral + Center Funds
In the "Budget by Partner" interface.

Thank you in advance

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-dc3e973075cb6f1d1052749e2bf86edd07a6aad98fd3ed572d7c7672b078f13b.png)

**Comment by htobon** [comment]
I liked it! Please make some tests and move it to the production environment. Please let me know when it is there.

**Comment by sebas932** [comment]
Tested and Done!
