### ISSUE TITLE
Change Management Liaison for Flagship Leader

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1031]
Hi Guys, 
Please take out the word "Management Liaison" from all MARLO and change it the same as we did for A4NH and PIM.

Please make this change as soon as possible.

Thank you in advance,

**Comment by sebas932** [comment]
I change in an email the following phrase : 

> The Flagship Leaders is part of the group of users called Management Liaisons and may be responsible for the following:

**for**

> The Flagship Leaders may be responsible for the following:
