### ISSUE TITLE
Cluster of activities leader - optional

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#1033]

**Comment by cgarcia9106** [comment]
@htobon  now is on dev, please check

**Comment by htobon** [comment]
If the field is optional, the red asterisks must not appear. 
This rule applies to everything in MARLO.

![image](https://cloud.githubusercontent.com/assets/5375915/26587678/9a9ebff2-4518-11e7-98dd-95aae1a130e2.png)

**Comment by cgarcia9106** [comment]
Fixed

**Comment by htobon** [comment]
Thank you. Can you please confirm this is in the production environment?
