### ISSUE TITLE
Fix issue in users search 

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1036]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-694f52c0548a04d8bbceef0e3b3d48272d8dd10eacadc984c0da378229e038f3.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-b0dcd32f1290516a9468dbe3fc1b10a02fb913278d0c29e0ae04a71c20fafd1f.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-6175e5676d27ee4d0326c670e9e039c4ae84b6e0d2719b1620103e10bd411423.png)
