### ISSUE TITLE
Change label in the projects list column

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1038]
Hi Sebas, please follow the instructions in the screenshot below.
Thank you.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-f67b411a0bc02e19e5bbfad0c1a934a8b42847f77ff4a91035fc1d6800bc5ab2.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-e388ca94b5bddbe7d4949c0572e51a9480b6d33843d1a47f6d9b3f0f2b3680be.png)

**Comment by carios1usb** [comment]
Hi @sebas932 , i made the requested changes in project list, view the image.

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-59981bf271a2d208da31a29821a9e359520fe3c4e5dbbec0831406495ef73aa0.png)
