### ISSUE TITLE
Pre-setting project budget

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1042]
When pre-setting a project, I went to the budget by partners section, did not do anything and clicked the save button.
Then, I got a yellow message saying that there are missing fields, but there are not yellow labels below indicating which missing fields must be filled. 

See screenshot:
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-c26334cb4e53c00fa7c02955bced4b369ecd161ccc1a9db8f36ca25a148fafeb.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-f7e95b6a60f472bb8a6cd60ddffe32592855f704fb1a52515a84634103a209a1.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-aaab98f4731627e9a1c8ed0d1eb4a93e4a70ff0bc2d4a710fa3d07456b0896b1.png)
