### ISSUE TITLE
Show standard regions and informative message in admin locations

### ISSUE THREAD

**Issue by carios1usb** [CCAFS/MARLO#1045]

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-316203c1a3fefd31894a5536ec63736b7ed3a821e3d42557f7d4284b3d52cda3.png)

**Comment by carios1usb** [comment]
Hi @htobon , I added the standard region list and the informative message, view the image. I await your response to push the commit.

**Comment by htobon** [comment]
Hi @carios1usb, I'm sorry but I don't see this interface into our testing environment.
Cheers,
