### ISSUE TITLE
Fix label when requesting a new user

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1046]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-ca2c695de2e198e3a911cafd4e599a10122e8e0611925a47cef6054d56333bdb.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-e58376bd9fe15422b5c3b0b6b528b2c84e82d72795b4d7f2da8af4166518e3b5.png)
