### ISSUE TITLE
Propose a Landing page for adding Platforms and Centers to MARLO

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1050]

**Comment by sebas932** [comment]
@htobon look at this proposal below

![Animation_landing.gif](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Animation_landing-b5c769354808dd9689bf1f1130767a9ce67b46638f4fea716053b7809ca88903.gif)

**Comment by htobon** [comment]
@sebas932 Very cool. Can you please justify the texts above the logos? I will share this link with David. Cheers.

**Comment by sebas932** [comment]
@htobon look to this second proposal below

![Animation_secondProposal.gif](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Animation_secondProposal-9de226fc240efee78b282dded98b752db755b4b6d7e634b57c4c0eb000270326.gif)

**Comment by htobon** [comment]
Hi @sebas932, as per conversation with David, Let's go to for the second option.
Cheers,
