### ISSUE TITLE
Prototype [Baseline indicators]

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1058]

**Comment by sebas932** [comment]
We need to go forward with this issue, below the mockup 

https://docs.google.com/presentation/d/1btHIK0lYU_7-jxw_8oUWJJyiLamqB9stmv5w0KfjhL0/edit#slide=id.g1681c2812b_0_59

**Comment by sebas932** [comment]
@htobon i am pending to go forward in this, can i start developing the prototype in a new branch ? or we need to refresh with David?

**Comment by htobon** [comment]
I'll follow up with David. thks for remind me.

**Comment by sebas932** [comment]
**Impact Pathway Level**
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-2fa6a4313354b8e63ceee7be92912bacf29f3c0ba664b196592d45dad744827a.png)

**Planning: Project level**
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-34fd7c23a98134b163a73688a683d26f99c0dc490f74755e6d05a6dcf4d35edb.png)

**Comment by sebas932** [comment]
**Reporting: Project Level**
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-1c0a7e2b901b662daf40c6e8bf1b6e00f1dc3f7a1638cac3c0c0fe222d7a0acf.png)

**Comment by sebas932** [comment]
@htobon i've working in a prototype of Baseline Indicators. Please look at the screenshots above, and let me know which improvements in text needs to be changed.

And i would like to release the development in Marlo Dev,  Can i merge this development into Dev branch and turning on only for CCAFS ? It will be showed in each outcome flagship.

**Comment by htobon** [comment]
Hi @sebas932, yes, please merge it into MARLOdev so I can take a look at it.
Cheers,

**Comment by sebas932** [comment]
@htobon the prototype is already in MARLO Dev

**Comment by sebas932** [comment]
It was tested
