### ISSUE TITLE
Best practices for regions and make a proposal

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#106]
Proporsal for Backend and Mockup

**Comment by HermesJim** [comment]
I proposed the regional composition of the United Nations based in the ISO 3166-1 

http://unstats.un.org/unsd/methods/m49/m49regin.htm#ftna

**Comment by HermesJim** [comment]
I had a comparison between CCAFS regions and United Nations Regions.
The unite nations separe Latin america Countries in three regions (Caribbean, central america and south america) 

[CCAFS_UN_Regions_Comparison.xlsx](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/CCAFS_UN_Regions_Comparison-fde8ab5ae528ac17d5ef0c35d0db75912f4a36aa57a5aff4535967e9137b969f.xlsx)

**Comment by htobon** [comment]
Great, thanks for documenting this activity.

**Comment by htobon** [comment]
We are looking forward Tonya's comments

**Comment by htobon** [comment]
We will talk with Tonya tomorrow, but I think we can close this issue as we will go ahead with the UN Standard.
