### ISSUE TITLE
Migrate standard regions

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1065]
Support document: https://datahelpdesk.worldbank.org/knowledgebase/articles/906519-world-bank-country-and-lending-groups

 - [x] Deactivate continents from locations and locations types.
 - [x] Create new regions.
 - [x] Change parent ID of current countries according to new regions.
 - [x] Deactivate old regions except 'others' region.

**Comment by AndresFVR** [comment]
Funding sources: ![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-bca4a0e9dea9e24a12d1ea0019b17d33d7f7a68beb2d6f0d72afe3f6ae9ca66f.png)

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-829a641725af0ca47293af4c85b498200ac9b606c6eb5b432b01a930607deed0.png)

Project Locations: ![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-41fcf246a1c963854e0e9764b436ab415a4a9e8ebe81bfcac512a737d608e99d.png)

**Comment by htobon** [comment]
@AndresFVR can you pls confirm this is finished and released into the production environment?

**Comment by AndresFVR** [comment]
@htobon yes, it is already released
