### ISSUE TITLE
Add description field to Project Deliverable on Planning and Reporting Cycle

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1069]
Approval process:
- **A4NH**: Yes
- **CCAFS**: Yes
- **FTA**: (Not confirmed - although they are not using MARLO as of yet)
- **Livestock**: Yes
- **MAIZE**: Yes
- **PIM**: Yes
- **WHEAT**: Yes
- **WLE**: (David and Emma are out of the office and will be back in 10 days)

**Comment by AndresFVR** [comment]
Planning: https://www.screencast.com/t/qih76cfD
Validator: https://www.screencast.com/t/958hVYyfq3

Reporting: No description field added. https://www.screencast.com/t/XdWiRoWK9OKq

**Comment by htobon** [comment]
I think that for reporting, it should appear too.
@sebas932 can you please confirm?

**Comment by sebas932** [comment]
@htobon yes, for reporting should be visible too.

**Comment by htobon** [comment]
@AndresFVR, please do it for reporting as well.
Thks.

**Comment by AndresFVR** [comment]
@htobon  @sebas932  Ok, i will do for Reporting too. https://www.screencast.com/t/UmjwIG71tp

**Comment by sebas932** [comment]
@AndresFVR  is this ready in marlo dev for being tested

**Comment by AndresFVR** [comment]
@sebas932 it is already merged into dev. But not in the dev environment.

**Comment by htobon** [comment]
Is there any advance on this?

**Comment by AndresFVR** [comment]
Hi @htobon, this is in marloDev to review.

**Comment by htobon** [comment]
Checked. Please release it to production.

**Comment by sebas932** [comment]
We are still pending for MARLO Family comments

**Comment by htobon** [comment]
Hi guys, please release this new field into production.
