### ISSUE TITLE
Unexplained creation of empty projects

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1084]
> We noticed four empty projects which nobody in PIM remembers creating.
> These are P675 to P678. Can you pull out the history of creation of
> these projects so that we understand how they appeared?

**Action Points**
- [x] @HermesJim  could you please check how those projects appeared or was created, maybe who and when in the history?

**Comment by HermesJim** [comment]
These Projects  was created by Maria Theresa Tenorio (m.t.tenorio@cgiar.org) the 2017-07-13

**Comment by sebas932** [comment]
Thank you @HermesJim
