### ISSUE TITLE
Null Pointer Exception when trying to request a new partner

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1086]
Steps to reproduce:

* Login to marlo test environment using user 'Grant Lay' select FTA as the CRP.
* Go to the System Admin screen and Select the Request Institutions page.  User will be presented with a FreeMarker template error:

>An error has occurred when reading existing sub-variable "countryInfo"; see cause exception! The type of the containing value was: extended_hash+string (org.cgiar.ccafs.marlo.data.model.PartnerRequest wrapped into f.e.b.StringModel)

The root exception is:

>Caused by: java.lang.NullPointerException
	at org.cgiar.ccafs.marlo.data.model.PartnerRequest.getCountryInfo(PartnerRequest.java:106)
	... 174 more

**Comment by sebas932** [comment]
Thank you @Grant-Lay for let us know about this issue. This is a new feature that @AndresFVR and me are working on, until we have finished i will hide the section from the System Admin Menu.
