### ISSUE TITLE
Improve Database connection performance

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1088]
Currently, when an user visits a specific section, MARLO opens and closes several connections at the same time, causing performance issues and some times causing our mysql server stop working. 

Therefore, would you please improve the architecture in order to better manage the connection in the database, perhaps making MARLO to manage one single connection per Action?

Thank you in advance.

**Comment by Grant-Lay** [comment]
[MARLO server side improvements.docx](https://github.com/CCAFS/MARLO/files/1284210/MARLO.server.side.improvements.docx)

Attached files which outlines the changes.
