### ISSUE TITLE
Fix CRP names in the database table

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1091]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-bc2ce11b25a46efc410c55124cc1896e391b2385c1b717fad748922c9368f10e.png)

**Comment by htobon** [comment]
I'm sorry but I'm opening this issue again as it was not properly implemented.
@jurodca, have you reviewed it?

The Guardian Style Guide states:
> **Use all capitals if an abbreviation is pronounced as the individual letters (an initialism): BBC, CEO, US, VAT, etc;** if it is an acronym (pronounced as a word) spell out with initial capital, eg Nasa, Nato, Unicef, unless it can be considered to have entered the language as an everyday word, such as awol, laser and, more recently, asbo, pin number and sim card. Note that pdf and plc are lowercase.

Source: https://www.theguardian.com/guardian-observer-style-guide-a

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-40a7f6e7b1032329f93bafd3037ed050ed442ae70faad44ae1c68a2f913c3615.png)

**Comment by cgarcia9106** [comment]
@jurodca  @sebas932 please review

**Comment by jurodca** [comment]
Hi. it's ok.
