### ISSUE TITLE
Process for validating new institutions

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1095]
MARLO-Family meeting (July 31, 2017):

**⇒ Institution current protocol follows:**

- as registered as a legal entity
- needs to be written in the original language (except for other characters) - consistent on naming national government agencies
- in a specific country is the current protocol … 
- add other protocol - We should be  etc with the country name. The existing category 7 (government) contains many entries of the ‘ministry of agriculture’ type. Can we say ‘Ministry of Agriculture, Malawi’ or similar?
- all INGOs and NGOs entered a single time (e.g. Oxfam, Save the Children), with option for user to select the specific country/regional offices 

**Action Point:**
Propose a process for validating the new institutions added into the database (perhaps 2 months after a cycle finalize)
- Schedule a meeting with a small group on how to tackle this.

**Comment by sebas932** [comment]
@htobon do you know about the progress of this issue ?

**Comment by AndresFVR** [comment]
Emma will explain us how to validate the institutions correctly.

**Comment by htobon** [comment]
This has been tackled with the help of Emma, Pascale and Amanda W.
They have instructed us on how to proper verify the new institutions requests, and Andres is leading this process.
