### ISSUE TITLE
Rest API architecture . (Deliverable Metadata)

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#1098]
- [x] To create abstract class to implement deliverable metadata harvesting
- [x] To create a utility class for connecting with external REST web services 
- [x] To create a JSON example of deliverable metadata that the Frontend will use
- [x] Implement development with CGSpace
- [x] Implement development with Dataverse
- [x] Implement development with ILRI
- [x] Implement development with IFPRI

**Comment by sebas932** [comment]
@cgarcia9106  this is the JSON template used in deliverable interface.
https://gist.github.com/sebas932/2afd68cadc79b0fcc3d6b98316c1a3fb

**Comment by sebas932** [comment]
@cgarcia9106 the external repositories were documented in #1115

**Comment by sebas932** [comment]
@cgarcia9106 I've checked and found some issues

**CGSpace**
- [ ] Authors in CGSpace doesn't load
- [ ] Open Access in CGSpASE (cg.identifier.status) TRUE("Open Access") FALSE("Limited")
- [ ] Publication Date in CGSpace (dc.date.issued)

**ILRI Datasets**
- [ ] rights (license_id)

**IFPRI**
- [ ] publicationDate in format  yyyy-mm-dd, currently show 2016-05-27T00:00:00
- [ ] The following URL doesn't work (http://ebrary.ifpri.org/cdm/singleitem/collection/p15738coll2/id/131348/)

**Dataverse**
- [ ] publicationdate doesn't load (timestamps.publicationdate)

**Comment by cgarcia9106** [comment]
@sebas932  review please

**Comment by sebas932** [comment]
@cgarcia9106 Please implement the issue #1106
