### ISSUE TITLE
Show projects that are active/on-going and closed 

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1100]
Show projects that are active/on-going and closed (including W3/Bilateral). Each project will show its status (i.e. on-going, complete, extended, cancelled) with an available field to allow Management Liaisons to leave comments when the project is extended, cancelled or complete;

Content tasks for *Hector*
- [x] Julian to send a reminder to all Project Leaders.
- [x] Follow-up with Julianna White on what needs to be done before September 1st

Technical tasks:
- [x] Dropdown for Project statuses: on-going, complete, extended, cancelled
- [x] Available field to allow Management Liaisons to leave comments when the project is extended, cancelled or complete;
- [x] Check and update the status for the projects
- [x] Second list to see close projects
- [x] Work on permissions to ML can edit Justification for a Closed or Completed projects
- [x] Enable reporting view for closed projects
- [x] Deploy on marlo-dev

**Comment by sebas932** [comment]
Project statuses dropdown were added and text field for comments 

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-470b0e560b476cf1b2f0724f3076210072f8ca31caf3242e646cb7f21bcee655.png)

**Comment by sebas932** [comment]
The Project status its being showed in the projects list section, see below
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-b4d7fae1f93858f272f5e457e5be5d620c373d0a43a679f95e40f4af0448b0f5.png)

**Comment by htobon** [comment]
Hi guys, please also refer below to a message sent by Lini with some useful suggestions for us to take into consideration:

>HI David,

>Yes, this is fine.  Perhaps the project numbers could have an extra letter to indicate it’s status, e.g CP267  for “closed project”, and that these projects include a “status of project” section on opening main page that provides any required information (reason(s) for end of project? E.g project completed, phase of project completed, staff change, budget change, integrated into another project, performance, other etc; and maybe year the project ended, to avoid problems like Pramod’s CIMMYT project).  I think information is optional.

>We could have a separate tab in Marlo for completed/archived projects

>For projects that transition into new projects, and it is just a matter of a new time period, maybe include a link or the number of the old project somewhere.  Could even code the new project to reflect the old one. E.g. 267.1, 267.2, 267.3 etc.  That way you could easily track sequences of projects.

>Good luck!
>Lini

**Comment by sebas932** [comment]
The "Archived" tab for projects Completed or Cancelled was added in project list, is ready for being tested in MARLO Dev @htobon 

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-96ce6bb3a794f256efb292c6e93fe68d16debe13c21a4b1c303e09d5309c3bd5.png)

**Comment by sebas932** [comment]
It was deployed in production
