### ISSUE TITLE
Implement functions for harvesting metadata from CIMMYT repositories

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1106]
Branch: dev-rest-metadata

- [x] Create connection class to CIMMYT
- [x] Map XML data to metadata Model
- [x] Add CIMMYT as example in deliverables section
- [x] Fix publicationDate

> •	Regarding Dataverse, apparently the OAI-PMH target I told you is
> working just fine. Let’s say that I want to list all the records
> exposing the metadata using the DDI standard, then I just run a
> standard OAI-PMH request as follows:
> http://data.cimmyt.org/dvn/OAIHandler?verb=ListRecords&metadataPrefix=ddi
> Dataverse uses a wide metadata elements catalog (please find it
> attached) and, if I am not wrong, all the fields can be retrieved by
> querying the OAI-PMH target. You might share the whole list of
> metadata elements needed by MARLO so that we can understand better why
> some of them cannot be retrieved via OAI-PMH, and then we could work
> together in order to find a way to make them available to MARLO.
> •	With respect to Moodle, I have never used its API and, therefore, I
> am not familiar with it. But, besides the information contained in the
> link I shared with you in my previous email, after a quick search on
> Google I found some interesting pages that could be used as a starting
> point for a larger research on the Internet. There is so much
> information about Moodle online that sometimes it is not easy to find
> what is needed. Anyhow, here you can find a list of the Moodle web
> service API functions:
> https://docs.moodle.org/dev/Web_service_API_functions . As you can
> see, there are several list-type and get-type functions that might be
> used for gathering information stored in the platform. In the
> following page you can find a short tutorial on how to create a web
> service client:
> https://docs.moodle.org/dev/Creating_a_web_service_client . And,
> finally, here you have a very detailed example, including code, on how
> to create a new user and then enroll him/her to a course via the API:
> http://www.spanidis.eu/?p=27 ; obviously this example is not oriented
> to extracting information, but I believe it could be re-used as a
> template for implementing other different web service clients.

**Comment by sebas932** [comment]
This will implemented on the issue #1098

**Comment by AndresFVR** [comment]
Missing Metadata Elements are:
language, open access, doi, country
