### ISSUE TITLE
Copyright note

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1109]
Liaise with David on how to include this information into the system.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-7601abfbcb4c0879cc85f855917307eba80117f89352c096f22829b3c78d5f88.png)

**Comment by sebas932** [comment]
@htobon do you know about the progress of this issue ?

**Comment by sebas932** [comment]
Moved to the next sprint
