### ISSUE TITLE
MARLO Legalities

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1111]
We should have Terms of references, Privacy notice and Software Licence explicit in the platform.

- [x] Define texts in collaboration with CIAT Legal office
- [x] Share them with MARLO-Family
- [x] Release it into MARLO

**Comment by sebas932** [comment]
@htobon do you know about the progress of this issue ?

**Comment by htobon** [comment]
Hi @sebas932.
The privacy notice is ready.
Please check the document located in: MARLO\2_Technical\2_2_Documentation\2_2_1_Manuals\Legal

Could you please create a new section in MARLO for this?

The other sections are still in progress.

Cheers,

**Comment by htobon** [comment]
After a number of back and forths with the CIAT Legal office, we have come to a final version of the documents that were shared with MARLO-Family.
