### ISSUE TITLE
toString methods on Entities are insufficient for logging purposes and can throw NPEs

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1114]
Currently many toString implementations on MARLO entities simply print the ids and many will throw Null Pointer Exceptions (NPEs) when an identifier has not yet been assigned (the entity is yet to be persisted).

For examples look at entities ProjectScope and ProjectPartnerPerson.  

`public String toString() {
    return id.toString();
  }`

Eclipse can assist with creating new toString methods that use the fields on the entity by right clicking on the class selecting 'Source -> Generate toString()'.  This exercise can be done for all entities and should only take 20 seconds per entity.

Auditing fields do not need to be included in the toString() method and should be refactored into a superclass anyway see issue #1113.   Also be careful not to include collections as this will trigger loading of the collection for lazy loaded associations, therefore just include a few fields besides the id that can identify the entity.  

For example for the Activity class:

`@Override
  public String toString() {
    return "Activity [id=" + id + ", title=" + title + ", description=" + description + "]";
  }`

**Comment by jurodca** [comment]
This issue is finished but it is in the dev-optimize-database-queries branch that is using @grantlay. Until the changes of the branch in staging or master are not found this issue will not close.

**Comment by htobon** [comment]
Closing this issue as it seems everything is finished here. What is still pending is to release this branch into the production environment, and this process will be followed in the issue #1123
