### ISSUE TITLE
Check out MARLO improvements of database optimization 

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1123]
Check out MARLO application with the improvements that Grant is working on about database optimization

**Comment by sebas932** [comment]
Hi @Grant-Lay, i've cheking out the branch dev-optimize-database-queries and i found some issues that isn't working properly in MARLO Impact Pathway and projects

- [ ] In Outcome Impact Pathway, i've tired to edit a Milestone, but saving, it returns a 500 page
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-e85d88b1886d5e658acb35c3b6c693d53ffd2b2f10ccda1725e72b3ac8774864.png)

- [ ] In Cluster of activities, i've added a new key output, then i tried to remove it, but it didn't work
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-8c1fe7a83e83eb9c0bf4ec94f85bfa57041dd5c179faa8b5eda66c68c7ee60d3.png)


 - [ ]  In project description when i tried to see a "History Version", the system return a Freemarker error.
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-39cdae2b4e335209c6f159fd740b2d5f3ad7deb0dfd8c0aa9df64464d140b540.png)

 - [ ] In project partners, as the issue above in a History versión.
 ![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-0ab9da13285c12326b67a07f6fc68d565d3153f034a2f4301849f2117baf4498.png)

- [ ]  In deliverables information "contact person(s) that will contribute to this deliverable", y chose a person from CIAT, but doesn't save 
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-938ff298d55c3b211205110bc2533f633c0bb8ef91543da87b0d3f3a0c99a3ef.png)

**Comment by sebas932** [comment]
Hi @Grant-Lay , i've found some MARLO reporting section issues that you could check, meanwhile i will be chenking with @jurodca if is there more issues

- [ ]  Saving a new Project Highlight gets an 500 error
> [http-bio-8443-exec-8]UnhandledExceptionAction [ERROR]: There was an
> unexpected exception org.hibernate.TransientObjectException: object
> references an unsaved transient instance - save the transient instance
> before flushing: org.cgiar.ccafs.marlo.data.model.FileDB 	at
> org.hibernate.engine.internal.ForeignKeys.getEntityIdentifierIfNotUnsaved(ForeignKeys.java:294)
> ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]

- [ ]  I have tried to add a new Outcome Case Study and it gets an 500 error
> [http-bio-8443-exec-3]UnhandledExceptionAction [ERROR]: There was an
> unexpected exception
> org.hibernate.loader.custom.NonUniqueDiscoveredSqlAliasException:
> Encountered a duplicated sql alias [id] during auto-discovery of a
> native-sql query 	at
> org.hibernate.loader.custom.CustomLoader.validateAliases(CustomLoader.java:524)
> ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final] 	at
> org.hibernate.loader.custom.CustomLoader.autoDiscoverTypes(CustomLoader.java:501)
> ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]

**Comment by Grant-Lay** [comment]
Also deleting the target year from the SLO indicators does not work successfully.

**Comment by sebas932** [comment]
The improvements were applied and are already in production enviroment
