### ISSUE TITLE
Fix issue of moving to CIAT from a CRP

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1126]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-312094d022b3376492cd2c0ac768bf78f09892d0c227baf1285962db3ab9b5af.png)

**Comment by HermesJim** [comment]
#fixed and improved the menu...

![image](https://user-images.githubusercontent.com/13221179/29587951-44996308-8755-11e7-9cd9-17f05c93a341.png)

**Comment by htobon** [comment]
Then.. can you please include the placeholder "--CRP--" for the CRPs?
