### ISSUE TITLE
Update texts in the landing page

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1128]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-109facd2c1a36496af25792a37669d5fcbae7664de9e6f2c8ee8b0110f367efe.png)

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-7e910a50e3125300afd13026d489e41edd0536c56f81fd45685611b40698f5cf.png)
