### ISSUE TITLE
Top menu to list the CRPs according to the users privileges

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1129]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-c1bafa9c698d29b74203cadff7c525546c84009fc350dbdfb7a5efb530f2b958.png)

**Comment by htobon** [comment]
As per conversation with @HermesJim, this will be done this week.

**Comment by htobon** [comment]
Was not ready this week, but @HermesJim promised to release it next week.

**Comment by htobon** [comment]
I have been informed by @sebas932 and @HermesJim that there is still a bug here and it will be fixed soon.

**Comment by sebas932** [comment]
-[] Fix the following 500 error, it happens when i tried to navigate from CIAT to CCAFS
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-9b7ac82781b5453adc8ec4498709320cecccffa647f08e089b7a25ed697fde0e.png)

**Comment by HermesJim** [comment]
Fixed.
@sebas932 can you please check if this issue is done ! 
Thanks.

**Comment by sebas932** [comment]
The feature was tested, its working
