### ISSUE TITLE
Reorganize partners/institutions (update, remove and include the new ones proposed) 

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1130]
https://docs.google.com/spreadsheets/d/1nLAD6UcfVTzPZGpJPxFkf26viWS82YPOR713tI4WE9E/edit#gid=969899790 

-	Process started in June 29th and finished in December 22nd, 2017.
-	1.709 institutions were validated.
-	1.033 were updated
-	239 were deleted

**Comment by AndresFVR** [comment]
Institutions to delete:
[Institutions to delete.docx](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Institutions%20to%20delete-c872458a9a53774c79ef60d24ec23b6c354f96487b3c462196370a62aeb1b96b.docx)

**Comment by sebas932** [comment]
We are waiting for Amanda, Emma and Pascale

**Comment by AndresFVR** [comment]
Remaining tasks:

Delete:
- ID 1845: CSAYN - Climate-Smart Agriculture Youth Network
ID 1840: AWGGCC - African Working Group on Gender and Climate Change

Update the following institutions to the new Institution type:

| ID   | Institution Name                                                                            |
|------|---------------------------------------------------------------------------------------------|
| 18   | Programa Colaborativo de Fitomejoramiento Participativo en Mesoamérica                      |
| 19   | Asociación de organizaciones de los Chuchumatanes                                           |
| 348  | Think Tank Gulbenkian                                                                       |
| 396  | Federation Nian Zwé                                                                         |
| 516  | Instituto de Manejo e Certificação Florestal e Agrícola                                     |
| 730  | Foundation for Participatory Research with Honduran Farmers                                 |
| 776  | Asociación de Cacaoteros Tecnificados de Padre Abad                                         |
| 842  | Fundación Procuenca Río Las Piedras                                                         |
| 875  | Asociación Coordinadora Indígena y Campesina de Agroforestería Comunitaria de Centroamérica |
| 1054 | Corporación Educativa Para El Desarrollo Costarricense                                      |
| 1345 | Association Coopérative en Synergie Féminine                                                |
| 1384 | Centre de Développement Communautaire                                                       |
| 1410 | Development Rural du Nord                                                                   |
| 1411 | Development Rural Durable                                                                   |
| 1434 | Femmes Business                                                                             |
| 1477 | Groupe d’Encadrement des Initiatives d’Auto-promotion Sociale                               |
| 1529 | Main dans la main                                                                           |
| 1771 | Fondation Nsimba Nzungila                                                                   |
