### ISSUE TITLE
Removing a ProjectClusterActivity in the ProjectDescriptionAction does not delete the ProjectBudgetClusterActivitiy

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1142]
Steps to reproduce. (I haven't tested this is staging branch - but I assume the bug is in there too).

After completing the ProjectBudgetByCoA screen, the user may go back to the ProjectDescription screen and delete a mapping from the Project to a CoA.  When going back to the ProjectBudgetbyCoa screen the CoA budget mapping does not appear.  But on the server side the row is not deleted from the database (or set to active=false).  Server side validation will fail on future updates because the total gender and total amount fields add the deleted CoA budget amounts.  Client side the validation works fine, which is confusing for the user.

A potential solution would be to delete any ProjectBudgetsClusterOfActivities that map to that particular CoA when the user removes the CoA from the project (i.e. in the ProjectDescriptionAction save() method).

**Comment by htobon** [comment]
@cgarcia9106 can you please check this in detail?
copying @jurodca

**Comment by htobon** [comment]
@cgarcia9106 will check this again to validate that the issue existing or if it was already fixed.
