### ISSUE TITLE
Create interface for adding contact points

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1146]
Branch name: dev-admin-contact-points 

In users list section (Add button of selection):
- [x] Create Backend process to add Contact Point Leader

Add record to Liasison User with Liaison institution as parameter.
Add role to the user if don't exists.

Also impliment deactivation of liaison users.

Review and if necesary fix the liaison institution addition.
- [x] Fix issues detected on tests
- [x] Release to Dev
- [x] Apply Hector suggestions 
- [x] Release and Test in MARLO Dev
- [ ] Release to production

**Comment by AndresFVR** [comment]
Ready to review in MarloDev

**Comment by AndresFVR** [comment]
Hector suggestions:
- [ ] Fix contact points bad writing - change points for point(s)
- [ ] Improve visualization of interface when the CRP has not contact points.
- [ ] Add role emails according to Marlo automatic emails document.

**Comment by htobon** [comment]
Tested.
found a 500 error after doing several things at the same time.

**Comment by AndresFVR** [comment]
Solved 500 error with commit 6e89dc3
