### ISSUE TITLE
Generate report in WORD latest version (.docx) 

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1148]
- [x] Do a research
- [x] Create document

**Comment by AndresFVR** [comment]
[Pentaho report-Output Word.docx](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Pentaho%20report-Output%20Word-88f50a5fe793986390f9631c8633a2fd6c593a752c0f72cbd235c6639dd7fc72.docx)

**Comment by htobon** [comment]
Hi Andres, thks for documenting this issue. Can you please elaborate a bit more about why pentaho is not able to generate DOCX files? Is there an official website and/or reason for that? Please include everything in the attached document.

**Comment by AndresFVR** [comment]
Hi Hector, there is not much information about the topic or why it couldn´t be possible.

Looking in Pentaho Forums and issue tracking we found the following:
Issue reported in 14/May/10 : The title of the issue is “As a report designer, I want to reports to output to MS Powerpoint and MS Word.”. There is no answer yet for the issue.
There is not much information about Pentaho report with Microsoft Word output and why it is not possible to export to report to Word. http://jira.pentaho.com/browse/PRD-2689

Also i have updated the attached document.
