### ISSUE TITLE
Sync MARLO with IWMI Knowledge Repository

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1149]
Branch: dev-rest-metadata

http://www.iwmi.cgiar.org/publications/library-catalog/
Contact: Chandima (Head of library )

**Comment by sebas932** [comment]
@htobon the library search (http://www.iwmi.cgiar.org/publications/library-catalog/) did not work when i tested and i did not find any way to harvest the metadata, it doesn't look like a repository, it's only show the outputs DOI listed

Could you contact the head of library ?

**Comment by htobon** [comment]
Hi Sebas, I have sent you a draft of an email to send to Emma and DRS. Please take a look at it.

**Comment by sebas932** [comment]
We are waiting from Hector's response

**Comment by htobon** [comment]
Emma just told us to contact Chandima directly.
as this is not a priority now, I will changed this issue with low-priority.

**Comment by htobon** [comment]
Charinda just informed us that IWMI is also using CGspace. Therefore, there is no need to develop interoperability with the IWMI's Catalog.
