### ISSUE TITLE
CCAFS - Project budget by country in MARLO

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1152]
> **Philip**: Would it be possible to ask management liaisons to put in a % breakdown of project budget by country in MARLO, like the gender % thing?  Would this be easy to do?  Fine to say no!

**Comment by htobon** [comment]
David will check with Philip on Tuesday 23rd about how this can be done and the level of priority.

**Comment by htobon** [comment]
David and me had a meeting with Laura (CCAFS Science officer - Flagship 1)  in which we decided to tackle this request later as the amount of work we have at me moment by adjusting MARLO for POWB is occupying all our time.

**Comment by htobon** [comment]
Philip and I decided not to go ahead with this as is hard to know.
