### ISSUE TITLE
Change collation to UTF8 at server level

### ISSUE THREAD

**Issue by jurodca** [CCAFS/MARLO#1163]

**Comment by htobon** [comment]
In the meeting of today, we changed the following variables into the server configuration:
character_set_server=utf8
collation-server=utf8_unicode_ci

I also identified that some tables are still set-up in latin1. @jurodca told me that he will take a look at them. A deadline for this process was not specified.

In addition, I shared with him a concern about the data that already exists in the database. I understand the collation of the tables was changed to UTF8, but it is not clear to me if we need to make a conversion process for the data that already exists.
