### ISSUE TITLE
MARLO-PLATFORMS: Create Architecture for entering Platforms, CRPs and Centers at same time

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#1166]
Currently MARLO manages the CIAT and CRPs data in different places in the database. The idea with this development is to use the same place and adapt the platform to also storage data from the CGIAR Platforms.

**Comment by htobon** [comment]
As per conversation with @HermesJim, this will be released in the testing environment during this sprint.

**Comment by htobon** [comment]
This development was released yesterday.

**Comment by htobon** [comment]
Thank you @HermesJim
