### ISSUE TITLE
CCAFS - Develop Baseline module for Flagship 3 (Lini & Meryl)

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#1168]
**Mockup:** http://bit.ly/2DgU7aU

**Technical tasks for Impact Pathway level**:
- [x] Create specificity only for CCAFS F3, add checbox selection in CRP Admin
- [x] Create column in Flagships to determine if baselineIndicator is available
- [x] Create baseline indicator functionality for Flagships
- [x] Create baseline inidicator model for Impact Pathway
- [x] Create baseline indicator functionality for Impact Pathway
- [x] Ensure the Impact Pathway is working fine with the tabs way
- [x] Add requered field indicator to the tabs in Impact Pathway outcomes section (Missing fields)
- [x] Release and Test in MARLO Dev
- [x] Develop the baseline indicator with the annualization feature 

**Technical tasks for Project level**:
- [x] Create the interface at project level with the baseline indicator fields
- [x]  Develop the save function of baseline indicators
- [x]  Validate the required fields is working once the save is finished
- [x]  Release and test in MARLO Dev

- [x] Release to production
- [x] Write a blog-post

**Comment by htobon** [comment]
I added a new outcome, filled all the fields and clicked the save button.
After that, MARLO deleted what I inputted and put some fields in red like they were incomplete, which is not true.
![image](https://user-images.githubusercontent.com/5375915/35280558-9278f5ba-001e-11e8-9326-c7eb08c974d0.png)

**Comment by htobon** [comment]
Testing 2:
I have created a new project. Then I filled everything in project description. And after hitting the save button:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-29c969f80e58278f5804fc1d7a08a986bff93c2b355830fcf1f88e5f02d23e45.png)

**Comment by htobon** [comment]
After another test, there are a couple of minimum issues:
- [ ] The URL to download the file at project level is not working.
- [ ] Instead of "Ask to the Flagship leader for the baseline instructions", please replace it to "There are no instructions for this baseline indicator(s). Should you have any questions, please contact the Flagship Leader directly"

Please fix those two issues and release it into production.

**Comment by cgarcia9106** [comment]
The URL tenia que ver con la configuracion del ambiente de marlo-dev

**Comment by htobon** [comment]
Blog-post here:
https://marlo-news.blogspot.com.co/2018/01/baseline-indicators-within-flagship.html

**Comment by htobon** [comment]
I have sent an email to Meryl asking feedback before this Friday 26th. If everything is ok, I'll close this issue.

**Comment by htobon** [comment]
We have not heard back from Meryl as of yet. So, I'll close this issue.
