### ISSUE TITLE
To fix previous spring 4.0.1 issues acording to de following comments

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#117]
- [x]	Revisar textos en la página de bienvenida  “Modo test en rojo grande”.
- [x]	Mensaje de error cuando no tienes privilegios  a otros CRPs “You don’t have Access to the selected CRP”.
- [x]	Quitar validación de user en dos secciones distintas.
- [x]	Salto de línea en tooltip de users online.
- [x]	Diferenciar ítem de menú “CRP Admin”
- [x]	Pensar dashboard en modo dinámico para multiple CRP.
- [x]	No guardar usuarios duplicados en “Program Management” section
- [x]	Documentar interface de AudiLog en Java

**Comment by htobon** [comment]
@sebas932, @HermesJim actualicé cada tarea para que puedan chequear cuáles están listas.

**Comment by HermesJim** [comment]
@htobon por el momento, yo he resaltado en negrita las tareas realizadas.

**Comment by htobon** [comment]
@HermesJim, ya actualicé el listado entonces basado en lo que se ha hecho..
