### ISSUE TITLE
Cimmyt Repositories (Dspace , Moodle)

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#1175]
Branch: dev-rest-metadata
- [x] Release and Test in MARLO Dev
- [ ] Release to production

**Comment by sebas932** [comment]
@AndresFVR  Could you help me adding CIMMYT DSpace to the repositories list.

They are using the OAI Protocol:
http://repository.cimmyt.org/oai/request?verb=Identify

**Comment by sebas932** [comment]
User view: http://repository.cimmyt.org/xmlui/handle/10883/19065
OAI Protocol View: http://repository.cimmyt.org/oai/request?verb=GetRecord&identifier=oai:repository.cimmyt.org:10883/19065&metadataPrefix=oai_dc
