### ISSUE TITLE
Retrieving CenterId from HTTP session throws a NullPointerException

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1180]
The getCenterID and getCenterSession methods both throw NullPointerExceptions when the user does not have a Center in the HTTP session.  Currently the block of code is in a Try and Catch block but this code can be improved by removing the try and catch blocks and replacing with a check to see if the Center is in the HTTP session.  Read Effective Java by Joshua Bloch as to why using Exceptions in your main logical flow is a bad idea (Exceptions are for exceptional circumstances not normal ones).

**Comment by htobon** [comment]
We should not have closed issues in our backlog. So, I have moved this into the current Milestone.
