### ISSUE TITLE
Marlo contact points for PPA Partners are not added to the crp_users table

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1197]
When registering marlo contact points for PPA partners in FTA, the expectation was that once the contact point has been saved the user will be able to log into that CRP.   

This does not happen.  

On investigation the contact point was not added to the crp_users table and this happens both for existing MARLO users (i.e. registered for another CRP) as well as new users.

**Comment by Grant-Lay** [comment]
Once you confirm the bug, I will need to run the following sql statements so that the two contact points can log into FTA:

INSERT INTO crp_users(`user_id`,`crp_id`,`created_by`,`active_since`,`modified_by`,`modification_justification`,`is_active`)values((SELECT id FROM users u WHERE u.email = 'nsepulveda@catie.ac.cr'),11,3,'2017-11-17 16:11:09',3,'',1);
INSERT INTO crp_users(`user_id`,`crp_id`,`created_by`,`active_since`,`modified_by`,`modification_justification`,`is_active`)values((SELECT id FROM users u WHERE u.email = 'a.poulos@cgiar.org'),11,3,'2017-11-17 16:11:09',3,'',1);

**Comment by AndresFVR** [comment]
Hi Grant, thanks for let us know about this issue, we have fixed it ([Commit f9338d5](https://github.com/CCAFS/MARLO/commit/f9338d513b5cbb7c559f9d2fed7fb053c79f9d84)) and the scripts were run into MARLO.
