### ISSUE TITLE
In reporting CRP mode - changes to a project's cluster activities are not saved

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1200]
Steps to reproduce.  

1.  Open a CRP in reporting mode
2.  Open a project and in the project description page add a cluster of activity using the dropdown menu.
3.  Save the project.

Expected result:   the cluster of activity is added to the project.
Actual result:  the cluster of activity is not added to the project.

I can see from the code that changes to the cluster of activities are not updated when in reporting mode.  If this is a business requirement the user interface should be updated so that the dropdown containing the cluster of activities should be read only.

**Comment by htobon** [comment]
This will be done when we work in the Reporting cycle.
