### ISSUE TITLE
Develop a summary report that generates the POWB 2018 template

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1203]
- [x] Create template with Pentaho Report Designer
- [x] Create POWB action

This is our first approach to allow MARLO to generate the POWB template automatically. 
Therefore, the first step would be just to generate the file with the current template (everything empty, only titles).

Since the format (.DOC) for Microsoft Word is not open source, the document will be generated using the format (RTF) which is free and can also be opened using Microsoft Word or any other document tool.

**Comment by AndresFVR** [comment]
Here is a Example of how it would be generated (Action is ready to be completed with POWB data): 
[POWBSummary-2018_20180130-1906.docx](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/POWBSummary-2018_20180130-1906-ac51b509a3bb31f6cf4aac002240a590031be6ef9718c5c5f5faf5bb0c8d176f.docx)

Note: It is a .docx file due to github doesn't support .rtf files

**Comment by htobon** [comment]
Hi @AndresFVR. 
This is very good. Thks for the update.

Please start working on the quality of the format. (Header, Footer, Margins, Borders, etc.)
Cheers,

**Comment by htobon** [comment]
@AndresFVR, would you like me to close this issue and create a new one?

**Comment by AndresFVR** [comment]
@htobon ok close this issue as it is solved please.
