### ISSUE TITLE
Issue when updating Struts2 to latest version

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1208]
When trying to update struts to the latest version, the internationalization files coming from the CRPs do not load.

**CONTEXT:**
MARLO has two types of internationalization files, the first one is the Global file (global.properties) which contains all the default texts that are being used in general for the entire platform. And the second ones, which are specific files that load depending on which CRP, CENTER or PLATFORM the user has logged in. For example, when the user log in into CCAFS CRP, the files "global.properties" and "ccafs.properties" would be loaded. And the "ccafs.properties" overrides the texts that are defined in "global.properties".

It is also important to know that the "InternationalitazionFileInterceptor.java" interceptor is the one responsible for loading the specific files mentioned above.

**THE ISSUE:**
When we try to update struts2 to 2.5.13 version, it seems the "global.properties" file is loaded, but not the CRP/Center specific files.

Here is an example:
Global.properties vs PIM.properties
In the main menu, PIM named the "Summaries" section as "Reports".

**global.properties**
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-48ba133957d50a77cb1e0c6edb99274b1dc5d141993daa11a77baf736acaf400.png)

**pim.properties**
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-e76ca6920b48863430d63712647315cbdfeca704c2cb26f186fc1648d0bf0d2f.png)

Here is what we see when MARLO is running locally using the new **version 2.5.13**:
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-3f242cc4e6ac0b297f44d9af67341d1b3429e61d650aad454b3188d292e2ae1e.png)

And here is what we see when MARLO is running locally using the older **version 2.5.3**:
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-2d28968dcb3bfe1f7c09e6a8be5c2857be24386c25ecdf4da60c747f77040072.png)

Perhaps we are missing something, but this is not working in our side.

On an additional note, the latest struts2 version released in maven is now the 2.5.14.1, which, perhaps we can use.

**Comment by Grant-Lay** [comment]
@htobon - fixed the issue, but there is one minor issue and that is if a user navigates between CRPs without logging out (i.e. using the crp menu), the first request may show the properties from the previous CRP. As soon as they refresh or do another request, the fields will return to normal.  It seems using a session variable to load different resource bundles (e.g. global.properties, pim.properties etc) is not something the struts2 designers had in mind as there is no easy way to reset the resource bundles between requests.  We might need to revisit this at some stage in the future.

**Comment by htobon** [comment]
Hi @Grant-Lay, thks for your coments on this.
I'll close this issue as this was already tackled and successfully solved a week ago.

The issue about the CRPs will be tackled in the the issue #1201
