### ISSUE TITLE
Green ticks do not appear after the user enters all mandatory fields when struts2 version is 2.5.13

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1209]
**Note that this issue does not appear using the current version of struts2 2.5.10, but we want to upgrade to version 2.5.13 (as the REST api addresses a security vulnerability in 2.5.12).**

When a user creates a new project and enters all the mandatory fields in a page and clicks on save, we expect the green tick to appear in the tab.  Instead the message is displayed that:

`The Information was correctly saved.
Please keep in mind that the fields highlighted below are missing or incorrect.`

Please see the two screenshots showing all mandatory fields complete (this issue is not confined to the project description page but also to the project budget and project partner pages too).

![image](https://user-images.githubusercontent.com/2264925/34753553-4daad972-f5eb-11e7-9cd8-b3bfed6b2bea.png)
![image](https://user-images.githubusercontent.com/2264925/34753561-57740456-f5eb-11e7-822b-06f8dceebdf4.png)

**Comment by HermesJim** [comment]
In this commit ac81598e66922cba01039bb078d1c2567faffd13, I add "if" validator in the missing fields values that was missing in the method that validate these sections (project description and project partners).
Please @Grant-Lay check if the issue has been fixed.
thanks.

**Comment by Grant-Lay** [comment]
@HermesJim the fix works for the project description page but it doesn't work for me for the partners and budget pages.

**Comment by HermesJim** [comment]
Hi @Grant-Lay .
In the commit 58b6cc5, I delete an unused map object, I think it was interfering with the current transaction that is being made in the form (front-end). This issue is also reported by PIM and they already verify their projects correctly whit the green marks.

**Comment by htobon** [comment]
I understand this issue was already solved when we updated MARLO to the new version of struts2. Thank you all for the works on this.
