### ISSUE TITLE
A4NH - Gender: New field for Name/Email of Gender Research for each project

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1211]
Estimated time: 8h

 1. Project Description
- [ ] Add A4NH specificity
- [ ] Add project partner column to project_info
- [ ] Change project description action
- [ ] Change project description validator
- [ ] Change project description ftl 
- [ ] Test in MARLO-Dev
- [ ] Release to Production   

 2. Project Partners
- [ ] Add A4NH specificity
- [ ] Add gender column to project partner
- [ ] Change project partner action
- [ ] Change project partner validator
- [ ] Change project partner ftl 
- [ ] Test in MARLO-Dev
- [ ] Release to Production 

> **Amanda W**: We need the name/email of the person responsible for gender research for each project.

**Comment by AndresFVR** [comment]
I will close this issue as Amanda requested.
