### ISSUE TITLE
A4NH - Gender: Add justification if project is not budgeting gender

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1213]
Estimated time: 5h
- [ ] Add A4NH specificity
- [ ] Add gender justification columns for budget per partner and budget per coas to project_description_info
- [ ] Change project description info model
- [ ] Change description action
- [ ] Change description FTL
- [ ] Test in MARLO-Dev
- [ ] Release to Production   

> **Amanda W:** If the project enters 0% of the budget for gender, then we need a question, like "Please explain why this project is not spending any resources on gender this year."

**Comment by AndresFVR** [comment]
1. The justification will be requested for budget by partners and budget by clusters?
2. Is it a A4HN specificity?

**Comment by AndresFVR** [comment]
I will close this issue as Amanda requested.
