### ISSUE TITLE
A4NH - Summaries (Search terms): Include columns for cross-cutting dimension and gender level of focus

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1214]
Estimated time: 3h
- [x] Add cross-cutting dimension to search terms (Projects sheet)
- [x] Add cross-cutting dimension to search terms (Deliverables sheet)
- [x] Change description search terms action
- [x] Release to Production  

>**Amanda W:**: Search terms (gender) – this spreadsheet should include columns for the cross-cutting dimension (gender) and the gender levels of focus; also, the search function should detect if the project has any gender element (right now it only searches the project description)

**Comment by AndresFVR** [comment]
Search terms report was improved adding cross-cutting dimensions fields and searching by gender,youth and/or capacity development for Projects and Deliverables sheets.

**Comment by htobon** [comment]
Hi @AndresFVR, thanks for this.
can you please always include a screenshot of the new developments?
Thank you in advance.

**Comment by AndresFVR** [comment]
Report generated from MarloDev: [SearchTermsSummary-2018_20180202-1545.xlsx](https://github.com/CCAFS/MARLO/files/1690781/SearchTermsSummary-2018_20180202-1545.xlsx)

Gender, Youth and/or capacity development are red when the word is into the search: https://www.screencast.com/t/jFuStP2t
Same for deliverable sheet: 
https://www.screencast.com/t/QFLfrpwfQ

**Comment by htobon** [comment]
Hi @ajwyatt, 
Just to inform you that we have released this request into production. Please check it and if there is anything that is not working, please open this issue again.
Cheers,
Hector.

**Comment by AndresFVR** [comment]
- [ ] Show Score in deliverables sheet instead of yes or no.

**Comment by AndresFVR** [comment]
We show scoring in deliverables sheet, please refer to the following screenshoot: https://www.screencast.com/t/8F5BmcQo

**Comment by AndresFVR** [comment]
Commit 38cb6a4: Changed how scoring is displayed as requested by @htobon:
https://www.screencast.com/t/3QdLkNJCGO
