### ISSUE TITLE
A4NH - Gender: Add justification on how gender is included on each grant

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1215]
Estimated time: 10h
- [ ] Add A4NH specificity
- [ ] Add gender justification columns to budget per partner and budget per coas
- [ ] Change budget by partner model
- [ ] Change budget by clusters model
- [ ] Change budget by partner action
- [ ] Change budget by partner FTL
- [ ] Change budget by clusters action
- [ ] Change budget by clusters FTL
- [ ] Test in MARLO-Dev
- [ ] Release to Production  

>**Amanda W:** From our gender team: In general, the gender level at the project level is not too useful. It would be very useful to have a description of how gender is included in each grant (i.e., if they say that a grant is 80% gender, what does that mean? Please justify). The descriptions of how gender is incorporated into each project are general and often do not point to how gender is incorporated into the actual work

**Comment by AndresFVR** [comment]
Questions/ Doubts:
1. The justification will be requested for budget by partners and budget by clusters?
2. Is it a A4HN specificity?

**Comment by AndresFVR** [comment]
I will close this issue as Amanda requested.

**Comment by htobon** [comment]
Thank you @AndresFVR,
