### ISSUE TITLE
A4NH - Summaries format suggestions? (Not clear)

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1216]
>**Amanda W:** Format (e.g., ready-to-use variations of the raw data in each tab of the workbook). I’ve sent suggestions. Are my suggestions not useful? Not realistic? Do they have to be agreed upon by the group? Should I re-package them in one file?

**Comment by AndresFVR** [comment]
Questions/ Doubts:
1. What are the suggestions?

**Comment by ajwyatt** [comment]
Can you please look at the Excel file I just sent related to issue #1218? That gives you some idea of what I'm suggesting. It would be better to have an Excel file with multiple tabs - one with all the raw data related to the funding sources, for example. Then, a tab with the funding source information for each managing partner for example. Then, a tab that might be the funding source information presented in a standard way that Tigist shares.

**Comment by AndresFVR** [comment]
This issue will be tackle in #1218
