### ISSUE TITLE
A4NH - Summaries: Create new summary report to list all projects in excel format

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1217]
Estimated time: 12h
- [x] Create excel design: projects
- [x] Create projects summary action
- [x] Test in MARLO-Dev
- [x] Release to Production  

>**Amanda W:** Some on missing reports - Full project report summary – would be useful for this to generate a report of all projects, in Excel format, with cross-cutting (gender) dimension details of projects and the gender levels of focus of deliverables

**Comment by AndresFVR** [comment]
This report has been developed. Check it in MARLO as "List of projects"
