### ISSUE TITLE
A4NH - Summaries: Create or update a summary report for deliverables

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1218]
>**Amanda W**: Highest priority for A4NH is a summary report that shows us deliverables (IDs and titles) and their relationships to funding sources (IDs and titles), MARLO Projects (IDs), CoAs, and Flagships. You’ve mentioned this is too complicated. However, for A4NH (with very few exceptions) – projects are mapped to only one cluster; projects cannot be mapped to more than one flagship. Most funding sources map to 1 project. I think this is possible and I can send you an example.

**Comment by AndresFVR** [comment]
We will need an example?

**Comment by htobon** [comment]
We will look forward to Amanda in order to get an example of what A4NH needs.

**Comment by MargaritaRamirez** [comment]
We will close this issue because is very old, we are exploring the best ways to present this information using our business intelligence.
