### ISSUE TITLE
P&R evaluation Projects

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#122]

**Comment by htobon** [comment]
This process is happening now. I'll put this issue in-progress as I'm available to provide any guidance to the evaluators in case they need it.

**Comment by htobon** [comment]
Support provided to Sonja.
I had to download in PDF format the 19 projects she is evaluating and I explained where to find the instructions as it was hidden in the file.

**Comment by htobon** [comment]
Support provided to Lini this morning. She was requesting access to the budget section on each project. (Budget sections is not being displayed if you are in reporting).

**Comment by htobon** [comment]
Evaluators finished their reports and now we are consolidating the information.
@sebas932 is in charge of getting all the info in one single file to be reported to Philip and Bruce.

**Comment by htobon** [comment]
We are almost done with the project evaluation. 
We are now waiting Philip's feedback (normalizing the scores).

**Comment by htobon** [comment]
Philip sent the feedback on monday July 4th.

**Comment by htobon** [comment]
James Hansen and Andy have responded saying that everything is ok. Still pending the confirmation from flagship 3.

**Comment by htobon** [comment]
I think this process finalized. The only thing is missing now is to organize all the files in the intranet for sharing and organization purposes. Let's close this issue and open a specific one to the next sprint.
