### ISSUE TITLE
A4NH - Funding sources: Add total budget in funding sources list 

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1220]
Estimated time: 5h
- [x] Create Function to calculate budget per FS phase
- [x] Change Funding sources List FTL
- [x] Release to Production 

>**Amanda W:** Is   it possible to add total budget column next to the direct funder on the   funding source list? This helps for accuracy and consistency check without   generating a summary or opening each funding source to just check on totals

**Comment by ajwyatt** [comment]
Would be nice to budget amounts in the table that's on the landing page of funding source section. Suggestion was instead of adding another column (table will be messy), we could add the $ amounts below the budget type.

**Comment by AndresFVR** [comment]
Budget amounts were added to the funding sources section. Refer to the following image: 
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-10705fb40a03504f28336ef6a6a0fcb5f66e616f03c1f7148fb020e161cf8f92.png)

**Comment by htobon** [comment]
Hi @AndresFVR for the work on this.
I'll close this issue as it seems everything seems to be ok.

**Comment by ajwyatt** [comment]
Hi. Sorry for the delay. Tigist sent me this message when I told her what you were planning to do. Feel free to communicate with her directly on how this table can be more helpful to her. Thanks. 

**Im so sorry- this won’t be that much of help. I think we can replace the direct donor with total budget if they are thinking of minimizing no. of columns. I think we refer to the budget more than tracing the original funding source. I was trying to avoid opening each funding source or run a summary just to see total budget. Greatly appreciate if this could be considered. I think it would be much more useful.**

**Comment by htobon** [comment]
Although Tigist responde the last email, it seems she has not seen that we already added the total budget in the table. So, I'm going to close this issue and liaise directly with her. In case there is something missing, I'll re-open this issue again. Hope this makes sense.
