### ISSUE TITLE
A4NH - Summary Funding Sources: Planning 2018 shows deliverables for 2017

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1222]
>**Amanda W:** A4NH has started 2018 Planning. When you generate the funding source summary (for 2018), it includes the 2017 deliverables. How can this be fixed? Right now, we are just removing any data in those columns when we clean up and share these summaries with flagships. However, in January, this limits the usefulness of the summaries for flagship planning meetings and POWB preparation

**Comment by AndresFVR** [comment]
This issue will be solved when annualization is released.

**Comment by htobon** [comment]
Amanda will test it and let us know if everything is ok.

**Comment by ajwyatt** [comment]
I just generated the 2017 deliverables report and the second deliverable in the list is for 2018 (D2273). When I generate the 2017 funding source report, D2273 (a 2018 deliverable) is in the list.

**Comment by ajwyatt** [comment]
@htobon - i would move this as a high priority. Other users are generating summaries from MARLO and discovering that the data in the Excel file has to be manually cleaned. Is there a problem with the way we've entered information in MARLO? Is it clear what the problem(s) are with both kinds of summaries? Thanks.

**Comment by htobon** [comment]
Hi Amanda, I think we are not ready yet with the summaries section after we released the annualization module. In discussion with David on Friday we were thinking to disable the whole section meanwhile we adjust them. Are you ok with this decision? Perhaps we can enable it only for CRP-Admins and PMU team.

**Comment by AndresFVR** [comment]
Amanda W:
> Key question is the same as for the deliverables summary: When you’re looking at 2018 funding, it sounds like we only want to see the deliverables with expected completion years of 2018 (not what was ‘paid for’ last year). Maybe we’re seeing some 2017 deliverables in the list because all of our 2017 deliverables have an unknown status? How can we handle this because it seems like we’ll always start planning before we start reporting, right?

> Seems like there could be some value in having a ‘master’ funding sources summary that shows you all the funding sources, regardless of end dates or status, and then columns for 2017 deliverables, 2018 deliverables, 2019 deliverables. However, when we’re looking at a single year – for the purposes of planning and PPAs – we need the snapshot for the current year.

**Comment by AndresFVR** [comment]
According to the meeting with Amanda we will do the following:

- [ ] Fix 'New Expected year of completion' column to show <Not applicable> when a FS is not extended.
- [ ] Change 'Expected year of completion' to 'Expected year of completion (Initial)'
- [ ] Review that extention date field appear for all CRPs in MARLO.
- [ ] Show FS with status on-going and extended only.
- [ ] Show deliverables of the selected cycle only.

**Comment by AndresFVR** [comment]
Changes were applied in production and development environment.
You can check this summary in the following link: https://marlo.cgiar.org/projects/A4NH/FundingSourcesSummary.do?cycle=Planning&year=2018&format=Excel

**Comment by htobon** [comment]
Thank you @AndresFVR. I'll close this issue. 
Can you please update Amanda about this development in the meeting of today? Thank you in advance.
