### ISSUE TITLE
A4NH - Question about internal approvals for CGIAR Centers

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1223]
At some CGIAR Centers, they have internal approval processes before entering things in MARLO. During planning and reporting, is there a way for managing partners to access MARLO in a draft version for internal use before it gets made public to flagships/rest of A4NH/rest of all other users?

**Comment by htobon** [comment]
Amanda will try to understand what is really the critical issue and will get back to us. 
I'm going to put this issue as low priority for now.

**Comment by ajwyatt** [comment]
I just don't have the bandwidth right now to talk with Bioversity to understand this issue from the Center perspective. I think we should remove it from GitHub and then we should consult on this as a MARLO family (b/c it's not an A4NH specific issue).

**Comment by htobon** [comment]
Hi @ajwyatt, thks for keep us updated. I'll close this. Cheers.
