### ISSUE TITLE
A4NH - Project Managing Partners - Question about who can remove them

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1225]
>**Amanda W:** It looks like only the CRP Admin/PMU can remove Managing Partners once they've been assigned to a project. Is this true? I just want to make sure it's not a bug. In this case, the Managing Partner did not have any funding sources/budget or deliverables associated with them in this project.

**Comment by AndresFVR** [comment]
It is not a bug, only CRP Admin/PMU can remove Managing Partners.

**Comment by htobon** [comment]
Answered.
