### ISSUE TITLE
A4NH - Management Projects - Gender question

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1226]
Estimated time: 6h
- [ ] Add A4NH specificity
- [ ] Change project description info model
- [ ] Change description validator
- [ ] Change description FTL
- [ ] Test in MARLO-Dev
- [ ] Release to Production  

>**Amanda W:** For management projects, is it necessary/appropriate to have a question about what gender analysis informed the design? For A4NH, the management projects will represent our different cross-cutting units and are not necessarily carrying out research. I'm suggesting that we consider eliminating the question and/or making it optional.

**Comment by htobon** [comment]
We will discuss this later with MARLO-Family.

**Comment by AndresFVR** [comment]
I will close this issue as Amanda requested.
