### ISSUE TITLE
A4NH - Funding source: Question about continuing Funding sources in the future

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1227]
>**Amanda W:** If a funding source is continuing for future years, can it keep its MARLO project mapping in those future years? So if a funding source runs from 2017-19, in each planning year, it would automatically be mapped to the same MARLO project that it was mapped to in the previous year. Right now it seems we have to manually re-map the funding sources to the projects in a new planning year.

**Comment by AndresFVR** [comment]
This issue will be solved when annualization is released. 
Funding source's projects will be mapped for future years with budget equal to 0.

**Comment by ajwyatt** [comment]
Great! I'll pass that along to Tigist. (Exploring how GitHub works...please be patient with me if I do anything dumb.)

**Comment by htobon** [comment]
We look forward to hear from Tigist.

**Comment by ajwyatt** [comment]
I've asked her to test it in the production environment and to send MARLO Support an email if she notices that this is not working properly. (Of course this has to wait until we close 2017 planning, which I don't think we will do until next week.)

**Comment by htobon** [comment]
@ajwyatt, ok, we look forward to hearing from her.

**Comment by htobon** [comment]
@ajwyatt, thks. I'm going to close this issue as this seems to be working as expected. Kindly let me know if you don't agree. Cheers.
