### ISSUE TITLE
CIAT - CapDev Module: Develop a submission module

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1230]
Currently the CapDev module does not have a submission system that allow administrators to identify the "interventions" that are completely finished and reported in MARLO.

- [x] Configure CapDev in MARLO Dev (review Users, Activate Section..)
- [x] Develop necessary changes
- [x] Test CapDev Section in Dev

**Comment by sebas932** [comment]
@jhanzuro found and issue and Hermes is pending to fix it

**Comment by htobon** [comment]
Hi @HermesJim, would you kindly let me know why this issue was moved under review? Is there something I should do? This is not clear.
