### ISSUE TITLE
A4NH - Develop a Excel template to allow external people to fill deliverables (For planning)

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1231]
Some times Flagship managers ask for deliverables to other people outside MARLO. The idea here would be to develop a template (in Excel format) that allow them to collect this information before entering in MARLO.

**Comment by ajwyatt** [comment]
Here's what I created and sent our teams. The "sources" for the dropdown lists are hidden in separate worksheets. 
[A4NH - deliverables worksheet.xlsx](https://github.com/CCAFS/MARLO/files/1627792/A4NH.-.deliverables.worksheet.xlsx)

**Comment by jhanzuro** [comment]
Hi @ajwyatt , I was working in this issue and  I created this template, you can make a copy from google docs or use the windows excel:
[Windows Excel](https://github.com/CCAFS/MARLO/files/1640350/Deliverables.Template.xlsx) or [Google Spreadsheet](https://docs.google.com/spreadsheets/d/1wTk1LthA0K0smb0gE41vb82L71lvR6UxA5PVFu82JM4/edit?usp=sharing) (recommended).

Any help, correction or suggestion for improvement is welcome.

**Comment by ajwyatt** [comment]
Hi @jhanzuro . I made some suggestions directly in the Google sheet. Please let me know if you have any questions. I was typing fast and may have not been clear. Thanks!

Based on this week's experience, could you think about how to combine this worksheet with the deliverables summary? You'll see that the deliverables summary has the information in a different format than this worksheet. So, if you're trying to send someone a worksheet with the 2018 deliverables that are known from MARLO plus give them space to add NEW deliverables for planning, it requires a lot of reorganizing. I suggest you either make this worksheet like the deliverables summary or vice versa.

**Comment by ajwyatt** [comment]
Here's an example showing you how I'm trying to combine the two sources of information (2018 deliverables already in MARLO + empty space to add NEW 2018 deliverables)
[A4NH - deliverables worksheet for FP4 only.xlsx](https://github.com/CCAFS/MARLO/files/1661461/A4NH.-.deliverables.worksheet.for.FP4.only.xlsx)
.

**Comment by htobon** [comment]
Hi @ajwyatt, thanks for the suggestion.
Is there anything we can help here? I can see that everything is under control on your side.
Perhaps we can discuss this issue tomorrow in our meeting.
Cheers,

**Comment by ajwyatt** [comment]
@htobon . I had to move forward and create something for A4NH. However, I thought this 'issue' was because you saw a need to create something like this for CCAFS and other CRPs. Right? So, my suggestions are (I think) relevant to help create a standardized, usable form for all MARLO users. You are right though - it's not a high priority for A4NH at this moment. Thanks!

**Comment by htobon** [comment]
@ajwyatt ok. So, I'm going to close this issue. This will be kept here in case we want to work on this later. Thank you!
