### ISSUE TITLE
PIM - Deliverables Classification for Managing Projects

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1237]
**Technical tasks:**
- [x] Create specificity for CCAFS
- [x] Insert new sub-categories into the database
- [x] Develop an equivalent table between the two lists
- [x] Validate the equivalent table with MARLO-Family
- [x] Move old records to the new sub-categories
- [x] Program the code to load the specific sub-categories for all the CRPs except CCAFS
- [x] Release into the testing environment
- [x] Release into the the production environment
- [x] Communicate MARLO-Family about this development
- [x] Write a blog-post

Please modify the current categories we have for Managing Partners and replace them by:
> Plan/strategy; Concept note; Communication material; impact assessment/evaluation report; Other report

Those categories must to appear only for Management Projects under the category "Governance, Administration & Management" in all the CRPs **except CCAFS**.

On the other hand, as per Dhanush's suggestion, CCAFS should keep the old categories.

**-------------------------DISCUSSION--------------------------------**

**Email Subject:** Deliverables classification decision pending

*December 5th, 2017*
>**David Abreu:**
>There are two pints for decision:

> 1.	We need to decide on the sub-categories and thus far we have two sets: 
>  A.      Used by CCAFS
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-42ecd615790d30ce340ec96eaf6fa3d6cb36b094594ce679bc9e602bc8823efe.png)

>  B.      Used by PIM:
> Plan/strategy; Concept note; Communication material; impact assessment/evaluation report; Other report

> 2.	We need to decide whether you find these sub-categories available to choose from:
>  C.      only in “Management” Projects, or 
>  D.      in both (Research and Management Projects)

Results of the vote:
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-fbbd4be13f06fa6d2f3a73c7971d99b5e30dd608eab9d1c6ff20fa1a6d205caf.png)

**Comment by AndresFVR** [comment]
This develop was released to production.

CCAFS:  https://www.screencast.com/t/N1GIPvae
Others CRPs: 
-PIM https://www.screencast.com/t/N1GIPvae
-A4NH: https://www.screencast.com/t/zBLlL3XXFMH

**Comment by htobon** [comment]
Blogpost published:
https://marlo-news.blogspot.com.co/2018/01/deliverables-classification-for.html

**Comment by htobon** [comment]
Good job @AndresFVR.
