### ISSUE TITLE
POWB - Deliverables: Change gender levels

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1242]
Table C. in POWB

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-09a45c4da18b08f3cedf61f0dde9a400963bf05e4dab5f484497b936e687e07d.png)

**Comment by htobon** [comment]
@sebas932 and @jurodca, Please refer to the following couple of improvements after testing this development:

- [ ] Please make the question about gender levels as read only in case the project leader has responded it before. Otherwise, please hide it. We should not ask the old list for new deliverables.
See screenshot:
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-ebafd44ba0fda4bd306621ce4f66201ed0c721c0d9a2773ccf2623d4ee0c2d43.png)

- [ ] The history of changes module is not working for that field.

**Comment by htobon** [comment]
In addition to the above, I have sent an email to A4NH requesting what to do with their gender levels vs the ones defined in the POWB template. Please follow-up their response in the email with subject "POWB - Gender Levels for A4NH"

**Comment by jurodca** [comment]
The last issues were fixed.

**Comment by htobon** [comment]
@jurodca, please release it into production.
