### ISSUE TITLE
POWB Adjustment - Budget by Flagship

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1243]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-00d777da2f89c1c20ea4bcf7694785897607cb383d2ce2cf71a88ead15011650.png)

**Comment by htobon** [comment]
I have sent a survey just now asking MARLO-Family to let us know which roles in MARLO will be able to edit each of budget types. The deadline for this poll is Friday 26th.

@HermesJim, please follow up on the results of the survey. This issue will not be closed until we have all the answers from the CRPs.

**Comment by htobon** [comment]
**Privileges:**
- [ ] A4NH
- [ ] CCAFS
- [ ] FTA
- [ ] Livestock
- [ ] MAIZE
- [ ] PIM
- [ ] WHEAT
- [ ] WLE

**Comment by HermesJim** [comment]
Hi, I Setup the section permission in all the CRP's according to the document.

**Comment by htobon** [comment]
@HermesJim, can you please confirm if this is already in the production environment?
In addition, is this also applied in the testing environment?

Thank you in advance.

**Comment by htobon** [comment]
@HermesJim, please confirm.

**Comment by HermesJim** [comment]
Hi @htobon                        
Yes, the section is already in production and also in testing environment.

**Comment by htobon** [comment]
Great! Thank you @HermesJim
