### ISSUE TITLE
POWB - Expected Studies (Outcome case studies, impact assessment and adoption studies)

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1245]
Table B in the POWB.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-395059934b0ac88e9204dc4cfc5afff5f4be9c01d21ec05ac3b32a6c6182a963.png)

**Comment by cgarcia9106** [comment]
@htobon  puedes probar en http://marlodev.ciat.cgiar.org/powb

**Comment by htobon** [comment]
Thank you @sebas932 and @cgarcia9106.
Can you please include the section described in the image below? The idea is that all those items should be multi-projects

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-5f69f5cc13086af7980d7f9bfec385690acafb7fed8bfb7755e624fc63a954df.png)

Rule: Only the owner of the Study can edit it. The other one can just read it.

**Comment by htobon** [comment]
After some tests:
- [ ] Dropdown list of projects needs to load only on-going projects.
- [ ] The whole section is optional
