### ISSUE TITLE
Livestock - Review roles

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1248]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-b73b6022d3eb292f737d8db462ba00b49855b322152394315f515cd13b5c47c3.png)

**Comment by cgarcia9106** [comment]
@sebas932 por favor revisar

**Comment by htobon** [comment]
I just have sent an email to Jane today informing that we adjusted the roles to fit Livestock needs.
