### ISSUE TITLE
Closing phases in the crp admin phases section leads to all phases disappearing

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1252]
To reproduce the issue go to the crp admin section and close all but one of the project phases and press save.  The expected result is that the list of phases appear showing one project phase open, but instead all the phases disappear and the text 'No Phases in the system' is displayed.

**Comment by Grant-Lay** [comment]
I think if a user closes all the phases, the list of phases should not disappear so that someone can correct the mistake (I assume the system requires at least one open phase?).  Therefore I have changed the logic to check to see if the list of phasesAction (instead of phases) is greater than zero (not 1) as this is the complete list of phases in the database rather than the list of open phases.

@sebas932 is it possible to have some validation on the client side that checks that at least one phase is open and if not disables the save button and presents a message to the user?   If not this validation logic could potentially be done on the save() method on the backend.  I've also noticed that the timeline doesn't seem to display correctly if there is only one open phase (despite also changing the logic in the timeline.ftl to `#if phases?size > 0`)

**Comment by sebas932** [comment]
Sure @Grant-Lay, i'll apply an small validation using Javascript to prevent save if there isn't at least a valid phase

**Comment by sebas932** [comment]
Hi @Grant-Lay, i've applied some changes in order to fix this issue, please let me know if it works as well

**Comment by htobon** [comment]
Hi @Grant-Lay, I'm going to close this issue. As per your consideration, please re-open it again if there is something we could be missing. Cheers.
