### ISSUE TITLE
BUG front-end: Project description label

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1256]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-65526f47c7c16325bfd1d37330bb3a2f9e7cc0d93c48fe0ffe1ade82f1c9df65.png)

**Comment by htobon** [comment]
This is still happening in the testing environment. Please make this fix quickly there. And please explain why this is happening in the testing environment and not in production.

**Comment by jhanzuro** [comment]
Fixed, There was different code in a macro in the testing environment and production.

**Comment by htobon** [comment]
Thank you.
