### ISSUE TITLE
BUG: When registering a user for the first time, the account was set to inactive

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1257]
When registering Joyce Kasyoki from ICRAF to MARLO and assigning her flagship manager privileges, her account was set to is_active = 0 and she was unable to logon.

I manually set her account to is_active = 1, but would like to make sure that this will not happen again for future new users.

Steps to reproduce:

1, Login to FTA as a crp_admin
2. Go to crp_admin section and add a brand new user to MARLO as a flagship manager.
3. Click save in the crp_admin section.
4.  Check the database and see if the user's account is active.

**Comment by htobon** [comment]
Hi @Grant-Lay, just to inform you that @cgarcia9106 fixed the issue in this commit https://github.com/CCAFS/MARLO/commit/10ef1d89a4dc5996121048169c8ff6759dd0744a

What was happening is that when the saveUser method is called, the user is extracted from the database and the updated get losts. So, Christian tried to solve the issue by creating a new Array and changing the "is_active" parameter there.

If you find a better way to do it, kindly let us know and we learn.

Cheers. Hector.

**Comment by htobon** [comment]
@Grant-Lay please close this issue when you read it. Thank you.

**Comment by htobon** [comment]
Hi @Grant-Lay, we have not heard back from you. So, I'll close this issue. Kindly let us know if the issue persists. Cheers.
