### ISSUE TITLE
A4NH - Summary Deliverables: Planning 2018 shows Funding sources for 2017

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1259]
> Key question: 
 • If deliverables are extended into a new year, what funding should appear? When you’re looking at 2018, you want to see the 2018 funding for that deliverable and do you want to see what funding was used in 2017, as well? Or, do you only want to see the 2018 funding being used to complete something that was promised in 2017? 
Right now, the summary is showing you all sources of funding that were ever used for that 2018 
If you only want the funding being used in 2018, for some extended deliverables the funding source IDs and Funding Window(s) columns will be empty. Unless, we could create a ‘rule’ so that in these cases, the summary would show ‘no current year funding’ in those columns. MARLO technical team – is that possible to do? Tigist – would that be helpful? 

> Other points…
• Since this is a summary for 2018, it should be limited to only what we expect to be completed in 2018. Would suggest that it not include deliverables that have been entered for other years. Anything in grey should not appear in this worksheet. 
• Not sure I understand the ‘new expected year of completion.’ We’re in planning year 2018. For 2017 deliverables that have been extended, this worksheet would show the expected year as ‘2018’ and the status as ‘extended.’ I don’t think we need this column in planning, but of course, we need it in reporting. 
• Highlighted cells – suggested changes to the wording. 

[Copy of Jan24 - 2018 planning issues with summaries.xlsx](https://github.com/CCAFS/MARLO/files/1664855/Copy.of.Jan24.-.2018.planning.issues.with.summaries.xlsx)

**Comment by AndresFVR** [comment]
According to the meeting with Amanda we will do the following:

- [ ] Show Deliverables of 2018 only.

- [ ] Add a new column to the deliverables report as follows: https://www.screencast.com/t/P6YEiGgJ
If the report is from 2018, Finished Funding will be those that ended at 2017.

- [ ] Wording in the Highlighted cells.

**Comment by AndresFVR** [comment]
Only deliverables of the selected year/cycle will be in the report: https://www.screencast.com/t/hIBhnbbBjIE
A new column was added to separate Open and Finished FS: https://www.screencast.com/t/mcC1AEY6
Open FS: 
- Those FS that have 'end date' greater or equal to the selected year and an on-going status.
- Those FS that have 'extention date' greater or equal to the selected year and have an extended status.
Otherwise, those are classified as Finished FS.

Changes to highlighted cells were also applied.

**Comment by htobon** [comment]
Thank you @AndresFVR, can you please improve the names of the columns as follows?

- [ ] Instead of "Open Funding", please replace to "On-going Funding Sources".
- [ ] Instead of "Finished Funding", please replace to "Archived Funding Sources".

Once this is done in the production environment and in the testing environment, please feel free to close this issue.

Cheers.

**Comment by AndresFVR** [comment]
This change is in the testing and production environment.
I will close this issue.
