### ISSUE TITLE
Deliverables: Update deliverable types classification into MARLO

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1268]
@HermesJim, please take a look at my latest email with subject "Classification of deliverables in MARLO" as well as the new Type and Sub-type proposed by MAIZE/WHEAT:

![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/c9b71376-3a0b-4894-8b5a-577ec709530a)

**Comment by HermesJim** [comment]
The Reclassification of the Deliverables types has been applied.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-b618e18d98c14e90b3cfe891efb89be10060ddf2917867a8f22d8f19ad01f7c1.png)

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-76a023bcdb274bad85b30cf78158541169a8573e0e2a288b444cf838d6104d14.png)


Also, I Added the new deliverable type Classification. 

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-5f12e01160eed8919c356f43f0bb9a77d0f06ebafb799d4cbb00984ed4c9f788.png)

**Comment by htobon** [comment]
@sebas932 Podrías por favor explicar aquí cuáles fueron los cambios exactos que hiciste?
Gracias.

**Comment by HermesJim** [comment]
Se reemplazo los tipos de Deliverables de acuerdo al correo de Paola; el cual era generalizar los tipos peer-review y non-peer-review. Por ejemplo Book (non-peer-reviewed & peer-reviewed) por solo Book. 

Se remplaza los _Journal Article_ y se re-categorizan en el tipo _Article for media_...

Y por ultimo se agrega los nuevos tipos de Deliverables de CIMMYT.

**Comment by HermesJim** [comment]
Toda esta información también se actualiza en los deliverables que tenían relacionado algunos de estos cambios.

**Comment by htobon** [comment]
@HermesJim, if this done, can you please close this issue? thank you in advance.

**Comment by htobon** [comment]
Hi @HermesJim, 
Can you please also include the following categories?

![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/5a2f4fa9-0955-4b4d-aab4-931321f5d451)

Cheers,

**Comment by HermesJim** [comment]
Hi, I Added the Deliverable categories.

**Comment by htobon** [comment]
Thank you. I will close the issue and, depending of what David responds us tomorrow, we open it again.

**Comment by htobon** [comment]
Hi @HermesJim, kindly let me know when the categories marked in white background color are in the system. thank you.

**Comment by HermesJim** [comment]
![image.png](https://images.zenhubusercontent.com/5798ae8de40e5714b16c9812/9fa155a1-ad3b-4c3a-9496-45aa908bd626)

**Comment by HermesJim** [comment]
![image.png](https://images.zenhubusercontent.com/5798ae8de40e5714b16c9812/10550307-0dad-4d0f-8a18-50469859797c)

**Comment by htobon** [comment]
This is becoming a little bit complicated. Sorry for opening this issue again.
since there has been a discussion in the MARLO-Family about the addition of these new categories in the current taxonomy, @HermesJim, can you please  make them available for MAIZE and WHEAT only? Thank you in advance.

**Comment by HermesJim** [comment]
Hi @htobon  
The changes has been applied in production and test.

![image.png](https://images.zenhubusercontent.com/5798ae8de40e5714b16c9812/4022eea8-49be-49db-819c-753357ec1c71)

**Comment by htobon** [comment]
Thank you @HermesJim                        .
