### ISSUE TITLE
Impact Pathway: Develop rules to allow Flagship Leaders to adjust the impact pathway in 2018

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1269]

**Comment by cgarcia9106** [comment]
https://slack-redir.net/link?url=https%3A%2F%2Fgithub.com%2FCCAFS%2FMARLO%2Fcommit%2F9424ffdf00a5361f263f0990d24cb540afaec8a8

**Comment by cgarcia9106** [comment]
https://github.com/CCAFS/MARLO/commit/9424ffdf00a5361f263f0990d24cb540afaec8a8

**Comment by cgarcia9106** [comment]
https://github.com/CCAFS/MARLO/commit/79042cc2d9b84bc64ba323f2f1e9702f9835426a

**Comment by sebas932** [comment]
The Key outputs outcomes contributions were validated and can't be deleted if there are associated projects
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-6feea9cb171439cc5c822d26df3b4748dde04084f20a0272dcd91265b620287b.png)

**Comment by sebas932** [comment]
The milestones from previous years are only for reading mode

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-97b9f6d131e1ff291a1182f3412fb847f6a48bf0515672b7e6c776444bb23930.png)

**Comment by sebas932** [comment]
@htobon the rules above were implemented and working in the production environment

**Comment by htobon** [comment]
@sebas932 kindly implement this development in the testing environment.

**Comment by htobon** [comment]
I have been informed by @cgarcia9106 that this is also implemented in our testing environment. So, I will close this issue.
