### ISSUE TITLE
OaiPmhServer can not connect

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#127]

**Comment by cgarcia9106** [comment]
I will write  to for help
aorth@mjanja.ch

**Comment by htobon** [comment]
Please write a draft of the email to me so we can contact him together

**Comment by cgarcia9106** [comment]
Vamos a llamar a este serivcio, para obtner los metadatos. https://cgspace.cgiar.org/rest/items/{item_id}/metadata
