### ISSUE TITLE
POWB Synthesis - Section: 1.1 Adjustments/ Changes to Your Theories of Change

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1270]
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/7620dbe0-7feb-46a7-a093-28b158d7c35e)

**Comment by HermesJim** [comment]
This section is deployed in the test environment .
Please review it and close if all the functionalities is done.

**Comment by htobon** [comment]
Hi @HermesJim, here is my feedback.

- [ ] Please keep the format in the PMU table according to what was entered in the Flagship fields (e.g. new lines)
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/75a07090-eefc-405d-aa07-bbfd99e7edd5)
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/b1159105-7ec4-47d0-a359-bcce4f78e196)

- [ ] Please check if the file annex is required or not
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/017df232-1a34-48ab-b451-41b3c71076eb)

**Comment by HermesJim** [comment]
This section is deployed in the test environment . With the Suggestions.

**Comment by htobon** [comment]
Hi @HermesJim and @sebas932, would you please let me know the status of this issue?
Thank you.

**Comment by sebas932** [comment]
Hi @htobon is ready for testing in MARLO Dev

**Comment by htobon** [comment]
Thank you @sebas932 and @HermesJim
