### ISSUE TITLE
POWB Synthesis - Section 1.5 Cross Cutting Dimensions

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1271]
![image](https://user-images.githubusercontent.com/4406128/35840352-b97abb30-0ac3-11e8-8bbf-76095bf38bdd.png)

**Comment by sebas932** [comment]
Ready for testing in MARLO Dev

**Comment by sebas932** [comment]
I found a couple of issues, @HermesJim can you helpme carry out this ?

- [ ] Duplicated Flagships in PIM CRP
![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/487a37ba-f389-4750-bb4a-79b68e60ac99)

- [ ] The table C does not work in PIM, no deliverables/outputs counted
![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/63828afa-c3c6-4d19-8626-fec7dda3a5c0)

**Comment by htobon** [comment]
Feedback:
- [ ] Replace outputs to "deliverables"
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/2c108b59-7b05-4f78-a047-cd49db3b83da)

- [ ] Phrasing changes
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/eed79390-7e72-4bf3-9421-c04e322e4680)

**Comment by htobon** [comment]
@HermesJim, would you please let @sebas932 and me know about the status of this section, as well as the issues reported by Sebastian 5 days ago?

**Comment by HermesJim** [comment]
Hi @htobon                        
Finishing this day.  I'll make the changes and upload into to dev.

**Comment by htobon** [comment]
Hi @HermesJim 

Here is the feedback:
- [ ] Table not working.
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/e1b4fd8e-6593-43cb-8fdc-f084488f5b28)
