### ISSUE TITLE
POWB Synthesis - Section: 1.3 Obtaining Evidence on Relevant Outcomes and Impacts

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1272]
![image](https://user-images.githubusercontent.com/5375915/35568573-7c5ed500-0597-11e8-8cc6-df3203b5b638.png)

**Comment by HermesJim** [comment]
This section is deployed in the test environment .
Please review it and close if all the functionalities is done.

**Comment by htobon** [comment]
Hi @HermesJim and @sebas932, I am afraid this section was not well conceptualized.
Please schedule a meeting with me ASAP.

**Comment by sebas932** [comment]
We decide to revamp this section and include in the next sprint

**Comment by htobon** [comment]
Feedback:

- [ ] Include link to expected study:
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/244842c1-2d04-47bb-887f-3b727512d7f3)

- [ ] Rephrase column
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/851f892c-285f-4889-93d1-5da86742f1f2)

**Comment by HermesJim** [comment]
@htobon                        
The Changes has been implemented in Dev.
