### ISSUE TITLE
Funding sources: Move finished Agreements into the "Finished" tab.

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1274]
Currently, when we open a new planning cycle (e.g. Planning 2018), all the funding sources are kept in the "On-going" tab with the idea that the respective Finance Managers, PMU, etc. go through each of the funding sources (previous to start the project planning) and close those funding sources that actually ended in the previous year.

However, this can be a very exhaustive process and we think MARLO can help.

Therefore, the idea is that, as soon as we open MARLO for a new planning cycle, all the funding sources that finalized in a previous year will be moved to the "Finished" tab automatically. Them, if someone wants to re-open a funding source, he/she just have to change its status.

**Comment by cgarcia9106** [comment]
https://github.com/CCAFS/MARLO/commit/6ffb7fdc6461f8464376683545155d7b81578f0c

**Comment by cgarcia9106** [comment]
https://github.com/CCAFS/MARLO/commit/a9fa1747b5a40ab003664dfdc35698b9f90448e4

**Comment by htobon** [comment]
Thank you @cgarcia9106
