### ISSUE TITLE
Funding Sources: Extension Date field

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1275]
Currently, there is no extension date in the funding sources section.
Thus, the idea is that if a funding source is marked with the status "extended", a new date will be asked and the previous "End Date" will be disabled.

This can also be used for opening a finished funding source.

**Comment by htobon** [comment]
After some tests here is what we need to develop:
- [ ] SA hide Extension date:
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/482c66ff-95cf-4383-868a-16798580dec0)

- [ ] CG After changing the status of a funding source from Complete to Extended to Complete and to Extended again, some information got lost.
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/7bedf78d-d584-4733-b9ab-77a5f0b2f0ee)

- [ ] Agreement status is not loading after synchronizing with CIAT-OCS
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/9747b85a-1428-4cf7-985a-010dd879bf28)

**Comment by cgarcia9106** [comment]
Funding sources not activated when I changed the status to on-going:

in the specific case of the screenshot is because we are in 2018 and the end date is less than 2018

for the rest of cases it is operated in the best way

**Comment by sebas932** [comment]
The Extension date was validated with the OCS Sync service

![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/2d665fb5-ea4e-40ad-b8a6-f8b95037f4d9)
