### ISSUE TITLE
Bilateral Funding Sources as conceptNote/Pipeline with future dates appear in finished tab

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1277]
Steps to reproduce:

1.  Login to FTA with Crp admin access.
2.  Go to funding sources page and click create new funding source
3.  Add partner managed funding source = CIFOR, title = testProposal.
4.  Add start date as future date e.g. April 2018 and end date = March 2022.
5.  Select Funding Window = Bilateral and Agreement Status = ConceptNote/Pipeline
6.  Enter prinicipal investigator = Grant Lay, Direct Funder = USAID.
7.  Click save.

**Note that after saving the funding source information appears in read only format except for the Agreement Status.   Also note that the Agreement Status options no longer include ConceptNote/Pipeline or Informally Confirmed**  

Go back to the funding source list page.  

Expected result = the funding source appears in the On-Going tab.
Actual result = the funding source appears in the Completed tab.

To make it appear in the On-Going tab the user needs to change the agreement status to On-Going.  But doing this is incorrect for a proposal where funding is not yet guaranteed.

**Comment by cgarcia9106** [comment]
El problema era que habia un .js que cambiaba los estados dependiendo del type del FS, se removio y se dejaron los estados como estan hoy en dia

**Comment by htobon** [comment]
Hi @Grant-Lay, what @cgarcia9106 meant to say is that this issue was already fixed.
What was happening is that there was a Javascript that, depending on the funding source type, it was replacing the dropdown status field by selecting a wrong value.

Would you please close this issue when you read it?
Thank you in advance.

**Comment by Grant-Lay** [comment]
@htobon @cgarcia9106 - so I have tested locally and the options *Concept Note/Pipeline* and *Informally Confirmed* no longer appear when entering bilateral funding sources.  Is this what the fix is?  I thought having the ability to show which funding sources were still proposals was quite a good feature, but perhaps I missed that discussion in the MARLO family.

**Comment by htobon** [comment]
Hi @Grant-Lay, that is a good point.
For now, and as per a MARLO-Family discussion focused on the POWB adjustments, the agreement status will be the same as we have with other components in the system (Complete, Extended, Cancelled, etc.). 

However, I was thinking that perhaps we should include another option to tackle this kind of information. Perhaps having a question to get the funding source type with more or less the following options: Concept Note/Pipeline; Informally Confirmed; Signed.

I'll propose this to David. 
Cheers,

**Comment by htobon** [comment]
Hi again @Grant-Lay.
After a further discussion with David and the technical team, we decided to include these two options as part of the list of funding source statuses.
Thank you for letting us about this. Cheers.

**Comment by Grant-Lay** [comment]
Closing this now as the two options are back.  Thanks!
