### ISSUE TITLE
Oops page: Managing exceptions when happening in the Custom Filter

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1278]
Usually, when the system throws an Exception, the user is automatically redirected to an “Oops Page”. This is intentional as the “Oops page” is managed by an Action that sends and email to MARLOSupport with the details of the error (a track trace). In addition, this is more user friendly because the user will never see an error like the screenshot below.

It seems then this expected behavior is not implemented when the error occurs in the Custom filter that was  implemented a long time ago “MARLOCustomPersistFilter”. So, the idea is that if some exception occurs within that filter, the user must be redirected to the UnhandledExceptionAction.

![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/5bb0c70d-d4c6-421d-900b-a091bf871f57)

**Comment by Grant-Lay** [comment]
This is a complicated issue as the Exceptions that are being caught in the filter (they happen on transaction commit) are not easily able to be handled by Struts2 (the struts2 filter has already completed processing).  This is one of the downsides to using the open session in view pattern for database transactions.  Remember using this pattern was a quick win - the better solution would be to have coarse grained transactions on the service/manager layer which gives the web framework (e.g. struts2) the opportunity to handle failed database transactions.  Unfortunately our Struts2 actions will require major refactoring to be able to move to this model.

What we can do is to have a static html page that doesn't use any freemarker templates for 500 exceptions.

**Comment by Grant-Lay** [comment]
@htobon @cgarcia9106 can you please review and if happy with the design get @sebas932 to make the html page nicer?  Please note it won't be able to use freemarker templates, so you won't really be able to reuse the existing 500.ftl code.

**Comment by Grant-Lay** [comment]
By the way if you want to test the fix out, the best way is to go to the MARLOCustomPersistFilter and on line 98 add the following code block: 

`      if (requestUrl.contains("fundingS") && "POST".equals(httpRequest.getMethod())) {
        throw new RuntimeException("test error page");
      }`

Then open a funding source and try and save a change.

**Comment by Grant-Lay** [comment]
Please note that web.xml is now referring to servlet version 3.0.  We can upgrade to 3.1 if everyone uses tomcat > v8.  

I had a feeling that I had already changed the web.xml to use version 3.0, but perhaps during a merge it got reset back to 2.4.  Strange.

**Comment by cgarcia9106** [comment]
https://github.com/CCAFS/MARLO/commit/fd7a30a13fca0bbe0bcea41a58332e9d46f4d3b0

 we redirect with js to the same action that manage the expections and put a message to the email MARLOCustomPersistFilter ERROR

**Comment by htobon** [comment]
Hi @cgarcia9106, thank you for the work on this.
@Grant-Lay, just to elaborate a bit more on Christian's message above.

So, basically what we did was a Javascript redirection to the current Action that is managing the error. We tested it and the user actually get redirected to the existing "Oops page" and we are indeed receiving the Exception via e-mail.

@cgarcia9106 was trying to do this redirection using the web.xml, specifically by using the tag <error-page>. And we think there is a way to redirect it into a Struts2 Action instead of a HTML.

**Comment by Grant-Lay** [comment]
Potentially you could do a redirect to unhandledExceptionAction.do in the MARLOCustomPersistFilter.  Is the exception stack trace getting passed to the Action using the javascript solution?

**Comment by htobon** [comment]
Not yet. We don't know how to do it. Right now we are just receiving the email with a defined exception.


![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/1d64a3d6-11aa-4a50-9c58-93a9ee831551)

**Comment by cgarcia9106** [comment]
Hi @Grant-Lay   we already get the expection through the http request

**Comment by htobon** [comment]
Awesome. Thks @cgarcia9106.
