### ISSUE TITLE
Project activities link

### ISSUE THREAD

**Issue by jhanzuro** [CCAFS/MARLO#1279]
When a link like this one https://marlo.cgiar.org/projects/CCAFS/activities.do?projectID=249&edit=true&phaseID=26#projectActivity-2848 includes an specific activity (#projectActivity-2848), the system should redirect to that activity, not to the list of activities.

**Comment by jhanzuro** [comment]
![projectactivitieslink](https://user-images.githubusercontent.com/30579639/35929812-59900978-0bfe-11e8-9f9d-a6af32ca7c77.gif)

**Comment by htobon** [comment]
Thks!
