### ISSUE TITLE
Date sorting in FundingSources list page is sorting by name of Month not Date for EndDate column

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1280]
The FundingSource List page sorts on all columns including the  end date.  When trying to sort FTA's funding sources (over 10 pages) the sorting is not by date but instead alphabetically by month.  Funding sources with an end date of April appear first as a result.

**Comment by htobon** [comment]
Hi @jhanzuro, can you please tackle this issue? Thank you in advance.

**Comment by jhanzuro** [comment]
This is Fixed.
![datesortingfs](https://user-images.githubusercontent.com/30579639/36097828-93a88408-0fca-11e8-8443-3691cbf3236b.gif)
