### ISSUE TITLE
Deliverables: Extended deliverables in 2017

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1282]
Please improve the deliverables section as per below:

- [x] Deliverables that were extended to 2017 should contain the green check mark and must be read only. The year field must be editable.
- [x] Instead of the initial expected year, please include the extended year in the "Delivery year" column.
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/0252f584-7e98-464e-8351-e1683b44d7fc)

**Comment by htobon** [comment]
I have been informed that this issue was finished.. however, after a first check.. it is not.
Please refer to the following image:

![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/f7152581-f669-4b89-9c08-f1707e084aa1)

**Comment by cgarcia9106** [comment]
![image.png](https://images.zenhubusercontent.com/5a71d6f04b5806bc2bc50ac9/a0f6abc6-a3fb-4852-9180-36bbf6435465)

**Comment by cgarcia9106** [comment]
![image.png](https://images.zenhubusercontent.com/5a71d6f04b5806bc2bc50ac9/e218d3ea-fca1-4442-a769-3c621fbb34cc)

**Comment by htobon** [comment]
Thank you @cgarcia9106.
