### ISSUE TITLE
F4 CCAFS Impact Pathways corrections

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1283]
- [x] Key Output 1: Drop Outcome 5
- [x] Key Output 2: Add Outcome 3.
- [x] Key Output 4: Add Outcome 3.  
- [x] Key Output 6: Add Outcome 2 and Outcome 5.  Drop Outcome 4.
- [x] Key Output 7: Add Outcome 2. Drop Outcome 4.
- [x] Key Output 11: Drop Outcome  4.
- [x] Key Output 13: Belongs to CoA 4.3, not 4.4.
- [x] Key Output 17: Drop Outcome 1.  Add Outcome 3 and Outcome 5.

**Comment by sebas932** [comment]
**Key Output 1: Drop Outcome 5**
	- Removed deliverables key output relation from (D433, D334, D368) in P42
	- Removed Outcome 5
	> Note: There was an unactive deliverables that appear in the relations list, Christian have fixed the issue


**Key Output 2: Add Outcome 3.**
	- Outcome 3 was added
	
**Key Output 4: Add Outcome 3.**
	- Outcome 3 was added
	
 
**Key Output 6: Add Outcome 2 and Outcome 5.  Drop Outcome 4.**
	- Outcome 2 was added
	- Outcome 5 was added
	- Removed deliverables key output relation from (D1239, D1234, D2235) in P46
	- Removed Outcome 4
	

**Key Output 7: Add Outcome 2. Drop Outcome 4.**
	- Outcome 2 was added
	- Removed deliverables key output relation from (D143, D187) in P42
	- Removed deliverables key output relation from (D322, D2137) in P48
	- Removed Outcome 4
	> Note: There was a technical issue removing Outcome 4 that Christian have fixed


**Key Output 11: Drop Outcome  4.**
	- Removed Outcome 4
	
**Key Output 13: Belongs to CoA 4.3, not 4.4.**
	- Removed the Key Output 13 from CoA 4.4
	> Note: There was a technical issue removing the Key Output 13 that Christian have fixed

**Key Output 17: Drop Outcome 1.  Add Outcome 3 and Outcome 5.**
	- Removed Outcome 1
	- Outcome 1 was added
	- Outcome 5 was added
		
	
================================================================


**Key Output 1**=Methods and tools to improve agricultural monitoring; forecast impacts of seasonal climate and extreme events on crops and biological threats; extend lead time and accuracy of food security early warning

**Key Output 2**=Guidance on interpretation and appropriate use of climate change projections 

**Key Output 4**=Evidence and insights from CSVs (with FP2), climate service pilots and national implementation initiatives

**Key Output 6**=Institutional arrangements that foster sustainable co-production of services with relevant agencies and targeted rural communities

**Key Output 7**=Tools and evidence to improve the nature, timing or targeting of climate-informed agricultural planning and food security interventions.

**Key Output 11**=Approaches for sharing knowledge and building capacity to provide effective agricultural insurance at scale, including South-South learning

**Key Output 13**=Approaches for sharing knowledge and building capacity to provide effective agricultural insurance at scale, including South-South learning

**Key Output 17**=Cost-benefit analyses of alternative climate services investments at national to regional scales, and of open vs. restrictive data policies

**Outcome 1**=8 of million farm households with improved access to capital, with increased benefits for women (millions)

**Outcome 2**=40 of institutions or major initiatives that use CCAFS research outputs for services that support farm households' management of climatic risks

**Outcome 3**=$ USD new investments by state, national, regional and global agencies, informed by CCAFS science and engagement

**Outcome 4**=20 of development organizations adapting their plans and directing investment to increase women's access to, and control over, productive assets and resources through gender-sensitive climate-based advisories and safety nets

**Outcome 5**=# of policy decisions taken (in part) based on engagement and information dissemination by CCAFS

**Comment by htobon** [comment]
Thank you @sebas932. I have communicated this process to Alison a Jim.
