### ISSUE TITLE
Summaries - Funding Sources Summary

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1285]
- [x] Projects without Funding Sources: For A4NH P333 have two funding sources (with $ amounts!) in the budget. Check this report.

- [x] Can you change the description so it reads like this?
This report lists each funding source that has been entered in MARLO and the project(s), cluster(s), flagship(s) to which it is mapped. Unlike the 'Master List,' this report shows you fewer details about each funding source. Funding sources that have been assigned to more than one project will appear multiple times in this list. The total budget listed is the amount of that funding source assigned to that project.

- [x] Suggestion: Could Funding Sources by Project include a column for Deliverable IDs? This way you could have a good summary by project of both funding and deliverables that you cannot get from Funding Sources – Master List. 

- [x] If the project is Management type the FL and CoAs columns should show Cross cutting and the FL/CoAs.

**Comment by sebas932** [comment]
Moved to the next sprint

**Comment by Grant-Lay** [comment]
@AndresFVR  - Hi is this the reason the Funding source summary is currently 'under maintenance'?  When will it be available again?

**Comment by AndresFVR** [comment]
Hi @Grant-Lay, we are making some improvements to update them with the phases development, it will be available the first days of march.

**Comment by Grant-Lay** [comment]
Oh ok.  The funding source summary report is quite useful for FTA, it is a shame we can't regenerate the report at the moment.
