### ISSUE TITLE
Move MARLO configuartion files into marlo-web project

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1287]
As per the conversation with the MARLO development team in 2017 when I presented the spring changes, we agreed that I would move the configuration files from the parent folder into the marlo-web project src/main/resources folder.  The benefits are that we do not need to do a maven build if we want to test out changes to property values, saving developers time.  We also can remove the warning in the pom.xml about copying files from outside the project.

One other benefit is that by having the properties files in the marlo-web project we can make use of Spring profiles, where we can declare the environment we are running in and disable or enable specific beans depending on which environment we are in.  For example the Swagger beans which document our web services are enabled for all environments unless we write logic which checks which environment we are in.  Using spring we can use an annotation @Profile({'dev', 'test'}) and the beans would only be enabled in the dev and test environments, or @Profile('!prod') which would equate to every environment except for production. 
Other uses would be that we could write a notification bean that behaved differently in our dev and test environments and we could check the emails that are sent are correct, rather than throw exceptions as it does now.

**Comment by Grant-Lay** [comment]
So this change is ready, but it requires some changes for both developers and for our test and pro environments.  

All the configuration files are now in a single directory under src/main/resources/config in the marlo-web project.

Marlo developers need to do the following, copy the marlo-dev.properties.sample file and rename it to marlo-dev.properties.  Then update the properties file as per normal.

For the test and pro envrironments, we need to do the following:

Update the marlo-test.properties and marlo-pro.properties files and commit the changes to github but leave all sensitive information (e.g. passwords etc.) as dummy values (e.g. XXXXXXXX).  
Then in the tomcat config we need to do two things:

1. Set the Java system property to -Dspring.profiles.active=test or -Dspring.profiles.active=pro
2. Override the password properties by setting java system properties -Dmysql.password=the_real_password -Demail.password=the_email_password etc etc.

Note that it is no longer necessary to use a maven profile to build the app.  mvn clean package is sufficient (we could reintroduce maven profiles later on, but for now I have removed them).

**Comment by Grant-Lay** [comment]
I discovered that logback wasn't working correctly so have fixed that.  For logging to work correctly on the developers machine add the following property -Dspring.profiles.active=dev.

For tomcat in production go to the conf/catalina.properties file and add the following to the end of the file:

#Custom MARLO properties
spring.profiles.active=pro
mysql.password=the_real_production_password

Same as above for the test environment but change the property values to:

#Custom MARLO properties
spring.profiles.active=test
mysql.password=the_real_test_password

**Comment by Grant-Lay** [comment]
@htobon - I have copied the marlo.properties file from the production server (which was strangely in the configuration/dev folder as there was no marlo.properties file in the configuration/pro folder @cgarcia9106 - please confirm this is the right file) and updated the marlo-pro.properties file on the branch.  I haven't committed it to github as I want to make sure which properties we want to keep confidential (this is a public repo by the way) before I do that.

So far the following would be overriden in the catalina.properties on the tomcat server.

- mysql.user
- mysql.password
- email.user
- email.password
- ocs.user
- ocs.password

The following perhaps should also be overriden:

- pusher.api.privatekey
- tawkto.api.key
- google.api.key
- mysql.host

What do you think Hector?

@cgarcia9106 could you please send me the marlo.propeties file from the test server, so I can do the same?

**Comment by htobon** [comment]
Hi @Grant-Lay, can we tackle this next week?
Thank you in advance.

**Comment by Grant-Lay** [comment]
Sure, next week is fine.  @cgarcia9106 can you send me the marlo.properties file that is being used for the test environment as mentioned above?

**Comment by htobon** [comment]
Hi @Grant-Lay, is everything ok with this issue?
Can you please let us know what is pending here?

Thank you!

**Comment by Grant-Lay** [comment]
Sorry @htobon I thought I had already closed this.

**Comment by htobon** [comment]
Alright. thanks!
