### ISSUE TITLE
Revise Tags created on Github

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#129]
Tag v4.0.1 says that there were only 8 commits.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-d1700cbd3746388f6ae0c054af5ca31975eb00322f6353aab2cb9d267190663a.png)

**Comment by sebas932** [comment]
Hi @htobon, this is not a Bug, it means that there are **8 new commits** since the tag 4.0.1 creation.
