### ISSUE TITLE
POWB Section: 2.1 CRP Staffing

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1290]
- [x] Create interface of CRP staffing
- [x] Create table by category and calculate the total and percentage of female
- [x] Create model, managers, dao, xml
- [x] Create Prepare
- [x] Create Save
- [x] Create Validator
- [x] Create migration for permissions
- [x] Test functionality
- [x] Test the interface

![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/ad9df163-161e-4339-887f-e94e011f5c91)

**Comment by htobon** [comment]
Feedback:
- [ ] FTE definition
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/96e87e93-d46f-42d6-b34c-7bda376025ac)

- [ ] Improve a couple of phrases
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/3be9199b-10c7-4b70-86f6-99cf0a9e4775)

**Comment by htobon** [comment]
Feedback:

- [ ] Total should be calulated
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/69eba020-409e-4a59-bf3d-0b3e010eece3)
