### ISSUE TITLE
POWB Section: 2.2 Financial Plan

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1291]
- [x] Create financial plan interface
- [x] Add planned budget table in the interface and calculate the total
- [x] Add table of Expenditure area
- [x] Create model, managers, dao, xml
- [x] Create Prepare
- [x] Create Save  
- [x] Create Validator
- [x] Create migration for permissions
- [x] Test functionality
- [x] Test the interface
- [x] Release into production

![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/1be52235-aa99-45d6-bbd7-1b42288c9982)

**Comment by htobon** [comment]
Good job.
