### ISSUE TITLE
Not all funding sources are appearing in funding source summary

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1292]
Environment:  production.
Phase:  2017 planning.

When preparing a 2018 funding source summary the following funding source (id 1743) does not appear in the list of funding list summary excel file, despite the duration of the funding source being 2016-2019.

To reproduce login to FTA and go to the summary section.  Select budget and click the excel button on the funding source summary section.  Select 2018 as the year and click generate.
In the first tab in the excel search for 1743.

Expected result: there is a row for 1743
Actual result: there is no row for 1743

**Comment by Grant-Lay** [comment]
Not sure if it is the same issue but FS1659 is also not appearing in the list.

**Comment by htobon** [comment]
@cgarcia9106, can you please check this today? Thank you.

**Comment by AndresFVR** [comment]
Hi @Grant-Lay, we have fixed it in the f6c9bd3 commit.

Could you please check it is working well now?

**Comment by htobon** [comment]
@Grant-Lay, if everything is ok here, please feel free to close this issue. Cheers.

**Comment by Grant-Lay** [comment]
This is looking much better.  However we as of this morning have 177 funding sources for 2018 and 169 are showing up in the excel file. I can see that 4 of the funding sources which have the title 'No defined' are not included, which is expected I guess, but I am still trying to find the remaining 4 funding sources.

**Comment by Grant-Lay** [comment]
Ok I have found the other 4.  They are FS1931, FS1930, FS1889 and 1937.  

These are all either in status _informally confirmed_ or _concept note/ pipeline_.  Is this the expected behaviour?

**Comment by AndresFVR** [comment]
Hi Grant, we have added the agreement status to filter Funding sources in the commit 
a10a21a. Now you should see FS1931,1930,1889 and1937 in the summary.

We are showing the funding sources with on-going, extended, informally confirmed or concept note/ pipeline status. Also, we are showing only FS that have end-date greater than the selected date and start-date less than selected date.

**Comment by htobon** [comment]
Thks @AndresFVR. This is right now in staging and will be in production soon.

**Comment by Grant-Lay** [comment]
All working now.
