### ISSUE TITLE
Generate the POWB Synthesis report

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1293]
- [x] 1.1 ToC Adjustments/ Changes
- [x] 1.2 Expected CRP Progress
- [x] 1.3 Evidence
- [x] 1.4 Flagship Plans
- [x] 1.5 Cross Cutting Dimensions
- [x] 2.1 CRP Staffing
- [x] 2.2 Financial Plan 
- [x] 2.3 Collaboration and Integration
- [x] 2.4 Monitoring, Evaluation, and Learning
- [x] 3.1 Management of Risks 
- [x] 3.2 Management and Governance

**Comment by sebas932** [comment]
Moved to the next sprint

**Comment by AndresFVR** [comment]
Here is a report generated in the local environment for POWB: [POWBSummary-2018_20180227-1516.docx](https://github.com/CCAFS/MARLO/files/1764520/POWBSummary-2018_20180227-1516.docx)

**Comment by htobon** [comment]
Hi @AndresFVR, let's meet today to discuss this progress. I think there is still much work to do with regards the format of the document.
Cheers,

**Comment by AndresFVR** [comment]
Hi @htobon we have improved the format of the document, please refer to the following report: 
[POWBSummary-2018_20180301-1345.docx](https://github.com/CCAFS/MARLO/files/1772389/POWBSummary-2018_20180301-1345.docx)

**Comment by Grant-Lay** [comment]
As mentioned to @htobon in a skype chat, if you have difficulties with pentaho generating ms word documents, I think apache poi would be a decent alternative (I've used it before for excel documents, but it also does word documents).

Here is a [link](http://www.baeldung.com/java-microsoft-word-with-apache-poi) to a tutorial on how to implement it

**Comment by htobon** [comment]
Thks @Grant-Lay. We started to build the document using that library.

**Comment by htobon** [comment]
Hi @AndresFVR, I'll move this issue into in-progress. So please move it into Review when you and Hermes think we should start the revision process.

**Comment by AndresFVR** [comment]
We generated the POWB report using Apache POI, here is the file generated from MARLO for CCAFS: 
[CCAFS-POWBSynthesis-2018_20180321-1439.docx](https://github.com/CCAFS/MARLO/files/1833706/CCAFS-POWBSynthesis-2018_20180321-1439.docx)
