### ISSUE TITLE
CIAT - MARLO Outputs Refactor: Outputs can contribute to multiple outcomes

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1295]
- [x] Develop necessary changes in CIAT - MARLO
- [x] Create Database Migration to Export the Output data in the new model
- [x] Refactor Action (Get and Save the information)
- [x] Refactor Autosave and history
- [x] Refactor Outputs UI

**Comment by HermesJim** [comment]
I Implemented in The test environment to check it the changes in Center Output Section.

**Comment by HermesJim** [comment]
![image.png](https://images.zenhubusercontent.com/5798ae8de40e5714b16c9812/85af7228-efd3-4117-b652-22aa077da815)

**Comment by htobon** [comment]
thks @HermesJim                        .
