### ISSUE TITLE
Design Database structure

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#13]

**Comment by HermesJim** [comment]
The team met to develop an initial design model.
[![MarloCRPUseRModel.JPG](https://docs.google.com/a/cgxchange.org/uc?id=0B5EWQK2RIXqAUnFFWmdzWjFmMHc&export=download)](https://drive.google.com/a/cgxchange.org/file/d/0B5EWQK2RIXqAUnFFWmdzWjFmMHc/view?usp=drivesdk)

**Comment by HermesJim** [comment]
@htobon , you can see how checkstyle work, generate report in \marlo-web\target\site\site.html (This folder can't save in the git repo).

Checkstyle has identified a bad name of a local variable in the HibernateListener.java file (See the attached image!
[ChekStyle_Error.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/ChekStyle_Error-743982c3e4fae7ee0be55de1f683f5ad3a512be0fa318def32f14f8196b9981a.png)
)

**Comment by cgarcia9106** [comment]
![users_diagram.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/users_diagram-4592e57641c1a6f7dec9ba97d292baf3725dcada16fdce704a846869d7e5a1c1.png)
Not include Permissions on this sprint
