### ISSUE TITLE
Partners managing funding source appear twice in 2018 planning mode

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1300]
When viewing a funding source in 2018 planning mode (which is closed), the partner managing the funding source appears twice.  Note that this behavior (i.e. appearing twice) is also happening in the funding source summary excel file.  However when viewing in 2017 planning mode (which is open) the partner appears only once.

2018 planning:
![image](https://user-images.githubusercontent.com/2264925/36086752-af42d8c2-1000-11e8-8b7a-172c56206de1.png)

2017 planning.

 
![image](https://user-images.githubusercontent.com/2264925/36086783-d148f000-1000-11e8-8f86-c32f9a741949.png)

**Comment by htobon** [comment]
Hi @cgarcia9106, can you please take a look at this?
Thank you in advance.

**Comment by cgarcia9106** [comment]
a migration ducplicate some data, i have created a migration to delete duplicated data

https://github.com/CCAFS/MARLO/commit/41330b592b13eb195f8502a404785feca4595bcc
