### ISSUE TITLE
Removing and adding center contact points (PPA Partners) is not working correctly

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1301]
I tried removing a PPA Partner contact point from FTA (Institution Tropenbos) and add a new contact point and:

1.  The old contact point can not be removed.
2.  The new contact point does not display in the PPA Partner screen (note that when I go to the user list that the new contact point appears and an email notification was sent out).

I am unable to remove Henk Lijftogt and newly added user Herman Savenije does not appear

![image](https://user-images.githubusercontent.com/2264925/36131531-d465fdc4-10a4-11e8-894e-1564160d4dc7.png)

In the user screen I can see that Herman has been added and Henk has not been removed.

![image](https://user-images.githubusercontent.com/2264925/36131614-34b73288-10a5-11e8-91ec-476c54985394.png)

**Comment by htobon** [comment]
Hi @Grant-Lay, we are also experiencing the same issue with CCAFS.
@cgarcia9106 is checking it right now. Will let you know when it is fixed.

Thank you.

**Comment by cgarcia9106** [comment]
Error in a validation, created the institution liasion again, corrected the problem and the data that were altered, for ccafs and fta

**Comment by htobon** [comment]
Thks @cgarcia9106.
I will proceed to make the respective modifications for CCAFS.

@Grant-Lay, can you please check that everything is ok in FTA?

Cheers.
