### ISSUE TITLE
Unable to remove a funding source from a project

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1304]
I am unable to remove a funding source from a project.

In FTA go to project with id 793 and in the Budget section under ICRAF try and remove the funding source with id 1687 and click save.  

Expected result : funding source gets removed.
Actual result: funding source does not get removed.

**Comment by htobon** [comment]
@cgarcia9106 please check.

**Comment by Grant-Lay** [comment]
Same thing is happening with P793 (duplicate funding source FS1766 can't be removed).  Putting this down as a reminder so that I clean up the data later once it is fixed.

**Comment by Grant-Lay** [comment]
Also project P809 can't remove FS1746
