### ISSUE TITLE
POWB Synthesis - Section: 2.3 Collaboration and Integration

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1307]
![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/89fdf461-3eb8-4d37-ba40-0cfc3cd2b0e4)

![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/66ba8f2d-d3a1-4687-b8c3-a2eee377de57)

![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/41eb1aa4-bbbe-40c6-ab9d-a5ce6757d1b6)

![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/064bda0d-d127-4f03-b1f0-b664296344cb)

**Comment by htobon** [comment]
Feedback:

- [ ] Partnerships: Include a table with data coming from projects.
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/f9adf1a4-c999-444b-b0ac-e2ed09c9e219)

- [ ] Improve tooltip text
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/885c260b-80fe-481d-addd-98ac022c3691)

- [ ] Divide main sections
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/1474b8e6-be38-4405-9325-a7a927bdf8bd) 

- [ ] Check list of Platforms and CRPs
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/7b9d588b-061c-4796-b04a-fca09b509c79)

**Comment by htobon** [comment]
Decision after we discuss with David and Tonya:

- [ ] 2.3.4 List of countries will be displayed in PMU only.

- [ ] We will group them according to the Regional Programs for CCAFS. So, for LAM, it will appear only the projects that tagged the RP LAM. And, the table will display the list of countries that those projects are contributing.
And then, we will be another table for "No regional programmatic focus projects"
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/fa35984d-ce14-4ecf-aa71-8487c054d057)

- [ ] Questions per Regional Program

- [ ] Please make sure, we are tagging at project level.

**Comment by sebas932** [comment]
- [ ] @cgarcia9106 create an ajax service for get the Flagships/Modules(crpPrograms) by CRP/Platform(globalUnit)
