### ISSUE TITLE
Tidy up audit logging in MARLO

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1308]
MARLO currently has hundreds (perhaps even > 1000 ?) of lines of code where the following fields are set on an Entity:

- createdBy - the user who created the entity
- modifiedBy - the user who last modified the entity
- activeSince - the date the entity was created.  (Note that this field gives the impression that when an entity is deactived - i.e. soft deleted, the activeSince date would be updated - but this is not the case)

Following the [DRY principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) (**D**on't **R**epeat **Y**ourself), we should standardize this.

This task will do the following:

1. Create an abstract class AuditingEntity class that all Entities that require auditing extend from.  This will reduce code duplication within the entities where the same fields are defined again and again.
2. Implement a hibernate pre-insert and pre-update listener to auto-populate the auditing values.
3. Remove all the code within MARLO that manually populates the values.

Other tasks that could be combined with this are:

- Currently the modified_by column is mandatory in the database.  This should be a non-mandatory column as the first insert should not populate the modified_by column.  A flyway script could remove all the not-null constraints from the modified_by column.
- Rename activeSince to createdDate in our new abstract AuditingEntity class.  A flyway script could update the column name from active_since to created_date to keep our code and database closely aligned.
- Most auditing frameworks have a modified_date column to show when the last modification happened.  This would be a good time to add it.

Note that the modification_justification would not be auto-populated as the user still needs to provide us the details themselves.  However we can and should do the following 
- add the field modificationJustification to the abstract AuditingEntity class
- remove the not-null constraint on the database in a flyway script.

This task will need to coordinate with other developers so that new entities (and new tables) adhere to the new auditing framework rules.

**Comment by Grant-Lay** [comment]
@htobon - I have done task items 1,2 and 3 to a single entity (Activities) to show what the pattern looks like.  I am happy to push forward and do the remaining.

**Comment by htobon** [comment]
Hi @Grant-Lay, apologies for the late response.

And thank you for this. We really appreciate it.

Christian took a look in detail of what you did and everything seems to be fine.
We think that, if you are happy to do this implementation, please feel free to continue with the rest of the actions. However, can you please make progressive merges into staging with the idea that the developers can visualize the updates and start adopting it for the new developments?

We understand you made this branch based on the REST-API, so, we will make sure the REST-API branch will be also merged in staging. 

Hope this make sense. 

Perhaps, can you please update the description of this issue and include all the actions that you are making changes so we see the progress?
E.g.
- [x] Activities
- [ ] etc.

**Comment by Grant-Lay** [comment]
Just a note that quite a few tables metadata_elements, center_all_types are using int instead of bigint for their id columns.  It seems that mysql is currently set to be relaxed about this, but if we were to run in strict mode I think the mismatch of values would fail.

**Comment by htobon** [comment]
Hi @Grant-Lay, can you please let @HermesJim know the status of this issue? Please feel free to contact him directly.
Cheers.

**Comment by Grant-Lay** [comment]
@HermesJim - I am almost finished doing changes 1,2 and 3 to all entities in MARLO.  I have tested the MARLO CIAT application but haven't tested the MARLO CRP application.
