### ISSUE TITLE
Set up PMD source code analysis tool to detect code duplication

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1309]
I have noticed a lot of code duplication in MARLO, and this is obviously a problem in that if there is a bug or we want to modify the code we have to remember to fix it more than once.   By following the [DRY principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) of software development, we write code only once.

Fortunately there are tools that we can use to detect code duplication and then give us ideas on how to fix them (e.g. move code repeated across multiple struts2 action classes into a manager class - then each Action method calls the manger class).  PMD is such a tool and comes with a maven plugin which we can use to generate a maven report within our maven site.  PMD not only does duplicate code detection it also can find bad coding practices such as: "unused variables, empty catch blocks, unnecessary object creation, and so forth".

Adding the PMD source code analysis tool to the reporting section of the parent pom will not change the normal build and will only be activated by running the mvn site goal.

**Comment by Grant-Lay** [comment]
This is ready, simply run mvn clean site and go to the project reports to see the CMD and PMD analysis.  As mentioned there are massive amounts of code duplication (see the CMD report).

**Comment by htobon** [comment]
Thank you @Grant-Lay.
We have merged this into staging so we can use it.
I think that, at some point, we should invest our resources on improving the quality of our code, perhaps when we are not too rushed to deliver new developments.
