### ISSUE TITLE
Funding sources closed projects sort throws a NPE if there is a null end-date in a funding source

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1312]
The following line of codes throws a NPE if a closed project does not have an end-date

`closedProjects.sort(Comparator.comparing(o->o.getFundingSourceInfo(this.getActualPhase()).getEndDate()));`

**Comment by Grant-Lay** [comment]
Changing the line to 

`closedProjects
      .sort(Comparator.comparing(FundingSource::getEndDatePhase, Comparator.nullsFirst(Comparator.naturalOrder())));`

fixes the problem.

**Comment by cgarcia9106** [comment]
https://github.com/CCAFS/MARLO/commit/66d6263b4d11cbe34965ac349e7e8e826eeb1a4e

**Comment by htobon** [comment]
It seems the issue was fixed.
Thank you both.

@Grant-Lay, if there is an easy fix, can you please commit it directly into staging?
would that make sense?

Please close this issue when you read it.

**Comment by Grant-Lay** [comment]
@htobon sure from now on I will do that.  I wasn't sure if the team were happy for me to do that, so I have been creating fixes on separate branches.
