### ISSUE TITLE
POWB Synthesis - Develop a Submission module.

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#1313]
- [x] Validate and Check Missing fields in each section with the _Check_ Button.
- [x] Submit The POWB Synthesis with the _Submit_ Button.
- [ ] Send Submission Email.

**Comment by HermesJim** [comment]
Green Check Sections.

- [ ] 1.1 Adjustments to Your Theories of Change
- [ ] 1.2 Expected CRP Progress
- [ ] 1.3 Evidence
- [ ] 1.4 Flagship Plans
- [ ] 1.5 Cross Cutting Dimensions
- [ ] 2.1 CRP Staffing
- [ ] 2.2 Financial Plan
- [ ] 1.1 Adjustments to Your Theories of Change
- [ ] 1.1 Adjustments to Your Theories of Change
- [ ] 1.1 Adjustments to Your Theories of Change
- [ ] 1.1 Adjustments to Your Theories of Change

**Comment by sebas932** [comment]
@HermesJim send an example of the submission email to Hector and check with him.

**Comment by sebas932** [comment]
- [ ] I've tried to submit a FP POWB Synthesis with a Flagship leader but i got the image below
![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/2ecf1b00-eaae-4c91-9b13-f3a44f7c9138)

**Comment by HermesJim** [comment]
Hi all.
I sent the image of the example of the submission email.


![image.png](https://images.zenhubusercontent.com/5798ae8de40e5714b16c9812/7f48e41f-f073-47c3-a5ce-7d1c6c20c562)

Also they can see the example into the MARLO Automated emails document:

https://docs.google.com/document/d/1gchg7Rmd6IBspMGkzIL1MugKIM2mSjtSg4sRSgx3qnA/edit#heading=h.ra6ryzi27stn
