### ISSUE TITLE
Budget by partner screen sometimes shows red text despite the values being correct

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1314]
Please see the screenshot below, this occurs after save.  The funding source amount has not been exceeded so it does not make sense why the text is appearing as red.  Note that this behavior seems difficult to reproduce and happens intermittently.

![image](https://user-images.githubusercontent.com/2264925/36827347-9f7e912c-1d45-11e8-8913-c8d54a1b75dd.png)

Here is a screenshot from the funding source page which shows the budget has not been exceeded:

![image](https://user-images.githubusercontent.com/2264925/36827383-d4bae1e2-1d45-11e8-8779-8e5b41067954.png)

**Comment by cgarcia9106** [comment]
It was a data problem, because when you were deleting a project you were not deleting all the relationships, which meant that the budgets relationship was active. An update was made to deactivate the necessary data and the elimination of projects was fixed
