### ISSUE TITLE
Display project title in breadcumb menu

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1317]
Something I have noticed when using MARLO is that when I move from the description tab in a project to another tab (e.g. budget) there seems no easy way to find out what project you are currently editing.

Could we expand the breadcrumb menu to include the name of the project?

**Comment by jhanzuro** [comment]
Hi @Grant-Lay, we add the project id into the breadcrumb menu and additionally we add a tooltip into the "project id icon" that displays the project title. I'll hope this is fine. Cheers.
![projectbreadcrumb](https://user-images.githubusercontent.com/30579639/37362528-718d385e-26c3-11e8-94be-56d372c7a622.png).

**Comment by Grant-Lay** [comment]
Thanks @jhanzuro.
