### ISSUE TITLE
Budget by partners section changed amounts (removed 000s) 

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1326]
The budget by partners section is removing 000 amounts in certain scenarios (this could be happening either when the project is progressed from Pre-setting to Ready for PL  or when the check the missing fields button is pressed -I need to do some more testing to confirm)

![image](https://user-images.githubusercontent.com/2264925/37505596-4ca9208c-2918-11e8-838b-47b2eb7e189c.png)

**Comment by Grant-Lay** [comment]
Actually this is much worse then removing just the 000, it removes all numbers after the comma so it is not as simple as fixing as by adding 000 to each number.

**Comment by Grant-Lay** [comment]
I was able to reproduce the problem locally (using the up-to-date staging branch).  It seems to happen when submitting the project to the project leader (transitioning from pre-setting to ready to PL).  

Original amounts in the two funding sources below were 100,000 and 50,000.

![image](https://user-images.githubusercontent.com/2264925/37507735-a91aebc0-2922-11e8-9596-462fdf8f7c52.png)

**Comment by sebas932** [comment]
Hi @Grant-Lay i will check the issue today

**Comment by sebas932** [comment]
Hi @Grant-Lay i fixed the issue, i figured out that was a bug that only happens in Firefox, after many laps I found that the correct way to reload the page using Javascript is with `window.location.href = window.location.href;`

**Comment by Grant-Lay** [comment]
Thanks @sebas932 for fixing this.
