### ISSUE TITLE
budget by CoA section is falsely claiming that information is missing

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1327]
See screenshot below of project 801 within FTA CRP.  The values all add up to 100% but after saving the green tick is not appearing and the message 

> Please keep in mind that the fields highlighted below are missing or incorrect.

 appears despite there being no missing fields.

![image](https://user-images.githubusercontent.com/2264925/37692211-d474a61a-2ce9-11e8-8831-c95d849f4f97.png)

**Comment by Grant-Lay** [comment]
@htobon any update on this?

**Comment by htobon** [comment]
Hi @Grant-Lay.

**Comment by sebas932** [comment]
Hi @Grant-Lay the guys will be checking in the validators in the backend side to understand what is happening, we will update you as soon we fix the issue.

**Comment by HermesJim** [comment]
Hi, I checking the Budget by CoA validator, we have not validate the Gender Specificity into the validator, I fix this bug, I Add  the gender Specifitie validation.

**Comment by Grant-Lay** [comment]
This is working now.  Thanks.
