### ISSUE TITLE
Adding multiple sub-departments separated by commas removes the data after the comma on save

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1328]
Hi as per the advice in the email on the 21st of March, I have tried saving multiple sub-departments for the government of Cameroon separated by a comma (e.g. 'National Forestry Development Agency, National Agricultural Research Institute for Development'), but when pressing the save button only the data 'National Forestry Development Agency' is saved.

**Comment by Grant-Lay** [comment]
@htobon any update on this?

**Comment by Grant-Lay** [comment]
Hi @AndresFVR, has this been pushed to production?  I am still experiencing the issue.

Also the [diff](https://github.com/CCAFS/MARLO/commit/1ecb7fbf7c5f4e1a8ee4184dd12bff066319bd4e) of the commit is showing that the whole file has changed.  Can you check your line ending settings in git, are correct, try run git config --list and check that the core.autocrlf property is set to true.

**Comment by AndresFVR** [comment]
Hi @Grant-Lay the commit is pushed to production now. I confirm you that the core.autocrif property is set to true.

**Comment by Grant-Lay** [comment]
This is fixed now.  @AndresFVR can you investigate why the diff is showing the whole file changed?  Can you work out if it is because of the line endings (Linux/Mac vs Windows) or is it because of tabs and spaces.
