### ISSUE TITLE
Update summaries with Annualization

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1340]

**Comment by mralmanzar** [comment]
an epic an all the related issues are closed.
https://github.com/ccafs/marlo/issues/1359, https://github.com/ccafs/marlo/issues/1339, https://github.com/CCAFS/MARLO/issues/1408, https://github.com/CCAFS/MARLO/issues/1358, https://github.com/CCAFS/MARLO/issues/1355, https://github.com/CCAFS/MARLO/issues/1344
