### ISSUE TITLE
establish UN m.49 regional standard in MARLO database

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#136]

**Comment by HermesJim** [comment]
The country  Netherlands Antilles was dissolved into five separate territories in 2010. 
Fortunately, this country did not have projects in p&r.  Netherlands Antilles was deleted and add the new countries in loc_element MARLO table. 

https://en.wikipedia.org/wiki/ISO_3166-2:AN

**Comment by htobon** [comment]
Noted.
