### ISSUE TITLE
Send Emails with HTML format

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#137]
_From @htobon on June 16, 2015 20:15_

We need to improve the SendMail class in order to allow it to send emails with HTML format.

Plus, would be great if we could use the following library (or any other), due to decrease compatibility issues with some email service providers:
http://commons.apache.org/proper/commons-email/index.html

_Copied from original issue: CCAFS/ccafs-ap#350_

**Comment by cgarcia9106** [comment]
on method send, put a param if is html
