### ISSUE TITLE
Improve the way to add new partners

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#138]
_From @GoogleCodeExporter on March 16, 2015 12:58_

```
In the satisfaction survey there were a couple comments:

- "Uploading partners is slow and time consuming - meaning we may neglect 
certain partners"
- "Some partners were not included in the proposed list. The platform should 
allow to add new partners"
- "It takes long time to adding many partners for one activities, May we have 
simpler way than waiting for e.mail from P&R team?"3
- "Adding partners required long time"

By this reason we should improve way to add partners to the database.
```

Original issue reported on code.google.com by `carvajal.hernandavid@gmail.com` on 15 Apr 2014 at 8:01

_Copied from original issue: CCAFS/ccafs-ap#256_

**Comment by htobon** [comment]
_From @GoogleCodeExporter on March 16, 2015 12:58_



Original comment by `carvajal.hernandavid@gmail.com` on 16 Apr 2014 at 3:12
* Added labels: **Milestone-Release1.4**
* Removed labels: **Milestone-Release1.x**

**Comment by htobon** [comment]
_From @hernandcb on March 19, 2015 19:13_

We can check some options to automatize the process like [Apache POI](poi.apache.org) or [JXIS](jxls.sourceforge.net)

**Comment by htobon** [comment]
We shuld improve the process of requesting to add a new partner.
In any way, there should be a manual process to validate that the partners are well inserted into our database.

**Comment by sebas932** [comment]
Dublicated with issue #551
