### ISSUE TITLE
Apply "Up Keep" changes in MARLO

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1381]
We decide to create a Phase called "Up Keep" that will take the Planning forms at Projects and Funding source level

![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/64d7f343-331a-4e14-ae0c-0a2894d6bd57)

**Comment by mralmanzar** [comment]
Already resolved on more than one issue:
https://github.com/CCAFS/MARLO/issues/1478, https://github.com/CCAFS/MARLO/issues/1531, https://github.com/CCAFS/MARLO/issues/1523, https://github.com/CCAFS/MARLO/issues/1485, etc
