### ISSUE TITLE
Organize the internationalization file

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#139]
_From @htobon on July 14, 2015 21:10_

Our internationalization file is currently disorganized (nort sure why!).

Lets order it, perhaps based on this file from GBIF.
https://github.com/gbif/ipt/blob/master/src/main/resources/ApplicationResources_en.properties

_Copied from original issue: CCAFS/ccafs-ap#359_

**Comment by htobon** [comment]
Let's do this for the next release.

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-2115e713c73835de0bb966ea4f79f45c4f240c5a5f0ca548c0699989cb7c43ff.png)

**Comment by htobon** [comment]
Would you guys please confirm that you took a look to the GBIF file I mentioned in the first message?

**Comment by sebas932** [comment]
Yes, i'm showing the GBIF file to Carlos right now

**Comment by cgarcia9106** [comment]
This task will be on each sprint
