### ISSUE TITLE
Define Maven Profile

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#14]

**Comment by htobon** [comment]
@cgarcia9106 Would you please explain the profiles you defined?

**Comment by cgarcia9106** [comment]
we have defined 3 profiles, in which for now only changes the location of the configuration file called:
dev: this is the default profile, this profile is used for the development environment.
test: This profile represents the instance of prubas.
pro: to set the profile settings when the system and will be released to users.

to generate the war depending on the profile should run the following command in maven:
mvn clean install -PprofileName
