### ISSUE TITLE
Harvest metadata from DOI link

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1406]
add to the sync additional info using the DOI url (Like volume, etc)

**Comment by sebas932** [comment]
How to get the following metadata from a DOI:

```
@article{
van_Soesbergen_2016, 
title={}, 
volume={},
ISSN={}, 
url={}, 
DOI={}, 
number={}, 
journal={}, 
publisher={}, 
author={}, 
year={}, 
month={}, 
pages={}
}
```

![image](https://user-images.githubusercontent.com/4406128/51606877-1593e680-1ee1-11e9-89e0-fe721407edc9.png)
