### ISSUE TITLE
Check that LiaisonUsers are deleted when a user is deleted

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1407]
I have three records in the liaison_user table in my local database that reference a user_id of a user that has been deleted.  

SELECT * FROM liaison_users lu
LEFT OUTER JOIN users u ON lu.user_id = u.id
WHERE u.id IS NULL;

This means that when trying to remove someone from the PMU, an exception will be thrown in the CrpAdminManagementAction.  

For now I will delete these records manually, but I am tracking this issue in case the database is not setup correctly (note there is a foreign key with setting on delete CASCADE, which should ensure the liaison_user records are deleted when a user is deleted).

**Comment by HermesJim** [comment]
Hi @Grant-Lay 

Hi Grant, thks for spotting this.
Indeed, I'm not sure why there are 3 records associated to non-existing users. This should never happen. 
Those records are marked as inactive, as a result, I think the fastest way to fix this would be to delete those 3 unused records.
Please refer to the following commit where I'm doing that:

https://github.com/CCAFS/MARLO/commit/e4f18b3a1d44cef5b36152ed0f8d93cd3410e639

**Comment by Grant-Lay** [comment]
@HermesJim - it is possible.  How are users being deleted anyway, I don't recall seeing this functionality in MARLO?

**Comment by HermesJim** [comment]
@Grant-Lay  -  
MARLO hasn't the functionality to remove or disable users.
When we decide to deny access an specific user, we do it manually and disable it into the database (is_active = 0).

As I mentioned before, we made a strong migration to merge the separate projects of MARLO and CIAT MARLO, and it is like the only event where we could say that maybe we did not take into account the user id's detected.

I should also mention that in most migrations we use this command _[SET FOREIGN_KEY_CHECKS = 0]_ 

I appreciate your observation on this case and our technical team will be pending at the moment of make a migrations, especially with the users.

Please Grant, tell me if I'm a little more understandable or if you have some other questions.

Thanks.
