### ISSUE TITLE
Check/Fix the metadata harvesting services

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1411]
**Checked in April 25, 2018:**

- [x] CGSpace [ Working ]
- [x] _CIMMYT Dataverse [ Broken ]_
- [x] CIMMYT DSpace [ Working ]
- [x] _Dataverse (Harvard) [ Broken ]_
- [x] IFPRI E-BRARY [ Working ]
- [x] ILRI Datasets [ Working ]

**Comment by AndresFVR** [comment]
We have fixed the CIMMYT Dataverse and Harvard Dataverse
