### ISSUE TITLE
JSON security - New Users 

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#142]
_From @htobon on June 16, 2015 21:35_

Apply security to the JSON URL createUser.do in ManageUserAction in order to only access through the ProjectLead interface and/or if the user has enought privilages to do it. 

_Copied from original issue: CCAFS/ccafs-ap#351_

**Comment by htobon** [comment]
@HermesJim and @cgarcia9106, please check this issue when you are developing the interface for adding new users.

**Comment by htobon** [comment]
Why is this card in a reviewing process?

**Comment by HermesJim** [comment]
The CGIAR Active directory library not work to add users, wihtout this funtionalyty can not work in this issue.

**Comment by htobon** [comment]
What did you do?
