### ISSUE TITLE
2.1 Variance from Planned Program - Annual Report - Synthesis

### ISSUE THREAD

**Issue by jhanzuro** [CCAFS/MARLO#1427]
- [x] Develop '2.1 Variance from Planned Program' section interface
- [x] Model
- [x] Prepare
- [x] Save
- [x] Validator
- [ ] Auto Save
- [ ] History
- [x] Test PMU role
- [x] Test FL role

**Comment by AndresFVR** [comment]
Developed back-end in the following commit 30efe5b.
Left:
- [ ] Validator
