### ISSUE TITLE
Prevent that two users access the same section at the same time

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#143]
_From @GoogleCodeExporter on March 16, 2015 12:58_

```
To prevent unexpected missed information we should prevent that two users can 
edit the same section at same time.

Perhaps showing a message telling what is happening.
```

Original issue reported on code.google.com by `carvajal.hernandavid@gmail.com` on 27 Mar 2014 at 4:10

_Copied from original issue: CCAFS/ccafs-ap#212_

**Comment by htobon** [comment]
_From @GoogleCodeExporter on March 16, 2015 12:58_



Original comment by `carvajal.hernandavid@gmail.com` on 16 Apr 2014 at 3:09
* Added labels: **Milestone-Release1.3**
* Removed labels: **Milestone-Release1.x**

**Comment by htobon** [comment]
_From @hernandcb on March 19, 2015 18:44_

To give a solution to this issue we should solve first the following issues:

- [ ] #159

**Comment by htobon** [comment]
We are going to implement a log functionality in order to display what was changed.
Let's think in a better solution for the reporting stage.

**Comment by htobon** [comment]
This card is pending to be developed as we could improve the functionality and allow  several users work in the same section.

**Comment by sebas932** [comment]
Created a function to prevent concurrence, below an example.

![Animation.gif](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Animation-849aab71142dd12eb549e3af15e1c85bc837a0d32eec4bbab1cba11aa73312ca.gif)

**Comment by htobon** [comment]
+1

**Comment by htobon** [comment]
I think we should schedule a 20min of time where all of us can test this functionality.
@sebas932, I would appreciate you lead this process with us. Please try to include David and tell him this test is not required for him to do it.

**Comment by htobon** [comment]
@sebas932 do not forget to schedule a meeting with David on board. Please do not do this in the last minute.

**Comment by sebas932** [comment]
I made some changes in order to improve the functionality, i think it's working well so far.
