### ISSUE TITLE
PublicationListAction throws an exception when saving

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1435]
The following exception is thrown when trying to save a publication (under Supplementary menu item).  This happens on the staging branch. 

Hibernate: select liasonsuse0_.user_id as user_id5_260_0_, liasonsuse0_.id as id1_144_0_, liasonsuse0_.id as id1_144_1_, liasonsuse0_.global_unit_id as global_u2_144_1_, liasonsuse0_.is_active as is_activ3_144_1_, liasonsuse0_.institution_id as institut4_144_1_, liasonsuse0_.user_id as user_id5_144_1_ from liaison_users liasonsuse0_ where liasonsuse0_.user_id=? order by liasonsuse0_.id

Jun 06, 2018 11:05:45 AM org.apache.catalina.core.StandardWrapperValve invoke

SEVERE: Servlet.service() for servlet [default] in context with path [/marlo-web] threw exception [org.hibernate.AssertionFailure: null id in org.cgiar.ccafs.marlo.data.model.DeliverableParticipantLocation entry (don't flush the Session after an exception occurs)] with root cause

org.hibernate.AssertionFailure: null id in org.cgiar.ccafs.marlo.data.model.DeliverableParticipantLocation entry (don't flush the Session after an exception occurs)

    at org.hibernate.event.internal.DefaultFlushEntityEventListener.checkId(DefaultFlushEntityEventListener.java:77)

    at org.hibernate.event.internal.DefaultFlushEntityEventListener.getValues(DefaultFlushEntityEventListener.java:192)

**Comment by Grant-Lay** [comment]
@htobon  Assigning this to @AndresFVR who has been working on this functionality.

**Comment by AndresFVR** [comment]
Hi @Grant-Lay, I have fixed the publication action and validator (see commit 
https://github.com/CCAFS/MARLO/commit/360e7b26d97e2725521060b06bdff9868d0413b3).

I hope it works now.
