### ISSUE TITLE
Control List inventory

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1444]
Deliverable: Excel Sheet with all control list

**Comment by HermesJim** [comment]
Control List Inventory :

- [ ] SLO/IDOs & Cross-Cutting topics/ Sub
- [ ] Crps/PTFs
- [ ] Flagship and Modules
- [ ] Phase of research partnership
- [ ] Innovation type
- [ ] Type of participant
- [ ] Policy / Investment type
- [ ] Land use types
- [ ] Type of activity / training
- [ ] Regions
- [ ] Policy marker for Cross-cutting dimensions.
- [ ] Organization type
- [ ] Geographic scope
- [ ] CGIAR Stage of innovation
- [ ] Deilverables Categories
- [ ] Location level
- [ ] Target Units
- [ ] Outcomes 2022
- [ ] Institutions
- [ ] Funding Windows
- [ ] Spheres
- [ ] Status
- [ ] Milestones
- [ ] Portfolio phases
- [ ] CGIAR research phases
- [ ] SDGs
