### ISSUE TITLE
Generate PDF projects in the CCAFS-Intranet

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1450]

**Comment by AndresFVR** [comment]
Uploaded to the following folder for @HT Hector review:
CCAFS-KDS\Documents\MARLO\2_Technical\2_7_Data\2_7_1_Reports\Project Portfolio 2017

**Comment by htobon** [comment]
Thank you @AndresFVR. I have uploaded all those files into the CCAFS Intranet.
Cheers,
Hector.
