### ISSUE TITLE
Fix Project History

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1458]
## Description: 

- [x] When saving with autosave, history shows empty fields
- [ ] Status is not loading the correct data (Sometimes showing numbers instead of words).
- [x] Flagship is not showing correct data.
- [x] Regions is not showing correct data.
- [x] Cluster of Activities is not showing correct data.

## Partners:

- [x] When adding a new partner (institution), it is not shown in the history.
- [x] Partnership: Phase, geographic scope shows empty fields.
- [x] Partnership: Wehn adding new countries, it is not shown in the history
- [x] Contact person: When adding new contact person, it is not shown in the history
- [x] Country office:When adding new country, it is not shown in the history
## Locations
- OK

## Contribution to Flagship Outcomes
- [x] Communications shows empty fields
- [x] When adding a new milestone, it is not shown in the history.
- [x] When saving with autosave, history shows empty fields for communications, next users and milestones

## Studies
- [x] Null exception when opening history

## Deliverables
- [x] History button has not been displayed

## Innovations: 
- [x] Empty fields
- [x] Displayed form as editable

## Project Highlights
- [ ] History button has not been displayed

## Activities
- [ ] Status is not loading the correct data (Sometimes showing numbers instead of words).
- [x] Deliverables displayed as null

## Leverages
- [x] When adding a new leverage, it is not shown in the history.

## Budgets
- [x] When adding a new fs,coa or fl, it is not shown in the history.

**Comment by htobon** [comment]
@AndresFVR Can you please check that this is working on all the sections metioned above?

**Comment by AndresFVR** [comment]
The check process will be done in the issue #1499
