### ISSUE TITLE
Submit Button: Not clear a project need to be submitted

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#146]
_From @htobon on March 4, 2016 15:3_

Usability Problem:
For some users, it is not clear a project need to be submitted.

![2016-03-04_1000](https://cloud.githubusercontent.com/assets/5375915/13530601/32c2c45a-e1f0-11e5-8fda-4a20584f6690.png)

_Copied from original issue: CCAFS/ccafs-ap#405_

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-e4b4eb359ee2d2ec0393f68d77221472760fd7f28a91c161be7f7f3137703283.png)

**Comment by htobon** [comment]
Not sure how you improved the usability.... The image doesn't show me we make some improvement from what we had before.

**Comment by cgarcia9106** [comment]
@sebas932

**Comment by sebas932** [comment]
I've put the following message, what do you think @htobon ?
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-798b2175ff5d25a47cb3df6690e63ac024cc264312b90b8dbc4a5dc37e860651.png)

**Comment by htobon** [comment]
Thank you @sebas932.
Please use the following text message:
"This Impact Pathway seems to be complete. Please click in the "Submit" button located at the left side in order to finalize the process."
