### ISSUE TITLE
Review list of Projects (On-going and Archived tab)

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1474]
Issue reported by Perla Castillo.
Check PIM project 583.

**Comment by AndresFVR** [comment]
Removed submission validation for closed projects on project list

See commit: https://github.com/CCAFS/MARLO/commit/be27cb7f5c4ef67df7f046042a156a2fbddbb6e7

**Comment by htobon** [comment]
@AndresFVR, can you please let us know the status of this issue?

**Comment by AndresFVR** [comment]
@htobon this issue is solved and released to MARLO (production environment).
