### ISSUE TITLE
CIAT MARLO Projects - Create CIAT Impact Pathway projects Contribution Section.

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#1479]

**Comment by sebas932** [comment]
We have created a new section only for projects coming from CRPs allowing the mapping to the CIAT Programs

![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/537c6aa9-54cc-4b2c-9f0e-08f3985e4396)

**Comment by HermesJim** [comment]
== UPDATE ==

Add CIAT IP Outcomes.

**Comment by HermesJim** [comment]
Update

![image.png](https://images.zenhubusercontent.com/5798ae8de40e5714b16c9812/b26bad8a-602c-4c03-ba87-2db4ec231aa6)
