### ISSUE TITLE
Replicate Impact Pathway and Funding Sources data to new phases

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1493]

**Comment by mralmanzar** [comment]
Developed
Impact Pathway
![image](https://user-images.githubusercontent.com/9383649/50160378-309e8580-02a7-11e9-9761-4e79ac094b63.png)
![image](https://user-images.githubusercontent.com/9383649/50160401-41e79200-02a7-11e9-8070-f7762e9bb14c.png)

Funding sources
![image](https://user-images.githubusercontent.com/9383649/50160528-97bc3a00-02a7-11e9-8cf9-d14d9fae02c3.png)
![image](https://user-images.githubusercontent.com/9383649/50160547-a73b8300-02a7-11e9-9983-213c9d0d67be.png)
