### ISSUE TITLE
Setup All CGIAR CRPs/Platforms In MARLO.

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#1503]

**Comment by HermesJim** [comment]
The rest of the CRPs is added

![image.png](https://images.zenhubusercontent.com/5798ae8de40e5714b16c9812/8ad1d411-25a6-4280-852b-99e5dd843a19)

**Comment by HermesJim** [comment]
Only MARLO Super Admin Can Access to the new CRPs.

**Comment by htobon** [comment]
Thks.
