### ISSUE TITLE
Setup Impact Pathway - RICE CRP.

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#1504]
- [x] Flagships
- [x] Outcomes 2022
- [x] Outcomes 2022 Sub-IDOs
- [x] Cluster of Activities
- [ ] Flagship Leaders, and Managers
- [x] Outcomes 2022 Milestones 2018
- [ ] CoA Leaders
- [ ] CoA Key Outputs
- [ ] CoA Key Outputs  Outcomes contributions

**Comment by sebas932** [comment]
Milestones 2018 were added according to the POWB 2018, but there are still missing information
