### ISSUE TITLE
Fix and organize MARLO Parameters.

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#1505]

**Comment by HermesJim** [comment]
![image.png](https://images.zenhubusercontent.com/5798ae8de40e5714b16c9812/8a55310f-fbd5-42e5-aaf2-2255327e5375)

**Comment by sebas932** [comment]
@AndresFVR could you check this issue? please =)

**Comment by HermesJim** [comment]
== UPDATE ==

- The number of the parameters must be the same number in all CRPs.
- Show the new CRPs.

**Comment by HermesJim** [comment]
Update .

![image.png](https://images.zenhubusercontent.com/5798ae8de40e5714b16c9812/31a07f2f-7996-40c0-8aa4-116b69023361)
