### ISSUE TITLE
Create querys to generate OICS for the studies template

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1506]
Queries Folder: CCAFS-KDS\Documents\MARLO\2_Technical\2_7_Data\2_7_2_Queries\Projects\Reporting\OICS_Template

Template folder: CCAFS-KDS\Documentos\MARLO\2_Technical\2_7_Data\2_7_1_Reports\Reporting 2017\Templates

- [x] Outcome Impact Case Studies
- [x] OICS SubIDOs
- [x] OICS SRF Targets
- [x] OICS Countries
- [x] OICS CRPs-Platforms
- [x] OICS Flagships
- [x] OICS Regional Programs
- [x] OICS External Partners

**Comment by htobon** [comment]
@AndresFVR can you please update the status of this issue?

**Comment by AndresFVR** [comment]
@htobon this issue is done, the querys are located in the following folder: CCAFS-KDS\Documents\MARLO\2_Technical\2_7_Data\2_7_2_Queries\Projects\Reporting\OICS_Template
