### ISSUE TITLE
Don't load all the previous activities in the activity lists that is shown in Planning and Reporting.

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#152]
_From @GoogleCodeExporter on March 16, 2015 12:57_

```
The platform will contain many past activities in the next years and, at some 
point, load a list so big will make slower the platform.
```

Original issue reported on code.google.com by `carvajal.hernandavid@gmail.com` on 26 Sep 2013 at 1:05

_Copied from original issue: CCAFS/ccafs-ap#148_

**Comment by htobon** [comment]
_From @GoogleCodeExporter on March 16, 2015 12:57_



Original comment by `htobon` on 3 Feb 2014 at 6:56
* Changed state: **Accepted**
* Added labels: **Milestone-Release1.x**

**Comment by htobon** [comment]
For us to improve the mockup

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-8836e68bb7af454b127180249d9fe18a0a6f0bfc40a3357718438a4e48442a4d.png)
