### ISSUE TITLE
Implement ImpactPathway Permissions

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#155]

**Comment by htobon** [comment]
Is there any evidence? (Image, screenshot, document, etc.?)

**Comment by HermesJim** [comment]
Yes, in the Security Database view (user_permissions); can be see the shiro security string of impactPathways.


![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-4882cad8a3c1b7e858cb63b1123c46c6a4d8682d17968fc891f33d6a4b2a7eec.png)

**Comment by htobon** [comment]
Dont't we have a google spreadsheet made by @sebas932 where we supposed to document all the permissions?

**Comment by HermesJim** [comment]
ah ok.. we dont've this document to MARLO.
@sebas932 going to start to create the document based in the actually user_permisions view.

i created the task #156
