### ISSUE TITLE
Configure MARLO locally

### ISSUE THREAD

**Issue by mralmanzar** [CCAFS/MARLO#1551]
Configure all the development environment of MARLO locally on my PC.

**Comment by mralmanzar** [comment]
Was all installed.
Was installed with the new eclipse version and works fine.
![image.png](https://images.zenhubusercontent.com/5b509ee6a8d8be5bda395611/6fc3d0b9-89ed-4bac-92cc-08fea2b29ca3)

all was correctly configure.

![image.png](https://images.zenhubusercontent.com/5b509ee6a8d8be5bda395611/6f4cd4c5-e96e-45a4-a017-200aa30b40b3)

**Comment by htobon** [comment]
Manuel, can you please update the intallation manual? Thank you in advance.
