### ISSUE TITLE
CIAT MARLO - Fix Issues.

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#1555]
- [x] Project : Program And Regions Section don't save.
- [x] Delete Acronym in Research Programs
- [x] Change Lead Programs to CIAT programs.
- [x] In CIAT Programas Delete CIAT in the list.
- [x] Change the Regions Names (To the Office Name)
- [x] Project Locations : Does not show items in read mode.
- [x] Project Flagship Contributions : Remove the delete button.
- [x] Admin
- [x] Shows I18n Text Acording to the Crp Shared Project.
- [x] Fix: Project regional mapping save
- [x] Fix: Description

**Comment by htobon** [comment]
Favor corregir los Bugs reportados por @sebas932:
- [ ] Me salió un error 500 guardando en la sección de ”CIAT Mapping”, lo que hice fue seleccionar y des-seleccionar “Additional Programs” y el “Program Lead” (http://guybrush.info/s/2018-09-16_223728.png)
- [ ] El validador en ”CIAT Mapping” no parece estar funcionando correctamente, en el modo debug me sale así (http://guybrush.info/s/2018-09-16_230202.png), pero como debería funcionar es así (http://guybrush.info/s/2018-09-16_230235.png)
- [ ] En un Project creado desde CIAT, en Project Locations no salen los “Locations Levels” (http://guybrush.info/s/2018-09-16_231059.png), tampoco salieron las regiones de World Bank (http://guybrush.info/s/2018-09-16_231253.png), salieron después de dar “save”.
