### ISSUE TITLE
Create a Permissions Spreadsheet Document 

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#156]

**Comment by HermesJim** [comment]
I create a pivot SQL query based in user_permissions view, to facilitate the creation of the document

**Comment by HermesJim** [comment]
We add the 1st Version of the MARLO permissions Document.

https://docs.google.com/spreadsheets/d/10tBDZIhmfr7DPAuGQHmRkL3Ji5cREk369RyT8G2okcs/edit#gid=1385857060

**Comment by htobon** [comment]
IS it located in our google drive folder?
If so, may you please tell me where?

**Comment by HermesJim** [comment]
Yes, the Route is 

MARLO/Technical/
