### ISSUE TITLE
Import Means of Verifications based on the proposals

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1562]
Import means of verifications for each of the milestones based on what CRP proposals.

![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/ea0b33ac-3d64-4360-acac-91fad936c72c)

Proposals are located in: 
MARLO\2_Technical\2_2_Documentation\2_2_1_Manuals\CGIAR-SRF\CRP-Proposals-2017-2022
(Table D - PIM Tables)

Technical tasks:
- [ ] Adjust database for milestones
- [ ] Adjust interface in the Impact Pathway section
- [ ] Import data from the proposal
- [ ] Make a report of what was done or could not done and the reason (per CRP)

**Comment by kenjitm** [comment]
This issue was already created and closed in the next milestone (V.2.4.2.15 POWB 2019 Adjustments S2)
