### ISSUE TITLE
Improve AWS Architecture for MARLO

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#157]
I have created an initial architecture for us to discuss and implement taking into consideration flexibility, performance and costs.

The architecture can be accessed online using the following link:
https://cloudcraft.co/view/8f174f37-65f8-4eeb-af28-72ae50c732b4?key=0dK6B0IFXbwYz1Me66O5TQ

![cloudcraft - MARLO Architecture.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/cloudcraft%20-%20MARLO%20Architecture-ee25aea3cffd72cac6c02cfeddd937c5245b825ad2a3c35bf32816310fbcff08.png)

**Comment by htobon** [comment]
Fabian Barco suggested that we should keep using the CIAT's email service.

![cloudcraft - MARLO v2.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/cloudcraft%20-%20MARLO%20v2-aca26c5e504a8ff551881e615163a39944fd058a00ed336077f32006fefd472c.png)

**Comment by pacamargo** [comment]
Hi guys, I have improved the architecture, please check it here: https://cloudcraft.co/view/f5bb6fec-297b-4c5f-8ebd-57a4ab6e477e?key=5N1-Oim3f_wnzCOo6sdzdg
I'm working now on the budget.

**Comment by pacamargo** [comment]
Please check the budget: https://goo.gl/4uhNqE

**Comment by pacamargo** [comment]
Please check this links:
RDS
https://aws.amazon.com/rds/
EBS
https://aws.amazon.com/ebs/
EC2
https://aws.amazon.com/ec2/

**Comment by htobon** [comment]
The new instance EC2 was bought on last friday.
Still pending to set-up the instance and install the users, tomcat, etc. 
Since @pacamargo is on holidays, this issue will be tackled on August.

**Comment by htobon** [comment]
Decided that we will get the RDS instance. The rest of the issue will be tackled in issue #336
