### ISSUE TITLE
POWB 2019 Section: ToC Adjustments/ Changes

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1581]
- [x] Create for 2019
- [x] HTML Fields

![image.png](https://images.zenhubusercontent.com/57fae24d95e42b6c5baa305d/5a1ac12d-bfcc-400c-8c41-420ca0bc1caf)
Mockup: https://docs.google.com/presentation/d/16k9kUv4Yc61OK-alyKn3s6mrNhDahUGgwzdLAf41cE8/edit#slide=id.g2ddff7f74e_0_45

**Comment by HermesJim** [comment]
Update

![image.png](https://images.zenhubusercontent.com/5798ae8de40e5714b16c9812/3fe1d965-a10b-4ee6-98c5-4129f75e6ad8)
