### ISSUE TITLE
POWB 2019 Section: Expected CRP Progress

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1582]
- [ ] Create model
- [ ] Save
- [ ] Autosave
- [ ] Validator
- [ ] Table 2A

![image.png](https://images.zenhubusercontent.com/57fae24d95e42b6c5baa305d/f94dd88e-de6d-4d9f-9364-cee80d7153cf)
Mockup: https://docs.google.com/presentation/d/16k9kUv4Yc61OK-alyKn3s6mrNhDahUGgwzdLAf41cE8/edit#slide=id.g428c573b37_0_275

**Comment by sebas932** [comment]
@HermesJim 

- [ ] [FP Mode] When there is an "autosave" file, the info changed doesn't applied after save 

- [ ] [PMU Mode] The "un-checked" milestones are still showing in the table

- [ ] [PMU Mode] The information entered by FPs doesn't appear in the table
![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/90667558-8523-444b-be80-c015a3baf196)
