### ISSUE TITLE
POWB 2019 Section: Planned Studies

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1583]
![image.png](https://images.zenhubusercontent.com/57fae24d95e42b6c5baa305d/3b327b3d-bfac-473f-951e-888b296746d1)

Mockup: https://docs.google.com/presentation/d/16k9kUv4Yc61OK-alyKn3s6mrNhDahUGgwzdLAf41cE8/edit#slide=id.g42d2e9309d_0_137

- [ ] Table 2B
- [ ] Save
- [ ] Autosave
- [ ] Validator

**Comment by HermesJim** [comment]
Update 

![image.png](https://images.zenhubusercontent.com/5798ae8de40e5714b16c9812/fb46af8e-1730-4bba-8343-02aa7652c2a4)
