### ISSUE TITLE
POWB 2019 Section:  Planned Collaborations

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1584]
![image.png](https://images.zenhubusercontent.com/57fae24d95e42b6c5baa305d/0d42a57e-8e31-472c-b4c0-18487896cb5d)

Mockup: https://docs.google.com/presentation/d/16k9kUv4Yc61OK-alyKn3s6mrNhDahUGgwzdLAf41cE8/edit#slide=id.g42d2e9309d_0_177

**Comment by sebas932** [comment]
This issue is duplicated with #1597
