### ISSUE TITLE
MARLO Family meeting: Action Points 27-09-2018

### ISSUE THREAD

**Issue by mralmanzar** [CCAFS/MARLO#1588]
Action Points of MARLO family meeting
- [x] POWB: See all the studies previous entered in the system, and the ones that are on-going (status) would be able to be edited. 
- [x] POWB: make sure the studies coming from the Management Projects are also available in the synthesis section
- [x]  Word limit for Flagships = (Max. Word Limit/ by FPs * 2) → rounded.
- [x] For the CRPs/Platforms which have a single Key-Output, the mapping to deliverables will be displayed automated.
- [x]  to align this like we do for the outcome impact case studies, i.e. asking geographic scope (global, regional which …, national, which …) - [See screenshot](https://www.screencast.com/t/6ezxft3KnuY)  → can be included in the POWB 2019

**Comment by sebas932** [comment]
@anamp07 has completed the last point pending in commit ee943bb
