### ISSUE TITLE
Update java versión to 8

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#16]

**Comment by HermesJim** [comment]
I Configure JDK v8 in Davinci Server.
[![Jv8.png](https://docs.google.com/a/cgxchange.org/uc?id=0B5EWQK2RIXqAUWJ1UmNuRVFIb1U&export=download)](https://drive.google.com/a/cgxchange.org/file/d/0B5EWQK2RIXqAUWJ1UmNuRVFIb1U/view?usp=drivesdk)
