### ISSUE TITLE
Implement an automated ETL process in Doppler

### ISSUE THREAD

**Issue by mralmanzar** [CCAFS/MARLO#1604]
- [x] Publish the ETL files on Github
- [x] Develop the ETL process on Doppler server
- [x] Create the job to automatize the process
- [x] Test
- [x] Create an informative [document]( 
https://cgiar.sharepoint.com/:w:/r/sites/CCAFS-KDS/_layouts/15/Doc.aspx?sourcedoc=%7B467A2777-AF92-46EF-AE69-BE3573F4E60A%7D&file=MARLO%20BI%20using%20Pentaho%20BI%20Suite.docx&action=default&mobileredirect=true)

**Comment by htobon** [comment]
Test
