### ISSUE TITLE
Deliverables: Redefine the list of licenses on MARLO

### ISSUE THREAD

**Issue by mralmanzar** [CCAFS/MARLO#1607]
Accordingly to the mail write on 22 October, add the CGSpace Licenses to MARLO.

**Comment by mralmanzar** [comment]
- Should check the licences created on Marlo and synchronize with the licences on CGspace accordingly  the page https://spdx.org/licenses/
- Include the licence name on the sync

**Comment by sebas932** [comment]
After a meeting with @AndresFVR and @htobon we decide to turn the current Licenses into database form and apply in deliverables.

Additionally, we need to meet with David in order to get in deep over this issue.

**Comment by sebas932** [comment]
In the last F2F meeting MARLO Family decides to takeout the list from MARLO
