### ISSUE TITLE
Feedback AR2017: Improve the automated link between MARLO and the IFPRI E-Brary

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1620]
> Deliverables - sync between MARLO and IFPRI's E-brary. Two small issues that we wish could be improved for next year's reporting: 1) the ebrary link doesn’t populate all the information for journal articles. I suspect this is because the ebrary lists the journal name, volume and issue all in one line and is not uniform, so the MARLO team didn’t have a specific format to pull this information directly. Therefore, we are asked to add the journal article, volume and issue for these individually. 2) Also, issue numbers are mandatory, but not all journals have issue numbers. I’m not sure if we should be substituting the month-year when there is no issue number?

**Comment by sebas932** [comment]
@AndresFVR here there is a table with some fields that we can improve

![image](https://user-images.githubusercontent.com/4406128/51619330-10916000-1efe-11e9-957e-f26a0d117f00.png)

**Comment by AndresFVR** [comment]
- [x] Description / Abstract
- [x] Publication / Creation date
- [ ] Publisher
- [ ] License
- [ ] Open Access
- [ ] ISI
- [ ] Journal
- [ ] Volume
- [ ] Issue
- [ ] Pages

**Comment by sebas932** [comment]
@AndresFVR I tried with the following link and it does not work
`http://cdm15738.contentdm.oclc.org/cdm/singleitem/collection/p15738coll3/id/157/rec/1`

**Comment by AndresFVR** [comment]
Thans @sebas932 , now it works. The problem was because it had a wrong doi url.
