### ISSUE TITLE
Migrate project budget by partners from POWB 2018 to 2019

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1626]
Ver ticket: https://marlo.freshdesk.com/a/tickets/516
Related with issue #1625

Currently, when a Project FS is saved in POWB 2018, the Project FS is not being replicated to POWB 2019.

- [x] Update interface in System Admin Bulk Replication: Add "section" select option
- [x] Create method to replicate Project Budgets: Any Project FS from POWB 2018 to POWB 2019 (in 2019 add budget =0)
- [x] Detect which crps haven't started planning 2019.
- [x] Migrate Project FS from POWB 2018 to POWB 2019.

**Comment by HermesJim** [comment]
[Update] I'll review and do the last actions points to close this issue.

**Comment by HermesJim** [comment]
[Update] I had reviewed all the information of the funding sources that was create at 2018 and these had a good 2019 replication. Maybe this issue was fix it but it was not closed.

I put it on review this issue, @htobon if you think this issue is able to close, please close it please.

**Comment by htobon** [comment]
Hi @HermesJim, did you had a chance to take a look at Tigist's message in the ticket system? She was the person who reported this issue.

**Comment by htobon** [comment]
Hello @HermesJim, I am still looking forward to your response to my question 8 days ago.
Will mark this issue as "New".
Cheers,
Hector.

**Comment by htobon** [comment]
Closing this issue. If something in project budget happens again in terms of data migration, we will create a new issue.
Thank you for your patience with this.
