### ISSUE TITLE
CIAT MARLO Feedback improvements [Nov 23rd, 2018] 

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1641]
- [x] Check the privileges of Program Leaders, they have issues creating new projects

- [x] Organize the list of projects depending on the user's permissions

- [x] To disable the CIAT MARLO automated emails 

- [x] Take out "CIAT Regions" and "Centers" from the "CIAT Lead Program" fo project
 ![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/cd589687-2681-4c1d-9b44-f15371a90fd3)

**Comment by HermesJim** [comment]
These Improvements are now in production.
