### ISSUE TITLE
Enable some categories of deliverables in CIAT MARLO

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1644]
Enable the following categories of deliverables in MARLO CIAT:
![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/bc604707-fd13-4db7-96b0-35f8ef124fca)

**Comment by sebas932** [comment]
@AndresFVR here is the sheet of deliverables classification to be updated after the change
https://docs.google.com/spreadsheets/d/16hpfWLAnfLNxLQtRqMBWjkw_BiPdKAUcB2simMmY9Yw/edit#gid=1095513705

**Comment by AndresFVR** [comment]
Hi @sebas932 the deliverable categories for CIAT have been enabled in the commit https://github.com/CCAFS/MARLO/commit/560d3b6517efd7aa487c8548ab44304c62d2a789.
Also the document have been updated.
