### ISSUE TITLE
CavDev feedback

### ISSUE THREAD

**Issue by kenjitm** [CCAFS/MARLO#1645]
**Types of participant:**
- [x] Farmer/ Producer - Includes farmers, smallholders, and agri-business producers.
- [x] Value Chain Actor - Includes input and output suppliers (agrodealers), aggregators, processors, storage suppliers, insurance suppliers, energy companies, etc.
- [x] Policy Maker - Includes politicians, policy advisers, government representatives, representatives from institutions with policy-making capacity.
- [x] Researcher - Includes both CGIAR and non-CGIAR researchers, including partner researchers and visiting researchers such as interns, MScs, PhDs, or researchers on sabbatical.
- [x] Technician: <DEFINICION PENDIENTE POR SIMONE>
- [x] Students: <DEFINICION PENDIENTE POR SIMONE>
- [x] Consumer - Includes users of goods and services at the final point of consumption. Consumers are only counted here where they are active participants in CGIAR activities, not simply as consumers of CGIAR research outputs, varieties, etc.
- [x] Funder - Includes funders/donors of all types, including government representatives participating in activities as funders.
- [x] Other - CRPs should include an opportunity/text box for suggestions here. If there are many suggestions of the same type, we can create a new category. If not, we revise existing categories to incorporate suggestions.
               
**Individual intervention:**
*Types:*
- [x] En vez de Sabatical - Placement or training visiting
- [x] Sacar Field trip.
- [x] Sacar Train the trainers.
- [x] El tipo Individual trainee es redundante porque estamos en una intervención individual.

- [x] Quitar la parte de Reach para las intervenciones individuales:
- [x] Comentar código.
- [x] Quitar esos dos campos en intervenciones individuales: Target group y partners.
- [ ] Las preguntas restantes pueden ir en description y quitar la sección de Additional information.
               
**Research programs dropdown:**
- [x] No está cargando del listado original. Hay programas que ya cambiaron de nombre. El listado debe cambiar en relación a los programas que existen en el panel de configuración.
 
 
**Group Interventions:**
- [x] En la pregunta de numeros de participantes, para cada una, poner debajo una opcion que pregunte si el numero es un estimado o no: "[] This number is an estimate".
- [ ] Dejar el Reach porque si es importante pero adaptarlo al modulo de geographical scope.
- [x] En target groups, cambiar por Type of Participants
- [x] Poner el listado de participantes que se encuentra arriba de esta nota 
- [x] Poner que Type of Participants sea de selección unica.
- [ ] Mover la pregunta (type of partipants) a description .
- [x] Preguntar si la intervención tiene un CapDev focalizado o no (Capdev-focused, Activity with some capdev objectives).

**Comment by htobon** [comment]
Hola Kenji, muchas gracias.
Aquí te dejo mi retroalimentación

- [ ] Pregunta de intervenciones en desarrollo de capacidades focalizadas:
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/75a413f8-2495-4a32-a624-f866c9d01ed9)

- [ ] Group Interventions / Type of participants:
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/8f6eea38-8559-4daa-b64a-c1939c3803b8)

- [ ] Listado de programas de CIAT en intervenciones grupales e individuales:
 ![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/67be1d4e-d08e-4594-b34d-8033371bb7ff)

- [ ] Revisar qué sucede con la internacionalización. Hice Ctrl + R, cargó bien, pero la siguiente vez volvió a cargar mal.
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/aa717d41-ad3f-49af-8013-ac8dab482384)

**Comment by sebas932** [comment]
Part of this issue was created in a separated issue, see #1668
