### ISSUE TITLE
AR 2018 - Projects: Create policies section

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1655]
![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/50831aa1-2563-4c3e-9549-41b69b7fc895)

--

![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/703fdaf8-632f-403d-ae36-c08bc38d1472)
![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/54c2b101-deeb-4040-80b0-e03bdd88250d)

**Comment by HermesJim** [comment]
We are still working on finish the Project Policies section.
but the section is already to be tested in MARLO dev.

**Comment by htobon** [comment]
- [ ] Please make sure the policies section is marked as optional. What would happen if a project does not have policies at all? How can the Project Leader mark the section as complete?
![image](https://user-images.githubusercontent.com/5375915/51132971-b90a3a80-1801-11e9-8ac3-e868c289742a.png)

- [ ] Validators for missing fields are not working. 
I created a new policy, then, hit the save button and got the following interface, which is wrong.
![image](https://user-images.githubusercontent.com/5375915/51133131-20c08580-1802-11e9-8f80-a4aa4f077501.png)
