### ISSUE TITLE
AR 2018 - Projects innovation adjustments

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1657]
![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/716aaccb-be89-4e96-884a-4d8d6dfd4640)
![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/72dbe2ef-0990-4610-8ad6-b3ba4f14bd11)
![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/4ba1e8fb-0558-46bb-aa28-082cfb88a4f5)

**Comment by kenjitm** [comment]
- [ ] Interface
- [ ] Save
- [ ] Validators
- [ ] History

**Comment by sebas932** [comment]
We will leave the History in a separate issue, it need to be adjusted for several sections.
Closing the issue
