### ISSUE TITLE
Develop MARLO to allow SERVIR Application with a different domain name

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1662]

**Comment by HermesJim** [comment]
Fix the HttpServlet exception when try to enter whit a not root URL.

**Comment by sebas932** [comment]
![image](https://user-images.githubusercontent.com/4406128/51390658-e1de4880-1afd-11e9-832c-5fdd02085955.png)

![image](https://user-images.githubusercontent.com/4406128/51390588-b78c8b00-1afd-11e9-9e54-b9ce42fe9861.png)
