### ISSUE TITLE
Update library versions.

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#17]

**Comment by htobon** [comment]
May you please list here the libraries and the versions that we will use from now on?

**Comment by cgarcia9106** [comment]
struts2.version 2.3.16
struts2-json.version 2.3.16
guice.version 3.0
mysql.version 5.1.39
junit.version 4.12
servlet-api.version 2.5
jsp-api.version 2.0
janino.version 2.7.8
poi.version 3.13
flyway.version 4.0.1
org.json.version 20160212
hibbernate-core-version 5.1.0.Final
jta-version 1.1
hibernate-c3p0-version 5.0.6.Final
commons-logging-version 1.2
xml-apis-version 1.4.01
apache-shiro-version 1.2.4
groovy-version 2.4.6
jasperreports-fonts-version 6.0.0
jasper-reports-version 6.2.2
