### ISSUE TITLE
Fix Outcomes issues

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#170]
- [x] Outcomes: Target Year limits (milestones year < outcome year)
- [x] Outcomes: Targets fields ordering (Target Year, Unit, value)
- [x] Outcomes: Contributions percentage validation per outcome
- [x] Outcomes: Improve process for selecting a Sub-Ido (Show Image)
- [x] Outcomes: Show idos types

**Comment by cgarcia9106** [comment]
@cgarcia9106  Outcomes: Target Year limits (milestones year < outcome year)
 @carios1usb  Outcomes: Contributions percentage validation per outcome
Outcomes: Improve process for selecting a Sub-Ido (Show Image) Won't fix on this sprint.
@cgarcia9106  Outcomes: Show idos types

**Comment by cgarcia9106** [comment]
@cgarcia9106 Outcomes: Target Year limits (milestones year < outcome year) done
