### ISSUE TITLE
AR2018: Project Budget Expenditures

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1719]
![image](https://user-images.githubusercontent.com/4406128/52421699-9d254c00-2ac2-11e9-9040-67a04b79f805.png)

**Comment by AndresFVR** [comment]
- [x] Model
- [x] Prepare
- [x] Save
- [ ] Autosave
- [ ] History
- [ ] Permission
- [ ] Validation
- [x] Interface
- [ ] Specificity

**Comment by AndresFVR** [comment]
Falta desarrollar la parte del history para terminar el modulo:

En este momento no se guarda el histórico de budget expenditures y cuando se ingresa al histórico se muestran estos campos como editables (lo cual esta mal).

**Comment by AndresFVR** [comment]
Requested changes by Hector: 

- [ ] Create permissions per budget type and assign (FM->All / CP -> Center funds)
- [ ] Analyze where could expenditures fit in the current reports
- [ ] Read mode (edit=false) not working properly (expenditures are still editable)
- [ ] Add overall year total and total per budget type.

**Comment by htobon** [comment]
Next Action Point is to talk with Julian and ask some final questions on how to move ahead with the production environment for CCAFS.

**Comment by sebas932** [comment]
This was done, if there are extra features we must create a separated issue
