### ISSUE TITLE
Adjust the Dissemination & Metadata deliverable section with the changes proposed by Pascale

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1727]
![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/b775ddb6-5446-4bd0-96a0-1c70eef4d526)

**Comment by sebas932** [comment]
Done, still pending the validator with the new fields (@AndresFVR )

**Comment by AndresFVR** [comment]
Added validator
