### ISSUE TITLE
[HJ]Revamp Activities model

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1729]
Changel model from composed_id to activities_info

See ticket #661: https://marlo.freshdesk.com/a/tickets/661

**Comment by HermesJim** [comment]
[Update]
This is the new Project Activities Model. 

![image.png](https://images.zenhubusercontent.com/5798ae8de40e5714b16c9812/17af1e38-eccf-4cb7-9544-bd2daa14c524)

**Comment by MateoVieira** [comment]
@yeyo2k3 can you check if this had been implemented?

**Comment by yeyo2k3** [comment]
Team decided to close and does not implement this issue.
