### ISSUE TITLE
Texts are not loading in MARLO (Internationalization file - .properties)

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1730]
Sometimes the properties file where the internationalized texts are found is not loading very well. What causes confusion among users because instead of loading the texts, the keys are loaded.

**Comment by kenjitm** [comment]
![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/ebb64683-7354-43ab-8788-00cac9cd9f47)
