### ISSUE TITLE
AR 2018 - Synthesis: Create a prototype

### ISSUE THREAD

**Issue by anamp07** [CCAFS/MARLO#1735]
**0. Narrative**
- [x] Executive Summary

**1. Key Results**
- [x] 1.1 Progress towards SDGs & SLO
- [x] 1.2 Progress by CRP Flagships
- [x]  Table 2: Policies
- [x]  Table 3: Table 3: Outcome/ Impact Case Reports
- [x]  Table 4: Innovations
- [x]  Table 5: Outcomes & Milestones
- [x]  Table 6: Publications
- [x] 1.3 Cross-Cutting Dimensions 

**2. Effectiveness and Efficiency**
- [x] 2.1 Management and Governance
- [x] 2.2 Partnerships
- [x] 2.3 Intellectual Assets
- [x] 2.4 MELIA
- [x] 2.5 Efficiency
- [x] 2.6 Management of Risks
- [x] 2.7 Use of W1-2 Funding

**3. Financial Summary**
- [x] 3.1 Financial Summary

**Comment by sebas932** [comment]
This was done
