### ISSUE TITLE
Create a report with all OICR of CCAFS

### ISSUE THREAD

**Issue by mralmanzar** [CCAFS/MARLO#1741]
Should create an Excel report that exports all OICR of CCAFS, like previous reports that was send.
This information should be Ready on march 25.

-------
Subject: RE: 2018 Outcomes.
 
Hi Bruce and Dhanush,
Does March 26th work for you guys? Project leaders have until March 25th to complete them.
Cheers,
David
 
From: Bruce 
 
David, can you predict on what day we can get a print out of all outcomes, as I have to book time with our external reviewers.
 
Best, Bruce

**Comment by kenjitm** [comment]
this issue is duplicated with #1357
