### ISSUE TITLE
OCS Web Service - Test Email Researcher

### ISSUE THREAD

**Issue by mralmanzar** [CCAFS/MARLO#1743]
Buenos días,

Se ha incluido el campo researcherEmail con la información de correo del investigador, este cambio se encuetra disponible en el servicio web getMarloAgreements, El link de pruebas donde se encuentra este cambio es el siguiente:

http://beta8.ciat.cgiar.org/abwws/MarloPort?wsdl

Es importante incluir en las cabeceras de la solicitud http los siguientes atributos

La estructura de respuesta del servicio web es la siguiente:

![image.png](https://images.zenhubusercontent.com/5b509ee6a8d8be5bda395611/f5b14f6e-07a4-4f0e-9b75-9a4e3ebbdb5b)

Por favor realizar la pruebas del consumo de este servicio y notificarnos por este medio con la finalidad de desplegar este cambio en el ambiente de producción.

Muchas gracias por la atención prestada.

Saludos,

**Comment by sebas932** [comment]
This ticket was re-assigned to @kenjitm, he suggests to meet with Hector to talk about this

**Comment by HermesJim** [comment]
[Update] I had implemented the new changes of the OCS Service and it works correctly in MARLO. I replied the email to Victor (OCS team) to update this changes in production.

**Comment by HermesJim** [comment]
OCS team has deployed the new version of their application including the Emails Researcher into our Web Service.
I had tested in production environment with successful results.
