### ISSUE TITLE
1.1 Progress towards SDGs &SLO 

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1747]
- [x] Interface
- [x] Model
- [x] Prepare
- [ ] Autosave
- [ ] History
- [x] Save
- [x] Validation
- [x] Permissions

**Comment by anamp07** [comment]
Sale un error después de hacer click en guardar. (https://www.screencast.com/t/IJmvaJ68uaN)

**Comment by HermesJim** [comment]
Solved.. Permissions modified for FPLs and PMUs

**Comment by sebas932** [comment]
We will leave the History and Autosave in a separate issue, it need to be adjusted for several sections.
Closing the issue
