### ISSUE TITLE
1.3 Cross-Cutting Dimensions

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1749]
- [x] Interface
- [x] Model
- [x] Prepare
- [ ] Autosave
- [ ] History
- [x] Save
- [x] Validation
- [x] Permissions
- [x] Graphs and lists
- [x] Table 7

**Comment by AndresFVR** [comment]
This section has changed because template changed.

**Comment by anamp07** [comment]
Climate change optional field is validated as required in section 1.3 Cross-Cutting Dimensions. (https://www.screencast.com/t/UJrtfsdTyRLY)
