### ISSUE TITLE
Samples

### ISSUE THREAD

**Issue by MargaritaRamirez** [CCAFS/MARLO#1763]
Soporte servidor Samples: El desarrollador Michael solicita revision del servidor ya que al ingresar nota lentitud en el sistema y al tratar de actualizar algunos plugins no se le es permitido por tema de permisos

**Comment by MargaritaRamirez** [comment]
Se reviso el servidor en conjuto con Santiago Restrepo, no se encuentran evidencias de ataques al servidor. 
En cuanto a permisos se solicitó al desarrollador revisarlos y cambiarlos pues algunos archivos son propiedad de SUDO.

**Comment by MargaritaRamirez** [comment]
Nos encontramos a la espera que TI nos confirme disponibilidad para configurar la instancia

**Comment by MargaritaRamirez** [comment]
Nos encontramos a la espera que TI nos confirme disponibilidad para configurar la instancia

**Comment by sebas932** [comment]
Closed due to this server was moved to another IT provider, CIAT IT will shut down the server in order to avoid futures charges
