### ISSUE TITLE
Create a Web Statistics report for 2108 in CCAFS

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1771]
Compile 2018 data for all the different data portals and websites and share with Marissa.
Files should be located in: KDS\2_Administrative\2_2_Reports\2_2_2_Statistics

**Comment by MargaritaRamirez** [comment]
We sent to Marissa the document on march 14. 
Waiting for her to reply

**Comment by sebas932** [comment]
The report was built with the statistics for 2018 at our end, if there any change, this will be handled in another issue.
