### ISSUE TITLE
Deliverables Summary: Tke out patent or PVP, Participants and Trainees

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1782]
These reports are currently not included into deliverables summaries.

**Comment by sebas932** [comment]
This report is not required anymore, MARLO Family decides to remove from MARLO

**Comment by htobon** [comment]
Hi Sebas, 
We agreed with MARLO Family that before taking out the fields in MARLO, we will share all data we have with them. Can you please confirm this was done?

Meanwhile, I am moving this issue to Review.

**Comment by sebas932** [comment]
This is a different issue, and there is no information about Intellectual assets to export in MARLO, this module was never used by anyone.

**Comment by htobon** [comment]
@sebas932 Noted. Thank you.
