### ISSUE TITLE
CGIAR Results Dashboard - Action Points

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1786]
**As per the meeting of April 8th, here are the Action Points for this week (April 8-12):**

- [x] Action Point: This week (**8-12 Apr.**) we will start to upload the data into the Dashboard and we expect to finalize this process by Apr. 17. Migration will be Apr. 12,  week of the Apr. 15-17 working with Tania to create in Tableau. (Tania off 22-26 Apr)
  - [x] Innovations (#C1)
  - [x] Formal Partnerships and Key Partnerships (#C2)
  - [x] Publications (#C4)
  - [x] Policies (#I1)
  - [x] Altmetrics (this is outside MARLO, but pulled in) (#I2)
  - [x] Outcome Impact Case Studies 

- [x] Manuel to update the excel status dashboard.

- [x] Action Point: This week - Manuel and Hector to prepare mockups on how the dashboard will look like and the adjustments needed by Tania (e.g. Pop-ups, Clarification messages, etc.).

- [x] Action Points: Manuel and Hector to prepare a mockup to present the CapDev indicator.

- [x] Action Point: Sebastian, Ana Maria and Manuel to propose a proper color palette for the dashboard. Maybe 2-3 options or only the right one

- [x] Action Point: Manuel to prepare/collect a list of adjustments/improvements needed, prioritize them and propose a work plan with the development team.

- [x] Action Point: Manuel to explore what we can do in terms of 2018 data

**Comment by mralmanzar** [comment]
All these items were done for AR2017.

![image](https://user-images.githubusercontent.com/9383649/57391408-185ed280-7184-11e9-8e6d-143e68ef61ce.png)
**Still pending to start developing the 2018 cubes.**
