### ISSUE TITLE
AR2018: Release selected reporting data to SMO for a cross-CGIAR data quality assurance exercice

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1797]
## In MARLO

**A4NH**
- [x] Evidence A: Policies
- [x]  Evidence B: Innovations
- [x]  Evidence C: Outcomes & Milestones
- [x]  Evidence F: Current External Partners
- [x]  Confidential OICRs (No Confidential Info)

**BIGDATA**
- [x]  Evidence A: Policies (No Data - [See screenchot](https://i.imgur.com/SF9aBNS.png))
- [x]  Evidence B: Innovations
- [x]  Evidence C: Outcomes & Milestones
- [x]  Evidence F: Current External Partners
- [x]  Confidential OICRs (No Confidential Info)

**CCAFS**
- [x]  Evidence A: Policies
- [x]  Evidence B: Innovations
- [x]  Evidence C: Outcomes & Milestones
- [x]  Evidence F: Current External Partners
- [x]  _Evidence D: Publications_
- [x]  Annual Report Document
- [x]  Confidential OICRs

**FTA (AR2018 NOT STARTED)** 
- [x]  Evidence A: Policies (No Data)
- [x]  Evidence B: Innovations (No Data)
- [x]  Evidence C: Outcomes & Milestones (No Data)
- [x]  Evidence F: Current External Partners (No Data)
- [x]  Confidential OICRs (No Data)

**LIVESTOCK**
- [x]  Evidence A: Policies
- [x]  Evidence B: Innovations
- [x]  Evidence C: Outcomes & Milestones
- [x]  Evidence F: Current External Partners
- [x]  Confidential OICRs

**MAIZE**
- [x]  Evidence A: Policies
- [x]  Evidence B: Innovations
- [x]  Evidence C: Outcomes & Milestones
- [x]  Evidence F: Current External Partners (No Data - [See screenshot](https://i.imgur.com/pc987Jq.png))
- [x]  Confidential OICRs

**PIM**
- [x]  Evidence A: Policies
- [x]  Evidence B: Innovations
- [x]  Evidence C: Outcomes & Milestones
- [x]  Evidence F: Current External Partners
- [x]  Confidential OICRs

**RICE**
- [x]  Evidence A: Policies
- [x]  Evidence B: Innovations
- [x]  Evidence C: Outcomes & Milestones
- [x]  Evidence F: Current External Partners
- [x]  Confidential OICRs

**WHEAT**
- [x]  Evidence A: Policies
- [x]  Evidence B: Innovations
- [x]  Evidence C: Outcomes & Milestones
- [x]  Evidence F: Current External Partners (No Data - [See screenshot](https://i.imgur.com/9fETkgr.png))
- [x]  Confidential OICRs

**WLE**
- [x]  Evidence A: Policies
- [x]  Evidence B: Innovations
- [x]  Evidence C: Outcomes & Milestones
- [x]  Evidence F: Current External Partners
- [x]  Confidential OICRs

## Not in MARLO
- GLDC
- RTB
- FISH

**Comment by mralmanzar** [comment]
on Confidential OICS, just CCAFS has 3 confidential, No other CRP use this functionality
