### ISSUE TITLE
Update the MARLO information with what is reported by CCAFS in the annual report document

### ISSUE THREAD

**Issue by mralmanzar** [CCAFS/MARLO#1798]
CCAFS sent the information of its AR2018 and we must validate if each section of the final report is correctly created in MARLO.
In case the information is not present, it must be included.
If it is wrong, it must be corrected.

**Comment by sebas932** [comment]
Notes from meeting:

** Prioritize Table 6: Publications:
- @mralmanzar : To export information of Management Liaisons in charge of each deliverable and deliver to @MargaritaRamirez 
- @MargaritaRamirez : Agroup publications per Management Liaison in a excel document
- @MargaritaRamirez : Notify to Management Liaisons deliverables changes (See Angela's email template)
- @sebas932: To improve the interface of synthesis publications in order to show relevant information like Deliverable ID
- @MargaritaRamirez: To update in MARLO the deliverables previously confirmed

Deadline: Confirm with David

**Comment by sebas932** [comment]
### To validate:


- [ ] EXECUTIVE SUMMARY

**1. Key Results**
- [ ] 1.1 Progress Towards SDGs and SLOs
- [ ] 1.2.1 Overall CRP progress
- [ ] 1.2.2 Progress by flagships
- - [ ] Flagship 1 (FP1) progress
- - [ ] Flagship 2 (FP2) progress
- - [ ] Flagship 3 (FP3) progress
- - [ ] Flagship 4 (FP4) progress
- [ ] 1.2.3 Variance from Planned Program for this year
- - [ ] A) Have any promising research areas been significantly expanded?
- - [ ] B) Have any research lines been dropped or significantly cut back?
- - [ ] C) Have any Flagships or specific research areas changed direction?
- [ ] 1.2.4 Altmetric and publication highlights
- [ ] 1.3.1 Gender
- - [ ] A) List any important CRP research findings
- - [ ] B) What have you learned? What are you doing differently?
- - [ ] C) Have any problems arisen in relation to gender issues or integrating gender into the CRP’s research?
- [ ] 1.3.2 Youth and other aspects of social inclusion/“Leaving No-one Behind”
- - [ ] A) List any important CRP research findings
- - [ ] B) What have you learned? What are you doing differently?
- - [ ] C) Have any problems arisen in relation to youth issues or integrating youth into the CRP’s research?
- [ ] 1.3.3 Capacity Development
- [ ] 1.3.4 Climate Change

**2. Effectiveness and Efficiency**
- [ ] 2.1 Management and governance
- [ ] 2.2.1. Highlights of External Partnerships
- [ ] 2.2.2. Cross-CGIAR Partnerships
- [ ] 2.3 Intellectual Assets
- - [ ] Have any intellectual assets been strategically managed by the CRP (together with the relevant Center) this year?
- - [ ] Indicate any published patents and/or plant variety right applications (or equivalent)
- - [ ] List any critical issues or challenges encountered in the management of intellectual assets in the context of the CRP
- [ ] 2.4 Monitoring, Evaluation, Impact Assessment and Learning (MELIA)
- [ ] 2.5 Efficiency
- [ ] 2.6 Management of Risks to Your CRP
- [ ] 2.7 Use of W1/W2 Funding

- [ ] **3. Financial Summary**

** Tables
- [ ] Table 1: Evidence on Progress towards SRF targets
- [ ] Table 2: Condensed list of policy contributions in this reporting year
- [ ] Table 3: List of Outcome/ Impact Case Reports from this reporting year
- [ ] Table 4: Condensed list of innovations by stage for this reporting year
- [ ] Table 5: Summary of status of Planned Outcomes and Milestones
- [ ] Table 6: Numbers of peer-reviewed publications from current reporting period
- [ ] Table 7: Participants in CapDev Activities
- [ ] Table 8: Key external partnerships
- [ ] Table 9: Internal Cross-CGIAR Collaborations
- [ ] Table 10: Monitoring, Evaluation, Learning and Impact Assessment (MELIA)
- [ ] Table 11: Update on Actions Taken in Response to Relevant Evaluations
- [ ] Table 12: Examples of W1/2 Use in this reporting period (2018)
- [ ] Table 13: CRP Financial Report

**Comment by sebas932** [comment]
We finally finished the update. Thank you @MargaritaRamirez !
