### ISSUE TITLE
Create an Acronyms service on CLARISA

### ISSUE THREAD

**Issue by mralmanzar** [CCAFS/MARLO#1800]
Should create a new service on CLARISA y order to get a list of acronyms included on:
- CCAFS Anual Report 2018
- CCAFS  site https://ccafs.cgiar.org/resources/acronyms

**Comment by mralmanzar** [comment]
Was created 2 services: Gell all acronyms and get acronym by id.
can be test it on marlodev.
![image](https://user-images.githubusercontent.com/9383649/61328279-485bcf00-a7e0-11e9-8719-2cef0b69e738.png)

**Comment by htobon** [comment]
Hi @mralmanzar, thanks for working on this.
The first service to get all the acronyms is ok, but the second one by ID is useless.
It would be more useful to have a service by the acronym.

Does it make sense?

**Comment by mralmanzar** [comment]
Was deleted the search by id of acronym service and replaced by a search by the acronym
![image](https://user-images.githubusercontent.com/9383649/61544360-e206c480-aa0a-11e9-9c91-2547fb5bdc24.png)

**Comment by htobon** [comment]
Hi @mralmanzar, again, I am not sure why this issue is here for review.
Can you please let me know what to do and where?
Meanwhile, I am moving this issue again to "New".
Cheers,
Hector.

**Comment by htobon** [comment]
Please refer below to some minor adjustments. 

As soon as you adjust the texts please release this the production environment and *let me know* via email so I can get back to Philippe.

Thank you for the work on this.

- [ ] Adjust description
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/416a3351-b9db-405b-b2c8-5f328f80711e)

- [ ] Adjust desription
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/3891391e-92bc-4786-a732-9135e1c8b223)

**Comment by mralmanzar** [comment]
Was updated the descriptions and deploy on production.
![image](https://user-images.githubusercontent.com/9383649/61962970-5fdd4980-af90-11e9-8e83-dae4ed0d502c.png)
