### ISSUE TITLE
Modify the MARLO security module to support external users

### ISSUE THREAD

**Issue by mralmanzar** [CCAFS/MARLO#1805]
For CLARISA it is necessary to create users read only that are not related to any CRP / PTF.
Currently, a user in the security model of MARLO must be associated with a global unit (crp_users) and the role is related to a global unit.
The security module must be modified to allow creating users that have no relation with any CRP / PTF.
For Example, create an user for CGSPACE

**Comment by htobon** [comment]
@mralmanzar Please document this issue and close it.
Thank you.
