### ISSUE TITLE
Create a Knowledge by the numbers newsletter

### ISSUE THREAD

**Issue by MargaritaRamirez** [CCAFS/MARLO#1808]
deliver the document with the paragraphs by June 28
1. write the paragraphs
2. show David for review and approval
3. Send Marissa for final review

**Comment by htobon** [comment]
Moving this issue to review as it is being checked and improved by Marissa.

**Comment by MargaritaRamirez** [comment]
We are waiting for the reviewing meeting with Marissa

**Comment by MargaritaRamirez** [comment]
Marissa sent the official communication on July 18
