### ISSUE TITLE
Create a revamp workplan for CCAFS Data & Tools section

### ISSUE THREAD

**Issue by MargaritaRamirez** [CCAFS/MARLO#1809]
deliver the work plan by June 28

**Comment by MargaritaRamirez** [comment]
We delivered a work plan for the sprint va.2.23 
For the next sprint we have to get the first draft of the publications in Data & Tools: Marissa told us that the Macaronni Brother from the back-end can get the information

**Comment by htobon** [comment]
Hi @MargaritaRamirez, 

Very good organized and documented.

I checked the workplan, the activities and the timeline, and they make sense to me.
With regards to the website protocol, it would be great to meet and improve the English as well as the questions we will ask the people in charge of the portals.

At some point, it would be great to touch base with David.

Thank you in advance,

Hector.

**Comment by MargaritaRamirez** [comment]
Hi @htobon, 

As this is only the work plan issue i will close it. 
The website protocol is another issue (#1812)
