### ISSUE TITLE
Create a process to expose a Project Page from MARLO in the CCAFS Website

### ISSUE THREAD

**Issue by MargaritaRamirez** [CCAFS/MARLO#1810]
design a work plan with Héctor by June 28

**Comment by MargaritaRamirez** [comment]
We will start the discussion with the MARLO back-end team

**Comment by htobon** [comment]
Hi @MargaritaRamirez, can you please let us know why this issue is reviewing process?
What needs to be reviewed and by whom?
I will move it to "New" meanwhile you respond.

Cheers,
Hector.

**Comment by MargaritaRamirez** [comment]
Hi @htobon this was the issue of the working plan and i was waiting for your comments. 
We created a new issue with Hermes of the process with the back-end so we can develop a service and document it. Perhaps we can delete this issue and continue with the new one in order to be organize and we can follow up the entire process. 

Cheers, 
Margarita
