### ISSUE TITLE
[CLARISA] Create query and create innovations services

### ISSUE THREAD

**Issue by mralmanzar** [CCAFS/MARLO#1813]
- [x] (GET) find an innovation by id
- [x] (POST) create a new innovation
- [ ] (TEST) testing service

**Comment by mralmanzar** [comment]
Was created 2 new services for Innovations.
Find an innovation by id 
![image](https://user-images.githubusercontent.com/9383649/60609352-1cbffa00-9d87-11e9-8a31-413636872294.png)
![image](https://user-images.githubusercontent.com/9383649/60609392-319c8d80-9d87-11e9-9a43-118e2a3b2299.png)
Create a new innovation
![image](https://user-images.githubusercontent.com/9383649/60609531-7f18fa80-9d87-11e9-9f12-7ee20b6506de.png)

**Comment by htobon** [comment]
Hello @mralmanzar,
Can you please let me know what needs to be reviewed here, the plan and who will do it?
Thank you in advance,
Hector

**Comment by mralmanzar** [comment]
Create and new innovation services finalized and putted on Dev environment.
@kenjitm can you please test those services?
You can test it with RTB, Project 1585 on 2018.
Tks

**Comment by yeyo2k3** [comment]
I include phase parameter to identify where are we working on for example AR+year, but Like every service on clarisa has the same problem if someone using a aplication not server, like angular, javascript etc couldn't use this feature

**Comment by yeyo2k3** [comment]
I modify get innovation method, Cause this  doesn't get countries relationship properly.

Now @sebas932 could be test it.

**Comment by yeyo2k3** [comment]
in last conversation.  I fixed json structure to implement Json Objects to identify relationship and remove ID String Arrays
