### ISSUE TITLE
Target units list

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#182]
ask hector the real list of target units

**Comment by cgarcia9106** [comment]
@htobon  Recuerda gestionar esta lista

**Comment by cgarcia9106** [comment]
% / year
% increase
% reduction
Agricultural development initiatives
Countries/states
Development organizations
Low emission plans
Million farm households
Million hectares (ha)
Million farm households
Million people
Organizations and Institutions
Policy decisions taken
Practices
Site-specific targeted CSA technologies/practices
Subnational public/private initiatives
Technologies

**Comment by htobon** [comment]
ok
