### ISSUE TITLE
Mockup to explain the process to finalize/close projects in MARLO.

### ISSUE THREAD

**Issue by mralmanzar** [CCAFS/MARLO#1837]
Design a mockup to explain the process to finalize/close projects in MARLO.
Sometimes when the project finalize, some deliverables, OICR, etc. still pending to be completed. Due to this, a project may be finalized but not closed.

**Comment by sebas932** [comment]
Done by @mralmanzar 

![image](https://user-images.githubusercontent.com/4406128/59792758-84137f80-929a-11e9-8350-ccabbc316f2c.png)
