### ISSUE TITLE
Create a master table with CIAT deliverables and a report

### ISSUE THREAD

**Issue by mralmanzar** [CCAFS/MARLO#1838]
CIAT already mapped MARLO project to the Programs/CIAT Region, we should create a list of deliverables produced by those Programs.

**Comment by sebas932** [comment]
A report was created with the information of deliverables mapped to CIAT Programs

![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/23597a59-4dcb-40cb-aa78-28a2a90eca80)

**Comment by htobon** [comment]
Hi @sebas932, please determine an estimate.
