### ISSUE TITLE
Verify and remove from interface and validations unused fields from MARLO

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1839]
Requested from the F2F Meeting

- [x] Project description
- [x] Partners
- [x] Contribution to Flagship Outcomes
- [x] Policies
- [x] Deliverables
- [x] Innovations 
- [x] Budget

**Comment by anamp07** [comment]
List of fields with current status: 
![image.png](https://images.zenhubusercontent.com/5b81b883dc633f0891418b32/009debd2-3931-4df0-9a23-304e29db25ec)
