### ISSUE TITLE
Adjust Outcome Impact Case Reports section in the CGIAR Results Dashboard

### ISSUE THREAD

**Issue by MargaritaRamirez** [CCAFS/MARLO#1840]
Adjust OICR interface and graph filters to include 2018 data. 

Tasks:
- [x] Interface. 
- [x] Add new graphs. 
- [x] Modify and add new chart filters. 

**Deliverable:** Section in testing environment. 
**Move to Review when:** Not applicable. 
**Move to Closed when:** Section is released in testing environment.

**Comment by sebas932** [comment]
@anamp07 we need to re-define the scope just for OICRs, Innovations and Policies

**Comment by anamp07** [comment]
Done. The section is ready in the testing environment. 
Tania will work in minor style adjustments for some charts. 

![image.png](https://images.zenhubusercontent.com/5b81b883dc633f0891418b32/9391f862-f544-4512-9576-a989c9909659)
![image.png](https://images.zenhubusercontent.com/5b81b883dc633f0891418b32/6c84b0e9-4626-482c-a0d4-6b8cadee9f07)
