### ISSUE TITLE
Adjust Funding Sources table interface adding a filter by institution

### ISSUE THREAD

**Issue by MargaritaRamirez** [CCAFS/MARLO#1841]
Filter by Institution
![image](https://user-images.githubusercontent.com/4406128/59925036-cb198600-93fc-11e9-8bb3-ab1f3d239d68.png)

Filtered by default for contact points
![image](https://user-images.githubusercontent.com/4406128/59925072-e1274680-93fc-11e9-9ccf-84e1a7ce4811.png)

- [x] Create filter button. 
- [x] Filter table. 
- [x] Adjust interface to display selected filter. 

**Deliverable:** Filter released in testing environment. 
**Move to Review when:** Ready for testing by Hector. 
**Move to Closed when:** Tested and approved.

**Comment by htobon** [comment]
Hello @anamp07, not sure why this issue is in the review process.
I am moving it back to "New".
Cheers,
Hector.

**Comment by anamp07** [comment]
Hello @htobon, the filter is ready for testing in MARLOdev. 
Can you please check it and tell us if there are any changes needed? 
Thanks,
Ana. 
![image.png](https://images.zenhubusercontent.com/5b81b883dc633f0891418b32/5167a2e3-cb3e-4e1f-b497-b8e5eabfb6d5)

**Comment by htobon** [comment]
Thank you @anamp07.
The filter is working fine. However, I do have a couple of comments with regards to usability.

- [ ] Can you please increase the width of the vertical progress bar? It was difficult from my side to move down-up with the wheel of the mouse. For some reason, each move takes 3 or 5 institutions at the time.

![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/2f62ef4d-7773-4c94-bcf6-552540a89cb0)

- [ ] If there is a filter, can you please make it available in the interface? I may happen that the user selects an institution and forget he/she did it. As a result, it will be confusing that not all funding sources are loaded in the table.
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/6d8de6bf-eb8b-48f9-868b-7573e068a10f)

**Comment by htobon** [comment]
Thank you @anamp07.
Closing this.

**Comment by htobon** [comment]
- [ ] Check the list of funding sources when a Contact Person is loggin in.
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/826b50d6-5e9f-4161-8943-6da4046fc9b7)
