### ISSUE TITLE
[SA][MARLO] Add popup to create funding source with some basic information and validations

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1844]
*Deliverable:*
*Move to Review when:* Hector need to test
*Move to Closed when:* Released in MARLO Dev

![image](https://user-images.githubusercontent.com/4406128/59925594-08cade80-93fe-11e9-8f4c-9272294d9313.png)

![image](https://user-images.githubusercontent.com/4406128/59925610-14b6a080-93fe-11e9-8df5-1e1ba93c7b9b.png)

**Comment by sebas932** [comment]
The interface is almost ready


![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/4847e8e7-e239-4c3e-8514-1a94c4345bb2)

![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/34b9a9c1-14ec-4c57-809b-dc6e5511d7ee)

**Comment by htobon** [comment]
- [ ] Null pointer when trying to add a FS from 2014 extended to 2016 (A174), synchronize it and then hitting the save button.
- [ ] If a contact point is logged, the center and the managing partner must be automatically selected.
- [ ] Detect duplicates taking into consideration the finance code *and the managing partner*
- [ ] Status canceled requires also a Finance code

Not for this sprint - @sebas932, please move these issues below for the next sprint:
- [ ] Synchronize with CIAT before or during the creation of the funding source.
- [ ] Look in the already mapped institutions (between Agresso and MARLO) and autoselect the drop-down (use probabilities for this).
