### ISSUE TITLE
[SA][MARLO] Add managing partner lead in Funding Source section and indicate which other CRPs are using the same finance code 

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1845]
*Deliverable:*
*Move to Review when:* Hector need to test
*Move to Closed when:* Released in MARLO Dev

![image](https://user-images.githubusercontent.com/4406128/59925827-8abb0780-93fe-11e9-8117-2b039a9e8171.png)

![image](https://user-images.githubusercontent.com/4406128/59926118-36645780-93ff-11e9-9b40-96a6c5d4504d.png)

**Comment by sebas932** [comment]
![image](https://user-images.githubusercontent.com/4406128/61958076-40d9ba00-af86-11e9-8a6c-6649c90f2738.png)


![image](https://user-images.githubusercontent.com/4406128/61958301-acbc2280-af86-11e9-9a4f-57d67fe2449b.png)

**Comment by sebas932** [comment]
I'm waiting to deploy this feature in MARLO-Dev, but there is an error that needs to be solved in the `dev` branch. @kenjitm and @HermesJim can you look at this?

![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/ffe04bbc-b0ed-4073-aa3e-c26a098a26f9)

**Comment by htobon** [comment]
- [ ] Columbia is not displaying:
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/7891e203-fad6-4323-8fa0-90da3cb78e2e)

- [ ]
