### ISSUE TITLE
[SA][MARLO] Adjust and create tables for funding source mapping and remove feature

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1846]
- [x] Adjust table of funding source CRP mapping
- [x] Create a new one with mapping coming from others CRPs
- [x] Create remove button (Only for own CRP mappings)

*Deliverable:*
*Move to Review when:* Hector need to test
*Move to Closed when:* Released in MARLO Dev

![image](https://user-images.githubusercontent.com/4406128/59926239-8511f180-93ff-11e9-93d7-575d0e3bde4d.png)

![image](https://user-images.githubusercontent.com/4406128/59926516-13867300-9400-11e9-85b2-ced439ab4baf.png)

**Comment by htobon** [comment]
- [ ] Un-map funding sources if the project is editable (submitted projects cannot be un-mapped)
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/973e2e01-dc87-49dc-8351-0d7b12bfa415)

- [ ] Please add a confirmation message.

- [ ] Table of mapped funding sources in other CRPs is not showing:
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/4c8545fd-94df-47aa-87d7-ce8d1dcb6d50)
