### ISSUE TITLE
[SA][MARLO] Add feature to map projects from funding source section

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1847]
*Deliverable:*
*Move to Review when:* Hector need to test
*Move to Closed when:* Released in MARLO Dev

![image](https://user-images.githubusercontent.com/4406128/59926628-52b4c400-9400-11e9-811a-716c4ac38dd8.png)

![image](https://user-images.githubusercontent.com/4406128/59926707-81cb3580-9400-11e9-85fa-98d71cc9af7b.png)

![image](https://user-images.githubusercontent.com/4406128/59926720-8859ad00-9400-11e9-88e9-b76c83960902.png)

![image](https://user-images.githubusercontent.com/4406128/59926745-914a7e80-9400-11e9-92ac-a3f95d8fa70a.png)

**Comment by sebas932** [comment]
- [ ] @kenjitm please validate the list of projects, project budgets already mapped to an institution, shouldn't appear in the list

![NQ2n0JX[1].png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/fcf6c2aa-979a-4757-93e5-9f3be5e84975)

**Comment by htobon** [comment]
- [ ] Please display only active projects:
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/66fd39cc-7c22-4c78-8ab1-10ec5c64ec18)

- [ ] Submitted projects cannot be mapped:
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/9d4b8cc0-5ac2-4117-97a7-f94dbb4d9256)

- [ ] Remaining budget not updated automatically
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/4f17e2fb-3072-4c93-b8dd-b06604c853d2)

- [ ]
