### ISSUE TITLE
[MARLO] Update email service to send secured messages through Secure SMT

### ISSUE THREAD

**Issue by mralmanzar** [CCAFS/MARLO#1849]
Now MARLO is sending its emails through CIAT SMTP because AWS blocks the SMTP default port (25). 
The idea is that those mails should be send by symantec server (Production SMTP) using the secure SMTP ports (587/465).
In order to accomplish this, should updated the Mail sender module on MARLO in order to change the way to send messages to secure SMTP. 
Additionally, this MARLO module must be capable to try to send the messagess  through server and if this server never respond, must change the server to use the CIAT server.

**Comment by yeyo2k3** [comment]
Santiago is working with AWS to enable SMTP secure port for testing SMTP exchange

**Comment by htobon** [comment]
@yeyo2k3 Can you please let us know the status of this issue?
Cheers,
Hector

**Comment by yeyo2k3** [comment]
I sent a Email to santiago, I remind him about request sent to AWS to open restriction on port 25 and opening secure port 587. 

we are waiting for an answer.

**Comment by yeyo2k3** [comment]
Santiago answered about open port 25 on AWS, now we can send emails through symantec again, 
I Update MARLO prod configuration and set Main SMTP to symantec and Backup SMTP to CIAT
After that we were testing and it's working
