### ISSUE TITLE
[MA] Define the evaluation Criteria for Business Intelligence Solution

### ISSUE THREAD

**Issue by mralmanzar** [CCAFS/MARLO#1850]
Should be defined which evaluation criteria will be taken into account to perform the analysis of the BI tools in order to do an issue statement to evaluate different BI tools 

**Deliverable:**  An initial Document with each Criteria 
**Move to Review when:** never
**Move to Closed when:** Hector approves the list

**Comment by sebas932** [comment]
Related with #1848

**Comment by sebas932** [comment]
@MateoVieira will help @mralmanzar to move forward this issue

**Comment by MateoVieira** [comment]
@mralmanzar has a draft document with the criteria that should be checked at the time of choosing a BI tool

**Comment by mralmanzar** [comment]
Due to the easy way to create the graphs, Datastudio will be the BI tool to create the Dashboards.
