### ISSUE TITLE
BI: Create the OICR cube

### ISSUE THREAD

**Issue by mralmanzar** [CCAFS/MARLO#1852]
- [x] Evaluate the 2017 data and made a proposal of how to handle the 2 years on Dashboard
- [x] Create the model of the OICR cube
- [x] Create and validate the queries
- [x] Create the ETL process
- [x] Update cube document

**Comment by mralmanzar** [comment]
In order to save all 2017 data was created a copy of stage tables.
For all the data created in the local database in AR2017 they updated the ID to not be confused with a new OICR id's of 2018.
![image](https://user-images.githubusercontent.com/9383649/61488077-f5fbe900-a96c-11e9-919c-7bf8beb6475b.png)

**Comment by mralmanzar** [comment]
Was updated all queries of dimensions, bridge and fact tables.
![image](https://user-images.githubusercontent.com/9383649/61488300-7b7f9900-a96d-11e9-99d9-4cfae5182b0e.png)
Additionally, was created all scripts to include new fields and tables(new tag dimension and new geographic scope bridge) .

i

**Comment by mralmanzar** [comment]
Was updated the ETL process.
![image](https://user-images.githubusercontent.com/9383649/61489365-27c27f00-a970-11e9-86f4-db4cf4b15df9.png)
On the dimension process and pre_fact was mixed the 2017 and 2018 data
![image](https://user-images.githubusercontent.com/9383649/61489488-7112ce80-a970-11e9-80fd-2db699483317.png)

**Comment by htobon** [comment]
Hi @mralmanzar, 
Thanks for the work on this and for documenting the process. Very useful.
Can you please let me know if I need to review something here? Otherwise, please mark the issue as complete.

Cheers,
Hector.

**Comment by mralmanzar** [comment]
Finally was sent to Tania the mail inform her that Policies is done.
The document was saved on [this folder](https://cgiar.sharepoint.com/sites/cgiar-prog-performance/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2Fsites%2Fcgiar%2Dprog%2Dperformance%2FShared%20Documents%2F004%2DTechnical%2FCubes%20Documents%2F2018&FolderCTID=0x012000497E0800B77DD945B96843E06C3CBB94)
![image](https://user-images.githubusercontent.com/9383649/62051970-2b5cce00-b1da-11e9-8f5f-708f7dbbd2a6.png)
