### ISSUE TITLE
[SA][MARLO] Create a Satisfaction survey for MARLO users

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1860]
*Deliverable:*
*Move to Review when:* Hector need to review
*Move to Closed when:* Send it to MARLO Users/Family

![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/fe9c8f6f-bef1-4277-a9b8-b43ab2e8bc98)

**Comment by sebas932** [comment]
@htobon I just adjusted the planning 2018 survey for Reporting 2018
Here is the link: https://docs.google.com/document/d/15ijsIN8VpZncrytDafZfQ9H0j8x3CW90tAIkJExQm5w/edit?usp=sharing

Should we ask extra questions?
What is the next step to move forward on this process?

**Comment by sebas932** [comment]
@htobon here is the link of the survey that was created in SurveyMonkey [without paid features].
https://www.surveymonkey.com/r/97G23KR

Can you please check and let me know how we proceed?

**Comment by MateoVieira** [comment]
I made some comments on blue

**Comment by htobon** [comment]
Thank you Sebas and Mateo.

Here are some minor comments:
- [ ] Q1 -  Can we select more than 1 CRP?
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/49dc9cc4-d144-4ba8-be4c-d960428b0c58)

- [ ] Q1 - EiB is missing.

- [ ] Q5 - Can you please update the screenshot?

- [ ] CIMMYT - Average time in MARLO
Shaylyn would like to know the average time a user spent in MARLO. Is this something we can include as part of the survey if the user selects MAIZE, WHEAT and/or EiB? In addition, can you please export this information from our Google Anaytics?
This is the message she wrote to us:
>Is the MARLO team planning to send a satisfaction survey to all users this year, as was done last year? Management at CIMMYT is interested to know the average time that each user spent filling their project information for planning and reporting. Is this something we could ask, or even something that we may already have data on?

**Comment by sebas932** [comment]
Hi @htobon, the question about Average time was added in the section #2 of the survey.
Meanwhile, I have generated the following statistic from Google Analytics. let me know if is useful.

![image](https://user-images.githubusercontent.com/4406128/64292387-e8f08480-cf2f-11e9-9454-ec1a4f163b02.png)

**Comment by sebas932** [comment]
@htobon and @MateoVieira will write an email to Shaylyn

**Comment by MateoVieira** [comment]
- [] Section #2 - is there any possibility that if you chose a different CRP/Platform of MAIZE, WHEAT or EiB, the "Section#2" doesn't appear ? 

- [] Q7 -  include the measurement unit Ex: ( h-Hours, Min-Minuts) in the question 

![image.png](https://images.zenhubusercontent.com/5d449dbb3950cc7f5c1719e4/ea812cfd-8efd-4e82-be5a-fd6519382613)

**Comment by MateoVieira** [comment]
I made some changes on the survey in the Q? order and I added some Questions  that were on the survey's draft (https://docs.google.com/document/d/15ijsIN8VpZncrytDafZfQ9H0j8x3CW90tAIkJExQm5w/edit)

**Comment by sebas932** [comment]
@MateoVieira ask Shaylyn for feedback

**Comment by MateoVieira** [comment]
-Shaylyn: "last year we added some questions about support received from the MARLO focal point so it might be nice to add those- do you have the survey from last year? If not, maybe just something like a 1-5 scale, and “How would you rate the support that you received from your internal centre-based MARLO focal point?”

**Comment by MateoVieira** [comment]
update done on the survey so is ready to be sent to Maize and Wheat users only 
we have already greenlighted from Shyalyn

**Comment by MateoVieira** [comment]
MARLO is not going to do the survey to nither of the users, maybe just share the survey draft to Shyalyn so she could use it and analyze the results 
MARLO Team will do another survey to ask about AR and POWB after POW2020 had finished.
