### ISSUE TITLE
Create mockup for CGIAR Results Dashboard sections for 2017 and 2018 data

### ISSUE THREAD

**Issue by anamp07** [CCAFS/MARLO#1865]
- [x] Outcome Impact Case Reports 
- [x] Innovations 
- [x] Partnerships
- [x] Capacity Development
- [x] Publications
- [x] Policies
- [x] Altmetrics

**Comment by htobon** [comment]
Hi @anamp07, I think we can close this issue as we finalized the mockups and we are looking forward to hearing from the SMO if they are ok.

Any new activity related to this topic we can manage it in another issue.

Hope this is ok for you.
Cheers,
Hector.
