### ISSUE TITLE
Create new field for Lead Center in funding sources

### ISSUE THREAD

**Issue by kenjitm** [CCAFS/MARLO#1866]

**Comment by kenjitm** [comment]
The following points were developed: 
- Create a funding source service
- Filter funding sources by selected institutions
- Detect contact point session
- Create funding source from the pop-up window
- Assign institutions, finance code and Assignement value when funding source is created

**Comment by htobon** [comment]
Hi @kenjitm, I am not sure what needs to be reviewed here. Thus, I'm moving this issue as "New" again meanwhile you clarify.

**Comment by kenjitm** [comment]
![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/ed0792f6-67c6-48b7-b4f7-ae57207a0792)

The indicated field is added in Funding sources, allowing to select a lead institution among its partners managing 

![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/a181eeb2-f145-45d3-aee0-b0f55111de6b)

**Comment by htobon** [comment]
Hi @kenjitm, I am still lost on what I should test here. Or should this be tested by anyone else?
Moving back this issue to "New".
Cheers,
Hector.
