### ISSUE TITLE
[MARLO] Fix Java Exception related to MarloBaseEntity Class

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#1869]
When Restart MARLO application in every environment sometimes after Login throws a Java exception where the error befall in MarloBaseEntity Java class. 

![image.png](https://images.zenhubusercontent.com/5798ae8de40e5714b16c9812/c50daa58-95b7-4ffd-8110-bb4761c1b81f)

**Comment by HermesJim** [comment]
[Update] In this commit https://github.com/CCAFS/MARLO/commit/bc5687dd2a39a46c574f14c6afd4743a59174e2d I had changed the timeout variables of the database connection poll (Hikari) and the Hibernate Transaction object also I replaced the deprecated package of MySql Java connector and update the last Mysql connector driver in MARLO project.

The team will review and test if the exception will not throws again.

**Comment by sebas932** [comment]
@htobon remember to contact Grant in order to see how he can help us

**Comment by HermesJim** [comment]
[Update]
the last Friday (August 30th), I made changes in the use of the session variables into MARLO, specially in the User Token session.

**Comment by MateoVieira** [comment]
can you check Sebas checkboxes?
@HermesJim @htobon

**Comment by yeyo2k3** [comment]
@Luisfben could you try to resolve this issue please?

**Comment by Luisfben** [comment]
Last week a solution to the MarloBaseEntity error was applied (locally), it is in testing. The solution was based on the information presented in this link: https://hibernate.atlassian.net/browse/HHH-10172

**Comment by MargaritaRamirez** [comment]
We will move this issue for the next sprint

**Comment by MargaritaRamirez** [comment]
We did an external contract with Premize who managed to identify the problem and we in the testing period. 
@kenjitm could you please document the solution that they informed us?

**Comment by kenjitm** [comment]
The MarloBaseEntity problem is solved by removing the isCenterProject () method from the Projects class.

This method causes the issue since within the Project class there is an object called CenterProject, which caused that when performing the deployment of the application, if the isCenterProject () method was first to read, the system would search for an object and when not finding it the error was presented.
