### ISSUE TITLE
Confirmation when some component could not be deleted

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#187]
Display a warninf message when some block of information could not be deleted in the system.

**Comment by htobon** [comment]
-1
Nobody worked on this issue.

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-66319a2f6f5ca9e7c68bca25029ee62c5eb57de4b62375ff73ed96f44ec71cd0.png)
