### ISSUE TITLE
Update Innovation Cube for 2018

### ISSUE THREAD

**Issue by mralmanzar** [CCAFS/MARLO#1872]
- [x] Create the model of the new innovation cube
- [x] Create and validate the innovation queries
- [x] Create/update the innovation ETL process
- [x] Send the information to Snowflake
- [x] Create innovation cube document

**Comment by mralmanzar** [comment]
Were included 2 new dimension for lead organization/entity and  top five contributing organizations/entities.
As OICR, was copied the 2017 information in order to merge it on Fact an dimension tables
![image](https://user-images.githubusercontent.com/9383649/61490117-d1eed680-a971-11e9-9935-5f46c881db80.png)

**Comment by htobon** [comment]
Hi @mralmanzar,
Can you please clarify why this issue is in the reviewing process? I just noted that not all checkboxes above are ticked. As a result, I infer this is not finalized yet.
I am moving this issue as "New" meanwhile you clarify.

Cheers,
Hector.

**Comment by mralmanzar** [comment]
Finally, Tania was sent the email informing her that the innovation cube is finished.
The document was saved on [this folder](https://cgiar.sharepoint.com/sites/cgiar-prog-performance/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2Fsites%2Fcgiar%2Dprog%2Dperformance%2FShared%20Documents%2F004%2DTechnical%2FCubes%20Documents%2F2018&FolderCTID=0x012000497E0800B77DD945B96843E06C3CBB94)
![image](https://user-images.githubusercontent.com/9383649/62051992-3ca5da80-b1da-11e9-8a79-95618de8e98e.png)
