### ISSUE TITLE
[CLARISA] Publication importing process

### ISSUE THREAD

**Issue by mralmanzar** [CCAFS/MARLO#1875]
Create a process that allows import the reported information about Publications in the deliverables tables.
- [x] Create an excel template to include publication reported
- [x] Create the import process that should create a new Peer review paper Deliverable, Annualize it and fill the fields
- [x] Testing

**Comment by htobon** [comment]
Hello @mralmanzar, can you please share the excel template?
I think we can advance with the CRPs so they start filling it. Do you agree?

Cheers,
Hector

**Comment by mralmanzar** [comment]
Totally agree.
Please ckeck the template [HERE](https://cgiar.sharepoint.com/:x:/s/CCAFS-KDS/Eai-QP6OiD1Ni4y8JTc6GnAB71tkYQ_m-Naty1Nhzd2iEw?e=U9hIHv)

**Comment by yeyo2k3** [comment]
Probably we need include publication Anual Report year on the service. To be reusable by others services in the future, Cause this, is better add to excel template this field.

**Comment by yeyo2k3** [comment]
I change over services creating a JSON structure, To follow structure, it is in clarisa and It have a example to complete Incluiding phase.
There are changes that hermes are working on  to anualize a deliverable, when these are completed , I'll anualize this task.

**Comment by htobon** [comment]
In conversation with @yeyo2k3, I am moving this issue to "In-progress".

**Comment by yeyo2k3** [comment]
I modify deliverable_info logic to include replication phase when a deliverable is not a publication.
now can create a deliverable by clarisa with phase and replication. 

@mralmanzar, @sebas932 or @HermesJim  test it please.

**Comment by mralmanzar** [comment]
Was tested using the SMO consolidated excel and works well. On regards of authors, should change the way to received. Now should receive all authors in a single field and save it on a metadata field.

**Comment by yeyo2k3** [comment]
I made a change that clarisa be able to include in a single field an authors list or a composite object  list with first name and last name.
![image](https://user-images.githubusercontent.com/51238402/64204000-6d70d380-ce5a-11e9-86ef-32c5ff055fda.png)
both works well but Object Authors List are saved in Deliverables Authors and Authors field be saved as Metadata Element.

@mralmanzar did check and tested, Its works 
@htobon If you want to know how it works, tell me.

**Comment by mralmanzar** [comment]
![image](https://user-images.githubusercontent.com/9383649/64285171-d6228380-cf20-11e9-8724-355cf00f9632.png)
![image](https://user-images.githubusercontent.com/9383649/64285217-f0f4f800-cf20-11e9-98ce-f847262bcc37.png)
![image](https://user-images.githubusercontent.com/9383649/64285250-01a56e00-cf21-11e9-968c-8850cc77bb8e.png)
Test finished. This service works for the Peer reviewed papers import.
