### ISSUE TITLE
Create institutions filter and filter the list when Contact Point is logged in funding sources list

### ISSUE THREAD

**Issue by kenjitm** [CCAFS/MARLO#1877]
![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/583aaf68-757a-465f-ac02-9ae6f5bb0d80)

**Comment by htobon** [comment]
Hello @kenjitm, I am not sure why this issue is in reviewing process.
Please clarify.

**Comment by htobon** [comment]
Hi @kenjitm, can you please take a look at my latest message? I think you missed it.
Moving back this issue to "New".
Cheers,
Hector.

**Comment by kenjitm** [comment]
Hello @htobon.
The funding source filter by institutions was developed, please test its functionality.

When one or more institutions are selected in the filter, only the funding sources that have these associated institutions are shown.

![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/ee804fb7-0134-429b-8310-db8d83faea78)

The development is in dev, you can try it in the following link: http://marlodev.ciat.cgiar.org/fundingSources/CCAFS/fundingSourcesList.do?edit=true&phaseID=56

**Comment by htobon** [comment]
Hi @kenjitm. thanks for the further explanation. 
I have made a couple of suggestions to @anamp07 in the issue #1841. And those are mostly referred to the front-end side. Therefore, we can close this one.

Cheers,
Hector.
