### ISSUE TITLE
[DP] (CLARISA) Create the SDG (sustainable Development Goal) related services

### ISSUE THREAD

**Issue by mralmanzar** [CCAFS/MARLO#1883]
- [ ] Define which services should be created that relate the SDG
- [ ] Develop the services

**Comment by MateoVieira** [comment]
the deadline already passed, shall we close this Issue? @yeyo2k3

**Comment by htobon** [comment]
We decided not to work on this.

**Comment by yeyo2k3** [comment]
new application Submission Tools  will be use the services. fro this reason the services was implemented and added to CLARISA as part of Once CGIAR General control list in research strategy 2030 section.

![image.png](https://images.zenhubusercontent.com/5d3718852c1c7b71d87abdf1/138963c9-3056-4925-b149-534c27245036)
