### ISSUE TITLE
Add new field to project Innovation for Other innovation type

### ISSUE THREAD

**Issue by kenjitm** [CCAFS/MARLO#1888]
- [x] Migration
 - [x] Update model
 - [x] Autosave
 - [x] Frontend field creation
 - [x] Validator
 - [x] Javascript funcionality - show/hide field

**Comment by kenjitm** [comment]
When the "Other" option is selected in innovation type, the indicated field is displayed.

![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/f441303a-bcc3-4de1-9109-f16f4bfcf4bf)

**Comment by htobon** [comment]
Hello @kenjitm, not sure what to do here.
I am moving back the issue to "New".
Cheers,
Hector.

**Comment by kenjitm** [comment]
hi @htobon .
The operation of the new field has already been tested.

A new field was added to Innovations, which is visible and mandatory only when "Other" is selected in "Innovation type".

![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/1d1a81b4-f6cb-4d1a-b382-7eafc8d895f2)

As indicated above, it is implemented for the field: validators, migrations, autosave, innovation model update, etc.

Development is in production.
