### ISSUE TITLE
Create CGIAR Results Dashboard Testing Environment

### ISSUE THREAD

**Issue by anamp07** [CCAFS/MARLO#1890]
- [x] Create dev branch in the repository. 
- [x] Create dev in Copernico.
- [x] Adjust Dashboard configuration.

**Comment by sebas932** [comment]
Added Testing environment in COPERNICO

![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/edee70f9-5a84-4e15-82bf-20fbba22549d)

**Comment by htobon** [comment]
@sebas932 @anamp07 Can you please inform the technical team about this testing environment?
Thank you.
