### ISSUE TITLE
[KT][MARLO]Remove 'Liaison User' and 'Gender Analysis' fields in MARLO

### ISSUE THREAD

**Issue by kenjitm** [CCAFS/MARLO#1895]
Delete all relationships of those 2 fields 

Delete unused fields in:
- [x] Objects models
- [x] Managers
- [x] Others actions
- [x] Fields references
- [x] HBM - Hibernate Mapping

*Deliverable:*
*Move to Review when:* all relationships of those 2 fields are deleted 

*Move to Closed when:* All the check marks are marked and be reviewed by @...? 

The actual detail status of the deleted fields can be tracked in:
https://docs.google.com/spreadsheets/d/1aKLtysTrroFJI7vcukMw5GvnDSIoM7VgdJCxk6O9WXM/edit#gid=0

**Comment by kenjitm** [comment]
Requested from the F2F Meeting

**Comment by kenjitm** [comment]
The actual status of this issue can be tracker in:
https://docs.google.com/spreadsheets/d/1aKLtysTrroFJI7vcukMw5GvnDSIoM7VgdJCxk6O9WXM/edit#gid=0

**Comment by MargaritaRamirez** [comment]
See the blog 
https://marlo-news.blogspot.com/2020/01/deleted-fields-in-marlo-project-menu.html
