### ISSUE TITLE
[Project Page] - Create a Project Information JSON Mockup 

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#1896]

**Comment by MargaritaRamirez** [comment]
Create the project description scope Json (Id, title, responsible, etc.)

**Comment by htobon** [comment]
Hello @HermesJim, thanks for developing this.
I am not sure who should test this so I took a look in detail at the last image and had a couple of comments on how we can improve (please refer to the image below). Can you please respond to each of them (with the number for each question)?

Thank you in advance,

Hector

![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/682b0ad7-6df8-4dcf-b189-4c42e0ff6684)

**Comment by HermesJim** [comment]
Hello @htobon 

I think the project pages workflow is assigned to margarita, the team in charge of the CCAFS web-page and you.

I am making a bit technical deliverable; a basic scheme and the most important functional that is the goal of this issue.

You see many confusing things in the JSON structure, because maybe you are not informed how is the technically  a JSON  structure is composed for easy way for a developer.

In addition, I have only had two meetings with Margarita where you have not been able to be involved in cause for your full time.

I think this issue is under review or we can close it and we open more issues if is necessary to be able to fulfill the scope of the Project page, one of those tasks in which you can be involve, such as adding detail or a true technical scope (JSON structure) to achieve the objective.

I would like to know what @MargaritaRamirez thinks about this Issue.

**Comment by MargaritaRamirez** [comment]
@HermesJim @htobon 

I received the information of the JSON developed by Hermes last week for the first to slides of the approved mock-up. 
When we consult to @htobon  he told us that we need to talk first with Marissa to know how to approach the Macaroni Brothers. 
This is for us to start the communication process and to let them know what the process will be.

**Comment by MargaritaRamirez** [comment]
@htobon 
Taking into account that the issue was made only for create a JSON structure for project description scope we will close it. We will discuss in the next sprint meeting what is our next step.
