### ISSUE TITLE
[KT][MARLO] Remove fields in MARLO

### ISSUE THREAD

**Issue by kenjitm** [CCAFS/MARLO#1897]
- [x] Creation of a report in MARLO with the information of the eliminated fields in all phases and for all CRPs
- [x] Remove fields in MARLO
- [ ]  Blog it (MV)

*Deliverable:*
**Move to Review when:** 
- [x] When this branch is in production 

**Move to Closed when:** The exported information be reviewed by @...?  

MARLO Family definition (DO NOT EDIT):
https://docs.google.com/spreadsheets/d/1GITAapJHd3OQVxFFruXEQeKQ2NDI9cdrWvPuobkR_lY/edit

The actual detail status of this issue can be tracked in:
https://docs.google.com/spreadsheets/d/1aKLtysTrroFJI7vcukMw5GvnDSIoM7VgdJCxk6O9WXM/edit#gid=0

Delete Fields Reports
https://cgiar.sharepoint.com/:f:/s/CCAFS-KDS/Eq7BpvQfIGRGujk-LKLhj2sB6c1AnOQxSzsiLGSzd9tJmg?e=G7KB21

**Comment by kenjitm** [comment]
https://docs.google.com/spreadsheets/d/1aKLtysTrroFJI7vcukMw5GvnDSIoM7VgdJCxk6O9WXM/edit#gid=2114541516

**Comment by sebas932** [comment]
@kenjitm remember to meet with @htobon in order to talk about the specificities

**Comment by MateoVieira** [comment]
@htobon can you please validate in Dev the adjustments?
