### ISSUE TITLE
Format Test davinci.ubuntu

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#19]
Datos de acceso:
IP: 172.22.52.69
User: davinciubuntu
Password: d@v1nc1ubuntu

**Comment by htobon** [comment]
I just sent an email to the CIAT-Network team asking to format the server.

**Comment by htobon** [comment]
I talked today with Fabian Barco but he just responded that he needs to talk with Dolly Gomez.

**Comment by htobon** [comment]
I talked with Alexander Zurita from CIAT-IT. He already made the formatting process.
It is still pending for Fabian Barco to setup the admin user.

**Comment by htobon** [comment]
Done.
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-e050d5a21563502c138f18e35488d09e2d70a34d13947427f3decc1cdd337846.png)
