### ISSUE TITLE
Linking MARLO projects

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1903]
Reported by Lini - CCAFS Flagship 3:

1.	Where should PLs report outputs and outcomes-under the old project or new one?  The projects intersect and build on each other. Also, many outputs have already been entered and it would be wasteful for people to have to reenter them.
2.	How could we view a comprehensive list of all outputs and outcomes from linked projects to see progress? This is necessary to understand progress on outcomes. Ideally we should be able to view all sections in tandem like this.
3.	In reviewing details of projects, like partners or budgets, in any transition year it is easy to be confused as to which project is relevant as some extended their deadlines and so they overlap. 
4.	Would be good to show projects numbers together (hyphenated?) so people are aware there are related projects

**Comment by sebas932** [comment]
@htobon is this issue duplicate with #1886? or should we do something different here?

**Comment by htobon** [comment]
Yes. Please proceed to close one of them and merge the descriptions here.
