### ISSUE TITLE
[MARLO] Enable OICRs Full Section in UpKeep

### ISSUE THREAD

**Issue by yeyo2k3** [CCAFS/MARLO#1906]
Include OICRs in upkeep

**Comment by HermesJim** [comment]
[Update]
Change the duplication logic into OICS Database managers and it managers relations.
enable OICS in project menu when the phase is upkeep.

Project OICS section in Upkeep already to test in MARLO Dev.

**Comment by sebas932** [comment]
- [ ]  Set read mode for older OICR in POWB
- [ ]  Modify drop-down of years, in order to allow to select only years greater than the current

**Comment by htobon** [comment]
- [ ] Level of maturities drop-down are not loading:
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/fd6cf549-27e9-47f2-a8a8-02fa262adede)

**Comment by HermesJim** [comment]
@sebas932  and @htobon 
I think this 2 task are new features and don't belong to the issue scope (Show OICS in Upkeep).

I propose to move in review  again this issue, if OICS works fine in Upkeep Close it.

**Comment by htobon** [comment]
Hi @HermesJim, ok.

Can you please create a new issue informing about the issue of the previous reported OICRs?
Once you do that, please paste the issue URL here and close this.

Do you agree?

**Comment by HermesJim** [comment]
Hi @htobon I created the Issues #1953 and #1954
I proceed to close this issue.

thank you!
