### ISSUE TITLE
AWS: Select a consultant and create Scope of the project with the help of the consultant.

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1907]

**Comment by htobon** [comment]
Moving this for the next sprint. 
CIAT IT unit informed us they are improving the AWS Architecture so we can start with this consultancy. They expect to have everything done before September 30th, 2019.

**Comment by htobon** [comment]
Still Pending:
- [ ] Respond the CIAT-IT requirements in terms of re-organizing the cloud components.

**Comment by htobon** [comment]
We decided not to hire a consultancy due to the CIAT IT team is currently making important improvements in the governance and features of the current AWS account that MARLO is using. As a result, we will close this issue.
