### ISSUE TITLE
[CGIAR Dashboard] Develop a script widget to embed the results dashboard in external websites

### ISSUE THREAD

**Issue by anamp07** [CCAFS/MARLO#1911]
Issue description
- [x] Remove header and unneeded code
- [x] Adjust menu. 

*Deliverable:*
*Move to Review when:* Ana validate the widget by herself 
*Move to Closed when:* Ana approves it

**Comment by sebas932** [comment]
@anamp07 the widget is ready to be tested, here the documentation
https://github.com/CCAFS/CGIAR-Dashboard/wiki/Embed-CGIAR-Results-Dashboard

**Comment by anamp07** [comment]
Hi Sebas, 

I tested the widget. It's working fine when it's embedded without the navbar. 

When the dashboard is embedded with the navbar, the header is visible in all sections except for home and it should be hidden. 
![image.png](https://images.zenhubusercontent.com/5b81b883dc633f0891418b32/2c2c43f6-378d-4b67-9189-edf864491be8)

Can you please fix it? 

Thanks, 
Ana

**Comment by sebas932** [comment]
Thank you @anamp07, the issue you reported above was fixed and released in the testing environment.
I communicated this feature to Tania and the CGIAR Comms person.
I will close this issue.
