### ISSUE TITLE
Action Points - MARLO Family meeting (August 8th, 2019)

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1917]
- [x] HT-DA-TS: *Budget 2020-20201*: MARLO Team will liaise with each of you separately.
- [x] HT-DA-TS: *Deliverable improvements*: Follow-up with Jules about the changes in templates (which were promised for end of July) (DA, TS).  If these changes are again very heavy bring this back to the CRP leaders who could then make some necessary comments to SMO, i.e. implications on submission timeline as well as reality check on online submission.  
- [x] 3 HT: *Closing projects*: Hold a virtual meeting with a smaller group in the week of 19.8.  Volunteers for the sub-group: PIM: Pascale (virtually as on leave), WLE: Emma, MAIZE/WHEAT/EiB: Shaylyn, LS: Helen - still on leave? Caroline available from Thurs.-Fri. next week. 
- [x] 4 HT: *Summary report by Countries*: (Hector) to share the template in a google doc and then get feedback e.g. on mock-ups as the team further develops this.

**Comment by MateoVieira** [comment]
we created tow new issues for each action described (3 & 4) in order to close this Issue:
for task 3 - Issue  #1988 
for task 4 - Issue #1989
