### ISSUE TITLE
QS1: Compare critical results with GlowRoot metrics

### ISSUE THREAD

**Issue by danipilze** [CCAFS/MARLO#1921]
- [x] compare critical behavior from MARLO QS1 Test 20190726 with GlowRoot Metrics 
- [x] Detect causes of this behavior, 
- [x] Document causes such database queries that are delaying performance, an other possible drivers of the problem

**Comment by sebas932** [comment]
This was done by @danipilze

**Comment by danipilze** [comment]
documented in https://docs.google.com/document/d/131QZmm4ludcha40dH8kdMHPQouFb8iWk-ObS1DRw9LA/edit#
