### ISSUE TITLE
[QS1] Implement the CDN in AWS S3 with IT

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1923]

**Comment by danipilze** [comment]
- [x] create AWS user, permisions and credentials for bucket
- [x] test user permisions
- [x] generate script for sincronizing data in S3
- [x] fedd S3 data with Github uploads

documentation
https://docs.google.com/document/d/1AS3jZ2XR7UkUsCayoAZV4tvjyEm5aAKgSKiLNF69OTM/edit?usp=sharing
