### ISSUE TITLE
Update CGSpace Training Manual

### ISSUE THREAD

**Issue by MargaritaRamirez** [CCAFS/MARLO#1925]
- [x] Taking in to account the PDF training manual that we have start a new version more visual
- [x] Start a step-by-step manual 
- [x] Send the manual to CGSpace support for their feedback
- [x] Send the manual to some people in the COMMS team for the usability and narratives 
- [x] Review the manual with Marissa for her feedback
- [x] Send the final version to all the community

**Comment by MargaritaRamirez** [comment]
We are waiting for Marissa's comments about the narratives and presentation

**Comment by MargaritaRamirez** [comment]
Until this date we do not have any feedback from Marissa or comms team about the final version of CGSpace training manual.

**Comment by MateoVieira** [comment]
we are waiting for the Email answer sent today
subject: Global comms team on leave next week Aug 26-30

**Comment by MargaritaRamirez** [comment]
We sent the email to the CCAFS comms team on September 27 and you can see the final version in this link: https://www.canva.com/design/DADehg7amvI/share/preview?token=GDqHYzO1IblQGjN7ZmKuRg&role=EDITOR&utm_content=DADehg7amvI&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton
