### ISSUE TITLE
[Importing Process] - Quality Ansure for CCAFS publications 

### ISSUE THREAD

**Issue by MargaritaRamirez** [CCAFS/MARLO#1926]
- [x] Get the list of deliverables IDs with missing or wrong information by MA
- [x] Update the deliverable information in MARLO
- [x] Validate again if the information by MA

**Comment by MargaritaRamirez** [comment]
We are waiting for @mralmanzar to validate if all the information it's Ok

**Comment by htobon** [comment]
@mralmanzar, can you please let us know where we are here?
Thank you

**Comment by mralmanzar** [comment]
I was validated again the list an just continue inconsistencies on the fields already discuses (Volume, issue and pages)
The new file generated is [here](https://cgiar.sharepoint.com/:x:/r/sites/CCAFS-KDS/_layouts/15/Doc.aspx?sourcedoc=%7BEF075E33-F4B7-46DE-8168-15BEC7EBD034%7D&file=CCAFS_publications_29082019_MA.xlsx&action=default&mobileredirect=true)

**Comment by mralmanzar** [comment]
After the last validation, all data is correct.
