### ISSUE TITLE
Submit impactpathway

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#193]

**Comment by cgarcia9106** [comment]
is missing email , and attach format

**Comment by htobon** [comment]
May you please create a draft of the email and send it to me? 
The idea is that you develop the functionality of sending this email so the only missing part would be to have a good message.

**Comment by htobon** [comment]
Perhaps I suggest you to put some rough message there and then please show me how the message is being sent, and who will receive the email? Once that is ready, I can help you improving the message. How does it sound to you @cgarcia9106?

**Comment by cgarcia9106** [comment]
ok

**Comment by htobon** [comment]
Please refer to the comments on the image below:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-ff6da24b396038e66de70af6e34ae9373663aebfa29fdc6035c0c7048ed4f6eb.png)

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-86f1b610c2e272838230c1df7e1dd84f0f50a0aa69fb3b672a8f39d78526b8ed.png)

**Comment by htobon** [comment]
More coments:
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-c4aba88e0761c14c04d5864f1b48f5ddda699487ddd02cd72e1332a01958df81.png)
