### ISSUE TITLE
[MARLO] Grant access to Finance Manager Roles to modify Budget Expenditures

### ISSUE THREAD

**Issue by yeyo2k3** [CCAFS/MARLO#1933]
Modify Marlo structure to allow Finance Manager Roles to modify budget expenditure in budget by partner section

**Comment by yeyo2k3** [comment]
I add a new intercerptor to validate finance Manager Role when someone access to  budget by partner section, and  can modify budget expenditure @sebas932  can you test this feature please?

**Comment by sebas932** [comment]
Thank you @yeyo2k3, I will check
