### ISSUE TITLE
[DP] (CLARISA) Implement Get Publications

### ISSUE THREAD

**Issue by yeyo2k3** [CCAFS/MARLO#1934]
[x] Implement Service to get a publication by parameters
[ ] Testing Service

**Comment by yeyo2k3** [comment]
I create a service by parameters as (Phase and Global Unit) that return  a list of publications with same model that we used to create a publication. 

@mralmanzar can you test it plz

**Comment by htobon** [comment]
Hi @yeyo2k3, I think this one was already tested. Right? 
If so, please feel free to close this issue.

Thank you,
Hector.
