### ISSUE TITLE
[SA] Improve filters in the CGIAR Results Dashboard to allow global filtering 

### ISSUE THREAD

**Issue by anamp07** [CCAFS/MARLO#1936]
Improve Year and Program filter in order to filter all sections when a filter is applied in any section.

- [x] Adjust Year filter.
- [x] Adjust Program filter. 

**Deliverable:** Filters released in testing environment. 
**Move to Review when:** Filters are ready for testing by any of the team members. 
**Move to Closed when:** Testing is finished and no changes are needed.

**Comment by sebas932** [comment]
Done and tested 
![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/9f858d3a-fcef-4914-8c2e-3c023cd48233)
