### ISSUE TITLE
[DP] (CLARISA) Contact Patricia by mail to introduce Diego Perez On Clarisa Testing Enviroment

### ISSUE THREAD

**Issue by yeyo2k3** [CCAFS/MARLO#1939]
[x] Introduce Diego Perez To Patricia from MEL to intialize testing enviroment.
[x] Explain workplan with patricia to test Swaager documentation about rest Services. 

Deliverable Email with retrospective by Patricia
Move Review when Diego Sends an Email to patricia to inform about swagger doc.
Move Close when Patricia Sends retrospective

**Comment by htobon** [comment]
Closing this issue as I heard from @yeyo2k3 that this is already done.
