### ISSUE TITLE
[MA] Import 2018 publications list to MARLO 

### ISSUE THREAD

**Issue by mralmanzar** [CCAFS/MARLO#1943]
All CRPS needs help to import all detailed data of publications in MARLO. 
Using new publication services of CLARISA should be loaded.
- [x] Check the information of the publication Excel sended by Grecia
- [x] Create the publication template
- [x] (SA) Develop a bulk upload that sends all publications to CLARISA
- [x] Create duplicates flags on MARLO

**Deliverable:** informative Email to Tania and CRPs, when all the publications were imported to MARLO
**Move to Review when:** NONE
**Move to Closed when:** After send the Email.

**Comment by sebas932** [comment]
Developed the algorithm to upload a list of publications through CLARISA

![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/8d906593-e8a8-48ad-b40b-59203bb6681a)

**Comment by mralmanzar** [comment]
All publication data was imported successfully to MARLO.
Additionally was created a new table to handle the publication groups. This in order to handle the duplicated publications.
The Scripts, cube and documentation was updated and sent to Tania.
![image](https://user-images.githubusercontent.com/9383649/65880988-4eca0380-e358-11e9-8af8-3cb2bec3cc3c.png)
