### ISSUE TITLE
Adjust deliverables validations in order to keep the required fields as “Planning mode” in UpKeep

### ISSUE THREAD

**Issue by kenjitm** [CCAFS/MARLO#1945]
The adjust means that the  deliverables “Dissemination & metadata” tab will be optional.

Issue description

- [x] Backend adjustments
- [x] Frontend modifications to the mandatory indicators

**Deliverable:**
**Move to Review when:** The tasks are completed
**Move to Closed when:** The development is reviewed

**Comment by htobon** [comment]
@kenjitm please update this.

**Comment by kenjitm** [comment]
Deliverables validators are adjusted in order to keep the required fields as “Planning mode” in UpKeep.

All fields in Dissemination and Metadata tab become optional in this phase
![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/950213c8-30e4-458a-b92e-8043023459bb)

Development is in production.
