### ISSUE TITLE
[MARLO] Enable Project Innovations Section in UpKeep

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#1949]

**Comment by HermesJim** [comment]
[Update]
Change the duplication logic into Project Innovation Database managers and it managers relations.
enable Innovations in project menu when the phase is upkeep.

Project Innovations section in Upkeep already to test in MARLO Dev.

**Comment by sebas932** [comment]
- [ ] I got the following error saving in Innovations

![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/9022f0e8-8c62-4a7b-a172-e98400c1b08a)

**Comment by htobon** [comment]
Hi @sebas932, thanks for the feedback. I am going to move this issue to In-Progress until we hear back from @HermesJim that this was fixed.
Cheers,
Hector.

**Comment by HermesJim** [comment]
Hi @sebas932
plase remember to test it in your environment because a didn't find the exception  into MARLO dev logs.

**Comment by HermesJim** [comment]
Hi @sebas932 
I fixed this null pointer exception.
Please can you test again.!
Thanks.

**Comment by htobon** [comment]
Hi @HermesJim, I have checked again and everything seems to be stable and ready for production.

The only thing that is not working properly is the year. Please refer to the following image:
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/8cd5e013-4c62-41d5-a457-c0d360952f4c)

So I propose the following. Please release this development in production now as it is working as expected and meanwhile if you can please fix the issue with the year.

What do you think? If you agree please feel free to close this issue.

**Comment by HermesJim** [comment]
Hi @htobon 
I see in the database and the previous page (Innovations List) and the year appears, maybe is a little bug in the front end, I will create a ticket with this detail and I will check it and try to fix.

![image](https://user-images.githubusercontent.com/13221179/64344530-43332900-cfb4-11e9-9fc2-c854c6f40519.png)


Thank you for your feedback.

**Comment by HermesJim** [comment]
I created the thicket #1287.
I deployed the project innovation to production.

Issue close.

Thanks @htobon and @sebas932
