### ISSUE TITLE
[HJ] Create Gender platform in MARLO

### ISSUE THREAD

**Issue by mralmanzar** [CCAFS/MARLO#1952]
As of POWB2020 the gender platform must be included on MARLO

- [ ] Create Gender as platform as Global unit
- [ ] Configure all gender parameters to allow Login and the creation of information in MARLO

**Deliverable:** Send an email to Héctor to inform you that this platform is working in MARLO
**Move to Review when:**  Gender platform is configured in MARLO dev. Should test MARLO and CLARISA
**Move to Closed when:** The change in the production of MARLO is put

**Comment by MateoVieira** [comment]
@HermesJim Open POWB2020 is the second priority on this sprint 4.3.5., so if this is a need please prioritize this please, we should open POWB.20 by Oct 15.19

**Comment by htobon** [comment]
Thank you @MateoVieira.
I confirm this issue is a priority as we need to have the Gender platform displayed in the drop-downs when we open POWB 2020.

Please also note that the Gender Platform should not appear when we open AR 2019.

**Comment by MateoVieira** [comment]
@HermesJim will leave a doc. explaining how to implement this.
