### ISSUE TITLE
[DP]Modify drop-down of years, in order to allow to select only years greater than the current

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#1954]

**Comment by HermesJim** [comment]
[Update]
I take a advantage to implemented a quick code to did this issue.

**Comment by HermesJim** [comment]
@htobon 
Can you check this in MARLO dev.
thanks.

**Comment by yeyo2k3** [comment]
there are some use case when this funtionality should be keep it from backend, I was talking with team  and is better control this date by frontend, @anamp07 could you help us with this control?
