### ISSUE TITLE
[SA][MARLO] POWB 2020 - Impact Pathway - Map Primary and Secondary SubIDOs.

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#1957]
POWB 2020 Limitation on # of sub-IDOs mapped to. Change to 3 max (1x primary, 2x secondary)

Deliverable:
Move to Review when: Hector Review
Move to Closed when: MARLO Dev

**Comment by sebas932** [comment]
![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/41c4fec8-a27f-4873-987b-fc36288d3fba)

**Comment by MateoVieira** [comment]
-	There was added  the option to choose the “Primary” Sub-IDO per Flagship/Outcome (https://i.imgur.com/IFe63zi.gif)
-	Sub-IDOs per Outcome were limited to max of 3 (https://i.imgur.com/3GJvA96.gif)
