### ISSUE TITLE
[MR][KDS] Project Page - Adding on the JSON the Project Location and Project Clusters of Activity Information.

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#1958]
Add to the JSON project location y project activities (DP)

- [x] implement project location to the JSON
- [ ] implement project activities to the JSON

**Deliverable:**
**Move to Review when:**
**Move to Closed when:**

**Comment by MargaritaRamirez** [comment]
We will do this in the next sprint after we send the new service to the Macaroni Bros

**Comment by yeyo2k3** [comment]
I added project Location to JSON format there is an example 
![image](https://user-images.githubusercontent.com/51238402/83809049-6a21a700-a67b-11ea-8660-75f1d2019788.png)

**Comment by MargaritaRamirez** [comment]
we will close this issue and create a new one taking into account that we need to include all the information now according to the static JSON
