### ISSUE TITLE
[DP] (MARLO CENTER) Project Center List improvements

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#1960]
Improve the filtering of CIAT Projects as we are still displaying project that do not belong to CIAT

- [x] Merge Project Centers List
- [x] Differentiate Centers and CRP/PTF projects
- [x] Add Column CIAT Partner Persons added on partners section.

Deliverable: Action Project List Fixed
Move to Review when: MARLO show CIAT projects and any project that CIAT is partner 
Move to Closed when: This Task is tested by MARLO Team

**Comment by MateoVieira** [comment]
@yeyo2k3 Diego can you describe more this issue, showing how is now, and explain the improvements

**Comment by yeyo2k3** [comment]
Done

**Comment by yeyo2k3** [comment]
I develop changes to include Center Staff List

![image](https://user-images.githubusercontent.com/51238402/69987320-3f5c6780-150d-11ea-92cb-329dcbfeb856.png)

**Comment by yeyo2k3** [comment]
Continuing with develop I create a new feature to diferentiate a center project with a shared project
![image](https://user-images.githubusercontent.com/51238402/69988038-cfe77780-150e-11ea-9f99-2a29f77569db.png)

**Comment by MargaritaRamirez** [comment]
@MargaritaRamirez please review

**Comment by htobon** [comment]
@yeyo2k3 if this is production, please close this issue.

**Comment by yeyo2k3** [comment]
@htobon  this issue is not in production yet, we have to create a testing plan, after testing we could be move from dev to prod.
