### ISSUE TITLE
[DP][MARLO CENTER] Fix the Project Focus Bug in Project Description.

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#1961]
Currently in CIAT MARLO, the shared projects does not show the correct CRP flagship that the Project is focused and shows the CIAT programs. (See Image)

![image.png](https://images.zenhubusercontent.com/5798ae8de40e5714b16c9812/7159dfa3-97b9-44da-97db-e009b85a0012)

Please fix this bug showing the correct CRP Flagships.
(see Image)

![image.png](https://images.zenhubusercontent.com/5798ae8de40e5714b16c9812/85a9551e-c9df-4aba-8736-8828ee27cf65)

**Comment by yeyo2k3** [comment]
I fixxed cause, it loading information about loged CRP in this case is a CENTER, and its no loading information about Share CRP info. 

![image](https://user-images.githubusercontent.com/51238402/69808629-fb3c3080-11b5-11ea-9538-00390d979804.png)

Additionally I added a funtionaly to restric to all user can modify info in a shared project except mapping centers programs and regions section to some roles.

**Comment by MargaritaRamirez** [comment]
@MargaritaRamirez please review

**Comment by htobon** [comment]
@MargaritaRamirez and @yeyo2k3 Should we close this?

**Comment by yeyo2k3** [comment]
@htobon this issue is in dev environment and has been not tested yet. we need time to create a test plan, after that we should be pass this develop to production.

**Comment by MargaritaRamirez** [comment]
We will close this issue according to @yeyo2k3 and @htobon  meeting last Friday 29/05/2020
