### ISSUE TITLE
[DP][MARLO CENTER] Improve the Project Presentation in MARLO CENTER.

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#1962]
In all share CRP projects in CIAT MARLO (CIAT CENTERS) :

- [x] All the sections in Read mode
- [x] In Project Budgets disable the link of the Funding Sources.

**Comment by yeyo2k3** [comment]
I develop restriction to enable read mode for shared projects and disable link to access funding source mapped to a partner

**Comment by MargaritaRamirez** [comment]
@MargaritaRamirez please review
