### ISSUE TITLE
[DP] (MARLO-CENTER)  Restrict access to projects at center section in MARLO

### ISSUE THREAD

**Issue by yeyo2k3** [CCAFS/MARLO#1965]
Restrict access to non-submited projects on landing page 
Update 2019-11

- [x] Show Upkeep information
- [x] Limit access to projects only if has been submited in last year AR phase.
- [x] Resctritc access only to center programs leader when an center admin has been mapped center programs and regions asociated to a Center for example CIAT
- [x] get access to project only to center programs leaders to map resource outcomes.
- [x] Show a new status with a validator function asociated to centers mapping

Deliverable: Restriction implemented on MARLO prod
Move to Review when Restriction is implemented on DEV
Close when Restriction is functional on PROD

**Comment by yeyo2k3** [comment]
we develop a restriction and update query executed to get all projects with project partners centers relationship by phase and summited status.

this is On dev enviroment to test if some one want to test, what about @sebas932 @htobon ?

thanks

**Comment by yeyo2k3** [comment]
I develop a restriction to allow a CRP admin can map programs and regions where CIAT center is collaborating

![image](https://user-images.githubusercontent.com/51238402/69988390-9400e200-150f-11ea-8fab-7e92bf6d5197.png)

when a non admin user logged, He can only  map outcomes where his area was mapped to project
![image](https://user-images.githubusercontent.com/51238402/69988654-0d98d000-1510-11ea-941e-29f3fa40ba1a.png)

**Comment by MargaritaRamirez** [comment]
@MargaritaRamirez please review
