### ISSUE TITLE
[KT][MARLO] Feedback of funding sources improvements

### ISSUE THREAD

**Issue by kenjitm** [CCAFS/MARLO#1966]
- [ ] Synchronize with CIAT before or during the creation of the funding source.
- [ ] Look in the already mapped institutions (between Agresso and MARLO) and autoselect the drop-down (use probabilities for this).
- [ ] Users should be able to change the funding type.
- [x] Validate the list of projects, project budgets already mapped to an institution, shouldn't appear in the list
![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/a133f3a3-de50-4704-9522-8883759a76b8)
</br>
- [x] Fix the check boxes marks for selected filters 
- [x] Check the names list of selected institutions
- [x] Take out CIAT or any other "Center entities" from the list of duplicated
![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/0d42f451-de3f-43a3-91cc-e3665941546d)
</br>
- [x] Validation for Rational field in Projects By Budget
![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/2049b56d-eeab-4522-8e07-39d3f3e90da9)
</br>
- [x] Remove Rational fields from last years in Project By Budget
![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/99dcea32-329b-47b5-a4e3-40263528de90)
</br>
- [ ] Table of mapped funding sources in other CRPs is not showing:
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/4c8545fd-94df-47aa-87d7-ce8d1dcb6d50)
</br>
- [ ] Un-map funding sources if the project is editable (submitted projects cannot be un-mapped)
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/973e2e01-dc87-49dc-8351-0d7b12bfa415)
</br>
**Deliverable:**
**Move to Review when:** Hector need to test
**Move to Closed when:** Released in MARLO Dev

**Comment by sebas932** [comment]
Hi Kenji,
Here there are other comments:

- [ ] Some Funding Sources have duplicated institutions.
![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/5f0caf30-3a0e-472b-8e5a-9cc1bf911eb9)


- [ ] When I filtered Bioversity in A4NH, some funding sources are appearing in both tabs (Ongoing, Archived), see __FS520 - W1/W2 to Bioversity for "Key leverage points"__
![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/1fa445d6-1159-479a-82f6-26836c7c180f)
![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/e745786c-dfc3-40c1-b89d-181aa74a1aa8)
