### ISSUE TITLE
[MA] BI tool Meeting

### ISSUE THREAD

**Issue by mralmanzar** [CCAFS/MARLO#1978]
Meeting with David, Manuel and team to talk about the proper BI tool for the SMO

- [ ] Check the cost of the premium licences of the top BI tools (Power BI, Tableau, Click View and Google)
- [ ] Evaluate the different alternatives to show quick wins. 
-

**Deliverable:** Meeting
**Move to Review when:** NONE
**Move to Closed when:** the meeting finishes

DASHBOARD (CCAFS)

**Comment by MateoVieira** [comment]
Related with Issue #1850 about criteria of a BI tool
