### ISSUE TITLE
[MA] Develop a Dashboard example with Qlickview

### ISSUE THREAD

**Issue by mralmanzar** [CCAFS/MARLO#1979]
Issue description

- [ ] Study about Qlickview
- [ ] Install locally
- [ ] Develop an example

**Deliverable:** An online Demo
**Move to Review when:**
**Move to Closed when:** The demo link be sent

**Comment by MateoVieira** [comment]
@htobon to be defined from you with @mralmanzar if move forthware with this.

**Comment by mralmanzar** [comment]
Not longer applicable.
