### ISSUE TITLE
[DP] A CRP Administrator should be able to decide the default landing phase for my users. 

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#1982]
Currently, CRP and PTF Administrators are able to open/close and display/hide phases in the system. However, they are not able to define the default landing phase to their users. As a result, this is something we are doing in our back-end.

The idea with this task would be for the development team to add the functionality for Administrator to define this landing phase. And here is the way how we propose to do it:

**Deliverable:** 
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/f617c720-8b57-46bd-a185-b10ce0f200c0)

**Move to Review when:** When the interface is fully functional in our testing environment (marlodev)
**Move to Closed when:** When the interface passed the test and is fully functional in our production environment.

**Comment by yeyo2k3** [comment]
we create a option to set a phase as default crp. When a user set check this radio button set the new phase as a new crp parameter to current phase, In next login get new changes on landing page for the new phase.
