### ISSUE TITLE
Think and develop an impact pathway graph for visualizing into Outcomes and CoAs

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#199]

**Comment by htobon** [comment]
This took more time to be developed than we expected.
This task is moved to the next sprint.

**Comment by carios1usb** [comment]
![Capture.jpg](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture-d5eb6590a096b68eaf727e9f0c2cf42d2355962f61e6a73e6545492e967feed6.jpg)

**Comment by carios1usb** [comment]
![Capture1.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture1-e3a72424c7f4a5d1ffd3bad6a6524349ee61a61b9055bb10e4f647c6ccc5a0f8.JPG)

**Comment by htobon** [comment]
:+1:

**Comment by htobon** [comment]
What happen with the discussion we had this morning related to this graph?

Pending action points:
- [ ] Include a download button (this can be done on this sprint).
- [ ] Improve the graph in a way the CoAs should have a lower level than the Outcomes. (This could be added as another issue and can be developed on the next sprint, therefore, please add the issue).
- [ ] Make relationships between CoAs and Outcomes (This can also be added as another issue and will be developed in a later stage when we develop the deliverables/outputs section, therefore, please add the issue).

**Comment by carios1usb** [comment]
![Capture.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture-a3d5b030de70e293c751afaaeef948d91653e16c1f87c4a1e90bba67126251d4.JPG)

**Comment by htobon** [comment]
Where are the other issues? the 3rd activity is still incomplete

**Comment by carios1usb** [comment]
Issues #266 and #267 created.

**Comment by htobon** [comment]
thks
