### ISSUE TITLE
[DA] Finalize the implementation of the CDN in S3

### ISSUE THREAD

**Issue by MateoVieira** [CCAFS/MARLO#1990]
Taking in count that there is a new S3 bucket for this purpose, apply CDN implementation using this artifact. 

- [x] Configure new AWS S3 bucket
- [x] Sync files to S3
- [x] Update feature branch with latest staging changes
- [x] Apply changes
- [x] Locally test

**Deliverable:**
**Move to Review when:** It works fine in feature branch
**Move to Closed when:** Changes are merged in staging

**Comment by danipilze** [comment]
documentation
https://docs.google.com/document/d/1AS3jZ2XR7UkUsCayoAZV4tvjyEm5aAKgSKiLNF69OTM/edit?usp=sharing
