### ISSUE TITLE
[SA] (CIMMYT specificity)  Remove the budget section in MARLO 

### ISSUE THREAD

**Issue by MateoVieira** [CCAFS/MARLO#1998]
Remove completely the budget section for CIMMYT’s Maize/Wheat CRP in MARLO at the project level, and just keep it at the synthesis level. Senior management wants to avoid confusion by not having a value in the budget section, so in past cycles, we had been entering “0” for each budget. We would like to take that one step further and remove it so that users do not see a budget section at all.

**Deliverable:**
**Move to Review when:**
**Move to Closed when:**

**Comment by sebas932** [comment]
We decided to remove the rule in the validator for all CRPs and platforms, so, it won't be required anymore
