### ISSUE TITLE
[SA] Adjustments in Synthesis for POWB2020

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#2006]
Issue description

Order by priority:
- [x] Show extended milestones in **table 2A** (Interface and Word Document)
- [x] In section **2.3 Planned Collaborations** for PMU, allow the possibility to add/edit collaborations entered by Flagships
- [x] Add an optional text field to add additional explanations about **Table 3** and show it in the Word Document
- [x] Include in section **2.3 Planned Collaborations** an information table similar to the developed for AR2018 **2.2 Partnerships** (See screenshot: https://i.imgur.com/c1SRgH8.png)

- [x] Test the hyperlinks and other types are working properly in the Word Document

**Deliverable:**
**Move to Review when:** is ready to test 
**Move to Closed when:** is released in production

**Comment by htobon** [comment]
Thank you @kenjitm and @sebas932 for working on this.
Here are some comments.
- [ ] **TABLE 2A** - Please fix the Word-document generator according to the following thought
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/3c8989aa-1d7d-41cc-87df-a747456108b3)

- [ ] **TABLE 3** Check word limit validator 
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/7e8b046e-0ada-43f8-9be4-2ae19ef707d8)

- [ ] **TABLE 3** Not sure a question is useful
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/f15d68d9-301a-404b-ae09-ef6b38836ac0)

**Comment by htobon** [comment]
- [ ] **TABLE 2C: ** List is cumbersome to read, we should allow the possibility to download it.
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/8b3f6784-741b-4a09-94fe-bc71d2fb13a1)

**Comment by MargaritaRamirez** [comment]
I made one test and the section let me include and delete without trouble 
My only comment is that maybe the additional comments of table 3 could appears bellow the table per se 

![test.jpg](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/8846fa89-b97a-4e28-a90a-eff95f4a7fa3)
![test 2.jpg](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/9d342364-85a3-4637-a766-73a3d720094a)
