### ISSUE TITLE
[MR] (AR 2019) Document annual report process

### ISSUE THREAD

**Issue by MargaritaRamirez** [CCAFS/MARLO#2009]
Create a document with all the steps that we have to accomplish before we send the final information of all the deliverables validated and with their score.  

- [x] Deliverable validation  
- [x] Journal paper by center
- [x] Publications list 
- [x] table for evidence D (AR template)
- [x] Statistics (how many OA, ISI, #articles, #publications, cross cutting dimesio,...) 

**Move to Review when: The template is complete
**Move to Closed when: The template is approved

**Comment by MargaritaRamirez** [comment]
@htobon @MateoVieira 
The template is complete at the following [link](https://docs.google.com/document/d/16XYArEGhuRbqJLsAweY6RVvWm8WGu7W36GytVNHBtTk/edit?usp=sharing) for you to review and make the necessary comments.

**Comment by MateoVieira** [comment]
waiting @htobon comments

**Comment by MargaritaRamirez** [comment]
Waiting for @htobon comments

**Comment by MargaritaRamirez** [comment]
Waiting for @htobon  comments

**Comment by MargaritaRamirez** [comment]
According to @htobon reviewing, I will close this issue.
