### ISSUE TITLE
[AP] (QA Platform) Create a diagram for the QA Process

### ISSUE THREAD

**Issue by anamp07** [CCAFS/MARLO#2010]
Create a diagram explaining how QA Process is going to be. 

- [x] Discuss how the process is going to be. 
- [x] Create the diagram. 

**Deliverable:** QA process diagram. 
**Move to Review when:** Ready to be reviewed by David. 
**Move to Closed when:** Reviewed and approved by David.

**Comment by MargaritaRamirez** [comment]
![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/9dad5570-a87f-425e-b58c-abd2611d7a26)
