### ISSUE TITLE
[MR] (Project Highlight) Revamp for the Project Highlight section in MARLO mock-up

### ISSUE THREAD

**Issue by MargaritaRamirez** [CCAFS/MARLO#2011]
According to ticket #1442 in fresh desk, we need to revamp the mock-up for the project highlight section in MARLO. We have to condensate the information and try to make fewer questions and let open space for the people to right. 

- [x] Review the message from Andy Jarvis and understand what is his suggestion 
- [x] Start the new mock-up 
- [x] Send to David and Hector for their approval
- [x] Discuss with Marissa if the section is useful and have her approval 
- [x] Send the mock-up to Andy and if is positive (HT-DA)
- [ ] Send the mock-up to MARLO family (HT-DA)

**Move to Review when: We send the mock-up to Marissa and Andy
**Move to Closed when: MARLO family approve it

**Comment by MargaritaRamirez** [comment]
![2019-11-20_0914.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/680018d6-49e0-4fc6-813c-6027c4ee5aef)

Work with Andy Jarvis message of project highlights and try to condensate the information in a simple way.

**Comment by MargaritaRamirez** [comment]
Nov 25: We made an update according to the suggestions of David and we put 2 options for the project highlights

https://docs.google.com/presentation/d/1cclP7ZFpKqApFrHyzugZ2EX5TW9ZUqEMP4CiNWevEVI/edit?usp=sharing 

Nov 27; Marissa liked the idea of the option 2 (make a short section in project description).  
Pending Task: Hector and David to share the idea to Andy, if positive, we will share it with MARLO family.

**Comment by MateoVieira** [comment]
Ask the TEAM witch CRP are using project highlights @MargaritaRamirez ??
to know who in the MARLO Family should be contacted

**Comment by MargaritaRamirez** [comment]
We ask @mralmanzar for his help to collect the information (database) of who is the CRPs that are working with Project Highlights to send it to @htobon so he can send the information of the revamp directly to that CRPs of MARLO family.

**Comment by MargaritaRamirez** [comment]
@mralmanzar sent the information with the CRPs that have project highlights active in their system: 

![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/0a454384-1dff-4bc6-a605-8eb77d424636)

Also, we reviewed the information and we find out 
![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/95f7b0f5-b4df-4203-8b47-02b529fa238a)

**Comment by MargaritaRamirez** [comment]
According to @htobon, we need to start a [template](https://docs.google.com/document/d/1QFPDT991YdbV8vZvF9g-6NB0NCBFnZ7TGc4vZwHMCB8/edit?usp=sharing) for the email that we need to send to MARLO family (the CRPs that have the section active) in order to have a unanimous desition to move the project highlights section to the project description. 
If they do not approve we will develop a specificity for only for CCAFS

**Comment by MargaritaRamirez** [comment]
We decided to only include the specificity for CCAFS
@kenjitm please proceed with this change only for CCAFS

**Comment by MargaritaRamirez** [comment]
@htobon please inform us if we can close this issue and have this improvement for the next cycle.

**Comment by htobon** [comment]
Hi @MargaritaRamirez. Thanks for following up on this. Since we are currently in the middle of the reporting period and this adjustment should have made before we start the process, I think we should at least wait until we finalize it and then we have a window of time to adjust the section again and ask for MARLO FAmily to review it and agree on it. What do you think? I would say that we should do this in May/June, 2020.

**Comment by MargaritaRamirez** [comment]
Hi @htobon ok, I will send this issue to future sprints. 
Thanks

**Comment by MargaritaRamirez** [comment]
@htobon are we going to do this revamp? we are 2 moth behind according with your comment in Feb

**Comment by MargaritaRamirez** [comment]
@htobon are we going to do this revamp? we are 3 moth behind according with your comment in Feb

**Comment by MargaritaRamirez** [comment]
This issue was canceled according to Hector's request.
