### ISSUE TITLE
[KT] DMSP/MEL Support pack create process to request addition of new guidelines

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#2014]
Issue description

![image.png](https://images.zenhubusercontent.com/5797d32de40e5714b16c907e/ec108d8c-1b95-4869-83e5-837d3b233d74)

**Comment by MargaritaRamirez** [comment]
Deadline: March 2020

**Comment by Edwin0307** [comment]
@kenjitm 
Kenji, can you please talk with Lizzy and understand the priority of this to decide if we can do it later? Or if we can keep the same way as we have now? Perhaps there are not so many requests per year.

**Comment by MargaritaRamirez** [comment]
According to the meeting 
1. @kenjitm step by step document
2. @Luisfben how to improve the way to upload the documents 

We will move this issue to the next sprint

**Comment by Luisfben** [comment]
**Activities pending**
- Check mockup with users
- Evaluate the implementation of a WebComponent to give same functionality to Management Support Pack
- Define like authenticate (Maybe with service token or directly with LDAP)

**Comment by MargaritaRamirez** [comment]
![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/9a680a0d-35bb-455a-81c5-4ac413abef29)

https://docs.google.com/presentation/d/1WueSN9DHqsLddXf0hM2ncTFvOgi9BVa1Ee3fRwiySeY/edit#slide=id.g8af55d5e41_0_71

**Comment by kenjitm** [comment]
The tool is explained to Felipe and he is assigned the necessary permissions and access to repositories and databases.

**Comment by felipelvira** [comment]
** THIS WAS MOVED TO https://app.zenhub.com/workspaces/marlo-57741a85e38255db5ee2475c/issues/ccafs/marlo/2201 **

-- Status changed to closed.
