### ISSUE TITLE
[DP] Create Database mapping for CLARISA indicators to CIAT programs and regions

### ISSUE THREAD

**Issue by yeyo2k3** [CCAFS/MARLO#2017]
- [ ] OICR
- [ ] Policies
- [ ] Innovations

Create a structure in the MARLO database to map the CLARISA indicators to CIAT programs and regions (centers)
so that the information of the templates entered by Lizzy  can be stored in MARLO

**Comment by MargaritaRamirez** [comment]
According with @yeyo2k3 this was no priority for this sprint because we change all the project from GLDC as a CRP.

**Comment by Edwin0307** [comment]
This has already been done when we added the mapping field to centers in the indicators.
