### ISSUE TITLE
[DP] (CLARISA) Implement CLARISA indicators (Policies)

### ISSUE THREAD

**Issue by yeyo2k3** [CCAFS/MARLO#2018]
Implement CLARISA functionalities to obtain data of CLARISA indicator (Policies)
Policies
- [x] Get
- [x] Post
- [x] Delete
- [x] Put
- [ ] Validator

**Comment by MargaritaRamirez** [comment]
@mralmanzar please test the service for Policies.

**Comment by htobon** [comment]
Validators will be tackled in a separated issue.
