### ISSUE TITLE
Redirect root URL to project path

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#202]
Please add a rule in the tomcat server to redirect 
http://marlodev.ciat.cgiar.org
to
http://marlodev.ciat.cgiar.org/marlo-web/

OR

Set-up the project so it runs in the root directory:
http://marlodev.ciat.cgiar.org

What do you think?
@sebas932, @HermesJim

**Comment by cgarcia9106** [comment]
http://marlodev.ciat.cgiar.org/ new link
