### ISSUE TITLE
[MA] (CIAT-MARLO) Project dashboard-CIAT

### ISSUE THREAD

**Issue by MateoVieira** [CCAFS/MARLO#2021]
Issue description: Add projects info to CIAT result dashboard, after this 

- [ ] define field information to show 
- [ ] create information cube
- [ ] create dahboar in DataEstudio

**Deliverable:** dashboard with projects information 
**Move to Review when:** hector check 
**Move to Closed when:**when Lizzy approve it

**Comment by MargaritaRamirez** [comment]
We will close this issue because the structure change and know we have to think according to the alliance.
