### ISSUE TITLE
[MA] (BI) Create cubes from CGIAR dashboard to BI

### ISSUE THREAD

**Issue by MateoVieira** [CCAFS/MARLO#2024]
Issue description: Copy cubes from CGIAR Results Dashboard (E.g. Innovations, Policies, OICRs, etc.) in order to use them in MARLO. 

- [x] create ETL( extraction,transformationand load information from dashboard cube to PowerBI)
- [ ] update CCAFS dashboars  to take cubes( OICR, Policies, Innovation, Deliverables) information 

**Deliverable:** Cubes located in the data warehouse and Power-BI connected to them.
**Move to Closed when:** When Power-BI is enabled and connected to the DataSources.

**Comment by MargaritaRamirez** [comment]
Pending dashboard: OICRs, Innovations, and Deliverables

**Comment by htobon** [comment]
This issue is moved to Sprint 4.4.2 as it is not critical and can wait.

**Comment by mralmanzar** [comment]
This issue will be divide in individual issues for each indicator
