### ISSUE TITLE
[MA] (BI) Deliverable cube 

### ISSUE THREAD

**Issue by MateoVieira** [CCAFS/MARLO#2025]
The current Dashboard of deliverables is not developed as a cube but as a master table. It must be changed to Cubes to be more user-friendly.

- [ ] design the cube structure
- [ ] define the Querys for each table and fact dimension 
- [ ] create the ETL
- [ ] adjust the Dashboard graps 

**Deliverable:** 
**Move to Closed when:**

**Comment by MargaritaRamirez** [comment]
The deliverable section is already in MARLO BI as a master table. 
We will close this issue
