### ISSUE TITLE
[MA] (CGIAR Results Dashboard) Document the cubes and upload it to Dataverse

### ISSUE THREAD

**Issue by MateoVieira** [CCAFS/MARLO#2026]
All cubes need to be documented in order for other people to understand how they are made and can play with the raw data. In order to do this, we are preparing a series of Word documents that describes all the tables and main columns for each Cube so others can use it as a reference.

- [x] update graphs (The graph that is at the beginning of the word document)
- [x] check text field 
- [x] Manuel and David to meet and release this out.
- [x] Upload document to Dataverse

**Deliverable:**
**Move to Review when:** HT and DA
**Move to Closed when:**when they approve it

**Comment by MargaritaRamirez** [comment]
Pending meeting with David for the final review.
