### ISSUE TITLE
[MV] (Project) Base lines 

### ISSUE THREAD

**Issue by MateoVieira** [CCAFS/MARLO#2027]
Mateo to create a baseline in terms of tickets + online chats + exceptions from this year (if possible, from previous years too). This baseline should be made per month. This will be used when the team is planning the objectives for 2020. 

- [ ] Take info from github
- [ ] Take info from google analytics
- [ ] draft on excel the base lines  

**Deliverable:**
**Move to Review when:** 
**Move to Closed when:**

**Comment by MargaritaRamirez** [comment]
We already plan our 2020 objectives.
