### ISSUE TITLE
[DP] (CLARISA) Create JSON examples of CGIAR Dashboard tables to MEL

### ISSUE THREAD

**Issue by yeyo2k3** [CCAFS/MARLO#2031]
Create a JSON example for every Dashboard Table exposed in CLARISA for MEL, 

- [x] Innovations
- [x] Policies
- [x] External partnership
- [x] Publications
- [x] Outcomes and Milestones
- [x] OICRs
- [x] Internal Cross CGIAR collaborations
- [x] Cap-dev
- [ ] W1/2 Use
- [ ] CRP financial Report
- [ ] Update Actions to Relevant Evaluations
- [x] MELIA
- [x] Progress Towards SRF targets

Deliverable : A folder with every JSON examples.
Move to Review when : Grant access to all JSON examples
Move to Closed when: Deliver examples to Claudio and patrica from MEL.

**Comment by MargaritaRamirez** [comment]
We already developed 6 JSON structure out of 13 for MEL 
Deadline: March 2020

**Comment by yeyo2k3** [comment]
we are currently made changes on MELIA and Status of Outcomes that impact in JSON structure

**Comment by yeyo2k3** [comment]
we will close this issue and open a new one for 3 lastest tables.
