### ISSUE TITLE
[KT] (replication) Impact pathway replication for all phases

### ISSUE THREAD

**Issue by MateoVieira** [CCAFS/MARLO#2032]
-Helen: "I closed POWB 2020 and opened POWB 2019 Upkeep to add numbers to the 2019 milestones.  Then when I closed that module and reopened POWB 2020, most of the milestones that flagships had entered as new for 2020 had disappeared, and the numbers for the ones that were extended from 2019 to 2020 were still missing in the table."

- [x] Identify replication problems of the phases from POWB to Upkeep
- [x] Identify replication problems of the phases from UpKeep to AR
- [x] Fix Outcomes replication problems of the phases from UpKeep to AR
- [x] Fix Sub-IDOS replication problems of the phases from UpKeep to AR
- [x] Fix Milestones replication problems of the phases from UpKeep to AR
- [x] Fix Outcomes replication problems of the phases from POWB to UpKeep
- [x] Fix Sub-IDOS replication problems of the phases from POWB to UpKeep
- [x] Fix Milestones replication problems of the phases from POWB to UpKeep

**Deliverable:**
**Move to Review when:** Develop is tested in Dev
**Move to Closed when:** Develop is in Prod

**Comment by MargaritaRamirez** [comment]
![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/7373ee16-ae90-44eb-8a47-f76656cbbb47)

**Comment by kenjitm** [comment]
https://docs.google.com/spreadsheets/d/1WQ6xQz_pUvqmxdQogsc_Vc0iilKEnYZn738ePtxnA9E/edit#gid=1985482201

**Comment by gcmartinezg** [comment]
This functionality was tested in DEV and is in MARLO Prod.
