### ISSUE TITLE
[GM] (CLARISA) Implement CLARISA indicators (Key External Partnership)

### ISSUE THREAD

**Issue by yeyo2k3** [CCAFS/MARLO#2035]
External Partnership
- [x] Get
- [x] Post
- [x] Delete
- [x] Put
- [ ] Validator

Deliverable: Clarisa funtionality 

Move to Review when:  Funtionality will be implemented on Clarisa Dev
Move to Closed when: Funtionality will be implemented on Doppler

**Comment by gcmartinezg** [comment]
Implementation is taking me longer than it should. I expect to finish PUT by the end of the day and to test that tomorrow morning.

**Comment by gcmartinezg** [comment]
All methods done and a little testing was made. I think it might need more intensive would be great. Validator pending because I do not know how to make that.

**Comment by htobon** [comment]
@gcmartinezg We will close this issue and will follow-up in another one in the next sprint.

**Comment by gcmartinezg** [comment]
@htobon reopened for testing purposes

**Comment by gcmartinezg** [comment]
Testing done, [changes](https://github.com/CCAFS/MARLO/commit/9122b36a2aadacce39cd4f7ae1a44319672890ec) were made.

**Comment by gcmartinezg** [comment]
Currently being tested on dev by Patricia. Waiting for feedback.

**Comment by yeyo2k3** [comment]
Patricia has been testing it and her feedback is that the service is working.
