### ISSUE TITLE
[AP] (Results Dashboard) Design a mockup to include Genebank data in the dashboard. 

### ISSUE THREAD

**Issue by anamp07** [CCAFS/MARLO#2038]
Design the mockup according to the information we received from Genebank. 

- [x] Analyze the data to propose charts (with Manuel). 
- [ ] Design the mockup.

**Deliverable:** Mockup. 
**Move to Closed when:** the mockup is finished.

**Comment by htobon** [comment]
Some ideas were written in Ana's notebook, but since this is not a high priority for the SMO and they will take this out in a different way, we decided to close it.

![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/2f8118ce-3be2-47fc-b942-b6beab2626f8)
