### ISSUE TITLE
[MA] (BI) Embed the project status dashboard in MARLO

### ISSUE THREAD

**Issue by anamp07** [CCAFS/MARLO#2039]
- [x] Develop the cube of project status. 
- [x] Develop the dashboard in PowerBI.
- [x] Design a mockup of how the dashboard is going to be in MARLO (AP).
- [x] Create the action in MARLO (KT).
- [x] Develop the front-end in MARLO (AP). 

**Deliverable:** Dashboard in MARLOdev.
**Move to Review when:** Dashboard is in MARLOdev.
**Move to Closed when:** Approved by Hector.

**Comment by mralmanzar** [comment]
Done
![image](https://user-images.githubusercontent.com/9383649/75688237-262e9880-5c6d-11ea-9aad-2677bf4aa577.png)
