### ISSUE TITLE
[FE] (QA) Create the progress page of the prototype 

### ISSUE THREAD

**Issue by Edwin0307** [CCAFS/MARLO#2042]
Create the homepage for the Admin and the Assessor view in the prototype. 

- [x] Create the back-end
- [x] Create the front-end

**Deliverable:** Progress Page
**Move to Review when:** Progress page is ready  
**Move to Closed when:** Progress page is reviewed

**Comment by MargaritaRamirez** [comment]
@htobon could you please liaise with @felipelvira for the test of this issue
