### ISSUE TITLE
[GM] (MARLO) Connect MARLO with different services to update deliverable information

### ISSUE THREAD

**Issue by anamp07** [CCAFS/MARLO#2058]
Connect MARLO with the following services to obtain information about deliverables:

- [x]  Web of Science (WoS)
- [x] Altmetrics
- [x] GARDIAN

**Deliverable:** Deliverables improvements
**Move to Review when:** The services are ready to be tested
**Move to Closed when:** The services are working on MARLO Prod

**Comment by gcmartinezg** [comment]
Removing ICRISAT connection as discussed
