### ISSUE TITLE
[LB] (MARLO) Allow MEL to add Innovations and Policies without having to select a specific project (Same as OICRs)

### ISSUE THREAD

**Issue by Luisfben** [CCAFS/MARLO#2060]
This is a back-end functionality for all of those indicators that do must be added as part of a project (Always). 

Since we will receive information from MEL, the idea is that they can also be added to the CRP and not to a specific project. Therefore, we would like to adjust the indicators for Policies and Innovations to make this happen. 

**Deliverable:** MARLO functionality
**Move to Review when:** Funtionality will be implemented on dev-clarisa-v2
**Move to Closed when:** Funtionality was  tested by Diego

**Comment by Luisfben** [comment]
@yeyo2k3 complete implementation please tested. Be went up on dev-clarisa-v2

**Comment by yeyo2k3** [comment]
the database migration has not been created on staging. when this one will be implemented this issue can be closed.

**Comment by Luisfben** [comment]
Hi @kenjitm y @yeyo2k3, can any of you please give me a space to explain how to do this. Thank you.

**Comment by yeyo2k3** [comment]
I implemented this DataBase migration. 
When this will be required, we have to search for these parameters.

**Comment by Luisfben** [comment]
Implementation was passed to production
