### ISSUE TITLE
[MA] (Interoperability) Analize the list of funding sources Institutions

### ISSUE THREAD

**Issue by mralmanzar** [CCAFS/MARLO#2064]
German extracted an Excel mapping between institutions related to MARLO financing sources and OCS contracts.
The goal is analyze this information and present to the Interoperability team.
- [x] Analyze the information 
- [x] Create some indicators about the information
- [ ] Present to the team

**Deliverable:** Presentation with the analysis
**Move to Review when:** 
**Move to Closed when:**

**Comment by gcmartinezg** [comment]
Analysis and indicators were made. As a result, an [excel file](https://cgiar.sharepoint.com/:x:/s/CCAFS-KDS/EcEZ9yfj80lLtOw4vPPUXyEBsQr6l_0RFte4jMaInv8J9g?e=Ao4RZF) with the information was created

**Comment by gcmartinezg** [comment]
The excel file was sent to Hector and Manuel. The analysis was included in a partner request [slide](https://docs.google.com/presentation/d/1v6M-GD5AtgQYTZdH6NBI4Ef_9onGJFZ1/edit#slide=id.p7)
