### ISSUE TITLE
[DP] (Altmetrics) Create JAR to update Altmetrics information in the CGIAR Results Dashboard

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#2066]
In this moment, the Altermics information in CGIAR Results Dashboard is not updated automatically, and we would like to develop an automated script which can help us in this process.
- [ ] Activity 1
- [ ] Activity 2

Here is how the information is being displayed in the dashboard:
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/2beb29a4-e35b-4978-ae33-c96bde90a1c1)

**Comment by gcmartinezg** [comment]
Main [completed](https://github.com/CCAFS/CGIAR-Dashboard-Altmetrics-Sync/commit/e58083f2a94a84f289d6514b1eb858151b7ddc08). I am currently testing the update process on my local database.

**Comment by yeyo2k3** [comment]
Actually @gcmartinezg are testing this.

**Comment by gcmartinezg** [comment]
Information updated. I am waiting for feedback to come.

**Comment by gcmartinezg** [comment]
Closed as discussed with @mralmanzar .
