### ISSUE TITLE
[GM] (Clarisa) Peer-Reviewed Publications (Table 6)

### ISSUE THREAD

**Issue by gcmartinezg** [CCAFS/MARLO#2068]
Peer-Reviewed Publications.

- [x] GET (Review)
- [ ] POST (Review)
- [x] PUT
- [x] DELETE
- [ ] Validator

**Deliverable:** _Clarisa_ funtionality
**Move to Review when:** Funtionality will be implemented on _Clarisa Dev_
**Move to Closed when:** Funtionality will be implemented on _Doppler_

**Comment by gcmartinezg** [comment]
I got stuck testing (OICR) Table 3, so I have not started yet. I plan to start next Monday.

**Comment by gcmartinezg** [comment]
@Luisfben could you test this please?

**Comment by Luisfben** [comment]
Sure, pass test result by Slack.
