### ISSUE TITLE
[AP] (MARLO) Develop a guidance for reporting Deliverables

### ISSUE THREAD

**Issue by anamp07** [CCAFS/MARLO#2070]
Add a text explaining how to report license in Deliverables dissemination (specially for deliverables dissaminated in repositories that are not synced with MARLO). 

- [x] Meet with Hector and Margarita to discuss and understand. 
- [ ] Include the text in MARLO.

**Deliverable:** The text is added to MARLO Deliverables. 
**Move to Closed when:** The text is added to MARLO Deliverables.

**Comment by MargaritaRamirez** [comment]
@anamp07 
Could be this: 
If you are not sure if the deliverable has a license, please search in the publication or the page the C symbol or the phrase "copyrights"

**Comment by MargaritaRamirez** [comment]
@anamp07 take a look to this, I think we can use this in the deliverable module

The Creative Commons License is an international publishing standard used to grant rights to use Open Access material. The [license code](https://creativecommons.org/licenses/) conveys specific things: 

BY: Attribution to the original author, all derivatives permitted 
SA: Share Alike meaning that derivative works must share the same license 
ND: No Derivatives meaning a work can be shared, but not changed 
NC: Non-Commercial, allowing a work to be shared and derived, but not for commercial purpose 
x.0: these are the legal versions of the license, so to see the differences you have to read the fine print of the legal language available from the Creative Commons website.

**Comment by MargaritaRamirez** [comment]
@htobon what should we do with this issue?
