### ISSUE TITLE
[MR] (Annual Report 2019) Quality Assurance process 

### ISSUE THREAD

**Issue by MargaritaRamirez** [CCAFS/MARLO#2088]
I need to create a message for the ML of each project asking for their permission to change the information in MARLO that we found after the deliverable validation process.

- [x] Identify all the changes in the deliverable document so we can export the information for each project
- [x] Create the email template 
- [x] Send the email to the ML with the deadline 

**Deliverable:**
**Move to Review when:** We have the email draft
**Move to Closed when:** Hector approve the narrative and we send the email

**Comment by MargaritaRamirez** [comment]
Draft 
Dear _____

As part of the annual standard quality checking and revision process to assure accurate data in MARLO, we have checked the list of deliverables that belongs to the projects led by _______ and identified a few areas where we propose some adjustments (please refer to the table attached). You can filter by the deliverable ID in order to revise the suggested changes. 

Please check the table and let us know if you have any clarifying questions, concerns, or further corrections to this no later than 15-05-2020 COB.  If we do not hear from you by then, we work under the assumption that these changes are correct and therefore will be taken forward in the system.

**Comment by MargaritaRamirez** [comment]
@htobon the message is Ok?

**Comment by htobon** [comment]
Yes @MargaritaRamirez.
Thanks so much for this.

I have slightly adjusted it in our shared google docs. Please feel free to start the process with the CCAFS MLs.
