### ISSUE TITLE
[LB] (MARLO) COVID-19 - CCAFS specificity

### ISSUE THREAD

**Issue by MargaritaRamirez** [CCAFS/MARLO#2099]
We need to be able to generate a report for this specificity in our summaries section

- [x] Define mock-up
- [x] Backend
- [x] Frontend
- [x] Test of integration
- [x] Deployment in production

** Mock-up **
https://docs.google.com/spreadsheets/d/1E6wIxoANvFmbgDsNpD2w3GuCKiBr56dak8LN69pd0yI/edit#gid=0

** Requirements **
- Excel report
- Available in the summaries section. Probably in the Projects sub-session
- What are the access permissions?

** Deliver date **
Ending May

**Deliverable:** MARLO functionality
**Move to Review when:** Funtionality will be implement on dev
**Move to Closed when:** Funtionality will be implement on production

**Comment by MargaritaRamirez** [comment]
@Luisfben could you please complete the task for this issue

**Comment by Luisfben** [comment]
![image.png](https://images.zenhubusercontent.com/5e4af1b8a6da9430d8344bcf/f3968dc0-6fe3-4460-aa38-68545d394615)

**Comment by Luisfben** [comment]
![image.png](https://images.zenhubusercontent.com/5e4af1b8a6da9430d8344bcf/a1c60c3f-358d-4251-85a1-e4f18eaf6e98)

**Comment by Luisfben** [comment]
![image.png](https://images.zenhubusercontent.com/5e4af1b8a6da9430d8344bcf/ee380e76-200f-477b-b477-06d0d5995698)

**Comment by Luisfben** [comment]
was passed into production!
