### ISSUE TITLE
Email when role is assigned

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#210]
Program Management
Flagship Leader
Regional Leader
Site-Integration Leader
CoA Leader

**Comment by AndresFVR** [comment]
@htobon I made the notification to the user when is assigned to a role.

**Comment by HermesJim** [comment]
This issue has been development by @AndresFVR . in the commit 3b69c9c.

Now, we check the text and dessing in the emails but this is another issue.
