### ISSUE TITLE
[AP] (Alliance Dashboard) Navigation menu in the top

### ISSUE THREAD

**Issue by MargaritaRamirez** [CCAFS/MARLO#2100]
Change the navigation menu to the top

- [x] Create a navigation menu on the top. 

**Move to Review when:** The menu is done and ready to be checked by Hector. 
**Move to Closed when:** The menu is approved.

**Comment by MargaritaRamirez** [comment]
@anamp07 could you please update the task for this issue.

**Comment by anamp07** [comment]
Done. 

I added a navigation menu with arrows to move back and to the next section. I also had a meeting with Lizzy to finish this, she approved it. 

![image.png](https://images.zenhubusercontent.com/5b81b883dc633f0891418b32/bdabea33-41ea-424f-aa90-86a9969a80e9)

![image.png](https://images.zenhubusercontent.com/5b81b883dc633f0891418b32/ea89c48a-efc1-4189-ba7a-cca6dbd10d99)

![image.png](https://images.zenhubusercontent.com/5b81b883dc633f0891418b32/f7464bfe-31ce-4ac2-a584-58ff9ef83767)
