### ISSUE TITLE
[AP] (Alliance Dashboard) Embed the dashboard in the CIAT web

### ISSUE THREAD

**Issue by MargaritaRamirez** [CCAFS/MARLO#2101]
Decide if only one to the Alliance dashboard or have each part separately embedded – Lizzy will connect Alejandro with Hector and Ana Maria

- [x] Contact the person in charge of the website to discuss how the dashboard will be included.
- [x] Adjust the dashboard if there is something needed for the embed. 

**Move to Closed when:** The dashboard is embedded in the website.

**Comment by MargaritaRamirez** [comment]
@anamp07 @htobon could you please update the tasks for this issue.

**Comment by anamp07** [comment]
Done. Embedded in https://ciat.cgiar.org/how-we-work/results-based-management/ 

![image.png](https://images.zenhubusercontent.com/5b81b883dc633f0891418b32/42b6a96c-481e-4b4b-acc0-249af750ccbb)
