### ISSUE TITLE
[MA] (Alliance Dashboard) Add filter for years

### ISSUE THREAD

**Issue by MargaritaRamirez** [CCAFS/MARLO#2102]
Add filter for years 

- [ ] Add a year filter in the top with the other filters.

**Move to Closed when:** the filter is included and working in the dashboard.

**Comment by MargaritaRamirez** [comment]
@anamp07 could you please update the tasks of this issue

**Comment by MargaritaRamirez** [comment]
We need to send the information to Tonya and Lizzy to close the issue
@mralmanzar @anamp07

**Comment by mralmanzar** [comment]
![image](https://user-images.githubusercontent.com/9383649/83688034-59592e80-a5b2-11ea-9892-9be18955cab4.png)
