### ISSUE TITLE
[MA] (Alliance Dashboard) Include 2017 and 2019 data

### ISSUE THREAD

**Issue by MargaritaRamirez** [CCAFS/MARLO#2104]
Include 2017 and 2019 data

- [ ] 
- [ ] 

**Move to Review when:** 
**Move to Closed when:**

**Comment by MargaritaRamirez** [comment]
@mralmanzar could you please update the tasks for this issue

**Comment by mralmanzar** [comment]
2019 innovations, policies, and OICRs were included in the alliance dashboard. 
![image](https://user-images.githubusercontent.com/9383649/83640467-c6989f80-a571-11ea-9335-43fecd3c6ea5.png)

**Comment by MargaritaRamirez** [comment]
We need to send the information to Tonya and Lizzy to close the issue
@mralmanzar @anamp07
