### ISSUE TITLE
[AP] (Alliance Dashboard) Add Data Information for the QA process

### ISSUE THREAD

**Issue by MargaritaRamirez** [CCAFS/MARLO#2106]
Tonya will send the narrative  for this process

- [ ] Include "Data and information is quality assured (for 2017 and 2018) b) Quality assurance is ongoing for 2019 data." in the dashboard.

**Move to Closed when:** The text is on the dashboard.

**Comment by MargaritaRamirez** [comment]
@anamp07 could you please update the tasks for this issue.

**Comment by anamp07** [comment]
Done. 

![image.png](https://images.zenhubusercontent.com/5b81b883dc633f0891418b32/72b5640a-9ecd-448b-ac98-c1b12b292b0e)
