### ISSUE TITLE
[AP] (MARLO) Check HTML component

### ISSUE THREAD

**Issue by anamp07** [CCAFS/MARLO#2107]
Check the HTML component to fix problems with copy and paste. 

- [ ] Check the component. 
- [ ] Investigate if there is another plugin we could use to avoid the problems of the current one.

**Deliverable:** List of plugins we could use to replace the current plugin.
**Move to Closed when:** We have a list of options or the problem with the current component is solved.

**Comment by MargaritaRamirez** [comment]
We duplicate this issue with the #2174 and was outsourced with Premize S.A.S.
