### ISSUE TITLE
[DP] (CLARISA) Simplify Indicator List Services

### ISSUE THREAD

**Issue by yeyo2k3** [CCAFS/MARLO#2109]
Simplify fields for indicators list services below y determinate if they were exclude on Synthesis to AR:

- [x] Policies
- [x] Innovations
- [x] OICR
- [x] Publications
- [x] Melia

Deliverable: CLARISA Indicator get List
Move to Review when: Feature will be deployed on DEV
Move to Closed when: Feature will be deployed on PROD

**Comment by MargaritaRamirez** [comment]
@yeyo2k3 please add the image of the ones that you have done

**Comment by yeyo2k3** [comment]
here is an example from OICR list, [Link](https://cgiar.sharepoint.com/:u:/s/CCAFS-KDS/EcIxZqgnvv5Jvg5WD9lRPs0Bpj1LRYWa_LI4Dp5ovn47JA?e=YmZSDz)
