### ISSUE TITLE
[GM] (KDS) Improve the services Stas.jar to get information per year

### ISSUE THREAD

**Issue by MargaritaRamirez** [CCAFS/MARLO#2112]
We need to improve the service or create a new one (taking into account the one that we already have) to get the downloads and views per handle (CGSpace) for a specific timeline (Jan-Dec XXXX) 

- [x] Take a look at the service
- [x] Understand the code
- [x] Raise whether a solution is possible or we need to develop another service

**Move to Review when:** 
**Move to Closed when:**

**Comment by gcmartinezg** [comment]
Two options were tested. One averaged 0.08s more per handle than the other one. For 526 handles, one took 206s and the other 160s so I went with the other option. Almost finished.

**Comment by gcmartinezg** [comment]
@MargaritaRamirez this is ready to be tested. Let me know when we can have a quick meeting to explain to you how does the new program work.

**Comment by gcmartinezg** [comment]
Meeting with Margarita finished. A [new issue](https://github.com/CCAFS/MARLO/issues/2151) was created for a future version of the program.
