### ISSUE TITLE
[MR] (KDS) Project Page - Include all the information in the service

### ISSUE THREAD

**Issue by MargaritaRamirez** [CCAFS/MARLO#2118]
According to our last meeting with the Maroni Bross we will proceed with the option: 

Option 1: Manual entry of the project to the website

Step 1: Website editor inserts the project node on Drupal and fills the ID fields with the MARLO Project ID
Step 2: Website editor clicks on SAVE button to save the content
Step 3: Website Importer fetches directly from Marlo all the fields for that particular ID and updates the Drupal Content (single item webservice used)

And we need to include now all the information in the service according to the static JSON that we sent to them on June 17, 2020. You can consult in the following [link](https://docs.google.com/document/d/1UazMvYkhjnucGPVYBq9lnbP7nxDabrD4-hm2LTXbyxE/edit?usp=sharing)  
- [Mock-up](https://docs.google.com/presentation/d/1WEBF7B6L4d6IPHIyudUgOavVD2QFJzSFDCSR5N-ryN0/edit#slide=id.gc54a768f2_0_0) 
Include: 
- [x] Activities
- [x] Contribution to CCAFS outcomes
- [x] Outcome case studies
- [x] Deliverables
- [x] Project Partners
- [x] Innovations
- [x] Policies

**Deliverable:**
**Move to Review when:** We complete the service
**Move to Closed when:** we test the service

**Comment by yeyo2k3** [comment]
Here is a example from service response [Link](https://cgiar.sharepoint.com/:u:/s/CCAFS-KDS/EcBpiYW-4m9Ns12miN0pB1cBxux9oa-ln6cgWVyg09Rdcg?e=Xc6t5K)

**Comment by MargaritaRamirez** [comment]
![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/8008b9e4-6d20-4380-8d66-01cf1777edbc)
