### ISSUE TITLE
[MA] (SMO Dashboard) POWB Data Review

### ISSUE THREAD

**Issue by MargaritaRamirez** [CCAFS/MARLO#2119]
Hello Hector and Manuel, 

Thank you for discussing the POWB data and next steps! Please find data for 2018, 2019, and 2020 attached. As per our discussion, Manuel will review and analyze the data sets to confirm whether the content and structure align with the MARLO data and then we decide how to move forward. 
Ticket #2092 

- [x] Review the information
- [x] Load the information in MARLO (standalone table)
- [x] Create the cubes Queries
- [x] Create the ETLs and send the info to Snowflake
- [x] Create the cube document

**Deliverable:** Cube document
**Move to Closed when:** mail is sent to tania with the cube document

**Comment by mralmanzar** [comment]
The information was organized an loaded in a standalone table in the MARLO database (results_dashboard_powb_milestones_info).
Al the queries and cube model are already finished.

**Comment by mralmanzar** [comment]
Was implemented the ETL to send the POWB milestones to snowflake.
![image](https://user-images.githubusercontent.com/9383649/88106745-9467ef00-cb6b-11ea-9ca9-27eab4528749.png)

**Comment by mralmanzar** [comment]
The cube document was sent to Tania and Porsha
![image](https://user-images.githubusercontent.com/9383649/88106817-b5304480-cb6b-11ea-805c-44add1436a32.png)
