### ISSUE TITLE
[LB] (MARLO) COVID-19 categories of impact

### ISSUE THREAD

**Issue by Luisfben** [CCAFS/MARLO#2123]
Include a drop-down menu for the current state of COVID-19 impact with these options:

- NO IMPACT - Activities unaffected and expect to achieve deliverables as planned
- MINOR RE-SCHEDULING - Activities have had to be postponed, but still expect to achieve deliverables by end of year
- MAJOR RE-SCHEDULING - Activities have had to be postponed and 2020 deliverables will be achieved only in 2021
- PARTIAL CANCELLATION - Some activities have had to be cancelled and some deliverables will not be achieved
- FULL CANCELLATION - All activities have had to be cancelled

- [x] Define mock-up
- [x] Backend
- [x] Frontend
- [x] Test of integration
- [x] Deployment in production

** Mock-up **
https://docs.google.com/presentation/d/1tDO6mGwESkOgQkkMgdnzjTnw27q8ttBJTwotonCtf5o/edit#slide=id.g74d2180936_11_5

** Requirements **
- not required

**Deliverable:** MARLO functionality
**Move to Review when:** Funtionality will be implement on dev
**Move to Closed when:** Funtionality will be implement on production

**Comment by Luisfben** [comment]
Hi @BrahianSalazar, please check backend

**Comment by BrahianSalazar** [comment]
The change was checked in local and works correctly. It was passed to testing environment (dev).

**Comment by BrahianSalazar** [comment]
The change was tested by @htobon , approval is given to go to prod.

**Comment by BrahianSalazar** [comment]
The change is already in prod.
