### ISSUE TITLE
Error Messages when user logins

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#214]
Based on the Authentication library shared by IT

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-b35e9bdd21d7f69b9201cb0c414d23313159453c36e5d55ff7a4d0c2a6e002e5.png)

**Comment by HermesJim** [comment]
Now catch the ADauth library login messages

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-874b931b82dd07e04a52c0d43754d19460abb625eecbfc4352184a81bdb80758.png)

**Comment by htobon** [comment]
Would you please also attach here all the other error messages? No need to attach screenshot.

**Comment by HermesJim** [comment]
messages are as follows: 

- **LOGON_SUCCESS**:"Login successful"
- **ERROR_NO_SUCH_USER**: "CGIAR User not exist"
- **ERROR_LOGON_FAILURE**: "Invalid CGIAR username or password"
- **ERROR_INVALID_LOGON_HOURS**: "CGIAR User account with restricted access in specific hours"
- **ERROR_PASSWORD_EXPIRED**: "CGIAR User password expired" 
- **ERROR_ACCOUNT_DISABLED**: "CGIAR User account disabled"
- **ERROR_ACCOUNT_EXPIRED**: "CGIAR User account expired" 
- **ERROR_ACCOUNT_LOCKED_OUT**: "CGIAR User account blocked"

**Comment by htobon** [comment]
To be reviwed by me tomorrow. @HermesJim please remember me.

**Comment by htobon** [comment]
The messages for CGIAR accounts should read as:

**LOGON_SUCCESS:** "You have successfully logged in"
**ERROR_NO_SUCH_USER:** "The CGIAR email provided does not exist, please try again"
**ERROR_LOGON_FAILURE:** "Invalid CGIAR email or password, please try again"
**ERROR_INVALID_LOGON_HOURS:** "Your CGIAR account has a restricted access at this time, please contact the IT staff from your Center"
**ERROR_PASSWORD_EXPIRED:** "Your CGIAR account password has expired, please contact the IT staff from your Center"
**ERROR_ACCOUNT_DISABLED:** "Your CGIAR account is disabled, please contact the IT staff from your Center"
**ERROR_ACCOUNT_EXPIRED:** "Your CGIAR User account has expired, please contact the IT staff from your Center"
**ERROR_ACCOUNT_LOCKED_OUT:** "Your CGIAR account is currently blocked, please contact the IT staff from your Center"

**Comment by htobon** [comment]
@HermesJim, may you please show me the messages for the users that are not using CGIAR accounts?

**Comment by HermesJim** [comment]
**Invalid User** : Invalid email or password, please try again
**User Inactive** : Your account is inactive
**User dont choose a CRP : Please select a** CRP
**User logged but choose a invalid CRP**  : You don't have Access to the selected CRP

**Comment by htobon** [comment]
**Invalid User:** "Invalid email and/or password, please try again"
**User Inactive:** "Your account is disabled, please contact your Management Liaison and/or the MARLO staff"
**User dont choose a CRP:** "Please select a CRP"
**User logged but choose a invalid CRP:** "You don't have access to the selected CRP"
