### ISSUE TITLE
[DP] (CLARISA) RTB Partners validation process

### ISSUE THREAD

**Issue by MargaritaRamirez** [CCAFS/MARLO#2146]
According with the last meeting on July 6 with Claudio the found 844 institutions that we don't have in MARLO. 
They shared the [list](https://cgiar.sharepoint.com/:x:/s/CCAFS-KDS/ES76yuDqPGVJl5q25cTZxh0BEjNfqlyGCGASovvSQpsiDg?e=sekGor) and we will have another meeting on July 13 so we can inform how much time do we need to validate the entire list. 

- [x] Review 60 partners out of the 844 reported knowing how many of them will need to create in MARLO
- [x] Report de average time to estimate the time and resource that we need to accomplish this task 

**Move to Review when:** when we have the 60 institutions validated
**Move to Closed when:** after the meeting with Claudio

**Comment by MargaritaRamirez** [comment]
July 13: 14/20 will have this information before our meeting today.

**Comment by mralmanzar** [comment]
Was validated 20 institutions and took around 3.5 hours

**Comment by MargaritaRamirez** [comment]
July 14: After our yesterday meeting, we decide 
1. We will create the partners that Hector marks as pending in the first sheet 
2. Diego will include the types of institutions to the 3d sheet and Hector will ask Sara for her help to mark the institutions. 
3 We will have until July 27 to create new partners

**Comment by MargaritaRamirez** [comment]
We will contract 2 persons to help us validating and adding the institution information of  MEL partners. 

Diego created a single document so we can all work in there. 
https://cgiar.sharepoint.com/:x:/s/CCAFS-KDS/EU4iXEgsiWlFnxubg1Qmj4UBcio2C3_6SNuGivL6_m5SAw?e=Bmvcwd

**Comment by MargaritaRamirez** [comment]
Next week we will start with working with Andres and Yamit in this validation process.

**Comment by MargaritaRamirez** [comment]
Aug 18: We started working with Andres and Yamit 
We will close this issue and create a new one to document the process that they report
