### ISSUE TITLE
[AP] (MARLO) Improvements in Funding Sources interface functionality

### ISSUE THREAD

**Issue by kenjitm** [CCAFS/MARLO#2155]
**Funding Source Interface**
- [x] Locate Achieved tab more visibly
We didn't change the look and feel of the tabs as this is the look and feel of all MARLO tabs. And it wasn't clear were it should have been put. From my point of view, it's ok in the place it is. 

- [x] Indicate when a finance code is already being used by other crp
![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/0632d261-6c4a-4eab-a868-f58ec1d012d2)

![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/b2b5aa64-7523-4177-b8de-ddbd20127a88)

- [x] Add explanatory text of what the funding sources achieved are
![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/3337f528-779d-4dd4-8e01-16d00998a4ea)

- [x] Add explaining text about managing partners, explaining that these should be mapped
![image.png](https://images.zenhubusercontent.com/5b81b883dc633f0891418b32/d69681ec-d194-4c90-a3f2-aa7306c199af)

- [x] Add explanatory text that a funding source can only be associated with managing partner projects
![image.png](https://images.zenhubusercontent.com/5b81b883dc633f0891418b32/b3900804-811f-4f9e-8eb7-956345e6afe3)

- [x] Add explanatory text of what the Agresso institution should be mapped in the Direct funder dropdown
![image.png](https://images.zenhubusercontent.com/5b81b883dc633f0891418b32/f85969d9-9a62-4c6d-aee4-2e4b2ed3051c)

- [x] Make the Finance Code field visible only when a Managing Partner is selected
As explained in the comment, we decided not to develop this as it is not necessary with the new feature for creating funding sources. 

- [x] Show full Funding Source title when syncing
![image.png](https://images.zenhubusercontent.com/5b81b883dc633f0891418b32/cd23aaf4-237c-47d0-88af-6f1bf20ee775)

- [ ] Check Direct Funder field validations - It is shown as if the field will be empty so it is filled when saving

May 2019 Mockup: https://docs.google.com/presentation/d/1yw2q1Iy1bX8fsYK2X0wF-1NzIL5tMxJ11PSFbmpHP8Y/edit#slide=id.g59e9d8d5db_1_49

**Deliverable:**
**Move to Review when:** Released in MARLO Dev
**Move to Closed when:**Released in MARLO Prod

**Comment by anamp07** [comment]
We decided not to develop this: _Make the Finance Code field visible only when a Managing Partner is selected_.

In the new Funding Sources features, the funding source is created after fillings some fields in a pop-up, including the managing partner which is a mandatory field.  

![image.png](https://images.zenhubusercontent.com/5b81b883dc633f0891418b32/aca89222-e9b0-4ad8-a981-281a00874f69)
