### ISSUE TITLE
[KT] (MARLO) Implement funding sources synchronization improvements

### ISSUE THREAD

**Issue by kenjitm** [CCAFS/MARLO#2161]
- [ ] Bring total budget from Agresso and save it in MARLO
- [ ] Avoid having to manually resynchronize funding sources
- [ ] Agresso has a tag where the CRP is indicated, they can be used to detect agreements that have not been created in MARLO
- [ ] Keep Original funder suggestion text visible after saving
- [ ] Synchronize funding source at creation if the agreement is On going.

**Deliverable:**
**Move to Review when:** Released in MARLO Dev
**Move to Closed when:**Released in MARLO Prod

**Comment by MargaritaRamirez** [comment]
we close this issue because @kenjitm  worked on it with another issue
