### ISSUE TITLE
[FE] (CCAFS) Support Packs

### ISSUE THREAD

**Issue by MargaritaRamirez** [CCAFS/MARLO#2170]
We are trying to integrate and create one architecture and the way to proceed to upload and update documents with both DMSP and MEL support pack
[Roadmap](https://docs.google.com/presentation/d/1EGCj2C_MiMBLv1aqgg0Ogxrq1AK7ftm4cXw54W45h2g/edit#slide=id.p) 
[Technical docs](https://docs.google.com/document/d/1RZlPC9Noff0eJtQ3GQxnjulYUThtT6F0Uil0Cg1KCa0/edit?usp=sharing) 

- [x] Continue the process that Luis Benavides begun 
- [x] Understand the code
- [x] Coordinate with Paola Cruz and export all the information that we have DMSP so she can review the information and help us with test

We close the ticket #2243 
**Deliverable:**
- [x] Resources excel file

- [x] Login module
- [ ] Upload resources module
- [x] Technical documentation

**Move to Review when:** 
**Move to Closed when:**

**Comment by felipelvira** [comment]
** UPDATES **

- Technical documentation. ([here](https://docs.google.com/document/d/1RZlPC9Noff0eJtQ3GQxnjulYUThtT6F0Uil0Cg1KCa0/edit#heading=h.7cch03h02r21))
