### ISSUE TITLE
Improve Error Pages

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#218]
- [x] NOT LOGGED = 401
- [x] NOT AUTHORIZED = 403
- [x] NOT FOUND = 404
- [x] ERROR = 500

**Comment by htobon** [comment]
@carios1usb, do not forget to update this issue.

**Comment by carios1usb** [comment]
![Capture.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture-952d7ba6fe5fa32dfcb4ab5c300e78f5accfae8e0efaa4b54b72636ab4d5b2c4.JPG)

**Comment by carios1usb** [comment]
![Capture2.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture2-fb6669b10adebc1513c9144214b313a15f7cae13d614b831414375563b9f5f1a.JPG)

**Comment by carios1usb** [comment]
![Capture3.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture3-e59f940c4e8c7f19515dee647d43dbfb4ef77f5f0c6f1dfe8fc1055ae10f66f9.JPG)
