### ISSUE TITLE
[CC] (MARLO-BI) Funding Sources Dashboard Mockup

### ISSUE THREAD

**Issue by ccastiblanco** [CCAFS/MARLO#2186]
Create a dashboard mockup for Funding Sources Module, based in existing reports

- [x] Reports
- [x] Create graphics in Power BI Desktop
- [x] Publish Mockup

**Deliverable:** Funding Sources Mockup presented to Hector Tobón
**Move to Review when:** Mockup created
**Move to Closed when:** Mockup validated

**Comment by ccastiblancoCGIAR** [comment]
Mockup validated by Hector. 
Close this issue, open a new one to create the data structure required.
