### ISSUE TITLE
[CC] (MARLO-BI) MARLO BI Presentation (Google Slides)

### ISSUE THREAD

**Issue by ccastiblanco** [CCAFS/MARLO#2187]
Create a Google Slides presentation for the BI Module in Marlo, explaining Power BI characteristics embedded in Projects, Milestones and Deliverables dashboards.

- [x] Define the global structure
- [x] Create Presentation

**Deliverable:** Google Slides Presentation
**Move to Review when:** Presentation finished and sent to Hector
**Move to Closed when:** Hector Validation and adjustments done

**Comment by ccastiblancoCGIAR** [comment]
Estructura inicial:

- Explicación del módulo. Para que sirve un módulo de BI (Que se va a mostrar)
- le brindan la capacidad de recolectar, organizar y. analizar rápidamente sus datos
- Ver informacion agrupada por diferentes filtros que te van a permitir ver de manera general el contenido en MARLO
- Primera version de BI es solo lectura. 
- Instrucciones de como llegar al módulo desde marlo
- Explicación del menú de Dashboards, Full screen y hojas de los dashboards
- Explicación de los 3 Dashboards actuales
- Explicación de funcionalidad de Power BI
- Filtros en la parte superior
- Filtros en cada gráfica que impactan a las demás gráficas
- Filtros de opción múltiple: con control para seleccionar varias
- Pantalla total -- esc para salir
- Drill Down para la grafica de milestones vs project contribution
- Drill thru para milestones data ----- projects
- Link para el reporte de projects
- Pop up para el detalle del project
- Buscar por título
- Exportar data desde las tablas. (sumarized or Underlying)

**Comment by ccastiblancoCGIAR** [comment]
Reunión el jueves 5 de noviembre con HT, MR y MA.
Adición a la estructura inicial:

- Objetivo del BI Advisory Group y de las reuniones con ellos.
- 
- Explicar un poco la arquitectura (quizás incluir un diagrama). Por ejemplo, decir que existen unos procesos de transformación de datos (ETLs) y que se actualizan cada cierto tiempo, en qué tecnología está hecho, quienes pueden acceder, qué tipo de especificidades se pueden realizar entre los CRPs, etc.
- 
- Incluir el Roadmap para revisión con el Advisory Group

**Comment by ccastiblancoCGIAR** [comment]
Reunión el martes 10 de nov con MR y MA.
Revisión de la Presentación, modificaciones realizadas sobre algunos slides para mejorar el entendimiento

Pendiente: Revisión de Roadmap con @mralmanzar

**Comment by ccastiblancoCGIAR** [comment]
Presentation was finished and presented in the BI Advisory Group Meeting on 19/nov/2020
Link to the presentation:

https://cgiar.sharepoint.com/:p:/r/sites/CCAFS-KDS/_layouts/15/Doc.aspx?sourcedoc=%7BC9C3BF09-7789-43BF-A31C-AE00F820092E%7D&file=MarloBImodule_20201105_CC_MA_MR.pptx&action=edit&mobileredirect=true
