### ISSUE TITLE
Implement Hibernate Data pool .

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#219]

**Comment by htobon** [comment]
Library C3P0

**Comment by cgarcia9106** [comment]
we implement pool on mysql server

**Comment by cgarcia9106** [comment]
On my sql config file : my.in add these lines:

interactive_timeout = 10
connect_timeout = 10
wait_timeout = 10
max_connections=3000

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-f393399dc0ea4deca389a2d8998ec40e529c122236a532d9d4c5ef0accac0f23.png)

**Comment by htobon** [comment]
The problem persists!
Please work on it the both of you as we need to get this fixed ASAP.

**Comment by HermesJim** [comment]
moving this issue to review so we can test the performance for a while.

**Comment by HermesJim** [comment]
After one week, The database in marlo dev was not down again.

**Comment by htobon** [comment]
Ok @cgarcia9106, well done.
Let's close this issue and if it happens again, we create anotherone.
