### ISSUE TITLE
Users should be able to disable the Autosave.

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#221]
Sometimes these type of users give technical support to the project leaders and they visit the forms. Thus, they should not save any information.

**Comment by HermesJim** [comment]
closed #221 in the commit https://github.com/CCAFS/MARLO/commit/cca64c29fe1b549ac7bb7d5bf1ebefb6bc693eba

**Comment by htobon** [comment]
Screenshot?

**Comment by HermesJim** [comment]
so far disable the autosave will be done in the data base..
I will created the issue to implement the user interface that has a functionality to disable the autosave.
