### ISSUE TITLE
[Button] Discard Autosave changes.

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#222]

**Comment by HermesJim** [comment]
The discard button appears when the form has a draft changes,

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-456171aefb8e1b96ddcdc0e53e7b8375e8892899c3f266fa90c247286d1c39df.png)

**Comment by htobon** [comment]
what about Discard changes?
