### ISSUE TITLE
[KT] (AICCRA) Cluster tags (Management, Flagship, Regional and Country)

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#2238]
In AICCRA, we have 4 types of projects which would be really great we can tag somehow. 
1. Flagship led, 2. Regional led, 3. Country led, 4. PMU led (Cluster Type)

![image](https://user-images.githubusercontent.com/5375915/120511609-2d70b480-c390-11eb-9362-885adfb2da4a.png)

- [x] Database
- [x] Manager
- [x] Migration
- [x] Front end componets

**Comment by htobon** [comment]
You should also include the type as part of the table which shows all clusters.

**Comment by kenjitm** [comment]
![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/98dddd4e-0d06-4d92-bd5f-e6f9289e2961)
<br>
![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/d9564744-9e32-47e1-be47-c298a9962a44)

**Comment by MargaritaRamirez** [comment]
@kenjitm here are the actions points from our meeting: 

- [ ] Remove the PMU tag - Use the management tag
- [ ] Remove the word Project from project tags
- [ ] Use different color for each type of cluster tags
- [ ] If is a research project only 3 options country, regional or flagship and if is management no need to ask for cluster type

**Comment by kenjitm** [comment]
![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/3e66365f-6b75-4961-a079-ccf58db697d4)
<br>
 - Management Cluster
![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/6e59bff6-fff8-4eda-8488-6c695da570a7)

**Comment by MargaritaRamirez** [comment]
@kenjitm thank you for the update of the tags. Just one comment and maybe we can change the grey color of the Flagship tag to a light blue or something different? or maybe its just me :)

**Comment by MargaritaRamirez** [comment]
https://www.screencast.com/t/RkkRWklSKV

**Comment by kenjitm** [comment]
@MargaritaRamirez Done 
![image](https://user-images.githubusercontent.com/17478511/121243677-9c07b380-c863-11eb-889c-c10e9158ca6a.png)

**Comment by MargaritaRamirez** [comment]
@kenjitm looks good to me
@htobon waiting for your comments
