### ISSUE TITLE
[TS] (AICCRA) Connect the dropdown list of the deliverable section of performance indicators with the information that the cluster have in the contribution to performance indicator

### ISSUE THREAD

**Issue by MargaritaRamirez** [CCAFS/MARLO#2245]
Connect the dropdown list of the deliverable section of performance indicators with the information that the cluster has in the contribution to the performance indicator

![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/114fc23a-8548-40e2-a67b-fbbe8d119b9f)
- [x] Show the right list in deliverable section
- [x] Develop save process
- [x] Develop replication process

**Comment by MargaritaRamirez** [comment]
@tonyshikali please update the tasks. Thanks

**Comment by kenjitm** [comment]
@MargaritaRamirez please test the save of performance indicator dropdown selection in deliverables section. Thanks

**Comment by MargaritaRamirez** [comment]
@kenjitm the dropdown list math with the contribution to performance indicator section. 
@tonyshikali remember to update the narrative of the message 
https://www.screencast.com/t/Sb33xxMJbBe

**Comment by MargaritaRamirez** [comment]
@kenjitm is there a way to show the indicators that are mappeded in order?
