### ISSUE TITLE
[KT] (AICCRA) Develop the export in word format of the progress target questions

### ISSUE THREAD

**Issue by MargaritaRamirez** [CCAFS/MARLO#2249]
Develop the export in word format of the progress target questions at the project level we need to collect all the information that the cluster leaders enter in the Progress to Targets questions 

https://www.screencast.com/t/O0N8NE7T

- [x] Add the indicators to the index list
- [x] Develop the option to the summary that contains the information of all clusters
- [x] Order the clusters by type: country, regional, flagship, management
- [x] Order the indicators by: PDO, IPI 1, IPI 2, IPI 3

**Comment by MargaritaRamirez** [comment]
@kenjitm please update the tasks. Thanks

**Comment by kenjitm** [comment]
![image](https://user-images.githubusercontent.com/17478511/122481226-edb2eb00-cf93-11eb-8831-b8b93537a0de.png)

**Comment by kenjitm** [comment]
@MargaritaRamirez The questions and answer format is updated ![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/6a20fa12-8d70-4bcb-919f-9b84549fc916)

**Comment by MargaritaRamirez** [comment]
I added information to clusters 102076, 102080, 102081

![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/31fa4334-9deb-4c6d-ba86-3555091829ac)

**Comment by kenjitm** [comment]
Added the indicators to index list
![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/9dcd6b26-0e3c-4fe6-b587-70f9aaab2d2d)

**Comment by MargaritaRamirez** [comment]
@kenjitm review the order 
The correct one is the following 

![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/e72f814b-0d81-450e-a986-b5670ec9a5ec)
![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/8394d874-3f2e-4bc1-8d29-cd835bb2f8cc)
![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/589aaf83-b808-4650-b053-ec0093b9aa3a)

**Comment by kenjitm** [comment]
The list was ordered

![image](https://user-images.githubusercontent.com/17478511/124924359-ff9b1300-dfc0-11eb-9782-d83a1c9c5787.png)

**Comment by MargaritaRamirez** [comment]
Thank you @kenjitm looks good
