### ISSUE TITLE
[KT] (AICCRA) Update labels

### ISSUE THREAD

**Issue by kenjitm** [CCAFS/MARLO#2262]
- [x] Change the name of Impact pathway section to Overall Performance Indicators
- [x] Change the name of milestones section to Intermediate Targets

**Comment by MargaritaRamirez** [comment]
@kenjitm please update the name 
![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/215fec5d-081e-41bb-a38e-e8c2e86a72c1)

**Comment by kenjitm** [comment]
@MargaritaRamirez The label was updated
![image](https://user-images.githubusercontent.com/17478511/122101051-7fc2c400-cdd9-11eb-96b1-f3d07a83019e.png)

**Comment by MargaritaRamirez** [comment]
@kenjitm thank you i will close the issue
