### ISSUE TITLE
[MR] (AICCRA) Improve narratives in AICCRA sections

### ISSUE THREAD

**Issue by MargaritaRamirez** [CCAFS/MARLO#2264]
Issue description.

- [x] Add the text in the deliverable section "If you want to disseminate your deliverable in a suitable repository, please contact margarita.ramirez@cgiar.org" 
- [x] Improve narratives in activities sections
- [x] Create the narrative for the Summary Progress Report

**Deliverable:**
**Move to Review when:** we have all narratives in place
**Move to Closed when:** Hector's approval

https://www.screencast.com/t/MqubrRAYgOAm
https://www.screencast.com/t/ya3POtpaA

**Comment by MargaritaRamirez** [comment]
![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/08d9ea1a-ea2e-49e5-8f09-e811071ef938)

**Comment by MargaritaRamirez** [comment]
@tonyshikali @kenjitm 
Could someone help me updating this information 
![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/857e4e47-7c97-44ce-bc6e-c2c1733659f7)

Update narrative: 
A cluster should have a set of activities that have been assigned a budget and are related to deliverables that are contributing to performance indicators.

**Comment by MargaritaRamirez** [comment]
@kenjitm or @tonyshikali if someone can help adding this information 

![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/141a0314-9203-4b35-a67b-d8169c9a25f4)

This report pulls out the information given to the different progress questions on each cluster. Also, you can download the consolidated version for all cluster information.

**Comment by kenjitm** [comment]
@MargaritaRamirez This information was updated
![image](https://user-images.githubusercontent.com/17478511/123005405-afdf0980-d37b-11eb-8fe1-7959c156d84a.png)
