### ISSUE TITLE
Make demo for several users working at same time in Outcomes

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#227]

**Comment by htobon** [comment]
Example in the image below:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-0c8ed3e20797225af8bc683af0cbc107ec2b157f86ba8b288d4df0006a46af9c.png)

**Comment by sebas932** [comment]
I made the system for showing to users at the same section a message indicating when someone execute "save" or "autosave".

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-41901d16b916f7cf8811c418ee3cd14342d56a973074e0f1bbc3bb3482f70557.png)

**Comment by htobon** [comment]
@sebas932 Do not forget to move the issues to Review/QA

**Comment by htobon** [comment]
What about the following message?
"This section is currently being modified by **Héctor Tobón**. If you make any modification here you will replace what the other person is doing."

**Comment by sebas932** [comment]
I think it's ok, changed to the new message

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-b82e64025d8e88860dbb45664323cd0d8e9ec5a36021b529238a2fa0e3f09512.png)
