### ISSUE TITLE
[MR] (AICCRA) Management task

### ISSUE THREAD

**Issue by MargaritaRamirez** [CCAFS/MARLO#2271]
Management task pending 

- [x] Ask Tonya the best way to display the information of the indicator guidance https://www.screencast.com/t/UltOiWEA5yS and https://www.screencast.com/t/G1mcqzGNR54
- [x] Ask Leroy how we are using in the alliance (if we are) the information that we have in quality check in MARLO 
Categories: 
Database/Dataset/Data documentation
Thesis
Research workshop report
Policy brief/policy note/briefing paper
Discussion paper/Working paper/White paper
Conference paper / Seminar paper
Lecture/Training Course Material
Guidebook/Handbook/Good Practice Note
User manual/Technical Guide
Outcome case study
Presentation/Poster
Multimedia
Brochure
Outcome note
Factsheet, Project Note
Infographic
Policy workshop/Dialogue report
Funder report
Concept note
Other Capacity

![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/5c5a86f9-0e2e-4393-a3ee-5b9b0f4ec1e1)

**Move to Closed when:**We have both answers

**Comment by MargaritaRamirez** [comment]
I sent the information to Tonya via teams and still not have answer

**Comment by MargaritaRamirez** [comment]
![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/e4a2ec5f-8070-49ff-ad59-1b36137bea8a)

**Comment by MargaritaRamirez** [comment]
@kenji could you please help us make the change that Leroy suggested 

![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/2f982910-567d-4045-88ea-35d8e3a0a151)




Here are the categories that apply
Database/Dataset/Data documentation
Thesis
Research workshop report
Policy brief/policy note/briefing paper
Discussion paper/Working paper/White paper
Conference paper / Seminar paper
Lecture/Training Course Material
Guidebook/Handbook/Good Practice Note
User manual/Technical Guide
Outcome case study
Presentation/Poster
Multimedia
Brochure
Outcome note
Factsheet, Project Note
Infographic
Policy workshop/Dialogue report
Funder report
Concept note
Other Capacity

**Comment by kenjitm** [comment]
This rule just applies for:
- Database/Dataset/Data documentation
- Maps/Geospatial data
The last information is wrong.

**Comment by kenjitm** [comment]
![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/d92784fb-aa99-439d-9c17-303668f021e8)

**Comment by MargaritaRamirez** [comment]
@kenjitm thank you for the clarification of the categories. 
Is working fine

**Comment by kenjitm** [comment]
The development is now in production environment @MargaritaRamirez

**Comment by MargaritaRamirez** [comment]
![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/ea387443-50d8-4cba-a499-5b935dcc8a76)
We uploaded the guidance in the testing environment. I will inform Tonya too.
