### ISSUE TITLE
[VV] (MARLO) Add graphs and rules to the Homepage

### ISSUE THREAD

**Issue by valviveros** [CCAFS/MARLO#2288]
Add graphs and rules to the Homepage.

- [x] Review what kind of Google Charts will be added to the homepage.
- [x] Include the graphs within the tabs for Projects, Deliverables, Studies, Innovations, Policies.
- [x] For Projects, add a graph by Institution or by Flagship, and another showing Open/Closed.
- [x] For Deliverables, add a graph by Status, Type of Deliverable and Open Access or not.
- [x] For Policies, add a graph by Type and by Level.
- [x] For Innovations, add a graph by Type and by Level.
- [x] For Studies, divide tabs between OICRs and MELIAs.
- [x] For OICRs, add a graph by Level and maybe by Contribution to SDGs.
- [x] For MELIAs, add a graph by Type.

**Move to Closed when:** moved to Dev.

**Comment by MargaritaRamirez** [comment]
After discussion with @gcmartinezg for the 3rd point is better to change the graph for the status of the projects 
- ongoing
- extended 
- Complete
Because the close project they have not been part of the information shown in MARLO

**Comment by valviveros** [comment]
Comments from @htobon to develop:

- [ ] Add a toggle to hide/show graphs (the graphs should appear by default).
