### ISSUE TITLE
[KT] (AICCRA) Cluster reports review

### ISSUE THREAD

**Issue by kenjitm** [CCAFS/MARLO#2289]
- [x] Review reports
- [x] Check comments
- [x] Check the information in AICCRA
- [x] Update the information in AICCRA

**Comment by MargaritaRamirez** [comment]
We create a spreadsheet where we can follow up those comments that are still pending 
https://docs.google.com/spreadsheets/d/1wHvo5knWZG4LmksIkmDMhN97wSyUMecU9qbJoW9YWsY/edit#gid=0

![image](https://user-images.githubusercontent.com/47789853/129359283-a42f0606-1924-4493-8efd-fba278f138d5.png)
