### ISSUE TITLE
Add Chekstyle Rules

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#23]

**Comment by htobon** [comment]
@HermesJim, where did you included these rules?

**Comment by htobon** [comment]
@HermesJim, could you kindly anwer my question above?

**Comment by HermesJim** [comment]
@htobon .. Jeje sorry.
Chekstyle is a maven plugin put in the principal pom.xml file (https://github.com/CCAFS/MARLO/blob/master/pom.xml , line 104). This plugin execute the checkstyle rules  from the marlo_checkstyle.xml file (https://github.com/CCAFS/MARLO/blob/master/configuration/marlo-checkstyle.xml).

I apply the Java Checkstyle rules by Sun, see the next url to view all the rules availables to configure. 

http://checkstyle.sourceforge.net/checks.html
