### ISSUE TITLE
[TS] (AICCRA) Fix download PDFs link in Overall Performance Indicators and Contributions to Performance indicators

### ISSUE THREAD

**Issue by kenjitm** [CCAFS/MARLO#2303]
In _Overall Performance Indicator_ Section, the user can add a PDF in _Progress to Targets Indicator_ Tab

![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/4988ac07-1ad2-429f-9a34-d9437f16d6db)

This PDF is visible and available for download in _Contribution to Performance Indicators_ at Cluster Lever
![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/a9e190f1-537f-4c33-b1ab-537fb7d31b1f)

Currently, the document is stored in the path _marlofiles/AICCRA/projects/_ (path defined in the files _marlo-dev.properties_ and _marlo-prod.properties_ on the test and production server respectively).

However, the file cannot be accessed, when generating the url for downloading it, it appears to be invalid.

**Comment by kenjitm** [comment]
The downloads links are working now in AICCRA dev:
![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/32aea659-c3d2-4008-9e03-062da839f229)

![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/22d3b4f3-fddc-4559-9e42-0f84aa4d9147)

**Comment by MargaritaRamirez** [comment]
Tested from Overall performance Indicator and is working fine.

**Comment by MargaritaRamirez** [comment]
Tested from Contribution to performance indicator section and is working fine

**Comment by MargaritaRamirez** [comment]
test the functionality in prod and is working fine
