### ISSUE TITLE
[GM] (MARLO) Add new deliverable status

### ISSUE THREAD

**Issue by gcmartinezg** [CCAFS/MARLO#2316]
Emma Greatix proposed the creation of a new status for deliverables (Partially Complete), for CRPs/Platforms to be able to identify deliverables that could not be completed on time. This status would replace in AR2021 the "Extended" status, as deliverables must not be extended into 2022.

**Move to Review when:** The status is on DEV

**Comment by MargaritaRamirez** [comment]
![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/d5a4098c-241e-45ff-b8b3-c6dde3e38ad3)

**Comment by htobon** [comment]
@MargaritaRamirez and @gcmartinezg I just had a brief call with Pascale in the morning of where we discussed more in detail about this development. Therefore, the idea would be the following:
- [ ] For this last reporting period, we should take out the statuses "on-going" and "extended". 
The rationale is that we should not have deliverables to be expected to be finalized in 2022. 
Thus, deliverables that will be reported this time should be:
a. "ready to be reported on" (which means the expected year is 2021); 
b. "complete" (the deliverable is fully completed with metadata information);
c.  "canceled" (the deliverable could not be finalized and a justification is provided)

- [ ] Please also add the new status category named "Partially complete" and the rules would be:
  - [ ] a justification must be provided obligatory 
  - [ ] make sure the justification is part of the reports in the summary section
  - [ ] the dissemination and metadata section is optional
  - [ ] these deliverables will not be part of the synthesis section (e.g. table 6)

**Comment by gcmartinezg** [comment]
@MargaritaRamirez @htobon The list of issues raised has been solved. This can be checked on DEV.

**Comment by gcmartinezg** [comment]
The functionality has been released in PROD. There were more issues after a revision. They were registered in #2358
