### ISSUE TITLE
[GM] (MARLO) Change logic on indicator load for Table 2, 3 and 4

### ISSUE THREAD

**Issue by gcmartinezg** [CCAFS/MARLO#2323]
We need to change the logic of Tables 2, 3, and 4 back as it used to be: when they are first loaded, all indicators should not be selected by default but the user has to choose them manually.

**Move to Review when:** The functionality is in Dev

**Comment by htobon** [comment]
@gcmartinezg and @yeyo2k3 
Can you please instead, rename this issue to be like "Develop the possibility for CRPs to manually submit individual items (OICRs, Innovations, Policies, Publications, etc.)". Plus, can you please include the screenshot of the mockup description of the issue? Thankyou.

**Comment by gcmartinezg** [comment]
@htobon the issue you are referring to is #2344. This issue has been finished and is already in PROD.
