### ISSUE TITLE
[KT] (AICCRA) Make the Progress to Targets questions uniques per phase

### ISSUE THREAD

**Issue by kenjitm** [CCAFS/MARLO#2328]
Make the progress to targes indicators (questions) uniques per phase
![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/3240bd60-deb9-40cc-be93-4f1d84c4de7c)
- [x] Save the information of the questions and their answers by phase

**Comment by MargaritaRamirez** [comment]
working fine and I tested in AR2021 with IPI 1.1
