### ISSUE TITLE
[KT] (AICCRA) Enable Overall Performance Indicator section for AR Phase

### ISSUE THREAD

**Issue by kenjitm** [CCAFS/MARLO#2335]
Currently, Overall Performance Indicator is in reading mode for the reporting phase in AICCRA, which does not allow modifications (if the role allows it) in this section.

![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/82961597-7eed-47a4-b7d6-ca7ea2ce4a0f)

- [x] Make editable for AR phase
- [x] Show save button

**Comment by kenjitm** [comment]
The Overall Performance Indicators section is editable for AR phase
![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/2db121d3-d638-4c30-b61c-e02171bfab03)

**Comment by MargaritaRamirez** [comment]
We can edit the information in the overall performance indicator tab in the AR2021 phase

**Comment by MargaritaRamirez** [comment]
@htobon could you please make some tests for this too?

**Comment by MargaritaRamirez** [comment]
We tested and is working fine
