### ISSUE TITLE
Improve mockup for Project Location

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#234]

**Comment by sebas932** [comment]
What do you think @htobon ?

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-e349b0373f726a1656de6efe8a4ad845de6ed0174aecbc0ef661f63a15b85b0b.png)

**Comment by htobon** [comment]
The mockup is good enough for now but possibly revisited later.
@HermesJim, @cgarcia9106, @sebas932 and @carios1usb please keep in mind that.
