### ISSUE TITLE
[KT] (AICCRA) Remove the LP6 section in AR2021

### ISSUE THREAD

**Issue by MargaritaRamirez** [CCAFS/MARLO#2347]
This is not part of the AICCRA project, please remove the section

![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/acb1bb15-2fc8-44a7-b086-a5ea98aaf84c)

**Comment by kenjitm** [comment]
Specificity for AICCRA disabled in test and production environments
