### ISSUE TITLE
[KT] (AICCRA) Create AICCRA Capacity Development Mockup

### ISSUE THREAD

**Issue by kenjitm** [CCAFS/MARLO#2349]
The template is located at: 
https://docs.google.com/presentation/d/1aUX_WJ99Rm-a4YsG-xgrx84W3aXyQlPK_KiswTljwcQ/edit#slide=id.ge82d74f50f_0_5

![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/a54ab50a-9bca-4962-b154-30842260967e)

**Comment by MargaritaRamirez** [comment]
After meeting with Sophia we will proceed in MARLO
