### ISSUE TITLE
Improve mockup for Project Partners

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#235]
- Collapsable information
- Allow the posibility to manually order the list

**Comment by sebas932** [comment]
Done
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-0cfee10b160004eb94b12d7d0e8cfc018659c199a9554429a71f1f471312477f.png)

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-081a5728f8891f49179638a3051f97eb5c59b742e8c2bdb5a7618e01723ca99e.png)
