### ISSUE TITLE
(Initiatives) Review and create partners request for the Initiatives

### ISSUE THREAD

**Issue by MargaritaRamirez** [CCAFS/MARLO#2354]
Validate the list of pending partners to map for the Initiatives that Allison share with us in the following link
https://docs.google.com/spreadsheets/d/1n3F4_j6cXlC7rEPr2edGOTXPCOCiYnQnYGtlEOamd3c/edit#gid=2052043601  

- [x] Validate the partners information
- [x] In case they exist in MARLO relate the ID if not, make the request
- [x] After creating the partners add the ID 

**Move to Closed when:** Finish the task

**Comment by MargaritaRamirez** [comment]
Please note that the followings partners need to be check and understand if we need to create them in MARLO or not 
![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/22c9271c-28f1-43ce-aa69-4dcd18490b36)

**Comment by ccastiblancoCGIAR** [comment]
The rows with yellow color are pending. The institutions need to be reviewed by Allison.

![image](https://user-images.githubusercontent.com/74072431/132687168-9d821c3e-8ace-4de5-80ff-333231b661b8.png)

**Comment by mralmanzar** [comment]
I had review 40 partners.
9 partners were not approved due to the few information found on the internet
