### ISSUE TITLE
[KT] (AICCRA) Add new deliverable sub-category

### ISSUE THREAD

**Issue by kenjitm** [CCAFS/MARLO#2366]
Add new AICCRA deliverable sub-category: "Capacity Development Event" for Training Materials

![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/9e81e274-4fd3-4eb7-adb0-7a5655698edb)

- [x] Create Migration
- [x] Check drop-down list and deliverable list type field for new element

**Comment by kenjitm** [comment]
The new deliverable sub-category was added
![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/92828153-0d9f-411e-9acd-9d78c7077658)
<br>
![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/cd030f5c-71e9-479d-90e1-c45597de5d5e)

**Comment by MargaritaRamirez** [comment]
is working for old deliverables and new deliverables
