### ISSUE TITLE
Share demo with the "MARLO Family" to get feedback on CRP Admin and Impact Pathway

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#237]

**Comment by htobon** [comment]
An email with the instructions on how and what to test was sent some minutes ago.
Let's wait until we receive their feedback.

**Comment by htobon** [comment]
This was succesfuully done.
We received feedback from Amanda. The rest of the team is busy but will make the feedback on early August.
I'll close this issue and will be pending on the feedback template we shared.
