### ISSUE TITLE
[KT] (AICCRA) Define and code rules for Deliverable Capacity Development Event Sub-Category

### ISSUE THREAD

**Issue by kenjitm** [CCAFS/MARLO#2373]
Define and code back-end and front-end validations for new deliverable sub-category element.
![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/3be3fd0f-4f15-4b85-bd6f-0f397ccc55c5)

See slide 3: https://docs.google.com/presentation/d/1aUX_WJ99Rm-a4YsG-xgrx84W3aXyQlPK_KiswTljwcQ/edit#slide=id.gee5f6a7c7e_0_23

- [x] Adjust validators for mandatory fields
- [ ] Show front end notifications for missing fields when its selected the new deliverable sub-category

**Comment by MargaritaRamirez** [comment]
chack the validation rules
Add two rules: 
- [ ] add the * mandatory for "Does this deliverable involve Participants and Trainees?" 
- [ ] not answer "No" by default
