### ISSUE TITLE
Sub-IDOs graph - fix text

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#240]
Please fix the text according to the following image:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-946323db82acbd470279239bb0192694d2bf9cae145bd1378323b50511b9d855.png)

**Comment by htobon** [comment]
May you please attach an screenshot?

**Comment by carios1usb** [comment]
![Capture.PNG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture-280c8cf35aa5273382229b993d17fceaeb301decbf6d0e2d5c6b528c26875f79.PNG)
