### ISSUE TITLE
Favicon for MARLO

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#243]
The current Favicon we are using is the one from CCAFS.
However, MARLO belongs to the 4 integrative CRPs.

May we have a custom favicon for MARLO?

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-1d081d40976352202b36def3c2ce9d27f05787c7e02bc18b6ba45cf00f108fc6.png)

**Comment by htobon** [comment]
@carios1usb: Why is this issue in Review?

**Comment by carios1usb** [comment]
![MARLO_favicon.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/MARLO_favicon-775079bdba02a38c732e15468a39b14eb53c1e6b9e73148758652370f49f07dd.png)

**Comment by carios1usb** [comment]
![MARLO_favicon1.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/MARLO_favicon1-b59904dcb24de4a795db434f521cd3c80d4f2a8444bbddb66353b2f21b7c0ebb.png)

**Comment by carios1usb** [comment]
![MARLO_favicon2.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/MARLO_favicon2-ec1e5218c41d792fabd4b96386a02b06f58c9f043e7aa67d6f74b3530cf9beb2.png)

**Comment by carios1usb** [comment]
![MARLO_favicon3.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/MARLO_favicon3-fc65d68dc6e21b341fd0e7687b6d46b58f2f28632a64b9cca50331433bd08ce0.png)

**Comment by carios1usb** [comment]
![MARLO_favicon4.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/MARLO_favicon4-e7064412e3765b7cfc1e5dbeb85365a1caec8f4d809a60fd1002f356474e5c22.png)

**Comment by htobon** [comment]
Option 5:
<TBD>

**Comment by htobon** [comment]
So far, we chose the Option 1.

**Comment by carios1usb** [comment]
![Capture.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture-bb186a7937f269632242975a0b58256ad061ab96a44740e8d32e8a387e586c7f.JPG)
