### ISSUE TITLE
Document Pusher Service

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#244]

**Comment by sebas932** [comment]
I made this basic documentation according to the already developed.

https://docs.google.com/a/cgxchange.org/presentation/d/1Krh5Yoxcm_wWIjzXnuCdhp60lm7rG7i9YiwUdENQNH4/edit?usp=sharing

**Comment by htobon** [comment]
I made a quick review but I think I need to review it in detail.
@sebas932 how would you like to proceed? Close this issue and open a new one for the next sprint? or move this issue to the next one? Please proceed as per your consideration.

**Comment by htobon** [comment]
This issue will be continued in the issue #331 
Thank you @sebas932
