### ISSUE TITLE
Update the license statement into the MARLO intallation manual

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#251]
The idea here is to update the document "How to configure Eclipse STS for P&R" to work with the new improvements we have done to our development environments.

**Comment by htobon** [comment]
Hi Guys, there is someone who has not the correct version of the text and each commit you are making is changing the text.

May you please re-check that you copied the correct version?

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-859c63de01da3439670937d34e7946ca78de5ed3bab5218cbbe76df8c6cd1630.png)

**Comment by HermesJim** [comment]
license text was changed, but looking at the document must make a complete change to have a document Marlo technical installation.

The technical document is created in the folder marlo / technical /MARLO - Development installation.
