### ISSUE TITLE
To adapt and develop Project list interface

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#255]

**Comment by sebas932** [comment]
Issue finished, Still pending to define project columns like "Budget" & "Submission"

**Comment by htobon** [comment]
@sebas932 may you kindly attach an screenshot?
Once you finish it please mark the issue as closed again.
Thank you in advance

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-af58e7274a25b699f9bfc903f94cad85185394b3787471f44f2fee6c8b5d1538.png)
