### ISSUE TITLE
To adapt and develop Project Description interface

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#257]

**Comment by sebas932** [comment]
Finished project basic information

**Comment by htobon** [comment]
@sebas932 may you kindly attach an screesnhot?
Once you do it, please close the issue again.
Thank you in advance.

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-bec3120a5bf9ee585003ccac301a4050ceedcbe0e2a8b62db9e1b79cdae311e5.png)
