### ISSUE TITLE
Improve mockup interfaces for Deliverables

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#258]
The idea here would be to improve the mockup for deliverables based on lessons learnt from the previous reporting cycle; to make a proposal and discuss with David (if possible, as he is on holidays).

**Comment by pacamargo** [comment]
I made some changes and modifications to the deliverables section, please check it out: https://docs.google.com/presentation/d/1EpoKyy_t_JEgu1a5sXsIgmuOWYILRueMAVFjuKawFAQ/edit#slide=id.g1330bf09ec_1_116

**Comment by htobon** [comment]
Will do. thks!
