### ISSUE TITLE
Popup - Search User - Clarify where the list of users come from

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#259]
Tonya's feedback:
> When I search for a person – where does this draw from – outlook?  Or a PIM CCAFS internal data base?

@sebas932 and @carios1usb, perhaps a good idea would be to include a clarification message explaining where this list came from.

**Comment by sebas932** [comment]
@htobon, what do you think ? if its ok, please close the issue.
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-ad50387ca085db40e39d748a6cef366f651dfa7c9163a1c804174baa1f1d99a9.png)

**Comment by htobon** [comment]
Instead of "Search people from MARLO Database", please change it to:
"Search person from our internal database"

The other message could reads as:
"Add new user"

**Comment by htobon** [comment]
Moving  this issue to "In progress" as I already reviewed.

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-9a4ab4660ca4e1cd1c29bd4a4cb9dbbeecff0259e290c698333a0481026d9744.png)

**Comment by htobon** [comment]
Great, thank you. :+1:
