### ISSUE TITLE
Change flagship names

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#260]
Tonya's feedback: 
>The box ‘program name’ is confusing – not sure if we have ‘flagship abbreviation’ – which we what we actually want here.  Or is what we want in there FP1, F1? – need to be more specific there.

Therefore, @sebas932 and @camilor67, instead of "Program Name", would you please change it to "Flagship abbreviation" and also include another one in the other field titled as "Flagship name"?

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-5527cb805f2f81eb5e576e263f1796778d93234e40c11da18821441215c34b8c.png)

**Comment by sebas932** [comment]
May she didn't see the placeholders "Acronym", "Flagship Name", changes was executed, look de screenshot below, if its ok please close this issue...

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-e1df33d3d7b8732a874a5567208a0896620916a09f32d6566626fa69da5afe72.png)

**Comment by sebas932** [comment]
Done
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-31eb6e7e892ecf55dfd1a51b327de091719f5cec023d390c441c044e6b73b70d.png)

**Comment by htobon** [comment]
Opened by mistake. Will close it again.
