### ISSUE TITLE
CRP Admin: Main menu location from Site Integration and message disclaimer

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#262]
Tonya's feedback:
> Site Integration should come right after regional mapping, I think it currently does not say anything and we might want to put a disclaimer in there that this is provisional for it to be available when there are more details defined. 

@sebas932 and @carios1usb: Please move Site-Integration after Regional Mapping and also include the following disclaimer message in the top of the interface that reads the following:
"This section is provisional for it to be available when there are more details defined"

**Comment by carios1usb** [comment]
![Capture.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture-bbd468c457510b7ae91cb4f29ce698348d76ead90cc6185417e0ae92c5ac8107.JPG)
