### ISSUE TITLE
CRP Admin: Improve section "Locations"

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#263]
After receiving a feedback from Tonya's, I figured out we could improve a little bit this section.

Feedback:
>Location page still looks very different from what we had in the mock up, not sure why? As it is it is not intuitive what needs to be entered.

**Action Points:**
- [x] Display the common location levels that are managing the system for all CRPs. Please refer to the screenshot No. 1 below.
- [x] May we improve a little bit the popup that is displayed when you hit "NO" to the predefined list question? Please refer to the screenshot No. 3. It doesn't say anything, perhaps we should explain why the system is worried about that decision? 
- [x] In addition with the previous issue, the popup should not be displayed if the person has not added any location.

**Screenshot No. 1:**
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-a13cc321fe78b35e2c9f3e9cadc4b45dee47e8b01c051c65d3e7f0f70676d9e9.png)

**Screenshot No. 2:**
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-b4a401033d651c0a8e65ea25c81d8075fc587051298e2f6db1d14e588afc5784.png)

**Screenshot No. 3:**
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-500bcdf3a4c0f27963b8a12046bfe15f492c7bc89e77d17db81e8e2def651628.png)

**Comment by sebas932** [comment]
Displayed default locations levels
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-6e2b5c935f5f1e5f778b19b04f79e933e0098836407db01e5eaea3803124c687.png)

**Comment by htobon** [comment]
:+1:

**Comment by sebas932** [comment]
@htobon   look the message below about the third point 

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-a85577142d7316c25303fffed98e2a1dc040463210cb4d7bdf1a5a864aaafcf0.png)

**Comment by htobon** [comment]
"...**24 locations** will be removed **from** the system"

**Comment by htobon** [comment]
what would happen if there are projects associated to those locations?

**Comment by HermesJim** [comment]
not so much on locations, but on all elements that created in CRP admin.

**Comment by sebas932** [comment]
I think, relations between locElements and projects will be removed with previous validation of the system

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-5d3edc7ce4a220332d08f8fa86c87f8e2a97777b242f4bbd62acff15ddccb54c.png)

**Comment by sebas932** [comment]
Second action point was created into another issue with priority medium. Issue #268
