### ISSUE TITLE
Impact Pathway: Display forms when there are nothing added yet

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#264]
Tonya's feedback:
> Would be good if I did not have to click on adding the first one but have the boxes right there up front for:
- Outcomes
- Clusters of Activities
- Sub-IDO

**Action Point:** @sebas932 and @carios1usb, if the section is empty, please display the form so they know what needs to be filled. 

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-f41af61c89a1cc7e360ed8c3d9a38d2051f0a8da44ac592b6d1f3bc304572dea.png)

**Comment by htobon** [comment]
Hi @sebas932, may I check this functionality?

**Comment by htobon** [comment]
@sebas932 may you please provide me a link where I can test it?

**Comment by sebas932** [comment]
Can we close this issue @htobon ?

**Comment by htobon** [comment]
Yes. thank you for following up.
