### ISSUE TITLE
Invalid email and/or password message resets the interface

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#272]
When an user writes an invalid credentials, the CRP got unchecked and he has to write again all the information, which is frustrating.

The idea would be that the selection of the CRP and the user/email keep in the interface.

See screenshot:
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-4a21479d3492ed7ec7c585cd26fc89c4976c3a4cf1c33166ff19b2c3e5aef71c.png)

**Comment by htobon** [comment]
@carios1usb, Screenshot?

**Comment by carios1usb** [comment]
![1.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/1-4b5e401075ed50fe5e3b9b8c7abdd27456f56c62ae28797ba3a549769e22baf3.JPG)

**Comment by carios1usb** [comment]
The page reloads, keeping user data

**Comment by carios1usb** [comment]
![2.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/2-7ccd46a37235bc72cc589a2b60e62c96507426aa29fcc1854aaf2f11879d4ea3.JPG)

**Comment by htobon** [comment]
Sorry.. I hadn't seen the last screeshot. This is fine.
