### ISSUE TITLE
Main menu: change CRP Admin link

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#273]
Instead of "CCAFS Admin", please just write Admin.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-91a0bbe6e7ab63b237743cf64facc87ead8fd45a16461bc3dc420b999b0b8e88.png)

**Comment by carios1usb** [comment]
![Capture.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture-5cd2965fedb8b25e41b159633bbc1292cb01db6d414c94516d76b99ec3123830.JPG)
