### ISSUE TITLE
CRP Admin: It is not clear what to do in Locations

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#274]
Please write the following message as help text for the section:

**"Please enter here any CRP specific sites, basins or geographic locations you want projects to be able to select from"**

In addition, please update the mockup to reflect what we have in MARLODEV.

**Comment by sebas932** [comment]
Done and updated the mockup.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-6f9ad2f5804280a5f202750bb1fb17685def76f5182f1ebfc40b1241a7c64889.png)
