### ISSUE TITLE
Impact Pathway: Target units - Users should be able to define new units.

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#275]
Since not all the target units will be defined when Flagship Leaders start the process of entering their impact patways, we should provide a way where they can enter units that are not into the pre-defined list.

Perhaps an idea wold be to include another option that reads as "Other (please define)" and if that option is selected, a field would be prompted where the user **MUST** have to provide the new unit.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-199b5ffe55fcaef3210802209e5d608d9e75e3662163d0faad20ea29e0525dff.png)

**Comment by htobon** [comment]
Guys (@sebas932, @cgarcia9106, @carios1usb, @HermesJim):
May you please focus on this issue please?
Thank you.

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-9052e598c353842f61995e62ca92cca9335aa0475fab1297ba30e6259f563f09.png)

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-da1b9eb6011f8b776a30a49139ccb03d3a219df5b8c8a146a44c171ff44694a7.png)

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-09d413711c29eebd098b166362662018a071d719f19da3f18264db8d693b93cf.png)

**Comment by sebas932** [comment]
Changed text message according to @htobon comment.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-b9b9841be5420c83c33ea34c45569bc272fdffa4159fb742bd0091b928622795.png)

**Comment by htobon** [comment]
May I test it?

**Comment by htobon** [comment]
I tested it and made some comments. Basically the most critical ones are:
- [ ] Avoid duplicates
- [ ] Avoid empty text
- [ ] Clear field when new target is added
