### ISSUE TITLE
Login Interface: Improve usability as it is not clear that a CRP needs to be selected

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#278]
**Feedback from Amanda Wyatt:**
> It was not obvious (to me) that I had to click on my CRP logo first. I kept clicking log-in before I tried something else

**Comment by sebas932** [comment]
I made some changes for improving the usability of login section.

- Change main menu "login" to "home"
- Change label "Select a CRP" to "Please select a CRP to login" and more relevant.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-7ab77651f6f518e4f86cd7224d1e020582f454706c027087cb95c34cf820eb4f.png)

**Comment by htobon** [comment]
Can we make it a little bit more obvious? Like adding an animation or something that we guide their eyes to the right side?

**Comment by sebas932** [comment]
Added an animation
![login-animation.gif](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/login-animation-e3e57db17f40ef141c51451462a8e21fd3df614ed7d1bdfc974789d5240cd594.gif)
