### ISSUE TITLE
Develpo MARLO IDOs & Cross-cutting IDOs interface

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#284]

**Comment by sebas932** [comment]
I made a basic interface showing the current data, still pending some details and save

![Animation.gif](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Animation-5967568160f9f8bca4f90307b76ad7f908c3723d34bf7f91fea855f010acc5fc.gif)

**Comment by htobon** [comment]
Still in progress
