### ISSUE TITLE
Create MARLO - Development instalation document

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#285]
The document was created in this path : 

MARLO/technical/MARLO - Development instalation

https://docs.google.com/document/d/1f1YsBcB-x6VY5Keil23VoNwlMyBK2nbF_W0_12TPol4/edit

**Comment by cgarcia9106** [comment]
Andres Valencia

**Comment by AndresFVR** [comment]
@htobon I modified the document https://docs.google.com/document/d/1f1YsBcB-x6VY5Keil23VoNwlMyBK2nbF_W0_12TPol4/edit#

**Comment by htobon** [comment]
Thank you @AndresFVR. 
As per our discussion, please apply the suggested changes and move this coard to complete.
