### ISSUE TITLE
Improve Footer Design.

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#288]

**Comment by htobon** [comment]
Please add the labels for this issue.

**Comment by carios1usb** [comment]
![f1.jpg](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/f1-f7f2db50195f2d5f5023f9eb4b09326e7459c74100b6e5e3c0c8841e06685390.jpg)

**Comment by carios1usb** [comment]
![f2.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/f2-b4a2db429e32f27b90ebbc282ef0f97e8dedd74d19887a5025d46244083da787.JPG)

**Comment by carios1usb** [comment]
![f3.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/f3-c5bbd7412e8b83279deee126c9b18f71f8b9d081c0cd8df064a4c38c2c27cec4.JPG)

**Comment by carios1usb** [comment]
![f4.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/f4-9d3d97549c6db480d1038c3d59d395a535556daf99a8e90b7d630d46afb45033.JPG)

**Comment by htobon** [comment]
Hi @carios1usb, please use some of the options above and move this issue as finished. If someone is not agree, we could re-open the issue and show the other options. Thank you in advance.

**Comment by carios1usb** [comment]
Ok @htobon

**Comment by carios1usb** [comment]
![Capture.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture-2770c0b22c3ef2958b3a22e5d34160fadabef7ebc0d98d659e94ced995457a26.JPG)
