### ISSUE TITLE
Improve project menu design interface

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#297]

**Comment by sebas932** [comment]
Improved interface adding some features like, project type below "Project Menu", inputs files component improved and added a color in the menu that represent the CRP Program of the project .

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-bdf0efd08b5af08d080125d5e08aeb858a68fc5077b5ba95edc82e65383e300d.png)

**Comment by htobon** [comment]
@sebas932 perhaps a good idea would be to improve the title of this issue and then close it. Because I noted that Project Descripton is not finished yet.
