### ISSUE TITLE
Improve User management popup

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#301]

**Comment by sebas932** [comment]
Revamped user management popup, @htobon what do you think ? if its ok, please close this issue.

![Animation.gif](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Animation-ab68e0eda9f9938d4d9c050d06b8ed623761edfe81c46042315c3bf7fd5eec96.gif)

**Comment by htobon** [comment]
great job guys!
