### ISSUE TITLE
Project location interface

### ISSUE THREAD

**Issue by carios1usb** [CCAFS/MARLO#302]

**Comment by htobon** [comment]
Project Location changed based on a new discussion with Tonya and David, therefore this issue, together with everything related to project location, will be worked in the next sprint.

**Comment by carios1usb** [comment]
![Capture.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture-7eb813c0b5196271445208758c2cefd9c52e33a730301fe9d600f9ec0c901395.JPG)
