### ISSUE TITLE
CGIAR Active Directory Library can not get the authentication messages.

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#315]

**Comment by HermesJim** [comment]
I talked by telephone with Jose Libardo discussing the issue in the Active Directory Library. He understood that the logic is failing and promised to fix it for Thursday August 4, 2016.

**Comment by htobon** [comment]
We made a follow up with him as we are still waiting for having the new version fixed.

**Comment by htobon** [comment]
A new follow up has been made. This time I copied David and Maria del Pilar.

**Comment by HermesJim** [comment]
I've upgrade the new CGIAR Active Directory Library, i test block my CGIAR user and MARLO get the correct message.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-a45c19ac297a47aa676ed223de7ddfc95cadc29d6482c19c718951be55a59ae8.png)
