### ISSUE TITLE
Improving Tawkto Position

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#324]

**Comment by sebas932** [comment]
I made some changes creating a custom Tawkto button

![Animation.gif](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Animation-0ddb4b92d8a1b8a0a2b6954f60c6c5cb3e0c6ac8909bd3dfd4203bc616c1736b.gif)

**Comment by htobon** [comment]
@sebas932, it didn't work on small screens. Let's discuss further.

**Comment by sebas932** [comment]
@htobon i didn't understand your comment

**Comment by sebas932** [comment]
The icon was moved to the left side .
