### ISSUE TITLE
Implement Project Location Country List Service.

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#325]

**Comment by htobon** [comment]
This issue still remains and should be made on this sprint. Why is it pending to be Reviewed?

**Comment by HermesJim** [comment]
i was moved today all the project location issues to Review , to move it in the next sprint.

**Comment by HermesJim** [comment]
The Service charge the list of the locElements that belong an specific locElementType (Ex: country, Province..)

**Comment by HermesJim** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-9a18e9294f8aa1f82c10aba0f9b351bc561e21e7008ee2bccd058289896d9312.png)
