### ISSUE TITLE
Review and improve technical documentation and include it in Github

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#331]
- [x] Pusher
- [x] History of changes
- [x] Auto-save

And more....

**Comment by AndresFVR** [comment]
@htobon This is the proposal for wiki changelogs and the Table of Contents Sidebar![Capture.PNG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture-6c1ef8c4f538f430d4be3f52b046f4576ad1ee39f8357b9137cad2bdf7b18830.PNG)

**Comment by htobon** [comment]
I didn't understand pretty well, perhaps we could talk briefly.

**Comment by AndresFVR** [comment]
Home![home.gif](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/home-91f7fb413a57c50acee600360d4bbfc5be663002e861148fe7b90286900218b8.gif)

**Comment by AndresFVR** [comment]
Autosave![autosave.gif](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/autosave-fde3f354b4802419c3632ac5a172994d99ed9caca812c306d53a3b9b3169ed40.gif)

**Comment by AndresFVR** [comment]
Instalation![installation.gif](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/installation-ed544b74b7c8574a8af7b3ae346644e7a536f606907932bded4c2a6a52ee0338.gif)

**Comment by AndresFVR** [comment]
Milestone![milestones.gif](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/milestones-7c3ad207e0000d2bf3b64a9408e95ed33548513323164319374c42e6ed3e56c6.gif)

**Comment by AndresFVR** [comment]
Pusher![pusher.gif](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/pusher-0b5442c6ea345b9c993c14ec1014c5a42306a0fa8eb038796385c74e9c97bae7.gif)

**Comment by AndresFVR** [comment]
Team![team.PNG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/team-d900c9b60f2e55db1e1aa513ba684951ffad8b5e79d707fc8cb24cb739137c98.PNG)
@htobon

**Comment by htobon** [comment]
Hi @AndresFVR, although the information was moved from word documents into the github wiki and is currently incomplete, let's mark this issue as finished.
Please create a new issue in "Bugs & Task" in order to improve the wiki later.
Thank you in advance.
