### ISSUE TITLE
Jane Poole cannot see Impac Pathway menu.

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#332]
Please refer to the Tawk chat.
She only can see Home, Admin & Projects in the main menu.

**Comment by htobon** [comment]
It seems the issue is fixed, however, I'll keep this card in review as I want to discuss further withthe technical team what happened and how to avoid this kind of problems in the future, as well as how to improve communications.

**Comment by HermesJim** [comment]
We do not consider the privileges of a PMU user. this issue fix in the commit 3b69c9c
