### ISSUE TITLE
Search template for rules

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#333]
Search templates for uses cases or requirements.
Search templates for rules.

**Comment by AndresFVR** [comment]
@htobon i fisnished the search and i selected user story template, i made a example of rules for outcomes. https://drive.google.com/open?id=0B3AELdwgDdBVRzR6U2p3SWR3dVE

**Comment by htobon** [comment]
@HermesJim, @cgarcia9106, what do you think? Do you see doing and updating this document in the future?

**Comment by AndresFVR** [comment]
@htobon this is a template of rules customized that  i think can be a better approach. 

https://docs.google.com/spreadsheets/d/1rLDSEJUMIXD_R70utCneDrPFZzXTxWCaR1vLZcU_DzU/edit#gid=130152019
Impath Pathway Outcomes
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-06a1d71e12f6830f0b17c517bf9ced52a15b83cd8159a6ff83f5a8f1bb5b658e.png)

**Comment by htobon** [comment]
Let's try to discuss further in my office.
