### ISSUE TITLE
Created button "Switch" for project pre-setting state

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#334]

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-c93c2dd290b08e1b51e4379fdba269186e710f392b79dcf9ce3a46c2375cdac2.png)


![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-8015c9caf37c7e3ff2f17c23d58411e54d5bcee8a95868ab2417313612fbbe63.png)

**Comment by sebas932** [comment]
Add new column to this record for saving the timestamp

**Comment by htobon** [comment]
Hi @HermesJim and @sebas932, may you kindly explain why this issue is under review? Should I need to do something here?

**Comment by HermesJim** [comment]
Hi.. @sebas932 review and test this issue and check if it is solved.

**Comment by sebas932** [comment]
@HermesJim the action point was "Add new column to this record for saving the timestamp", did you do this task?

**Comment by HermesJim** [comment]
in the coomit 	9e0ff94. i implement the _presetDate_ variable to set and get the Date that the project pre-setting has change.
