### ISSUE TITLE
CCAFS - Organize Climate Smart Villages in MARLO

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#338]
Currently we are mixing the concepts of "CCAFS Sites" and "Climate Smart Villages".
Those are the same and are currently standardized.

We need to fix this in MARLO with the help of Osana.

**Comment by sebas932** [comment]
Write an email to Laura Cramer

**Comment by HermesJim** [comment]
I updated the CSV in project Locations replacing the CCAFS Sites with the CVS according a the document. also I updated the CSV deleting CCAFS Sites and the CCAFS sites was deleted.

I Check the coordinates in the CSV and they are ok!

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-e80e7a0b6eda5fb5642854427ba7429d38b647d00af5ba004e82f431d0ee842b.png)
