### ISSUE TITLE
Set-up architecture for creating project in PDF format 

### ISSUE THREAD

**Issue by carios1usb** [CCAFS/MARLO#347]

**Comment by AndresFVR** [comment]
@htobon i set up the architecture with christian support. The pdf is being generated passing the parameter in the action. Carlos is helping with the design.

**Comment by AndresFVR** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-4124c109e0b051900e7149e55265c17b29fac687df901ab35a9ae126b0afac6d.png)

**Comment by AndresFVR** [comment]
[basic.pdf](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/basic-067608b13dddf713085e5b4bc14241aaecbb4161a30ea0204fc6778ae6f20d52.pdf)
