### ISSUE TITLE
Project Deliverables interface

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#360]

**Comment by carios1usb** [comment]
![Capture.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture-e4587c24f14d7d43b9c088842369a84ce9fcf37af078905f0977105a82aa29ac.JPG)

**Comment by carios1usb** [comment]
![Capture1.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture1-62074043123313b89d4e07a7be53e3f7ee23c06e7a0e0876a2cc369b58b10857.JPG)

**Comment by carios1usb** [comment]
![Capture2.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture2-7b141e2e8ea51eea071b9fddad50ac49e58c99ccf1f8936408e26e2caef3392f.JPG)
