### ISSUE TITLE
Deliverables List: FAIR Colors

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#381]
**Add a legend:**
Green = Achieved
Red = Not achieved
Gray = Not defined

**Comment by carios1usb** [comment]
![Capture.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture-8ec38baa10eed54bebf426a3935a783e69ae3a6aee48171f3b742dbe2a10657c.JPG)
