### ISSUE TITLE
Change label of "Scope of your project" in Project Description.

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#389]

**Comment by sebas932** [comment]
@htobon can you provide us the text ?

**Comment by htobon** [comment]
I didn't understand what should I do here.

**Comment by sebas932** [comment]
@htobon the text that David said in the last meeting and you wrote

**Comment by htobon** [comment]
@sebas932 May you please ask him directly? I was expecting some of you wrote it as a new issue.

**Comment by htobon** [comment]
We decided this section won't be developed.
