### ISSUE TITLE
To resolve the process for monitoring milestones in contributions to CRP Outcomes

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#413]

**Comment by sebas932** [comment]
**Older Version**
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-44a08148d24397b443add5fe964c351efe5ecb06e5cdae8a8dcf1aaea1ffeb9f.png)

**New Versión**
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-3165f1e877fc4f459ef08e8a5ffa01b97abe54166f66e1f38c811089e1aada29.png)

**Comment by sebas932** [comment]
@htobon what do you think ?

**Comment by htobon** [comment]
Fine

**Comment by htobon** [comment]
@sebas932 should I close it?
