### ISSUE TITLE
Update users in P&R

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#416]

**Comment by HermesJim** [comment]
Whit the help of @sebas932 , we update the P&R users list on the users document.
https://docs.google.com/spreadsheets/d/1RBaNUdVMrlQO7RB6-dagD7-FJ6pHjL23AglufasxYbc/edit#gid=265764211

@htobon  send this update to Ou Lin.

**Comment by htobon** [comment]
Thank you!
