### ISSUE TITLE
Instead of Regional Mapping, please change it to Regional Programs

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#418]
Please also change the name of the Action.
from regionalMapping.do to regionalPrograms.do

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-c1fd3abec48e97f7bc42b6f3b20b0b0282cdb20b1331e9c98059319ac1bf334e.png)

**Comment by htobon** [comment]
Screenshot?

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-6f0166cce36bb623dab9d8d20f717392478ba81e5af2c0f975e8b2c6b2c27e1f.png)
