### ISSUE TITLE
Sentence for concurrency editing box

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#421]
Please refer to the following message:

>You are not able to edit this section right at this moment.
To continue on read mode please, click here.

**Comment by htobon** [comment]
Screenshot?

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-65f4bec511846342a55a41fbec930981b598f3317941c4e8be771bbd00cfb0b4.png)
