### ISSUE TITLE
Create and improve the Glossary section in MARLO

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#422]
Also, to make a link in the footer, or in other place more publicly  visible

**Comment by carios1usb** [comment]
![Capture.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture-b92f14a06d974fadfdf2784abaafcea0650eb359ec8de0e9b8d2795d784f21b6.JPG)

**Comment by carios1usb** [comment]
![Capture.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture-2c5ccfcf1b0e8247794427933b4c1e3015c641ed92ba766e7a993e9fcf73c110.JPG)

**Comment by carios1usb** [comment]
![Capture2.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture2-07b714a5b21d65d65e6929c115dd3b76dd6b77bac5d19e07e4898aa8981a537e.JPG)

**Comment by carios1usb** [comment]
Hi @htobon , i'm waiting for tonya's response

**Comment by htobon** [comment]
Hi @carios1usb, I think this will be done with the help of Amanda and Nancy, possibly at some time from Nov 2-4 when they are here at CIAT.

**Comment by carios1usb** [comment]
Ok @htobon

**Comment by sebas932** [comment]
Close issue, open if there are any Specificity
