### ISSUE TITLE
Dropdown list for Milestone years

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#423]
Requested by Pascale:
> Could a drop down menu by added for target years to avoid data entering errors? For instance at the moment nothing prevents me from entering 2015 as a target date. Should we authorize only 2017 to 2021 for milestone target dates?

**Comment by carios1usb** [comment]
![Capture.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture-5710f493be19f8d64fdd1a29831bbedfa9ca832ed01efaddec4f9bdd1cb80484.JPG)
