### ISSUE TITLE
Get MARLO (marlo.cgiar.org) Security Certificate

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#439]

**Comment by HermesJim** [comment]
@htobon  sent the email to requesting the purchase of the security certificate for the domain marlo.cgiar.org

**Comment by HermesJim** [comment]
@pacamargo  has diligence with IT the purchase and the installation of the certificate in https://marlo.cgiar.org.

![image](https://cloud.githubusercontent.com/assets/13221179/19731348/c06cc4d2-9b62-11e6-9b03-c00a03d8397f.png)

**Comment by htobon** [comment]
Hi @HermesJim, may you please redirect the http protocol to https?
If I write marlo.cgiar.org in my web explorer, it loads the website without the certificate, which is a non-expected behaviour.

May you please do it and le me know when it is done? Thank you.
