### ISSUE TITLE
CRP Admin

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#44]
Backend, Frontend, Mockup

- Flagships
- Regions
- Site-Integrations
- Users
- Sub-IDOs Contribution

**Comment by HermesJim** [comment]
Issue Finished. 
Marlo has all crp admin sections.

![image](https://cloud.githubusercontent.com/assets/13221179/16881420/c148521a-4a7f-11e6-9e8e-887976e12272.png)
