### ISSUE TITLE
Data migration from P&R to MARLO.

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#440]

**Comment by cgarcia9106** [comment]
Script 
https://drive.google.com/open?id=0B3O_c4Ip9PVFTFo2UkYwSldtLU0

**Comment by htobon** [comment]
I'm quite confused about this issue.
It reads that you made the migration of the Activities table from P&R into MARLO, however, when I look into the script folder, I see two files:
The first one is related to a user permissions, and the second one related to the full database.

May you kindly elaborate a bit more on this usse?

Thank you in advance.

**Comment by htobon** [comment]
By the way, I have moved the folder into:
/MARLO/Technical/Data/
Cheers.

**Comment by htobon** [comment]
@cgarcia9106 and @sebas932 have explained to me in the daily meeting what this issue is about.
