### ISSUE TITLE
Review institutions Model Structure.

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#444]

**Comment by AndresFVR** [comment]
Create again institutions from backup:
```sql 
SET FOREIGN_KEY_CHECKS=0; 
DROP TABLE institutions;
CREATE TABLE institutions LIKE institutions_backup20161010; 
INSERT institutions SELECT * FROM institutions_backup20161010;
SET FOREIGN_KEY_CHECKS=1; ```

**Comment by htobon** [comment]
Database model was improved. 
@AndresFVR is currently classifying those headquarter instutions and secondary instutions.
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-74c2a4430cda8d1097f267a3fb884b35e41aab0bad94157a1899b247ae54a020.png)

**Comment by htobon** [comment]
This issue is finished. 
The institutions data will be followed-up in the issue #549
