### ISSUE TITLE
implement Add Projects button in Project List.

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#447]

**Comment by htobon** [comment]
@HermesJim, Is there any reason why this issue is under review?

**Comment by htobon** [comment]
Hi @HermesJim, I'm not sure if you are reading my comments here on github, may you kindly explain why this issue is under review? Should I need to do something here?

**Comment by HermesJim** [comment]
Sorry..

this issue are re opened because the project creation do not work in the dashboard section. 
but this fix has finished, @sebas932  or @AndresFVR plase,  check and review if the issue is finished.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-f5b915851c9ecebe0098266c09e03a4976dbbcb414ecac91afa9697c8e8df472.png)

**Comment by sebas932** [comment]
Tested
