### ISSUE TITLE
Improve impact Pathway Graph

### ISSUE THREAD

**Issue by carios1usb** [CCAFS/MARLO#449]

**Comment by htobon** [comment]
Please attach an screenshot or show it to me.

**Comment by htobon** [comment]
This is a very important issue. I'm not sure why it was closed without any comment.

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-b3c11a93f6b4aa263120726704443b7e24cb5042f90bca95a6a69b966d340ce7.png)
