### ISSUE TITLE
MARLO Dashboard

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#45]
Create dashboard view

**Comment by carios1usb** [comment]
![Capture.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture-29ec40bb57db2c22dea8bb3e2673c8326043e47b30e4b8b69763d3ef1f1702b0.JPG)

**Comment by carios1usb** [comment]
![Capture1.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture1-257e982958c3117247bd0627086ec5fed32c3ee5287356b541afa9bdfacabe3d.JPG)
