### ISSUE TITLE
Check MARLO rules and mandatory fields

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#450]
- [ ] Outcomes
- [ ] Cluster of Activities
- [x] Program Management
- [x] Regional Program
- [ ] Site Integration
- [ ] PPA Partners
- [ ] Custom Locations
- [ ] Project Description
- [ ] Partners
- [ ] Locations
- [ ] Contribution to CRP Outcomes
- [ ] Other contributions
- [ ] Deliverables

**Comment by htobon** [comment]
We won't do this as it implies to much time on our side, which we don't have right now (unfortunately).
