### ISSUE TITLE
highlight missing fields when validate form.

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#451]

**Comment by htobon** [comment]
Is there anything I should do here?

**Comment by htobon** [comment]
Hi folks, is there anything I should do here?

**Comment by carios1usb** [comment]
Hi @htobon , please review this architecture implemented in marlo and give us the feedback

**Comment by htobon** [comment]
Hi @carios1usb, may you kindly let me know how do you expect I should review the architecture? Are you going to explain it to me at some time in my office? Or do you have some diagrams or figures that I can see to understand?
Cheers.

copying @sebas932
