### ISSUE TITLE
Test Active Directory Library in Machete.

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#458]

**Comment by htobon** [comment]
@HermesJim, Is there any advance on this test?

**Comment by HermesJim** [comment]
@htobon  i try access MARLO in machete using the LDAP library but does not work.
I have pending test the Library outside (in my house)

**Comment by HermesJim** [comment]
I try to Access to the platform outside of CIAT (in my house) and authenticate using the LDAP library and works it, so maybe the problem to authenticate in MARLO must be that the ports that needs the LDAP library are blocked.

**Comment by HermesJim** [comment]
In the commit https://github.com/CCAFS/MARLO/commit/1074990a6d8dea025293430b1a48b503993756b6
catch the exception when MARLO can not connect to CGIAR LDAP library.

**Comment by HermesJim** [comment]
@pacamargo has sent an email to CGIAR Net to authorize the access from the server (MACHETE)

**Comment by htobon** [comment]
We have to reset and reinstall the server from the begining again and now the livbrary is working as expected. I'll move this issue here as this is under review.

**Comment by sebas932** [comment]
@htobon, @HermesJim  can we close this issue ?

**Comment by HermesJim** [comment]
Yes. The AD authentication its works in Machete.

http://marlo.cgiar.org/

Just only missing in machete the https redirection.
@pacamargo will go help in this task.
