### ISSUE TITLE
Design model for SRF and impactPathway

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#46]

**Comment by HermesJim** [comment]
Chrsitan and Me were meet to draw a SLO and IDO database model. 
[![SRFModel1.jpg](https://docs.google.com/a/cgxchange.org/uc?id=0B5EWQK2RIXqAcGVqX0YzYmtSNlU&export=download)](https://drive.google.com/a/cgxchange.org/file/d/0B5EWQK2RIXqAcGVqX0YzYmtSNlU/view?usp=drivesdk)

**Comment by htobon** [comment]
Las paticas de las relaciones están al revés.

**Comment by htobon** [comment]
En términos generales veo muy bien el diagrama.

- Serían tan amables de clarificar qué significa la tabla indicator_types?
- Recuerden que la columna debe llamarse "acronym" en vez de _acrom_
- Qué tendrá la columna _acronym_ de la tabla cross_cuttings? Creo que no es necesaria.
- Para qué sirve la tabla SLO_Indicators?
- La tabla _Indicator_targets_ por favor renombrarla como SLO_indicator_targets

**Comment by HermesJim** [comment]
Realizaremos los siguientes cambios :

- Indicator_types será eliminado
- slo_indicators no sera relación muchos a muchos; remplazará la tabla indicators.
- Indicator_targets cambia de nombre a slo_indicator_targets.
- cross_cutting solo tendrá los campos id y name.

**Comment by htobon** [comment]
Favor adjuntar imagen del nuevo modelo.

**Comment by cgarcia9106** [comment]
![crf_diagram.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/crf_diagram-e7943f94adae3b0394bdd64a311111120b4addc1a9fee872466afdcb59270f1c.png)

**Comment by cgarcia9106** [comment]
![crf_diagram.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/crf_diagram-85ad1592484a92b61c16fb1c329f5ec36d7be234ac7146790391147f31756ed9.png)

**Comment by cgarcia9106** [comment]
![impat model.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/impat%20model-de844ce149de74f3f768a0b4ec02fff92273ad4034b67fafd7011afa96112b53.png)
