### ISSUE TITLE
Improve PDF Project full report style

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#460]

**Comment by AndresFVR** [comment]
@htobon i made some changes in the style according to your comments, please review the pdf in a chrome tab.
[full.pdf](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/full-5fc70cd9ee4e3feeffb450bc4c73f48557db97bd092d4c994bbe98bc11e3aa5c.pdf)

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-c319c7d02bc48cf22c7565a3689fdcfe96664b696b308121fa712a6e866683ce.png)

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-20607838217ec35c0060839e2de1b73f84fcb59fee57159ad9eb8ffedb88320e.png)

**Comment by htobon** [comment]
I'll review it early next week.

**Comment by htobon** [comment]
Please make the adjustment as per our conversation this morning.
Cheers.

**Comment by AndresFVR** [comment]
# Standard Font
  `<font size={ } face ={ } > `

| description 	| size 	|      face      	|  color  	|
|:-----------:	|:----:	|:--------------:	|:-------:	|
| Heading 1   	|   5  	|     Verdana    	| #8a4508 	|
| Heading 2   	|   4  	|    Segoe UI    	| #000000 	|
| Heading 3   	|   3  	|    Segoe UI    	| #000000 	|
| Table title 	|   3  	|    Segoe UI    	| #000000 	|
| Text        	|   2  	|    Segoe UI    	| #000000 	|
| Footer      	|   2  	| Segoe UI Light 	| #000000 	|

**Comment by AndresFVR** [comment]
[Full_Project_Report-CCAFS-P6-20161027-1620.pdf](https://github.com/CCAFS/MARLO/files/557079/Full_Project_Report-CCAFS-P6-20161027-1620.pdf)

**Comment by AndresFVR** [comment]
Submitted: [Full_Project_Report-CCAFS-P6-20161028-0939.pdf](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Full_Project_Report-CCAFS-P6-20161028-0939-c27d1c364f9e4b43543e00c3b8db42b8e5eaa199d4465d4607cb66637e1e8980.pdf)

**Comment by AndresFVR** [comment]
Example project: [Full_Project_Report-CCAFS-P253-20161103-1442.pdf](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Full_Project_Report-CCAFS-P253-20161103-1442-4cd4a6e26c9aeb216814883456c0d76dbf879dac00c605a253aaaf229d7a7261.pdf)
