### ISSUE TITLE
Rule: CRP Admin / Program Management Team / Access

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#462]
Rule: Only CRP Admins and Super-Admins can access to this section.

If a guest user type the URL manually, he could access to the section, which is not correct.

**Comment by AndresFVR** [comment]
Database with no role:
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-9d54c15dfd5c9f3e9a17233a44a56f5c0a1cc7c22e0903f33e0fa29ee7d84c58.png)

Access to crp admin:
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-6222aa02435fa5f8e6b3c69a7201a5c815ddf1b18d28d45798163f38f3cb0b96.png)




refer to https://docs.google.com/spreadsheets/d/1rLDSEJUMIXD_R70utCneDrPFZzXTxWCaR1vLZcU_DzU/edit#gid=519641172

**Comment by HermesJim** [comment]
This bug is fixed in the commit No. https://github.com/CCAFS/MARLO/commit/3b0c2d2103fb984bb16ee0e8c860519dfd9b468e

**Comment by HermesJim** [comment]
The users that not have CRP Admin or super Admin role and try to access an a CRP admin section , will be redirected to not authorized page.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-98fa962d06135202c0d7dcab29666c8308c13a8a4839be4f803e5ab8b546dc17.png)

**Comment by htobon** [comment]
@AndresFVR, may you please check this rule and if everything is ok may you please close this issue?
Do not forget to update our rules document, pehaps a good idea would be to color the issue with a green background so we could understand that it has been resolved.

**Comment by AndresFVR** [comment]
I checked this issue and the rule is being met. I made the changes on the rule document.
I will close this issue.
