### ISSUE TITLE
Rule: CRP Admin / Program Management / PMU User

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#463]
Rule: It must exist at least one PMU user per CRP

Testing results: A warnign message was not displayed

**Comment by AndresFVR** [comment]
Tested and a warning message was not displayed
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-40be7e751a45b24aa13b2f233991751519806ced8e03838dc26d13e6dafea014.png)

**Comment by AndresFVR** [comment]
@htobon @cgarcia9106 The warning message could be:

Please keep in mind that must exist at least one program management user.

**Comment by AndresFVR** [comment]
Checked and there wasn't a warning message:
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-59ae083d338f53c6fe57ca5079d4659a55709f0488256bfd536a37b70029f603.png)

**Comment by AndresFVR** [comment]
Checked
 ![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-9b746b90d901bc96eb263e645ab0b17c3707a57641d8f2b7068a5145f2a3136b.png)
