### ISSUE TITLE
Rule: CRP Admin / Program Management / Add PMU User

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#464]
Rule: You cannot add an user that is already added as part of the PMU team.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-bd5d2107ba0cf4cd5482aa28ae8bd75104385eb5768b4e4584bc2e738dd84fe5.png)

**Comment by AndresFVR** [comment]
Tested in system and db

![repetead_PMU.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/repetead_PMU-bd43b60ea059e481a12dc4203be3786762fb552968c72b1b416f53421f0c10e4.png)

![repetead_PMU2.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/repetead_PMU2-8ababcfb2147e72b7c90286a0213cbb594455b2b62ce5972e3e7695316bd8f5f.png)

**Comment by cgarcia9106** [comment]
Lo probé y no encontré esta falla @AndresFVR  queda pendiente de que lo revisemos

**Comment by AndresFVR** [comment]
@htobon 
Lo probé y ya no encontre la falla, voy a cerrar este issue y actualizar la regla.

**Comment by htobon** [comment]
great,
