### ISSUE TITLE
Rule: CRP Admin / Program Management / Add PMU User

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#465]
- [x] Rule: Each user added must be assigned as Management Liaison for the institution Program Management Unit
- [x] Rule: If a person is removed from the list, it should be removed from the list of Management Liaisons

**Comment by AndresFVR** [comment]
Tested adding the PMU user but bd managment liason didn't change.
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-7f5659951e48abf33fa1a1c7ec28e6fd3fdccfcf8e00ce667d49d0a6efecca2b.png)

**Comment by AndresFVR** [comment]
@cgarcia9106  i can't remove the PMU User from the list of PMU.

**Comment by AndresFVR** [comment]
@htobon checked.
