### ISSUE TITLE
Email for new PMU assigned into the system

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#466]
- [x] Improve the email that is being sent to a person that is assigned as part of the Program Management Team.
- [x] Improve the email that is being sent when the person is not part anymore of the Program Management Team.

**Comment by htobon** [comment]
@AndresFVR, please improve the subject as follows when a PMU is assigned:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-c27ea69be2581cd8c8136a4b9d1bcac0899b644336f6237cf69b9aecfe8e49b7.png)

**Comment by htobon** [comment]
And please improve the otherone when is being unassigned:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-b676bf45b02429406f4d3b233eb4b8f82eb63e129635934167ad0c0f3cf07313.png)

**Comment by AndresFVR** [comment]
@htobon Done
![image](https://cloud.githubusercontent.com/assets/5505233/19400694/fb39127c-921c-11e6-8fae-bd41bd361f6d.png)

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-65d2807ff77a0eada0652f9bea9996274e0f3614f322649572f0bfeb3d883ac3.png)
