### ISSUE TITLE
Rule: CRP Admin / Program Management / Add Flagships / At least one

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#468]
Rule: It must exist at least one flagship per CRP

Testing results: No warning message displayed
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-ebe807c02ed486856f14f0cec5bd94b666fcbf91bbe8401db4a35d129b31b36b.png)

**Comment by AndresFVR** [comment]
Checked and there wasn't a warning message:
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-981c1526a653798e96ac1f2495e7af169a446bba8330276bc326cd78ac3b7d1b.png)

**Comment by AndresFVR** [comment]
Checked
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-9d9c516be3dbe296beac7f11946706e8afecb3b807679f5e433dfb50b0879f22.png)
