### ISSUE TITLE
Rule: CRP Admin / Program Management / Add Flagships / Repeated abbreviations

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#469]
Rule: Flagship Abbreviations/Acronyms cannot be repeated

**Comment by AndresFVR** [comment]
Tested, and no warning message was displayed.
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-b091de069c98657d980f3b6739702d7bd7ede52562e98b756bc07bcdf58ae80e.png)

**Comment by AndresFVR** [comment]
when adding repeated flagship it shows the following warning message 
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-18d3fde137ba46feb5fdea4bb70782acaa3a6fc4092883cf2a08366ce1edc1a8.png)
But allow to save the Flagship with the repeated acronym. 

@htobon  decided to close this issue.
