### ISSUE TITLE
Email for new Flagship Leader assigned

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#470]
- [x] Email when flagship leader is assigned in the system
- [x] Email when he/she was unnassigned

**Comment by htobon** [comment]
Flagship leader assigned:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-447313847419c72cc9b28984e92a2b0711214d7fe9929a0da36627d63e533e18.png)

**Comment by htobon** [comment]
Flagship leader unassigned:
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-4693d4c91388d55b2451f1b3d693e6196c17ad51b704d37f4e487a61d4a70093.png)

**Comment by AndresFVR** [comment]
TEST aparece porque es el servidor de prueba.

**Comment by htobon** [comment]
Si, lo sé. Me refiero a lo otro.

**Comment by AndresFVR** [comment]
Done 
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-9b926d4de3fe286e6ef992496209d2553e569a2c65874b2085ded4fa7a276520.png)

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-e9728574ec4074b8b333e4abb7e966bbc528fb452051a013b2cabd2375349632.png)
