### ISSUE TITLE
Rule: CRP Admin / Program Management / Remove Flagships

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#471]
**Rule**: You cannot remove a flagship that has at least an outcome associated

Testing Results: The system is not letting us remove an entire Flagship, thus, we could not test this rule.

**Comment by AndresFVR** [comment]
Tested and this is te message of STS console:

![delete_flagship.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/delete_flagship-4276e704cd7f69d3ce47d4f22e670f035b3b37e73c414049222cb4f6ce8d7f1f.png)

**Comment by sebas932** [comment]
It was solved
The remove button doesn't appear if there are more than one project related 

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-9993ceeff0743ef1916178058873ca310fafd7444712f9de5db10d436ef2ab1f.png)

**Comment by AndresFVR** [comment]
Added to rules document
