### ISSUE TITLE
Rule: CRP Admin / Program Management / Regional programs

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#472]
**Rule:** You cannot select "NO" If you have already defined regional programs on your CRP.

**Testing results:** Currently, if you select "NO", all regional programs are being removed from the system. Which is very unsecure!

**Comment by sebas932** [comment]
@AndresFVR  please check

**Comment by AndresFVR** [comment]
Checked 
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-ef3144f42547a9dd01d395d4ca3363750ea292373dce1aa92e95ebbc4966f600.png)
