### ISSUE TITLE
Rule: CRP Admin / Fagships / Remove Flagship Leader

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#473]
**Rules:** 
- [x] You cannot remove a flagship leader who is a managment liaison of at least one on-going project
- [x] You can remove a Flagship leader who is a management liaison of a finished project
- [x] When removing a flagship leader, it must be removed from the Management Liaison list.

**Testing results:** We could remove a Flagship leader that is ML of an ongoing project. It seems there is not a relationship between the management liaison list and the Flagship leaders.

**Comment by AndresFVR** [comment]
Tested an on-going project and allowed to remove the FL:

![flagship_managment_liason_delete.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/flagship_managment_liason_delete-fa8dfa7fe3fcd22ed1041d8120b2eaf8abc75d979802660635ad283cb94e8998.png)

![flagship_managment_liason_delete2.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/flagship_managment_liason_delete2-2dfcec42446374bd57ff925e82210e84d0705e8c0a1d59d115ec98826b980597.png)

**Comment by sebas932** [comment]
checked

**Comment by htobon** [comment]
This rules need to be checked by @AndresFVR .

**Comment by AndresFVR** [comment]
Checked
