### ISSUE TITLE
Rule: CRP Admin / Regional Program / Add Program

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#474]
**Rule:** There must exist at least one Regional Program per crp in case the CRP is going to manage Regional Programs

**Testing results:** We could click the save button without adding any Regional Program. A green message was displayed.

**Comment by AndresFVR** [comment]
Tested and no warning message was displayed 
![oneregionalproram1.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/oneregionalproram1-caa6b29d10fbbf39a183fa2fefd0cbcd605edb7ca636078db92469b8c2888f55.png)

**Comment by AndresFVR** [comment]
Checked and there wasn't a warning message. 
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-b71b6e58f0ffe7944c082ecc4700ceeb88857816bfc6bb161a5ec55c7f5a7a62.png)

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-9138dbec3643e9ff4f930efeebd454b29d64303d301b2f4505f76eccbb9f0182.png)

**Comment by AndresFVR** [comment]
Checked
![image](https://cloud.githubusercontent.com/assets/5505233/19317161/bb9d65d2-9069-11e6-8fe6-8919c3c24251.png)
