### ISSUE TITLE
Rule: CRP Admin / Regional Program / Access

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#475]
**Rule:** Only CRP Admins and Super-Admins can access to this section.

**Testing results:** A guest user could access the section typying manually the URL.

**Comment by AndresFVR** [comment]
Tested and a guest user can access to regional program section
![guest_regional.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/guest_regional-4346f1eaa06ce66b8503de01c758c0c51ac8d697f6279cd050711918240a5724.png)

**Comment by htobon** [comment]
May you please attach an screenshot so @AndresFVR and me could validate what was done?
Thank you in advance

**Comment by HermesJim** [comment]
The users that not have CRP Admin or super Admin role and try to access an a CRP admin section , will be redirected to not authorized page.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-2aa03d429388e8f4c3ee258e5f5c73aa3cc45d3728cb9214860c788cb638dce0.png)

**Comment by htobon** [comment]
@AndresFVR, may you please revise this issue as well and make the changes in the rules document as per your consideration?

Thank you in advance.

**Comment by AndresFVR** [comment]
I checked this issue and the rule is being met. 
I will close this issue.
