### ISSUE TITLE
Rule: CRP Admin / Regional Program / Add / Abbreviations

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#476]
**Rule:** Abbreviations/Acronyms cannot be repeated

**Testing results:** Abbreviations/Acronyms can currently be repeated

**Comment by AndresFVR** [comment]
Tested and allow to add repeated abbreviations
![twiceRegionalAbbreviation.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/twiceRegionalAbbreviation-e81f1b1bbdba24bf85b933369ccd48e41901a89f105eb12bb74ba54d9df714ad.png)

**Comment by AndresFVR** [comment]
No changes here @sebas932 @cgarcia9106. 
Warning message wasn't shown.

**Comment by AndresFVR** [comment]
Checked, thanks @sebas932
