### ISSUE TITLE
Radio buttons in "Bilateral co-funded projects" popup (Participating center, CRP Lead Center)

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#479]

**Comment by sebas932** [comment]
Popup
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-3e7f8540a18a63f1e2f32a70c87791e4d769f698ebc80bafaeb696e301d2bbab.png)

Project Bilateral Cofunded Interface
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-8f43ee36be69f54475ff3867355650d1988acc0f7091a4e63ce0b87372461e58.png)


Still pending for saving this new value into the database.

**Comment by htobon** [comment]
Hi @HermesJim, may you kindly explain why this issue is under review? Should I need to do something here?

**Comment by HermesJim** [comment]
Hi.. @sebas932 review and test this issue and check if it is solved.

**Comment by HermesJim** [comment]
In this issue @sebas932 to be review and implement in the front end catch the information.

**Comment by htobon** [comment]
Ok, so I'll move this issue to in-progress as it seems there is still more work to finish it.
