### ISSUE TITLE
Develop login interface and multicrp

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#48]

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-32b7102571412001f77dfc01fcad3db5d33a15db9e8e9e707b29597dc8693386.png)

**Comment by htobon** [comment]
Sebas, may you please include the aclaratory message highlighted in yellow?
In addition, please note that the message that reads: "Thank you for being part of exclusive group of testers....." should be showed if the properties configuration is set-up as test. May you please confirm that?

![image](https://cloud.githubusercontent.com/assets/5375915/15578449/1d3426ac-2326-11e6-9508-0589e1b1dbf9.png)

**Comment by sebas932** [comment]
The disclaimer note was added and yes, the tester message is validating the production config parameter

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-8efa9135728a7d1b41f963080666b7eaa7669978241b2e3413c037e7dfbc04c7.png)
