### ISSUE TITLE
Fix permissions in project deliverable Listfor PLs

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#484]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-121c94a402f6fb5bd543aabc55faa6b5fd98d2d78881fe5a6206e61e6e329f4f.png)

**Comment by htobon** [comment]
Hi @HermesJim, may you kindly explain why this issue is under review? Should I need to do something here?

**Comment by HermesJim** [comment]
Hi.. @sebas932 review and test this issue and check if it is solved.

**Comment by htobon** [comment]
@sebas932, may you please check it again and get back to @HermesJim if there is any problem? or close this issue.
