### ISSUE TITLE
Add outcome section to PDF Project Report

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#485]

**Comment by AndresFVR** [comment]
@htobon I added outcome to full project description summary.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-5ea0bd9734d1364c6977382182a32d20add88dfd67ee6539bd9cdb7c480ed4a8.png)

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-dcef13f0a17f4a58965c3847fe583035192d0f0b7d91c91bd01913c5aa443a8c.png)

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-c1af7b88eda0503353df6471ff286d9ca9f186c3c0846ce0b4ae9f0310c2fc15.png)

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-e9413218e03ba720b6c1f9754921ed822678534e831d5b71cbcc065eb2ec7386.png)

**Comment by htobon** [comment]
I would like to review it. That's why I opened the issue again.

**Comment by htobon** [comment]
Let's close this issue and follow-up the entire PDF in the issue #460
