### ISSUE TITLE
Regional programmatic focus option is not saving in project description

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#486]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-f29998697a61d180c87d2ec8b45f3f37da28bd55a3c6768f56326af8ee36f665.png)

**Comment by htobon** [comment]
This issue is a bug, not an improvement.

**Comment by sebas932** [comment]
i've tried, and it isn't working =/
