### ISSUE TITLE
Adjust connection pool

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#490]

**Comment by cgarcia9106** [comment]
We created a Thread  to disconnect the hibbernate sessions each 10 seconds

**Comment by htobon** [comment]
Not the best option. May you please look for a better way to manage the connection pool?

**Comment by htobon** [comment]
@cgarcia9106, may you please use 1 hour each day until friday to get a better solution for this problem?

**Comment by htobon** [comment]
@cgarcia9106, 2 days ago I wrote a message here asking you to work on this issue during 1 hour each day. I didn't receive any response on your side, may you please confirm that you followed my suggestion? And in addition, may you please let us know here any advance on the issue? Thank you.

**Comment by cgarcia9106** [comment]
No lo hecho, he tenido otros issues importante, este fin de semana revisare este tema con calma para dar una mejor propuesta.

**Comment by cgarcia9106** [comment]
Por el momento se va a cambiar al time out,
