### ISSUE TITLE
Rule: CRP Admin / Program Management / Add Flagship / Management Liaisons relationships

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#492]
**Rules:** 
- [x] The new Flagship must be part of the Management Liaison Institutions List
- [x] The new Flagship leader must be part of the Management Liaison User List

**Comment by HermesJim** [comment]
@AndresFVR  these rule has been implement. please check if the rule is correct and close it.

**Comment by AndresFVR** [comment]
Checked
