### ISSUE TITLE
Rule: CRP Admin / Regional Program / Remove Leader

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#493]
**Rules:** 
- [x] You cannot remove a regional program leader who is a Management Liaison of a on-going project. A message must be displayed explaining why the leader could not be removed.
- [x] You can remove a Regional Program Leader who is management lisaison of finished projects

**Comment by sebas932** [comment]
Still pending validate liaison institution

**Comment by AndresFVR** [comment]
Checked 
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-9519351bc699a112fdb2460db54c0100ae25dfe47e1d1c5efa5905478f493f0b.png)
