### ISSUE TITLE
Create and implement interface for linking keyOutputs and Outcome

### ISSUE THREAD

**Issue by carios1usb** [CCAFS/MARLO#495]

**Comment by carios1usb** [comment]
![Capture.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture-37da0533fcde05de4277f1a570630528be7d0270b1585dce4405ea9532f214c9.JPG)

**Comment by carios1usb** [comment]
![Capture1.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture1-183023e330a74d27c44f9a9fc43589ac97248b446c8ea13726f896bd69391af3.JPG)

**Comment by htobon** [comment]
@carios1usb, there is not a clear instruction of what I have to do here. May you elaborate a bit more?
Thank you.

**Comment by carios1usb** [comment]
![Capture.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture-bacd9a7d7230c117cf85df74b993523aa05323a089b3d51e411d016a2885e6a9.JPG)

**Comment by carios1usb** [comment]
![Capture2.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture2-69a88f0386f70952631ca48c25d44dec84377820ecf61ccd8ef5136f6e71feda.JPG)

**Comment by carios1usb** [comment]
![Capture3.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture3-9defa4aaf99586f258a3d513df775310590b78a278c2edc6b6e6a1bdc313bf61.JPG)

**Comment by carios1usb** [comment]
Hi @htobon , could you review this section again?

**Comment by htobon** [comment]
Hi @carios1usb, may you please attach an screenshot with a key output contributing to three outcomes?

**Comment by carios1usb** [comment]
![Capture.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture-607b818419041d8c2b2c509b9bde71132a914de215681b7cbf92e35fa0914877.JPG)

**Comment by htobon** [comment]
@carios1usb, please attach an screesnhot where all the contributions have the same percentages. (33.33%)

**Comment by carios1usb** [comment]
![Capture.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture-e9d65a8b339a97fc590ba5baa7637187f3baade0efbf7b136f989b36fba640ed.JPG)
