### ISSUE TITLE
Add deliverables section to PDF project report

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#496]

**Comment by AndresFVR** [comment]
@htobon I finished this section also with chart, carlos will improve it design.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-34110d28dc03ea5e67264563edc788dea596754e5cd67ea11fae6937db5a3d13.png)

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-aa2b80c68c24f33fa8aa15dec8c03374918ebf3ba4ce061244876c986a6392b4.png)

**Comment by htobon** [comment]
Thank you @AndresFVR, I would like to check it and provide feedback.
Cheers,

**Comment by htobon** [comment]
Let's close this issue and follow-up the entire PDF in the issue #460
