### ISSUE TITLE
Alert the user when leaving from a particular section and there is a draft version to be saved

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#507]

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-335c4c778f99feda5af2010234a5081668c0949be8a733eeb6194603a01eae26.png)
 @htobon what do you think ?

**Comment by htobon** [comment]
Great. Simple and easy to read.
Perhaps we could improve the message to read something like:

"Please be aware that this section has information saved in a draft version, we suggest you to click on the Save button"

I'm not fully convinced. May you think in an alternative proposal?
Thank you!

**Comment by sebas932** [comment]
I think its ok
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-2f9b3d282f57e359b22a2d9656faf14b7197cc0dbf17782a9cdb0b7f9ec76eca.png)
