### ISSUE TITLE
Deliverable: partners persons are not listed according to partners section.

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#509]
Test it creating a new project

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-ccde3cd671cd0e47dce96545c9b673d6abd6971368d229735bb838c9881403cb.png)

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-78b82ef9f560ff45a115b22310be533b3ab328de9d620b4ad740e495f428c772.png)

**Comment by sebas932** [comment]
@HermesJim is still pending in activities
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-80ead177bc21de8f6240a8c8525ff501f66ee061809c6a0b7940d37e46acf2be.png)

**Comment by htobon** [comment]
@HermesJim to follow-up.

**Comment by sebas932** [comment]
@HermesJim remember this issue, activities section is still pending to fix the Activity leader list
