### ISSUE TITLE
Issue with project budget permission

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#512]
I've created a new project as a ML user
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-95266e0686298c40855dcb7d5b1704544627b698425c27b8662139aec8b45026.png)

**Comment by HermesJim** [comment]
Establish the following Budget Permissions : 

- [ ]  FP (Finance Person) Can Edit Anual W1/W2
- [ ]  PL and PC Can Edit Gender and Select Bilateral Cofunded projects.
- [ ]  FPL, CP, and ML Can create new Project Bilateral Cofunded.
- [ ] PL Can edit Center Founds.
- [ ] PL Can Submit.

**Comment by htobon** [comment]
Hi @HermesJim, may you kindly explain why this issue is under review? Should I need to do something here?

**Comment by HermesJim** [comment]
Hi.. @sebas932 review and test this issue and check if it is solved.

**Comment by htobon** [comment]
@sebas932, may you please check this issue and close it if you think everything is solved?
Thank you in advance.
