### ISSUE TITLE
Error creating a new project in Livestock CRP

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#514]
016-09-26_13:46:55.771 - [http-bio-8443-exec-7]UnhandledExceptionAction [ERROR]
        : There was an unexpected exception
freemarker.core._TemplateModelException: Java method "org.cgiar.ccafs.marlo.action.BaseAction.getProjectSectionStatus(String, long)" threw an exception when invoked on org.cgiar.ccafs.marlo.action.projects.ProjectDescriptionAction object "org.cgiar.ccafs.marlo.action.projects.ProjectDescriptionAction@24945645"; see cause exception in the Java stack trace.

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #assign submitStatus = (action.getPro...  [in template "WEB-INF/views/projects/menu-projects.ftl" at line 65, column 11]
	- Reached through: #include "/WEB-INF/views/projects/men...  [in template "WEB-INF/views/projects/projectDescription.ftl" at line 26, column 9]

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-2257669bf3106f2390f6921e8a112bcb193fb574d8bc6040f64b5bd473efa694.png)

**Comment by htobon** [comment]
Please mark this kind of issues as "Type-Bug".
thks.
