### ISSUE TITLE
Add new activity expanded

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#515]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-935bb9dbcdab41df3ff29c029df28efab3f2dcf5624617bc3a7aaa34da1d2832.png)

**Comment by carios1usb** [comment]
![Capture.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture-47142346544a24b610f3d0227a68182ff58dd9b8b9a7e614edf8e1094fdf3e96.JPG)
