### ISSUE TITLE
Validate if there is budget to be distributed in CoAs

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#517]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-93ab38b9f4d9301cfd6086c81f366a303161621895d60ac47d7ca858b3f3cbe2.png)

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-f5ad5e4d253f29fbbc6434e02ab5f494f0fe7998b6b1c70834985a4e99a9b9cf.png)

**Comment by sebas932** [comment]
@htobon could you helpme improving the message ?

**Comment by htobon** [comment]
Hi @sebas932, what about the following message?
"There is not need to distribute the budget by Cluster of Activities since this project doesn't have any budget allocated."
