### ISSUE TITLE
I've tried to save a draft version in project locations, but it didn't work

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#520]
- [x] It show a green message but theres is missing fields ?? 
- [x] didn't understand
And the draft versión does not save

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-a4176006a87a15ac54ce47ae1b83eba2cc73321ad9676c1b4a02b68698430503.png)

**Comment by HermesJim** [comment]
@sebas932  i fix and implement new functions in project locations.
please review the section and if it works, closed it.
thanks.

**Comment by sebas932** [comment]
I've checked this issue and i found that there is something wrong

![Animation.gif](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Animation-ab73f38cfbd7cbde6cd778552b4f012f99ebde0ea9f61dd8cad4b0dcecea97ad.gif)

and

![Animation.gif](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Animation-48a24f08c3daa0b46dac827253c292e95f811285000fbe40902891c3ee8c20e8.gif)

**Comment by HermesJim** [comment]
@sebas932  i fix these errors, please check if the section works good.

**Comment by sebas932** [comment]
Checked
