### ISSUE TITLE
Define Help Texts for each section at Project Level

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#524]

**Comment by sebas932** [comment]
I've created a template and im waiting for a response.
https://docs.google.com/spreadsheets/d/1soF3EUVy7yizRFyv_9rpEZ71XADRIYNr7h8-dCyoM9M/edit

**Comment by htobon** [comment]
Thank you @sebas932. I think this will be done with the help of Nancy and Amanda who will be here from Nov 2 to 4. Please remind David and me to include some window of time in our agenda for this matter.

**Comment by htobon** [comment]
Hi @sebas932, the help text are finished.. please take a look at them in the shared spreadsheet.
Please focus only the ones in CRP-Admin, Pre-Setting and Planning.
The ones included in Reporting are not ready as of yet.

**Comment by htobon** [comment]
Is there any advance on this issue @carios1usb ?

**Comment by sebas932** [comment]
@htobon is still pending to review the help text for deliverables section

**Comment by htobon** [comment]
@sebas932, may you please write the following for the deliverables section and open this issue when it is done?
> A deliverable is a specific, tangible product, like a workshop report, paper, dataset, scenario, etc. Deliverables are part of key outputs. Unlike key outputs which are generic categories, deliverables are specific and time bound with an expected year of completion.

**Comment by htobon** [comment]
@sebas932, is there any advance on this issue?

**Comment by sebas932** [comment]
Done
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-3385da55a521bafca711145666711690df1886a26bd0725d909fd096a4811d4a.png)
