### ISSUE TITLE
Update user manual

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#525]
- [x] Request old manual to Hector.
- [ ] Update manual.

**Comment by AndresFVR** [comment]
More professional

**Comment by htobon** [comment]
Please find below the latest version of our user manual for P&R:
[CCAFS_PR_UserManual_20160727_PC_DA_HT.docx](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/CCAFS_PR_UserManual_20160727_PC_DA_HT-eb05c38dbfe391e70cfb562de7ac8af6e7941f41d25510672670c9f4b29e5c41.docx)

**Comment by AndresFVR** [comment]
@htobon User manual proposal: [MARLO_UserManual.docx](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/MARLO_UserManual-2d98411953a87ab99681f7e25dee15ef4565f0fbf5f29fe0c2c7b722c768933d.docx)

**Comment by AndresFVR** [comment]
Update budget diagram:  [MARLO_UserManual.docx](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/MARLO_UserManual-d1a001db95433d51390a3067d76d10bb4e37346a7b782b13b8332b0a00c06ac8.docx)
