### ISSUE TITLE
Create PDF guide that explains what is going to be requested in projects on the planning phase by a ML

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#526]

**Comment by AndresFVR** [comment]
Project level, make the distinction of user and type of project.

**Comment by htobon** [comment]
Please take a look to the templates we used to send. The idea is to update and improve them.
Changing the priority of this issue to High.

[Project-Template-CORE.docx](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Project-Template-CORE-6b14e934f8ea2ffe18ae88778a1e8afaf501999aa7cd6704129446c6e19f7cad.docx)
[Project-Template-BILATERAL.docx](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Project-Template-BILATERAL-ebbae401d0808c98a531553258d4281dbdaad042bd2a239123605985b7a76d98.docx)

**Comment by AndresFVR** [comment]
This is a proposal:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-28f36c865466301b26f1fcc37c86bf309c1600956ff30030dd604c5c903b911f.png)

**Comment by AndresFVR** [comment]
To take in account: I changed the issue name to specify that this document will be for a ML. Later, i will add the PL and PC issues for PDF guide(template)

Cover page proposal:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-9cd8207a5404824ed2ab11eb7134e510f0f7b89cf5d9177447ba4f9584a96a12.png)

**Comment by AndresFVR** [comment]
Project Description proposal: 

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-16f6ab09d98752594b6e2f2e51be96f33218faf597b14cd5feee87170dd7ad30.png)

**Comment by AndresFVR** [comment]
Project Partners proposal:
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-5002ef490a4e83892450427e30c00421c4f6b5ecabe7e175da59591f9a08b1ae.png)

**Comment by AndresFVR** [comment]
PDF proposal: [Project-Template-CORE-for-Managment Liaison.pdf](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Project-Template-CORE-for-Managment%20Liaison-0e246dc67e753f159c2dbfcc43475e0ca8195b7f7d59aa5628c46383a94e8ffc.pdf)

**Comment by AndresFVR** [comment]
Core Template: [Project-Template-CORE-for-Managment Liaison.pdf](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Project-Template-CORE-for-Managment%20Liaison-6ff0e5fd59a2713eb7f4438ac0600093a6e120fa4bda94496f734471136eebd6.pdf)

**Comment by AndresFVR** [comment]
Bilateral Template: 
[Project-Template-Bilateral-for-Managment Liaison.pdf](https://github.com/CCAFS/MARLO/files/544841/Project-Template-Bilateral-for-Managment.Liaison.pdf)

**Comment by htobon** [comment]
Hi @AndresFVR, thank you for this. I'm going to send the Project Leader template to the Marlo-Famili and see if we have some feedback. 

I'm going to close this issue as it is finished.
