### ISSUE TITLE
Organize projects buttons

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#527]
Projects buttons:
- [x] Add W1/W2
- [x] Add W3/Bilateral Standalone
- [x] Add Supplement projects

**Comment by htobon** [comment]
@sebas932 please do not forget to update our mockups. thks.

**Comment by sebas932** [comment]
Project type buttons were added and updated in the mockup

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-d5816ad534693f85fa47649d38878dd262ef3af0eea8858ef83a15767d718e5d.png)
