### ISSUE TITLE
Outcomes/Assumption no data

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#528]
If assumption has no data, then don't show the assumption text.
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-e2b13f5a85f3663308b6576800ae645ad450ffad7b71a6ddb6c3af5b310090da.png)

**Comment by cgarcia9106** [comment]
@AndresFVR  que esto

**Comment by cgarcia9106** [comment]
@carios1usb  revisalo

**Comment by carios1usb** [comment]
![Capture.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture-a5c8198662ac67f50722149fd42392a916df2caca711fa06b86f030e5da6bf2a.JPG)

**Comment by carios1usb** [comment]
![Capture1.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture1-a3edd09da5fe574eccd959cca4a4605d31961ccbde24585ba6d15a965e5fb667.JPG)

**Comment by htobon** [comment]
Please update the pharagraph as follows:
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-345ba7054fc7c8632dca593aab1ddf6d78910948f022160a484e81feade7b6b4.png)

**Comment by carios1usb** [comment]
![Capture.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture-9956979fbcbd7fc51d4cf0456821a9d4039f91f607b621fdc2e13f7bb840404a.JPG)

**Comment by htobon** [comment]
Please improve the messages as follows:
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-6afbfaba0a0c90666a4ba11373f37669aef97dd6247a0f7a5f9b735ca115c134.png)

**Comment by carios1usb** [comment]
![Capture.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture-06e7c0bd6b3f8116e6bece34fab584024718bf95cd09fd9cdc7e0278ec3a04ea.JPG)
