### ISSUE TITLE
Add submition information in PDF

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#529]

**Comment by AndresFVR** [comment]
@htobon I added submitted project description on top of the PDF, i got this info from the table submissions.
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-ca229a23e22d8d38776fee2012650b8dfc250b8e08c1c5e0bb06f85ac6dd2d25.png)

This is a not submitted project 
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-f2cd2f06fdd023de7ccc2868f0e0e8de58e3c66c943a762882fedfb9f6999181.png)

**Comment by AndresFVR** [comment]
Thanks @carios1usb for review

**Comment by AndresFVR** [comment]
@htobon  
Submitted
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-1c619d5c62301c74cd4f787e2402744c75ff3d9557ffa4537301e7f1512a962c.png)

Not submitted
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-7774de717ea9fb1fc2c849d827489c6905e4bebc998976ce7253ef23ba195d91.png)

**Comment by htobon** [comment]
great.
