### ISSUE TITLE
Update MARLO Version

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#533]
Please update the version of the source-code.

We are now in the v4.0.9-SNAPSHOT
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-946f3dc0885ccf0d91cb3a7d77b11865853d34b0bdc70d3783cd62514ade72e5.png)

Do not forget to make the change in the two projects.

Thank you.

**Comment by HermesJim** [comment]
I change the version in the POM files.

![image](https://cloud.githubusercontent.com/assets/13221179/19075820/3567b822-8a0c-11e6-9fdb-ba38159929cb.png)

**Comment by htobon** [comment]
thks.
