### ISSUE TITLE
Improve versions of Pentaho libraries in the POM file

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#535]
Please define the versions of each library of Pentaho into the list of versions we have at the begining of the file. Please refer to the  following screenshots:
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-f55c6571d9299746a109d4e25ebd05a10acbbfb30779c311625edb863529acfe.png)
------------------
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-e6ab43457ab8ee305c2517ce90f8285a8e27a52df1d3806a8738eb16a9953381.png)

**Comment by AndresFVR** [comment]
@htobon i updated the POM file
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-1e8cd95be1044489cc5ab0a3283ea4376e6a0b06620c1e8d7eb74765e8dd8e74.png)

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-cab7f21d0f52acb3be77545839b721699321569f0b757b297252a2e553739414.png)

**Comment by htobon** [comment]
great. thks
