### ISSUE TITLE
New flagships leaders in new CRP can't login into MARLO

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#536]
I tried create a new Flagship leader in Livestock CRP, then i tried to loggin using the new flagship leader email but it didn't work

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-0515174c34a6633c18cac2082e06a7a71a899b8ba2cd6ff01f4cad4d8c916439.png)

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-674b06d6fbaf8ca9f9bf7635c79079442c3eb75653a14f9e296997f8fdf4cbba.png)

**Comment by HermesJim** [comment]
@sebas932  you can try to assign again a flagships leaders and pmu users on different crps and login .

**Comment by sebas932** [comment]
I've tried to add a new flagship and flagship leader but it didn't work

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-ba4c4735245c79b27ffc6fe1a717ae00223d2ff0f17bf762510d480d40990343.png)

i can not see the user with privileges 
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-f98af57eafd665f5cf7bd92f6e25e38573d8d5c6fc6b8197975137f97e376ab0.png)

**Comment by HermesJim** [comment]
@sebas932  i assigned new permission for the FPL. now all FPL can create projects. please check it.

**Comment by sebas932** [comment]
Checked
