### ISSUE TITLE
List Key outputs in deliverables section

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#537]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-1a1edcaff8249ec9716f7903b636fc7b1f77704039b4f3e949cb38e517dcfba4.png)

**Comment by HermesJim** [comment]
@sebas932 are look if these project have assigned a cluster of activity in project description?

i test wiht a project that have an cluster of activity and in deliverables appears the keyoutputs list.

![image](https://cloud.githubusercontent.com/assets/13221179/19157771/084adda0-8bac-11e6-9a51-8106da4b7376.png)

![image](https://cloud.githubusercontent.com/assets/13221179/19157785/122a3fa0-8bac-11e6-808b-c9ce1f371303.png)

**Comment by sebas932** [comment]
Checked
