### ISSUE TITLE
Error when submitting an impact pathway

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#538]
I tried to submit an impact pathway and got the following error:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-c75ea60357af08d780f27ef6319d3954e7dd7f829806949818e9c8bb22ef4b66.png)

**Comment by cgarcia9106** [comment]
@AndresFVR  will test it!

**Comment by AndresFVR** [comment]
I checked this
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-db80a0c553df68f60e5f8e366da94f9af90a9afb1fa51a67a8fa8c559a65a5f7.png)
