### ISSUE TITLE
Term "Core" should be taken out from the system

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#542]
Please review all MARLO and take out the term "Core".
Instead, please replace it to W1/W2.

From now on, we don't have Core Projects, but we have W1/W2 Projects.

**Comment by HermesJim** [comment]
i Change the core for W1/W2 in the global text.
please review if in MARLO exists other core text project.

![image](https://cloud.githubusercontent.com/assets/13221179/19195072/92b35ab6-8c75-11e6-9537-a64de54672e3.png)


![image](https://cloud.githubusercontent.com/assets/13221179/19195086/98f225ba-8c75-11e6-86c6-25ec7726bf8b.png)


![image](https://cloud.githubusercontent.com/assets/13221179/19195096/a3300a4c-8c75-11e6-861d-133ae675c25d.png)


![Uploading image.png…]()

**Comment by htobon** [comment]
great. thks!
