### ISSUE TITLE
List of Projects ordering

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#543]
Please order the list of projects by project_id ascending.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-cad42244bbfc2895cfdafd5b2d67fac626403344c609a3fc79aa34cac0ce6283.png)

**Comment by HermesJim** [comment]
I change the Order in the project list.

![image](https://cloud.githubusercontent.com/assets/13221179/19190931/bf62007c-8c65-11e6-8363-0ef6d7b29bd5.png)
