### ISSUE TITLE
Update Installation manual with tomcat/context

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#545]

**Comment by AndresFVR** [comment]
@htobon will review later

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-6f79393edd8883e8d6b7217609dac4c1e594679fc1aa97df2a4e165f2cb329c4.png)

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-7868503c829e1c47ad2cb10d530cf00f7ad888dc1f457ac081f841cd432070b0.png)

**Comment by htobon** [comment]
Revised.

**English version:**
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-81d3642680c49b96f0bf22722c6365f30f6b49edade708c537fbac22315c1d43.png)


**Spanish version:**
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-17671440df02d125c7cbf8e1f19ca64249c204c803c7f30bbab3f1739168e909.png)
