### ISSUE TITLE
Display green checkmarks when an impact pathway is submitted

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#550]
Please make the missing fields validation process when an Impact Pathway is submitted. See screenshot below:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-09d1633589c2f623abcb351b8f90c8092bb327e3f29ed613853ff2646efe9ef6.png)

**Comment by htobon** [comment]
Please attach an screesnhot

**Comment by htobon** [comment]
@cgarcia9106, why are you closing this issue if I have requested you to attach an screenshot?
I'm asking you here by second time!. Hope you can do it. (2 minutes of your time).

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-0785cda1bdadd6740b709ddf1c0663e5d16bbd4af3378238a889c2b706049bd0.png)
