### ISSUE TITLE
Design mockup for partners with headquarters

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#551]

**Comment by sebas932** [comment]
I made this proposal

**Project Level**
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-a5f9844d4fbeb149198125470cab96826d90e9f35884e6395dca9ffcd6bfa8c0.png)

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-bb2a0fc958d5a80d62b6a5ba23e35dee010545b5ec27504b5b9866d52fd26d36.png)

**Marlo Admin Level**
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-b9bc05afb28162fda2b10914a883aa9f196d50fab1e72aee455cbf9e35b19247.png)

**Comment by htobon** [comment]
Approved. Please go ahead and apply this mockup to MARLO. If you want please close this issue an create the specific ones for the technical aspects.

**Comment by htobon** [comment]
@sebas932 ?

**Comment by sebas932** [comment]
We will implement in another issue.
