### ISSUE TITLE
Allow users to add CoA identifiers

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#553]
`Pascale Sabbagh: We need to see the numbers of the clusters. For instance 1.1, 1.2, etc. If we are refering to flagship 1 as F1, we should be refering to cluster 1.1 as C1.1. I think this means adding the cluster numbering in the impact pathways where we enter the clusters`.

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-d8e35d29c96d860411524bdd0e90e740e6de460e744f33ee1fe970668ce62ad1.png)
