### ISSUE TITLE
 Create live notice message to notify that the platform will be updated

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#56]

**Comment by sebas932** [comment]
The function is working with a plain JSON file, still waiting for web service that catch the message using the database
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-f871273b3d1cd7b9dc38e83c3e1cf98e0aedc23cec9a26e5177275bedbf44813.png)

**Comment by sebas932** [comment]
Reaction after "Roger that" button
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-143422f410a49c954e1612e26ff09097e4f307ae0d405e6f51fcbf8a679f9fd5.png)

**Comment by sebas932** [comment]
The web service will be worked at the next spirng - closed
