### ISSUE TITLE
Disclaimer message for the testing environment

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#560]
Please include the following disclaimer message in our login page:

------------------------------------------------------------------------
Thank you for being part of the exclusive group of testers; 
you are in the right place!

In order to better understand and try to improve the user experience, 
the test environment of MARLO uses Hotjar service which is a tool 
that reveals the online behavior of our users. Therefore, we may record 
mouse clicks, mouse movements and scrolling activity within this
testing environment **only**. Hotjar does not collect personal information 
that you do not voluntarily enter in this website. More information can be 
found in https://docs.hotjar.com/docs/what-is-hotjar 

Please be aware that everything you enter in the **testing environment** 
may be removed from the database at any time.

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-35b5f27606d3aa7aa3653c58f6fa6d878bfa94657849806bfed38652ecbe03c5.png)
