### ISSUE TITLE
Admin section - Custom Locations

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#562]
Further explanation for the meaning of "Default location levels":

-----------------------------------------------------
>The default location levels refers to the levels which are standard and available to all participating CRP. Should you need a specific location level particular for your CRP (e.g. CCAFS Climate Smart Villages, etc.), please create below.

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-8a62811c37bfc250b9eaabbc1e7d2857b309ea0661230814fe428a956dd5130f.png)
