### ISSUE TITLE
Target Units Impact Pathway - Outcomes

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#564]
Take out the creation of target units. They will be done, for now throw the online chat (technical chat) upon request.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-1f42dd743ebba9a175d6d4d54e13a0228b631542b164160114b961329cf47f12.png)

In addition please include the following message:
>If you can't find the adequate target unit, please inform technical support by leaving a message in the online chat (bottom left)

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-597e2c6f42e3a3380e109337cc4de42bf70a01e20fd02d46bed0b14fd9545a46.png)
