### ISSUE TITLE
Impacth Pathway marked as complete but it is not

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#567]
I (as flagship leader) just added an outcome and the system is saying that my impact pathway is complete. However, I have not added CoAs yet.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-f4a03d66fc8536a5c8486e01d9765837764b1d73f07cdf79b4c9fb2559f0df96.png)

**Comment by htobon** [comment]
please attach an screenshot

**Comment by htobon** [comment]
@cgarcia9106, I'm opnening by second time this issue as I have requested you to attach an screenshot that takes 2 minutes of your time. May you please do it? 
I have the feeling you are not reading my messages here.

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-ae6323dbc16f379f55385b9194a6f8993e35755cb03d7074d6cc8bc92f5a410a.png)
