### ISSUE TITLE
Server error when trying to add repeated sub-idos

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#568]
I tried to add the same sub-ido to a specific outcome and got an error.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-a05767d9bdf7380a78ddaf7460b39e9d4802af63fa28bfd7786aabe1a9bcef11.png)

**Comment by sebas932** [comment]
Solved commit in 7eada8d

**Comment by sebas932** [comment]
Solved commit in 7eada8d
