### ISSUE TITLE
Outcomes section - Invert order between Su-IDOs and Milestones

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#572]
Please put Sub-IDOs first and then Milestones.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-612b9a343a871ac7519657d8850be82f28a3c9487b4fb518465d45a633707fca.png)

**Comment by htobon** [comment]
Please add an screenshot and close it again.

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-d1853bec08c2c01e53d7bef5feb5fd3d108f4f23fcce78dd3cacf5c53507602d.png)
