### ISSUE TITLE
Key Outputs in Impact Pathway

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#573]
Please apply the changes described in the following screenshot:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-42b25154c0a075dac827378df13b3af4c307a90008968ef6d2d88dfddb95c8ad.png)

**Comment by sebas932** [comment]
We had this 
!
[image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-3bb7ed83a422071c553aa3243b63ca7fe166d9c178fec4904cc4006a0516b635.png)

**Comment by sebas932** [comment]
done 
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-875769d322e63f0f34c67cfb6fdf871d7f30c311ab7ad255baaee6d69b51181a.png)

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-cec4719e694b7365589fb6c0a1f387a925b66718eb4f98dbe211fb6b91f2b2e6.png)
