### ISSUE TITLE
Projects List - Add project buttons

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#574]
Please take out the button "Add W3/Bilateral" project if the user is looking at W1/W2 projects only.

Same comment when the user is in W3/Bilateral projects.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-1079c29133b63a52f2412eb56154b80c77e019ef90dfcd0df72df908dc89888d.png)

**Comment by sebas932** [comment]
All Projects
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-a0fdfb7ecaa085e293a97c8ac60bfb9441fd97c97f517e3bfeb56c38de994ff4.png)

W1W2 Projects
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-805c1eb19f4d1e51853cfcaca1147e265dc74e39fdaa0763b672e1d7e138ff6d.png)

W3Bilateral projects
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-a8cb98d820fa4ccf9cc71d79290cf64d6cfaf020751a8ea09c1394535fd1a133.png)
