### ISSUE TITLE
Deleting projects that don't belong to my flagship

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#578]
As Flagship leader, I must not be able to delete projects that belong to other Flagship Leaders.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-5b05f00ed1215cf218a6831f11d11afe36b885fea479130a9ee8c37b385d1b20.png)

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-803a44eddbf96db44cae3382e4ae8f264ecc99354bf92c7406f8122d9dcbd82c.png)

**Comment by sebas932** [comment]
This issue was solved
