### ISSUE TITLE
Disable PDF Button

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#579]
Please follow the instructions below:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-b4c43ccb357e85da3a931fbb4228848eb55db57b5f3dc0783cec6cfd8533fd61.png)

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-b3a73314dd4af8aae4593aad2a0b7c4eba0d26d21b845a49360ac3bfda19997e.png)
