### ISSUE TITLE
Please hide the links that are not working in the footer

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#580]
The following links are not working, please hide them to avoid confusion.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-2e703ef4cf2c3be64a3ac8c12ce99684437110f93b3710854a86bbec8a2b057a.png)

**Comment by htobon** [comment]
@carios1usb, may you please attach an screenshot?

**Comment by carios1usb** [comment]
![Capture.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture-e96e672e49c8753c5ba92c87262bccc1a8b5f3e44c0c8c1ce76d55959d1394f1.JPG)

**Comment by htobon** [comment]
thank you.
