### ISSUE TITLE
Project Locations message

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#581]
If the user is on read mode, please do not ask the user to select a location.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-2948e32efd95d3af133922fd72aad174eb6fc3bd626733aa50c6dd42b4a6b288.png)

**Comment by htobon** [comment]
@carios1usb, may you please attach an screenshot?

**Comment by carios1usb** [comment]
![Capture2.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture2-53236070b866aefd96c4f8f44c27346cf27736d61c1acac9da18a1e6077b3ab2.JPG)

**Comment by htobon** [comment]
Please also re-phrase the question highlighted in the following screenshot.

Please keep in mind that in read-mode we do not ask questions. We just affirm the metadata for the project.

![image](https://cloud.githubusercontent.com/assets/5375915/19659606/36b5750c-99f2-11e6-8232-2cfaa926f1ec.png)

**Comment by carios1usb** [comment]
![Capture.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture-5ac786a02588185a4626bf9888b9d23e4b0b70122313383a0ebff25776842197.JPG)

**Comment by carios1usb** [comment]
Hi @htobon , can you help me to improve this message?

**Comment by htobon** [comment]
Hi @carios1usb, it is fine. thks.
