### ISSUE TITLE
Project locations - Google maps

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#582]
Al hacer clic en esos botones, se pierde el foco del mapa, y entonces los puntos ya no aparecen.

Lo probé logueandome como AJARVIS y entando al proyecto 18 en modo read.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-410bbffbadd7e204a4de2a1c3cef57420a11dd27dcb143779e0af21a4e6bcee8.png)

**Comment by htobon** [comment]
@carios1usb, may you please attach an screenshot?

**Comment by carios1usb** [comment]
![Capture1.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture1-f97b6154ac5a55714e42889bcb95663ae0292a93347b3bc0f6f2e81a925afc91.JPG)

**Comment by carios1usb** [comment]
![Capture.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture-0adde69dd4d5dd35e5f26c1bc87995efb3b5f159a8ef93efd58fa5690a26d01d.JPG)
