### ISSUE TITLE
Contribution to CRP Contribution in read mode

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#583]
Please replace the text as follows:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-da791f7117707e03182f9095c8d17bd45a884c41679672150a6687cd48bfae79.png)

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-1355a4f799363909565021a8af458bc45d311fd1725113937e4510789be6b4d5.png)
