### ISSUE TITLE
Add deliverables in read mode without privileges

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#585]
This is a security issue:

If the user is on read mode, he/she must not be able to add new deliverables.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-1c00a2d0a1d12e39c91260f977c7c7d8f2022cc9f2585ac536e97604844bf6c8.png)

**Comment by htobon** [comment]
By curiosity, I clicked the button and got the following error. I'm not sure if it is related to the issue above.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-901bc9c9e04bbf0aa695bdf68690efa005ab536d6f9ebb53e7de84b45472f585.png)

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-12abd2b2bb689a6dcf0c6808cb3be16a1a3ea6c9894e79eabb1bd8f2a881edae.png)

Is still pending validate in the back-end if the user has permissions for adding a deliverable.
