### ISSUE TITLE
Deliverable Partners without acronyms

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#586]
If an organization doesn't have an acronym, it is being displayed as null. Please fix it.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-50000ba93f35bc372ef2fe345f0ac60bc3ab5561eeb57f4883215203b232ed4a.png)

**Comment by htobon** [comment]
Please attach an screenshot.

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-c9bf290d7eccc52ec4dbb51b4e82e67499538ba5dfed2bd6b445f60629ca32bc.png)
