### ISSUE TITLE
Deliverable year of expected completion is not displayed

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#587]
The year for the expected completion is not being displayed in the read mode.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-0956492607b37ed0e071efcdd6db49e2bfa9ded3701e43d687df8f0ab8fb81c2.png)

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-f5ae2c5370d2c15ee26426cc3817517f01f541db418f68e8d09d841bbb1026bc.png)
