### ISSUE TITLE
Activities in read mode

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#588]
Please take out the "select" question when the interface is on read mode.
In general, please avoid asking the user to take any action if the interface is on read mode.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-7062137fbb862684c877e25c9cb654618801e23b68bd1b3884144e5b87c091b4.png)

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-7db786c37f4d8c37a03f346e357a43406f8127a06cb6ddab8ab6ddae56252e7d.png)
