### ISSUE TITLE
Budget by partner in read mode

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#589]
Please take out the asterisks in red to all questions if the user is on read mode:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-a4fd7f88e8759ad8a1cb4518ba5a34b15f0172025c6b7c3f0e0a67e286f59d6d.png)

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-5cf81341f866c59042085a53e328a840c48cb13c9d0ef3103d0a785dab55b005.png)
