### ISSUE TITLE
Previous years in Budget by partner when read mode

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#590]
Please take out the highlighted message below if the user is on read mode.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-74d02b59df51568667e049a2ad6a68d74de10481a23f2a244b2ee25fd4e76296.png)

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-0b51fbb0de09671673a15772a7be13ded9f82524a506531382af0e7d37c34ff9.png)
