### ISSUE TITLE
Summaries Section: Create partners and projects they relate report 

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#594]

**Comment by AndresFVR** [comment]
[report-designer-preview5811387426068383512.xlsx](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/report-designer-preview5811387426068383512-d11be4592a30dee1cf574563891be194f2888ece361a165a10ac78510797f26c.xlsx)



![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-4d77c96ee3107a073cd95201194a92551a9cf1b43bc555e38deac0624a4e4dde.png)
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-36bc0f18bc1ca074947ae6402d2a9c373711c3867d1f3d99977a6e38736dc2dd.png)

**Comment by htobon** [comment]
Hi @AndresFVR, good job. Please apply the changes according to our discussion in my office.

**Comment by AndresFVR** [comment]
Partners Leading projects:
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-08278ace1c09d060261fcd38b01284ff1bdc7560598fa42c10ac123e3859b8fa.png)
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-5cd285b8fa74e4192a1d8815d9adb99e1969d16af47d7e4388b76232c918738c.png)
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-e59ec9566537ae2aa34a19f34d569040d44e0c039e7af8a3ca7494c1573b9b74.png)

Partners working with CRP: 
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-a278239456b02d2030dc11f90b2ef48a5f390f5ac0e230a60be01921dd0fa0da.png)
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-76415e502cae18ac0a4173a319be269967758cba165b60198ad846800500a945.png)
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-49fa3e192b2b0e51617ec8a630e4102b502a5deace34ba3837c84f82ffae33d2.png)

**Comment by AndresFVR** [comment]
Project Partners: 

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-682208979407537429c42ceb8c92ad0469c7b340bcd84138f18b581905aa8db7.png)
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-f37cd3ae2bd0061ea0e9a52377112aea39e72cdd8977c0f7815e0158d1c9c7fc.png)
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-375d92d57284bdfc24b5e0a56af25d67887f06b9c5996002852c587b6d9d0be4.png)

**Comment by AndresFVR** [comment]
Partners Leading:
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-736b98b0a4eed20e9a7c320417b5724448c90405ccd2b4d677432b10006796a0.png)
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-536f034ca736378cd5b3a1beaed611295d869c1d150d99e13a91be7cfedec70d.png)
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-1869a2d9f4516b52471e83214180a57309d4221227febca0671876a0a0c87fe2.png)
