### ISSUE TITLE
Create PDF guide that explains what is going to be requested in projects on the planning phase by a PL

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#599]

**Comment by AndresFVR** [comment]
Core Template: [Project-Template-CORE-for-Project_Leaders.pdf](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Project-Template-CORE-for-Project_Leaders-ff8ba20267c124b52311634d17510e8580c0b4ab579b12047109b2e88dde857e.pdf)

**Comment by AndresFVR** [comment]
Bilateral Template: [Project-Template-Bilateral-for-Project_Leaders.pdf](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Project-Template-Bilateral-for-Project_Leaders-6567fdd479b65dc871a40a3cb673e29f89eb45b316ce0be6a3c9fd36dee696a3.pdf)

**Comment by htobon** [comment]
We are looking for David's response.

**Comment by htobon** [comment]
Please refer to issue #526
