### ISSUE TITLE
Finance Manager roles per CRPs

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#600]
Please set-up the Finance Manager roles for each CRP as follows:

For CCAFS, A4NH and WLE, it will be a specific person in charge of entering W1/W2 budgets and PPA Partners in MARLO

However, for PIM, who will be in charge of this responsibility will be the people who belongs to the PMU Team.

Please make the tests.

**Comment by sebas932** [comment]
Moved to the next milestone
