### ISSUE TITLE
Validate permissions when a flagship leader is assignee in projects section

### ISSUE THREAD

**Issue by carios1usb** [CCAFS/MARLO#606]

**Comment by cgarcia9106** [comment]
1. Cuando asigno un flagship leader no salen impactpathway section
2. cuando asigno un flagship leader como management liason de un proyecto, al entrar con esa persona no tiene los permisos para editar.
3. si elimino la persona de flagship leader, esta sigue como management liaison ?
4. Si elimino la persona de flahsip leader y management liaison, no debería poder crear proyectos
