### ISSUE TITLE
Bilateral projects that ends before 2017 should not be selected

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#608]
Please refer to the screenshots below:
## ![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-4a86726149244528b588e727a08206e06cdd631886262061e6976dc23577d40b.png)

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-a181239311b5154fbbcaf4c64cb829624a4933a778554a3bcba78f7613bec4b3.png)

**Comment by sebas932** [comment]
This issue was solved
