### ISSUE TITLE
Mockup: Alternative way to manage W1W2, W3/Bilateral Projects

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#609]
https://docs.google.com/presentation/d/1ZdJQ-IsrSNZ4SDuFtgDNTKSP48QOgKyou8GDpQTvNOk/edit#slide=id.g17ca59c238_0_410

**Comment by htobon** [comment]
Hi @sebas932, I have reviewed the mockup. Good job!.
Please take a look at the comments.

**Comment by htobon** [comment]
@sebas932, I think the new mockup and idea look very well and it seems aligned for what other CRPs are looking.

May you please add also the deliverables section? We are also required to know to which funding source each deliverable is being funded.

**Comment by sebas932** [comment]
This mockup is finished
