### ISSUE TITLE
Project leader can update project summary

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#610]
Project leader must be able to update the project summary.

**Comment by htobon** [comment]
Hi @cgarcia9106, may you please attach an screenshot?
Thank you.

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-cb60b879bc8cb3cfe46a9661a4b118c0d04ef6ef6c0607e4eb06451f4491a802.png)
