### ISSUE TITLE
Improve disclaimer message in the testing environment.

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#611]
Please include the following disclaimer message at the left of our login page.

----------------------- **DISCLAIMER for testing environment** -------------------------

Thank you for being part of the exclusive group of testers. 

In order to better understand and improve the user experience, the MARLO test environment uses Hotjar service which shows the online behavior of our users. Therefore, we may record mouse clicks, mouse movements and scrolling activity within this testing environment **only**. Hotjar does not collect personal information. More information can be found in https://docs.hotjar.com/docs/what-is-hotjar 

Please be aware that everything you enter in the MARLO testing environment may be removed from the database at any time. 

------------------------------------------------------------------------------------

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-6837a91a5342c5c350d0e36e7dc6d20d5fd2651a8399ee0a03a1946b0d9a84f8.png)
