### ISSUE TITLE
Supplement project leaders

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#612]
Project leaders for Supplement projects are  not being displayed correctly in the system:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-26805c11d52f02567166e74be8b025e994777dc1ce3177c89ff1dcf1964b8c12.png)

**Comment by sebas932** [comment]
This issue is done

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-aecf8217648c62cbfb05611b35e86c34094efeae87da42bc5ad72b7b7b55f1b9.png)
