### ISSUE TITLE
Order Flagships alphabetically

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#614]
Please order the Flagship list alphabetically

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-bf8f6bbcca0a1530f73d7a79d4c025f85977957df1935b54cd76171412e33f5e.png)

**Comment by cgarcia9106** [comment]
![order fps.PNG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/order%20fps-1dfaaa735995da52ac0890ac9ab56ba7365d2fe81aff39256d110c2d5157db61.PNG)
