### ISSUE TITLE
Previous deliverables should not appear for planning

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#616]
If we are planning for 2017, we should not see deliverables that already were reported. Instead, they should be displayed perhaps in a separate table.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-fc4c6cf882c2fc939c162b14b4c7ffc6ba3826b20313a3586ddd10a036d2b0f5.png)

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-700644941d61b891fffbc5e9644d7f703218b2ea07e3e118ccee951152f7a882.png)

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-a59e3cc0f2763566ea6373078ed4b4a1f45341153a73e15deece30581c2b8194.png)
