### ISSUE TITLE
Management Liaison Contact Person its inconsistent in CCAFS Projects

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#619]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-f1c8a50bf276bc2b88f6104499ba0ebc275b74b00fe7233d5990a7378d854c77.png)

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-14c74c94666217961e05275e330d064d1a40d0967ac111bca7702fb5c2f44c73.png)

**Comment by htobon** [comment]
According to @cgarcia9106 this issue was fixed in the new baseline.
