### ISSUE TITLE
Include a CoA identifier field 

### ISSUE THREAD

**Issue by carios1usb** [CCAFS/MARLO#620]

**Comment by carios1usb** [comment]
![Capture.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture-8d746eec0f0a8fe9e5dca4c656d1b14e887088ab663820632073b731a9c04c1a.JPG)

**Comment by htobon** [comment]
Great @carios1usb. 
May you please attach screenshots for other sections where the CoAs are listed?
- Project Description
- Deliverables
- Budget by CoA
- Project Portfolio report (the one that is generated in PDF format)

Thank you in advance.

**Comment by carios1usb** [comment]
Project Description:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-fa9684c985e8e8aa0d05b89a361525a87a5889b814e179ab5642289d96209a95.png)

**Comment by carios1usb** [comment]
Budget by CoA:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-65803f170b040f6eb34c67ead2af7d24a5009fd445134fa5f67676d96c451717.png)

**Comment by carios1usb** [comment]
project description in the pdf file:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-11824558aba2f0b7e5125097037b63e6b57d76c76e3201e3aa6183e060cbb7bc.png)

**Comment by carios1usb** [comment]
Budget by CoA in pdf file:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-237f90f7bf02a70feb0e3c82cb69b4357689ce6c737d84b5cef2bfff3abf2ff5.png)
