### ISSUE TITLE
Fix the full graph service 

### ISSUE THREAD

**Issue by carios1usb** [CCAFS/MARLO#624]

**Comment by htobon** [comment]
@carios1usb, what is this issue?

**Comment by carios1usb** [comment]
@htobon ,the service give me duplicated data.

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-c4ba849671104ae631feefe8269584e19a7d6460b084511e1302990ef033c3af.png)
