### ISSUE TITLE
Validation problem in CRP-Admin / Custom Location section

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#626]
I just clicked the save button in the Curstom Location section and got the following warning message. However, I cannot see what is missing.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-1289c3589d05428a6171af6d08c4cfc21a999a8d1c9b6723eb37b9be5b13609d.png)

**Comment by sebas932** [comment]
Moved to the next milestone

**Comment by cgarcia9106** [comment]
![locations.PNG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/locations-48e50a5ce61ef43ac7c9c2420f8332beeb5a592ff24b78c74325f5a9e74307ff.PNG)
