### ISSUE TITLE
Change limit words acoording to David and Tonya Feedback

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#628]
`CoA should have 20 words for titles max`
`Milestone should have 50 words max`
`Key outputs should have 30 words max`

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-2cf4e9462c959f098911a97299e485c1563f09c612476286e04ff707200d64d8.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-611a1d35d38dcc7d30d5fd692437ff648e16a4c6fb76eda1d5a0542a220fdb5e.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-87e01dca4c18ffcfe9d46eab07da4fd443523bd7e84a88a317d65007bd90673b.png)

**Comment by htobon** [comment]
Great, thks @carios1usb
