### ISSUE TITLE
Can't complete Deliverable section

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#630]
Can't complete even if i fill all missing fields on ongoing projects of 2017 onwards.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-db22a2a495e74a46d7c7b5f4066aeaa315940ad16948c5140c4930dd80f91fd8.png)

**Comment by cgarcia9106** [comment]
![deliverables complete section.PNG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/deliverables%20complete%20section-2e65dfa8368f66bb7fd453cf628917d873b88a6e3dd4b6bf80139f70365b6759.PNG)
