### ISSUE TITLE
Fix format for cluster of activities in project description that doesn't has an identifier

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#635]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-fae23f646a6566ab22e695f59b1dcc05095baecb0167fe9e8905ee0ad45a6128.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-68d1d115dd8ccfa187957e8041bec97c7609c60623bf156f5bcf5303368b1c2c.png)
