### ISSUE TITLE
Issue validating CoAs section

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#636]
Please refer to the screenshot below:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-491681aa515c520ed4ebc86ca15d18deef6f8579e9e9423f1cea9ef4d0705fba.png)

**Comment by sebas932** [comment]
Moved to the next milestone

**Comment by cgarcia9106** [comment]
![coa validator.PNG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/coa%20validator-ef6a3266134a981ec93524da1b8e4805edcb30cab468f95b069b5e871f2ba824.PNG)
