### ISSUE TITLE
Add a description field for Funding Sources

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#638]
Please add a new field for entering the "description" of the funding source.

Requested by Pascale:
>In the pop up window for entering bilateral/W3 projects, can we add a "Summary" field? Oftentimes the title alone is not very informative

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-90eeab21c5937ecd19fe13b181547ba93dd5efdb05e3e40670e1b8593489d3d0.png)

**Comment by htobon** [comment]
Sebas, may you please make the title field smaller?

**Comment by htobon** [comment]
Please attach an screenshot

**Comment by cgarcia9106** [comment]
already has screen shot!

**Comment by cgarcia9106** [comment]
@sebas932 Sebas, may you please make the title field smaller?

**Comment by htobon** [comment]
Pleae also include the screenshot in the Funding Sources section.

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-904244e1c837dcf975efd106fd581d32366a3afbad8c29810ecf44f25bfbbd47.png)

and the popup

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-9df0566a002c6a902a76358e4a8559edab9216cc2f5409480c2c9a2114b51df6.png)

**Comment by htobon** [comment]
Great, thks!
