### ISSUE TITLE
Document how Shiro works in the system

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#64]
Develop a document that describe how Shiro is set-up in the system, how is its architecture and how, as a developer, can be used to assign permissions to the users. The idea then would be to include this documentation into the Github Wiki section so other developers can understand easier and work with it.

**Comment by HermesJim** [comment]
I create a Spanish Draft Security Document 

https://drive.google.com/open?id=1jH4_-5fCtOXFnHmQye1vvBOHuCqTT-B1s0zyYzQOxQ0

**Comment by HermesJim** [comment]
I Create a English Draft Document.
Please help to fix my bad english .

https://drive.google.com/open?id=1llUWslEnctHudMtfVsAsdcIKAZP2gHlbQ4z7VGho1cY

**Comment by htobon** [comment]
Thedocument needs to be improved as per comments from @htobon

**Comment by HermesJim** [comment]
I update the document ..
add the shiro wildcard image.

https://docs.google.com/document/d/1llUWslEnctHudMtfVsAsdcIKAZP2gHlbQ4z7VGho1cY/edit#

**Comment by htobon** [comment]
No.. it is not finished yet. Let's discuss in detail how we can improve it. Sorry.

**Comment by HermesJim** [comment]
OK no problem. We were pending changes we can make to the document.

**Comment by htobon** [comment]
Closing this issue.
