### ISSUE TITLE
Deliverables: Can't delete new deliverables.

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#640]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-f85c05a6177734fc2b8a502038f3b29a08c3acf4c81c449efb415ebac587d329.png)

**Comment by htobon** [comment]
Please attach an screenshot

**Comment by cgarcia9106** [comment]
![to delete.PNG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/to%20delete-370483005bfc1bc41ac15f2f0ab400f9472e50afdbc479d8c0696c817dd9d325.PNG)
