### ISSUE TITLE
New Contact Point for ICRAF

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#641]
**Task 1:**
Please assign Todd Rosenstock as Contact Point of ICRAF. Please keep Henry Neufeldt.

**Task 2**
Please unnasign Contact Point privileges for Audrey Chenevoy. Please also keep in mind he still will play the role of  Project Leader and Project coordinator for some projects.

**Task 3:**
Please assign Todd as ML for the project 207:
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-a560b9f14e20b77f8e5f8a644de47b9875cf662f364efe10e84ef605b926f14b.png)

**Comment by sebas932** [comment]
Moved to the next milestone

**Comment by HermesJim** [comment]
I update these information in MARLO production database.

![image](https://cloud.githubusercontent.com/assets/13221179/20405288/6c5128ea-acd6-11e6-8cbe-9d1342f7f147.png)
