### ISSUE TITLE
Save Funding source in deliverables section

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#642]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-2b46c5050ff6dd2110eab3aa1afb2f05d4a4e37fc73632eb1911549e8e5832fb.png)

**Comment by sebas932** [comment]
Remember add this as required in the validator

**Comment by sebas932** [comment]
Will be implemented the way for adding more than one funding source to the project

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-73494b28fbefadd7da0ffe0b05f497756a0c1bddc04a928a17bf0828f8c9b788.png)
