### ISSUE TITLE
Fix validation for CRPs that doesn,t have regions in project description section 

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#643]

**Comment by htobon** [comment]
Please attach an screenshot

**Comment by cgarcia9106** [comment]
![regions validator.PNG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/regions%20validator-a8823a37e67cb769a5318ecfc182cd88dfe3b9b9ceaa23a5c83242218d9c032f.PNG)
