### ISSUE TITLE
Add gender question in CRP Outcomes

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#649]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-08d8555e736beb72dae2e865c97eccb3b128f66f4d109d538b22d5ac3719efc3.png)

**Comment by sebas932** [comment]
@cgarcia9106 is still pending save the information

**Comment by cgarcia9106** [comment]
wont fix

**Comment by htobon** [comment]
Hi @cgarcia9106, may you please kindly let me know why this issues is not going to be done?
The gender should be asked per Outcome in the CRP Outcomes section.

**Comment by htobon** [comment]
duplicated #665
