### ISSUE TITLE
Order partners by name

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#653]
When loading the partners list into the partner section, please load them by name.
Currently the firstone that is being dsiplayed is WUR.

**Comment by sebas932** [comment]
Moved to the next milestone

**Comment by cgarcia9106** [comment]
![order partners.PNG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/order%20partners-4115bf95c4ade0d54450d598ee3083b19f5f5f7a02cc5a91c3a1588aada18857.PNG)
