### ISSUE TITLE
Upload contract to Funding source popup/editable interface

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#656]

**Comment by cgarcia9106** [comment]
![email.PNG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/email-5bbe1bc54464df5124cc203ad9a325787520e15995d32b069274adefbd800f9f.PNG)

**Comment by cgarcia9106** [comment]
![file fu.PNG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/file%20fu-47fe8a6f3bf00bfb2539b85a38276be4f8232b7e41d57789ba816cd213c3b663.PNG)
