### ISSUE TITLE
Hide Outcome contribution percentage in Key Outputs

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#659]

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-a1dec205591c77ef7b4e2207e9f44706d3f6035a95cd37b54bcddef0ff047649.png)

**Comment by sebas932** [comment]
@carios1usb  please calculate the percentage of contributions automatically.

**Comment by htobon** [comment]
@carios1usb, please take a look at this issue and close it when it is done. thks

**Comment by carios1usb** [comment]
@htobon , this issue was solved through the issue #682
