### ISSUE TITLE
If the funding window is "center", automatically set the institution as a donor

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#661]

**Comment by sebas932** [comment]
-[] Take out yellow message in funding source

**Comment by carios1usb** [comment]
![Funding popup.gif](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Funding%20popup-07acc3bae11c0efa9d2b791f09ddc55e0d6a79b3933470a0935a38eee8580a50.gif)

**Comment by sebas932** [comment]
Thank you @carios1usb
