### ISSUE TITLE
If the funding source is a center, the donor will not appear.

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#664]

**Comment by sebas932** [comment]
If the funding source is a "center", the donor field will automatically selected and disabled

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-1f1fa12ff53399022d7f9adb81aae12238466715c4aabcce70593a7218191c45.png)

**Comment by sebas932** [comment]
@carios1usb could you apply the same rule in Funding source editable view.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-0ec0653fd92513a12e544aac58fd50df0981b9b7902c3ef57b70fe8b4cdb922e.png)

**Comment by carios1usb** [comment]
Done @sebas932

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-b8bc0353d4c16aa9f64d7afd4d8b319664e05f216a40ac1ff4ec7299971d0ca1.png)
