### ISSUE TITLE
Update new deliverables classification metadata

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#667]

**Comment by sebas932** [comment]
Verify status and ask to Paola about classification table

**Comment by htobon** [comment]
Hi everyone, Paola just sent us the new classification to @cgarcia9106 today.

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-0d06dc99aa5e8f2e1d05e20a97364791f363708da8611a79ba70da6257b31f3c.png)

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-bb007a322b5a6a9f713973d860ae942e0a656b4f5d527035d60786f4ab141286.png)
