### ISSUE TITLE
Update countries list.

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#67]

**Comment by htobon** [comment]
Hi @cgarcia9106, would you please let us know from which site did you update our list of countries?

**Comment by cgarcia9106** [comment]
on loc_elements table

**Comment by htobon** [comment]
mm I see... We agreed together that you were going to look on the internet for an updated list of countries, as the current one is possibly out of date.

**Comment by cgarcia9106** [comment]
Remove countries
BruneiEast Timor
Falkland Islands
Holy See (Vatican City)
Hong Kong
Macau
Macedonia
Micronesia
North Korea
Pitcairn Islands
Republic of the Congo
Saint Barthelemy
Saint Martin
Saint Vincent and the Grenadines
South Korea
Svalbard
Syria
Taiwan
US Virgin Islands

**Comment by cgarcia9106** [comment]
New Countries 
Aland Islands
Bouvet Island
Brunei Darussalam
Hong Kong, Special Administrative Region of China
Macao, Special Administrative Region of China
Congo (Brazzaville)
Congo, Democratic Republic of the
Côte d'Ivoire
Falkland Islands (Malvinas)
French Guiana
French Southern Territories
Guadeloupe
Guernsey
Heard Island and Mcdonald Islands
Holy See (Vatican City State)
Iran, Islamic Republic of
Korea, Democratic People's Republic of
Korea, Republic of
Lao PDR
Latvia
Macedonia, Republic of
Martinique
Micronesia, Federated States of
Myanmar
Norfolk Island
Palestinian Territory, Occupied
Pitcairn
Réunion
Russian Federation
Saint-Barthélemy
Saint-Martin (French part)
Saint Vincent and Grenadines
South Georgia and the South Sandwich Islands
South Sudan
Suriname *
Svalbard and Jan Mayen Islands
Syrian Arab Republic (Syria)
Taiwan, Republic of China
Tanzania *, United Republic of
Timor-Leste
United States Minor Outlying Islands
Virgin Islands, US
Wallis and Futuna Islands
