### ISSUE TITLE
Show remaining budget in search funding sources popup and add a link to go to the funding source directly 

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#670]

**Comment by carios1usb** [comment]
![Funding popup.gif](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Funding%20popup-c2ece4f7bf5504c0e60d7501bc54e485c5d781340e1493f206c9a2429ee0c6ba.gif)

**Comment by sebas932** [comment]
I made a minor change in the remaining budget currency, thank you @carios1usb
