### ISSUE TITLE
List CoAs alphabetically by ID in Project Description

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#675]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-c11d1271974a371ca1d9b293ae1bf97b737ef7c0aced776529f1bdfd8119709a.png)

**Comment by htobon** [comment]
@cgarcia9106 please, include screenshots.

**Comment by cgarcia9106** [comment]
![coas.PNG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/coas-b55155c504efead51b4cb94dd74d59555138b4d0c3ca9072641158a236cfbd88.PNG)
