### ISSUE TITLE
No decimal digits in the contributions percentage 

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#677]
Reported by Tonya/David
It should not add the decimal digits in the contributions

**Comment by sebas932** [comment]
@carios1usb could you do this for Sub-IDOs contributions

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-d30d22238e0b416f6c46b972e8df1997a1806b96500aae880b491980394b2343.png)

**Comment by carios1usb** [comment]
Yes sure! @sebas932
