### ISSUE TITLE
Glossary link 

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#678]
Reported by Pascale

`"To view a glossary of relevant terms click here". I clicked and did not see the glossary`

Maybe "Click here" should be more visible

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-9cfd4797f357e42759d7bf465a12c436c39070f410f731730c14a460db36834d.png)

**Comment by sebas932** [comment]
Thanks @carios1usb
