### ISSUE TITLE
Issue with PPA Partners in PIM 

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#679]
Reported by Pascale 

`When entering new partners, it seems that any CGIAR center is considered PPA partner by default, irrespective of how I have defined the PPA/managing partners in the admin. I understand the logic, but we should revisit if indeed PIM only has a few CGIAR centers as managing partners (other centers being called strategic partners or collaborative partners).`

**Comment by cgarcia9106** [comment]
![ppar partenrs 2.PNG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/ppar%20partenrs%202-84a1aae0b8ff60a4dda4d49402dd781886ad03d965daf0f34bdeaf191414c118.PNG)
![ppa partenrs.PNG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/ppa%20partenrs-268df4620f30ca05409b6f712682145c16609a975129858e1da27e9d13a8ef65.PNG)
