### ISSUE TITLE
MLs should be able to select W3/Bilateral/Center Funding sources to projects

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#681]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-a62f45d5f329dc89bfae16c9f31cd2d85c1ec1fbd8eec2cffd5956dfb86ef54a.png)

**Comment by htobon** [comment]
@sebas932, @cgarcia9106, may you please let me know any advance on this?

**Comment by cgarcia9106** [comment]
![permissions w3.PNG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/permissions%20w3-ee91f76b145d3211c1c60563ce921046e60f206675bfea29c809e3112cd6b64b.PNG)
