### ISSUE TITLE
Hide Key Output contribution percentage in Cluster of activities

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#682]
@carios1usb this issue is similar to #659, please calculate the percentage distribution automatically

**Comment by carios1usb** [comment]
I solved this issue and the issue #659 

![Capture.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture-f3af96e2cb40b30d0f901a4c0d0f613faa95b1d87f1aaff2f36b6aa11b406d2b.JPG)

**Comment by carios1usb** [comment]
![Capture2.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Capture2-079524bcf026f1917d36a0e5a682b0597f82c6a4b6efd36602d7cf9833702c0b.JPG)

**Comment by sebas932** [comment]
@carios1usb please show the key output contribution again
