### ISSUE TITLE
Footer email

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#683]
My email is pointing to an URL which is wrong. 

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-6cb234f794f5e615620dd767a45f8c0a74021f5ca9ab9b640c17072503864d7c.png)

**Comment by carios1usb** [comment]
![emailto.gif](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/emailto-6c4f77d61feb3b897ab79ae1673098ecc66992321b98977ae3ac02621737148c.gif)

**Comment by htobon** [comment]
Thank you!
