### ISSUE TITLE
Update List of Sub-IDOs from our SRF

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#685]
Please kindly make the suggested changes according to the screesnhot below:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-e8367d3dc9cd5b73546a908df4c5406226f5febf3db90c0ed4cfba33ba777880.png)

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-db42b9015ba2a68877fcbba57c355f079504ac172abc835c3ba92d67d9edecb8.png)

**Comment by htobon** [comment]
Please fix the typo.

![image](https://cloud.githubusercontent.com/assets/5375915/20312299/f82f8b20-ab20-11e6-8035-2acd7cc17c82.png)

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-30772722a6b49fb648125713b2942ca0d2f43944296b3c8d6e6a6be3c8c8bbd1.png)

**Comment by htobon** [comment]
great thks.
