### ISSUE TITLE
Emails with credentials is not working

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#688]
The email that is being sent to new users is not sending the information to access the system. Please refer to the screenshot below:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-d398bcb6aa14881f45ac5dc7e3d6f645829b28361ea4c72e8df556548a73e48b.png)

**Comment by htobon** [comment]
Christian, please apply the following changes:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-4b8b19a9868fb6c8f6ed0cd58d634b44f9a42a6faecd46828cda9a52ba3126fa.png)

Thks!

**Comment by cgarcia9106** [comment]
![email.PNG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/email-7fa29c8efc720f7fca152d4a165e622b28b9cecfa1edebfbc19b599808debb21.PNG)

**Comment by htobon** [comment]
Still missing the extra line after the two points.

Please check my comments again.

**Comment by htobon** [comment]
@cgarcia9106, may you please let us know any advance on this?

**Comment by cgarcia9106** [comment]
![Credential emial.PNG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Credential%20emial-a46559fd13e97bd1c04dda3c7197af95b10045061df55c20d07f46f02b8c81f6.PNG)

**Comment by htobon** [comment]
@cgarcia9106, please connect to slack.
The "new line" should go after the two points (:).

>Please use the following credentials to access the platform:

>**Link:** .....
>**Email:** .....
>**Password:** .....

**Comment by cgarcia9106** [comment]
![Credential emial.PNG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Credential%20emial-6ee42efe0efbf6aadd3310eab21f0df6e52ec10cce9008b80646591d0ada6bf0.PNG)

**Comment by htobon** [comment]
The link is not clickeable.

**Comment by cgarcia9106** [comment]
![Credential emial.PNG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Credential%20emial-8e890a0719a2a98bcf923dccb98865639f909e9862e5c0b8d33849bdeb617122.PNG)

**Comment by htobon** [comment]
Finally finished. Thank you.
