### ISSUE TITLE
User display problem

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#689]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-fe15a82ad52b267f356cd66ced8e6b8510eebbdbaf30897a61ac8986f1aaaa3e.png)

**Comment by sebas932** [comment]
@cgarcia9106 could you check, i think this come from the database ?

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-6c0e74999ccc5253f077b0dd6b4d9c0a36bac9c9df04d69de30055e51ef0eb9e.png)

**Comment by cgarcia9106** [comment]
Revise que la talba estuviera en utf8

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-83399e77f8bd5a749bfb9bdbb9f9de31e75c7ca20cb18cf2d99ca5547d73eba4.png)

Corregi dos usuarios que tenian este problema , quizas fue un errror de migracion trallendo los datos de p&r
