### ISSUE TITLE
MARLO Users list

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#690]
Please create a MARLO users list in the same format as we did it for P&R.

Thank you.

**Comment by htobon** [comment]
@HermesJim, may you please let us kno any advance on this issue?

**Comment by HermesJim** [comment]
I created the Marlo user list based in the Data baseline put in the production database.
the infromation was created in te follow spreadsheet

**Comment by htobon** [comment]
@HermesJim, may you please check again this list?
@cgarcia9106 and me were making some changes recently.

thank you in advance.

**Comment by htobon** [comment]
@HermesJim ?

**Comment by HermesJim** [comment]
Yes Hector.
I has updated the list at 12/7/2016
