### ISSUE TITLE
Deliverables - Aclaratory message for new category classification

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#691]
- [x]  Please include an aclaratory message in the same way as the screenshot below.

The aclaratory message should reads as follow:
> *Due to improvements in our deliverables classification, may you please check that the category and subcategory for this deliverable are well classified?*

- [x]  In addition, please also include the popup we had in our previous version in P&R

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-6d5c21f6da6aec9eaf7de0285745e06759e8d4aea55f98e8ba2e78673dfbfdd4.png)

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-3ca6212126b9796fb2079dc8bfe3c22994aadb5ab0929e0bc65eb4c9ffdc29e3.png)

**Comment by htobon** [comment]
@carios1usb, may you please let us know any advance on this issue?

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-b4ba95b4311085d9680e3edd5c46db89b2ec3787a29532c27f9ff21ba1ecde28.png)

**Comment by htobon** [comment]
Hi @carios1usb, please fix the typo.
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-65c51042c11707bc50b883e26721bf50cf3306dfe0b41024fbc185e4bf2596eb.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-ad53ea98f6d867b43bd8bd5cdb0a11eb6b89531f0a75850dd0430929ea4e50e1.png)
