### ISSUE TITLE
Fix contribution error in Impact pathway

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#693]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-922d7a4de6e5a0fd7aa8cd6f6a66e477ac2644aea777a277963ec6c817790d9b.png)

**Comment by htobon** [comment]
@carios1usb, please check this as soon as possible

**Comment by htobon** [comment]
@carios1usb, please close this issue when it is done.
