### ISSUE TITLE
Question required in Partners section

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#696]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-e00690c85d784214b2d672c7222c42768d26abb2aa01afb03228164bd100546e.png)

**Comment by cgarcia9106** [comment]
@sebas932  poner el *

**Comment by sebas932** [comment]
![image](https://cloud.githubusercontent.com/assets/4406128/20500453/77cb56e8-b003-11e6-9803-d807ed949119.png)
