### ISSUE TITLE
Rename label in Program Management and Regional Program

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#697]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-2763e7bd4e066e7cd153af379bc35c06d364a719ab942bbb365a0abeef660ff3.png)
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-7870d4985bb5e29c7697d0360d0c8661bddac22306bdd04f3d1313b82282aa64.png)

**Comment by sebas932** [comment]
Done

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-5f5288cb4a619d59731fce07b91f8d8219c527da60206862e85ed3191956960d.png)

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-0b0a704fa069e766666a2acacbf634d79dd2c5076c4d7cfe7c43de6335880c69.png)
