### ISSUE TITLE
Impact Pathway submission

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#705]
Please include the year when submitting an impact pathway:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-9adda230b019a55f0effac42beddcb11dd1118e82b124c64da22108b8c74482c.png)

**Comment by cgarcia9106** [comment]
se le pone el year de planeacion ?

**Comment by cgarcia9106** [comment]
![years.PNG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/years-5081f5a7207d78563424f9f673a1557d7e77a6675cb0b6d0b5d5f691216dbd21.PNG)

**Comment by htobon** [comment]
Yes, thank you.
