### ISSUE TITLE
Justification in Cluster of Activities is saved as "a" as a text

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#707]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-301c3b5473f42854a21ca2b6cf1bbe45b472fded17a753c99500fe60c6323a95.png)

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-d884a908f4d6f4812166caca4c4f1b7f759d134a86b3e14ff0610e8f5c67ed6a.png)
