### ISSUE TITLE
Confirmation Popup when changin project from pre-setting

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#709]
Please take a look at the following screesnhot:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-5bedb41c60eaf1c408e5e387bfd386c34df6aaf0150653a94e76faa9b1a6c636.png)

**Comment by sebas932** [comment]
@htobon what is the message if the user change of "Yes" to "No" ? 
I think should be something "Are you sure this project will be editable only for the management liaison?"

**Comment by htobon** [comment]
What do you think about thisone?

"Are you sure you want to make this project to be in pre-set mode? it won't be able to be edited by the Project Leader and/or Coordinator"

**Comment by sebas932** [comment]
Done !

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-e02c482dce31065095800149e7f70dd0820ef3a352d35006c5277d46ae5e61d3.png)

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-cd4efd3e50f95f81e375ec41ce011b6ba8b603267f1b0666b7ad481fb170d635.png)
