### ISSUE TITLE
Check CGIAR AUTH for test and prod

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#71]

**Comment by htobon** [comment]
Person in charge was on holidays. We will talk whit him this week.

**Comment by htobon** [comment]
Waiting for the new library developed by IT.

**Comment by htobon** [comment]
I just talked with Jose Libardo. The library is expected to be ready by the end of today.
Let's see what happen.

**Comment by htobon** [comment]
Jose Libardo sent today the new version for the library and a user manual. As we are at the end of the sprint 4.0.3, we will implement it but the new features will be developed in the next sprint.
