### ISSUE TITLE
Take out Close [X] icon from the help texts

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#710]
Please take out the [X] button from the help text boxes

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-2b25e9be23fb62759929ab42e58cdaf4519bea939bcb42025a8e0f56e2bc83d5.png)

**Comment by carios1usb** [comment]
Done @htobon 

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-eb2fd39020079391616034f1d0f48abf191452266e2d972d5c7e7b613b7f6982.png)
