### ISSUE TITLE
If the project is submitted, Project Outcomes section can't be editable 

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#711]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-adf64e949cce2da5fdff18b9c5d227d2432197e4c29d01b5667a0d4b3491acd3.png)

**Comment by sebas932** [comment]
Same issue for deliverables section

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-b7e47fb7df45cc60edad49e378afdc75575ce556dcf152cc7dd16865c48d9662.png)

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-b535a0d12adb6073aa263c76b9cd38aee502e0aa92a4ea668ab791a7c010d012.png)

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-db8a4f3cfe597c84c13d8dcc397c75def89989ab6b1226fa732971226159f7e2.png)
