### ISSUE TITLE
Order PPA PArtners alphabetically

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#712]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-23539468b2e3e57ed49a51512dd9cca35bf3e8ab9567e27fc47e0540db31b637.png)

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-ae0045733d09627e1ff6b74db2b56705b9147fd06a4ef0a7741fca980d1745dd.png)
