### ISSUE TITLE
Create summaries interface

### ISSUE THREAD

**Issue by carios1usb** [CCAFS/MARLO#716]

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-21111c1686f72dbbf4e5b66675ba4432ccd727af51e8f0fa69da1b1f08809390.png)

**Comment by AndresFVR** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-2726603ed9202352bc064f62b46b50afcb88def743b559b9e150ea789d23ee09.png)
