### ISSUE TITLE
Backup process in MARLO production

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#718]
Please set-up a backup process in MARLO production before we release it.

**Comment by cgarcia9106** [comment]
@htobon  me puedes explicar

**Comment by htobon** [comment]
@cgarcia9106 La idea es desarrollar un proceso automatico de backup de la base de datos cada 4 horas.

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-fb5654690fe49aa0ee070ddfc2e089deae4235f4b84d41087549b29d34d6fe64.png)

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-1c550c6631b887265ae781ff3087cc90bbb11ce75572a5756442f2138dbc167e.png)
