### ISSUE TITLE
Display only two decimals maximum

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#720]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-693a9591451e5f7d537f65811e7fad1354901350fd187a2ca250d711f794f4fd.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-c568d418a79cbe11006b146cc3ecb40c4f5db8920263a2c1cd2f80b97a164620.png)
