### ISSUE TITLE
Create Marlo Deploy Bash file.

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#722]

**Comment by HermesJim** [comment]
I Created the bash file to re deploy MARLO production when it have changes (Stops tomcat, pull git, mvn clean install, start tomcat).


![image](https://cloud.githubusercontent.com/assets/13221179/20579201/6b6a2fe0-b199-11e6-9ee5-412142d180ae.png)

**Comment by htobon** [comment]
Great!

**Comment by htobon** [comment]
Is it working now? If so, please close this issue.
