### ISSUE TITLE
Improve PDF report (Planning)

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#723]

**Comment by AndresFVR** [comment]
@htobon There are few examples of PDF report.

CCAFS New project:
[Full_Project_Report-CCAFS-P253-20161128-1342.pdf](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Full_Project_Report-CCAFS-P253-20161128-1342-07d61097e7b9268dde687d9a8d7affd5aeea41075414d13ef43aa3db6c0f7f75.pdf)

Empty project PIM:
[Full_Project_Report-PIM-P254-20161128-1346.pdf](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Full_Project_Report-PIM-P254-20161128-1346-575903275cf33d567bcac0d98b71f12781e959c3c14544422b4d1764628cbee0.pdf)

Project 2 with few modifications:
[Full_Project_Report-CCAFS-P2-20161128-1354.pdf](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Full_Project_Report-CCAFS-P2-20161128-1354-701f86e16297ed58dbe2cdbdeeceb5e20ba809da32bb7a9f8464c6dac3b5ec24.pdf)

**Comment by htobon** [comment]
Thank you @AndresFVR, please apply the changes as per our discussion in my office.

**Comment by AndresFVR** [comment]
Hi @htobon, i applied the changes as you will see in the next images. 

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-292113d17a02d0574cb28863d542f8b92e5e1240f13cfdba8e6030a1586e465d.png)

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-72e0cf78264b4bcd94659174bd5b9afa0a807ec07d187c128164ab615627a426.png)

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-37bf8d6891f8dde017c4d9da64b5db48713af81294ed026773f6ad0b8f0d66b0.png)

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-6ffb85f48fdffa7871addd49328156bc14864bc2d13dc23ece85a55014b6c826.png)

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-30d057e0a27e99e53ff865d0759512012926d27e33d7a840c3465484e68c2157.png)

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-5d4d875ffcd0495db8ed1811b150b86b2175d7e58b46bcb06ff489f79008b5bf.png)

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-5a13766e4970c55af2a7242d9ecd2fb6fb764661beb56fd522f352bcfea7367b.png)
 5 more pages of countries...
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-f4d001f0daa678a43bbb6f7c06de15899136aabc51bdf521b356d61536b7a2be.png)

**Comment by AndresFVR** [comment]
Submited P1: [Full_Project_Report-CCAFS-P1-20161201-1308.pdf](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Full_Project_Report-CCAFS-P1-20161201-1308-c107d3931b05677e6ee82e1f6ab915a646db187a192f5224fea378e1a1f0bec8.pdf)

P2: [Full_Project_Report-CCAFS-P2-20161201-1315.pdf](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Full_Project_Report-CCAFS-P2-20161201-1315-6769ea6096947c458e03fb702f25bdccd4aea0de74eddf5869419384b483be6f.pdf)

**Comment by AndresFVR** [comment]
New P253: [Full_Project_Report-CCAFS-P253-20161201-1329.pdf](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Full_Project_Report-CCAFS-P253-20161201-1329-f7155ceababd9c69c7c702fb9d2509b04e7b57daed7abe7049a64db4e1b1135c.pdf)

**Comment by htobon** [comment]
Great job. New improvements will be followed up in separated issues.
