### ISSUE TITLE
Message is not being displayed

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#728]
In MARLO-Production:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-d30223633050d2386016013e3d29e376cd5426afda35b820fa4e74c6bfeeaaf3.png)

**Comment by sebas932** [comment]
done

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-fb6e361987e9fa86782ba3b992d4d3bfe275c9ff4508e24619d25ad28ac771ca.png)
