### ISSUE TITLE
When i saved in deliverable information, the justification is always the same

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#729]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-1c3335b48f5d9aaaeefe4f12deb4ad6013f1c92f415c6bb2a385594ce9bdba5e.png)

**Comment by cgarcia9106** [comment]
Ok

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-6132ba6162456ac3489b8edcca600b3fa95089972911d981725d7fe1a9ce6fba.png)
