### ISSUE TITLE
Document backup process (Email to Paola)

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#731]
Please send an email to Paola, explaining the configuration of the cronjob for the backup process. (copy me)

**Comment by cgarcia9106** [comment]
![emails pa.PNG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/emails%20pa-03bd2e340535ba90441834f481cbfa97193551e29ea58be1ded735f50b32d85a.PNG)
