### ISSUE TITLE
Improve add deliverables visualization in Activities section

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#733]
Add a composed name with: Deliverable ID, Subtype and title

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-3e9ee60be5fcaccd0b4cb6ac3dc67c128f3e7888826593fb45e350d0f5e67a82.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-12d27adcad073b312d57838fbcd27e25c2a5f170d2feb9313e6ebc00f54ad20d.png)
