### ISSUE TITLE
Create Outcome Synthesis interface 

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#737]

**Comment by sebas932** [comment]
Created Outcome synthesis interface

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-ad44e658a88becb53c2c7125e2e9c724df843b808b7ba852e7dd19e918fa0cdb.png)

**Comment by sebas932** [comment]
@htobon What do you think ?

**Comment by htobon** [comment]
It was presented in the Amsterdam meeting and everything was fine. Will close this issue.
