### ISSUE TITLE
[Front-end] Implement reporting fields in contribution to crp outcomes

### ISSUE THREAD

**Issue by carios1usb** [CCAFS/MARLO#744]

**Comment by sebas932** [comment]
Implemented reporting fields

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-88f8ebbcbe6c67c335af20cf3586e719b93065cae60e90701e8e14b5410e9cd6.png)


![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-ccf3464ad002425bdf18d6e69a0fb44825d0ad62088cf13c0e66577ad077a072.png)


![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-706a1d3f05d81d34e6793cf3f1d1670d1436f752ec9a19f529a9ac5d3737981e.png)
