### ISSUE TITLE
Create reporting tabs in deliverable section

### ISSUE THREAD

**Issue by carios1usb** [CCAFS/MARLO#745]

**Comment by htobon** [comment]
I'm not sure what I should review here. Again, there is not any comment on clear instructions on what to do. Moving this issue to open again.

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-5f81ed443a22fb34ba5b7fbbc60e1cfd5b0cf4655a66220884c594be263277f0.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-2c34bc430eb8c1de0b76ea1df9bf39738bae061b2f391c1305cf16947e16e708.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-a111e9b65edbde16033df0c5f83b049de2e964fccb510a9abce2a324baa71243.png)
