### ISSUE TITLE
Remove continent from location levels

### ISSUE THREAD

**Issue by carios1usb** [CCAFS/MARLO#747]

**Comment by htobon** [comment]
Hi @HermesJim, Is there anything I should do here?

**Comment by carios1usb** [comment]
Continent was removed by @HermesJim 

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-f4384f9058d8f26d0dcfc026acf102f9a442358c04c3761a97234dc9d4cf4502.png)
