### ISSUE TITLE
Create Github Statics

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#751]

**Comment by AndresFVR** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-289b7f391762ed1c4d163338075faa63976354ababc549b5dbe033e25e2115be.png)

**Comment by carios1usb** [comment]
Hi @htobon , i have tested the "power bi" platform, this platform allows you to customize the graphics to get different types of reports. See below .

![reportType.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/reportType-4361aa2271b895e9af4170c472251c061d612152f03bfe9dcaf353fb7e3de204.JPG)

**Comment by carios1usb** [comment]
Also this platform allows you to get data from the repository and make reports through excel.

![list.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/list-89c9a6ea1ee5f51ee8fb74de9f64d231953f873a34348486d0f1b082815a7df6.JPG)


![issueExample.JPG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/issueExample-3a5c663e0db8db9447f840f84b570928955e1a3e7e33a5725ed62a68a9d52428.JPG)

**Comment by htobon** [comment]
Unfortunately, this task was never finished and this is not a priority now. Will close this and continue later when we identify this a real need for the team.
