### ISSUE TITLE
When there is an error saving in deliverables, some lists doesn't work 

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#754]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-d4544dff155a869d354d5dbb8e1b3d3ea550837eb971f1f28d43d6eadcdfb113.png)

**Comment by cgarcia9106** [comment]
cuales listas/
?

**Comment by htobon** [comment]
Mira el screenshot @cgarcia9106

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-874318b80974fa9e7ee44341a292c41e80bc82bf49a5c3dc0972640daaf312f6.png)
