### ISSUE TITLE
Popup Founding Sources - Link to Founding source section

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#755]
If someone click on any place of the founding source, please use the same behaviour as if the user clicks in the "select" button.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-d7943150ae007ee26daa560680d139c7a85a677bafae534a494454646b5ae343.png)

**Comment by sebas932** [comment]
Fixed

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-1f35382db5ded1f0c8bbdb43ed24717794e75f0a91777e53c834e7916a33e13f.png)
