### ISSUE TITLE
Add the timezone in date that is displayed in the last edition made

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#757]
Hi Carlos, please add the timezone on the date of the following screenshot. 

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-d5f2123da4cd25ac191a2dafb0cae08e2d3aba22168e24d8d816958744f5237a.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-37c14a5f47e02e3575d594008228c826492e3bb6847bef6e145e6e4ee6b14d7f.png)

**Comment by htobon** [comment]
Would you please test it in the same timezone used by the server and attach an screenshot?
Thank you in advance.

**Comment by htobon** [comment]
@carios1usb, it is not working as it was before. <ey you please check? The following screenshot was taking from MARLO-production:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-1fddafac31cc2cc4682143567f4a9871dd3824491910ed56a577cf78bad78773.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-4d07e3cae000c40376becd8574562db2988be7ab33b7b44cd5c1585df51c7706.png)
