### ISSUE TITLE
"Succefull saved" mesage doesn't appear after saving in project locations

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#758]
And the field validation is not working and the draft is not deleted

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-352b9f45eb01e083c9797da66771bcb75b42f36e90732e8f74ac5e2db202ddc6.png)

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-492f5475706e36298976a2f3a37e6cfeecb691e326b2328c52bfd9e67af1390b.png)
