### ISSUE TITLE
Validate expected value in project outcomes (0 and positives numbers)

### ISSUE THREAD

**Issue by carios1usb** [CCAFS/MARLO#765]

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-47f289240f01a18487349bf0b7f4ce3f77c30823615374e6dbc4901f3b2ac198.png)

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-a4143ee671b80e7dd71cf538393bfe67cf9e2c9aac410f762956cbb637bd3588.png)
