### ISSUE TITLE
Create basic Interceptors

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#77]

**Comment by htobon** [comment]
Which interceptors?

**Comment by HermesJim** [comment]
To validate authorization and permissions before executing an action, run the following interceptors:
-requireUser
-keepRedirectMessages
-accessibleStage
-trimInputs
-validate {Section} Parameter
-canEdit {Section}

**Comment by HermesJim** [comment]
Closed, Marlo've The Basic Action Interceptors.
