### ISSUE TITLE
Glosary - order by alphabetically.

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#770]
The Glossary is not order alphabetically.

![image](https://cloud.githubusercontent.com/assets/13221179/20931485/3bff9d84-bb9f-11e6-956e-d8b16578eebf.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-f39f7fe96aa9b0ba717802115b1d26b75c34b50958275f8cd78f39d9d2225593.png)
