### ISSUE TITLE
Delete "Points" in Request partners PopUp

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#771]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-34e86c2df4cea87dc2855052e0f1eb5f8f8cd454309a3524cab7355f198f641e.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-d91f1665010c78b04395e9675e5a58361d21b5e4f7d53b153ceb1b901f65e55c.png)

**Comment by htobon** [comment]
Por favor no olvides incluir el texto que estaba en los cuadros grises.

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-7f060eafa4b09d2bc54b617ab02a7f6c8b257117d2949a0d4ebb7d549d1e8ee5.png)
