### ISSUE TITLE
Bug in Funding Sources

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#774]
Reported by Amanda:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-5c7d230c136cab962af8dceaaa698df2530d229070c53349d296c3eb9c57e73b.png)

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-f8c562fce6719ae491e4b97b381fa715fab1f71bbc321985f647b37d620d731d.png)
