### ISSUE TITLE
Create SearchTerms Summary xls

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#775]

**Comment by AndresFVR** [comment]
@htobon I finished this report, you can find below a few comments

Projects: 
- Outcomes field has been removed because now the relation is 1...*
- Search applied to :  "Project Title" and "Project Summary".
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-6c02ef3984cf3da4bd938261409c12d6d3cf63a80620350b163cad35a6c3c5b2.png)
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-0dd161a5b79469554d64e1c922b4e8df057f56a85a0529a3dbcd295cc170c36a.png)

Activities: 
- No changes 
- Search applied to: First to "Activity title" and "Activity description" and if and only if ocurrence is found on the previous fields, search is applied to "Project Title"
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-9c6d678ea379a9a4d30b6a3ab7c1b10522c772077867edf116bd8a0ee0d72e55.png)

Deliverables: 
- Fields that were deleted: Next User, Knowledge..., Strategies.
- Search applied to: First to "Deliverable title" and if and only if ocurrence is found on the previous field, search is applied to "Project Title".
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-f65fc79d04c60a5dfe1a543d2e2792d10da341ce6e040415ac2dccad5c3d9efc.png)

**Comment by AndresFVR** [comment]
[SearchTermsSummary-20161214-0908.xlsx](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/SearchTermsSummary-20161214-0908-b7a9c223568af664ccf0556bf8605bc5dd9214960b5bc347c625b0ac7461faac.xlsx)

**Comment by htobon** [comment]
Very good job Andrés!
May you please come to my office tomorrow so we could revise some details together?
Thank you.

**Comment by AndresFVR** [comment]
@htobon According to our conversation i updated the report:

[SearchTermsSummary-20161220-1624.xlsx](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/SearchTermsSummary-20161220-1624-81d2db94e743cf47883ad25e516fb4202e056c8a41b02a915af99a1685a09954.xlsx)

**Comment by AndresFVR** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-412cb30f4b5dc986d222d236b9ce774a682d841fa5b93e7ce27112a98e8de707.png)

[SearchTermsSummary-20170111-0852.xlsx](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/SearchTermsSummary-20170111-0852-a7b0f629802feb3a280ea86f8bb61cdec43c26f5a0b9de9618cfb1cb51e93fe5.xlsx)
