### ISSUE TITLE
Fix Key output read text

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#777]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-795c997b05a1d4ed82927949c3748b476f1733c83b8d008c2116afe3724d03da.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-2a9d458da317982cfaa1e7f07d95401372c1fe50f0857c6420a20c702be7d3d5.png)
