### ISSUE TITLE
Repeteaded words in the deliverable type list

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#778]
http://screencast.com/t/C3ChCg4tjM

**Comment by carios1usb** [comment]
@cgarcia9106

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-2e869906452f9627f267f5a7399803263ca6dadb705181923e9025aeeafbc5bd.png)
