### ISSUE TITLE
Icon for Global location is not clear

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#779]
Setting a project as global is not very intuitive at the moment. Please improve the question:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-daaca6779aa92aec7ca7357920dc9bb51389a5019df9bbc70570bef028a4e47c.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-61816b00909e57a032b5bf6c1dc49247cc932a4908bad2b7c6a9379355b8705b.png)
