### ISSUE TITLE
Add logic on PDF to Administrative projects

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#781]
En los projectos que son administrativos:

Description ocultar los Coas y los fps y los rpls
Ocultar la seccion de crp contribution
Deliverable ocultar el key output

Nuevos cambios: 
Eliminar gender de description
Eliminar cross cutting de deliverables.

**Comment by AndresFVR** [comment]
Administrative project test:
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-1c0534d12b8b4fdbc57f521946d8ce405d16712f190ac1565631b40f178c8ad9.png)
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-3a6f6c2a6eafd835285a863a7c2811869c28c5241c7e28181ffd81d9207e7784.png)
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-d457576fbe1bba84c9d9d7f5b41e2444b44d6be29fc6082a04aae64d48d31fa2.png)

**Comment by AndresFVR** [comment]
Not administrative:
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-66580c800901424c06a302e9355d3320d6b30e20e369e51a153fcc797a5ca58a.png)
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-3c6307b6ddf8100fd45add702b8eec1b0044c2cb5055518a4e4e9e33005fb931.png)
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-2d082e0c93b18c1c8b53f5c5ce90d404a911af4ad747349d8d94809be4877316.png)

**Comment by AndresFVR** [comment]
Administrative:
[Full_Project_Report-CCAFS-P322-20161221-1111.pdf](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Full_Project_Report-CCAFS-P322-20161221-1111-a3bee15054b3c80f0da76d4c4a08c8a76986a77bd720facbf022559ecc3fd2f1.pdf)

Not Administrative:
[Full_Project_Report-CCAFS-P1-20161221-1116.pdf](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Full_Project_Report-CCAFS-P1-20161221-1116-0f25841348b69151c2d8f6650dfdd4e315cdae0ef152615daafb852f682a1302.pdf)

**Comment by htobon** [comment]
May you please come to my office so we can discuss in detail about these reports? thank you in advance.

**Comment by AndresFVR** [comment]
@htobon I made the following changes:

Titles:
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-d80594eeecbb76b92be166e74a31ea8a62647098ffa6fc10b061ebe197bc39d0.png)
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-cdab5ccfa8b5620235071a4a85acbc7d280a353830fc97fa7cf7c0288dd2846c.png)

Hide Gender:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-d881474d7bf6a20fcd2772da555aab55c0d14fe1745f0d4f1c97bca00f825a9e.png)

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-dbd654db833e9faf8359057fd8d845cb6b8d6bedc2992651d02342de92487d75.png)

Project 273- Management: [Full_Project_Report-CCAFS-P273-20170106-0749.pdf](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Full_Project_Report-CCAFS-P273-20170106-0749-77d83a884a1daa92e47b9ca585fc91892cf0e98e14c4a4182f7840d9170b4214.pdf)

Project 269 - Research: [Full_Project_Report-CCAFS-P269-20170106-0751.pdf](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Full_Project_Report-CCAFS-P269-20170106-0751-74dbae97d498dc0e410607cffd6bbcfcce53f7c20d80fd394d9d4763cf06d03f.pdf)
