### ISSUE TITLE
Document Rules -  Other contributions

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#79]

**Comment by htobon** [comment]
-1
Nobody worked on this task.

**Comment by htobon** [comment]
@cgarcia9106, @HermesJim, @sebas932 
Guys, please do not forget to work on this task.
Cheers.

**Comment by HermesJim** [comment]
I add the system login Rules in MARLO Rules - Impact Pathway document

**Comment by htobon** [comment]
Which document?

**Comment by htobon** [comment]
May someone response my question above?

**Comment by HermesJim** [comment]
in this document

https://docs.google.com/document/d/1kWxH5nffBDu3haUAWYrPw5Mpd2hJ6H1oPVGQzb8v-eM/edit#

**Comment by htobon** [comment]
-1
Still more work to do on this task

**Comment by htobon** [comment]
This is something to work with the backend student.
