### ISSUE TITLE
Funding Source - Lead Partner message

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#800]
See image below:
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-88c2b2485818e058ee29b10e97f19e6d8282b700cf92405549a159d0b38ac488.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-dc9713fbd86b80089fcd545406ac98b6dd375839f44066715ea90127c3f2b011.png)
