### ISSUE TITLE
Update user manual

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#818]
Please update the user manual for the following attached file.

[MARLO_UserManual_20170111_AV_HT_AW.pdf](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/MARLO_UserManual_20170111_AV_HT_AW-c19c8401e2248a07392e264c08c938d8e1dd417a6fa1cf9cf523c5fe32bcbaea.pdf)

**Comment by AndresFVR** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-b1b8455005419a0cc8d70450f1762fdeaf8c05ec23cde743e38580a673f3b9ca.png)

[MARLO_UserManual_V1.1.pdf](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/MARLO_UserManual_V1.1-d3210e3e368a4157b51d5ca8fcaa54ef3358c33c02988d219c0a0df8ba9859ae.pdf)
