### ISSUE TITLE
Please hide the Next Users section for A4NH

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#819]
Please also be sure the following is working:
- PDF generated
- Validation for missing fields
- Submission

**Comment by sebas932** [comment]
It was applied in the interface, still pending backend validations and PDF Report

**Comment by AndresFVR** [comment]
Applied on PDF Report

![image](https://cloud.githubusercontent.com/assets/5505233/21994426/9f992e1e-dbed-11e6-83b1-76e12b60ee86.png)

**Comment by sebas932** [comment]
Done

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-9b547fffac0d10d4799b067312ef6c342d5714c23ef292457973d4a1545b74ad.png)
