### ISSUE TITLE
CCAFS Outcomes - expected value visualization

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#823]
If the value is an integer, please display it without decimals.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-a847091a38ccf01a77c0c838dff92ea10263784261dc4bc5c96893dc3206c814.png)

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-96334b2b080d8047f8cf7456e8099bb5a5a8e99e4fd8b7fc9ef0515dfdd976b9.png)
