### ISSUE TITLE
Partner visualization

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#824]
There is a null in a partner:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-766574e64cc9c7626f7f47fcd9f7930f0f1a97a5700d5e470f34eeef668f1733.png)

**Comment by AndresFVR** [comment]
Solved ![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-d419bf9ca9014398a72047c12ef10ebed70faf4daf769658d93db5a693d54c1b.png)
