### ISSUE TITLE
Interface issue in project by partners

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#825]
There is an issue when adding a new user as contact person in budget by partners.
Please refer to the screesnhot below:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-fe05b75b3a0596844daa43a76d1b7263eeca3bc295fcfa8b18b00490608b7821.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-008bde03bfab2ba6c9118d9b9012493716fa2b7a94ee992f78902356f77fc477.png)
