### ISSUE TITLE
Create budgetByCoAsSummary report xls

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#826]

**Comment by AndresFVR** [comment]
@htobon I finished the budgetByCoAsSummary xls report 

[BudgetSummaryByCoAs_20170113-1558.xlsx](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/BudgetSummaryByCoAs_20170113-1558-5dc3c73749edbac6bc95039b1ea0e8e3ec033362ff059d107c3e5b88c34911d8.xlsx)

**Comment by htobon** [comment]
Thank you @AndresFVR, may you pelase come to my office to discuss how we can improve it?

**Comment by AndresFVR** [comment]
@htobon I made few changes on the report

[BudgetSummaryByCoAs_20170119-1004.xlsx](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/BudgetSummaryByCoAs_20170119-1004-0db2942806c45a6fe5b3edc6b7725ac323e3f4627cc9708830a19b71e4af3896.xlsx)

**Comment by AndresFVR** [comment]
@htobon New changes made on the report

[BudgetSummaryByCoAs_20170123-1046.xlsx](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/BudgetSummaryByCoAs_20170123-1046-e81552c4f8e87e50a43d0a71886426c651678c677b7a482aa4328aad6e0c68e7.xlsx)
