### ISSUE TITLE
Set up view user permission to new nomenclature.

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#83]

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-25d95859d6cb151c81f54f711409b69f2b04e26921ddd4dfdd50f5167330d82c.png)

when says project_id: it would be the project id

**Comment by cgarcia9106** [comment]
when project_id would be the project_id

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-9a31c5293a3dfd3521f8c1e7d16af1015f1437e404946d4f578315e861622216.png)

**Comment by htobon** [comment]
**CCAFS** is bad spelled. Please pay attention on these details.

**Comment by cgarcia9106** [comment]
ok

**Comment by htobon** [comment]
May you please attach the new screenshot as prove of the fix? Thank you in advance.
