### ISSUE TITLE
Implement CRP Closed cycle.

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#831]

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-ff51cba29ffdde7e4fe6211b2c875bc55194742cee403439f62d323e62b742d3.png)

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-e0f5fbdc1f7fbe58fa7e6fa0b579701ddbbbcaf1be923a09ea4e8a4a4677f998.png)
