### ISSUE TITLE
 Pentaho not support unicode UTF8

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#834]

**Comment by AndresFVR** [comment]
@HermesJim  will add to the server's installation manual the addition of fonts.

**Comment by AndresFVR** [comment]
To solve this issue is needed to install the following fonts to the server:
- Segoe UI
- Verdana

**Comment by htobon** [comment]
Is there any advance on this? @AndresFVR

**Comment by AndresFVR** [comment]
@HermesJim and I had made some test and we installed successfully the fonts in marlodev because the font folder existed in java. Nevertheless in Production the folder did not exist, we are searching for solution in the production environment.

**Comment by AndresFVR** [comment]
@HermesJim copied the fonts files to usr/share/fonts and then rebooted tomcat.
@htobon Because the problem is solved, I will close this issue.
