### ISSUE TITLE
Add test users access to MARLO Reporting Testing Environment 

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#842]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-d71307cb1f50b44d79bd5d7beb2aabd4db3b06e15abed14f1f00204b9784bb76.png)

**Comment by HermesJim** [comment]
Users Add and activate to enter MARLO DEV - Reporting.
http://marlodev.ciat.cgiar.org/reporting/
