### ISSUE TITLE
Key outputs are required in the impact pathway

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#849]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-6127485c5ee5d1c0bd9b5679465a8e162dea61214fc4b2ee6d2786984236947b.png)

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-1ddf2f57d608d457ff8c69cf31e08a9b2f572f755c0ccbecf67b63c4fbca046f.png)
