### ISSUE TITLE
Hide message when Impact Pathway is submitted

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#850]
Please hide the message pointed in the screenshot when the impact pathway is submitted.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-b052561e9f15290e796a1ad138af79b1eedaea279832976ab158a31aaf10fc89.png)

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-bd32e2ef0d882b3cc1e66ab039403aa50f0a467fb7a175cabebf674573a4bead.png)
