### ISSUE TITLE
Check duplicates in users table

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#851]
Please check for duplicates in the users table.

>Pascale: in the database of people there appears to be duplicates. For instance Mark Lundy is there with two different emails: mlundy@cgiar.org, and m.lundy @cgiar.org. Can we correct this and check for duplicates?

**Comment by AndresFVR** [comment]
Lista de usuarios duplicados que están activos:
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-88ef25d3433cca28945c3bcdf89cca741cf1ce7462ed32c908746aae9c08c880.png)

Lista completa con usuarios activos e inactivos:
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-5b0e3d890eb791eeeb16ad4e9ecd4d273be998dcc6b00207741bd279c0f97c95.png)

**Comment by AndresFVR** [comment]
Se buscó cada uno de los correos la lista de direcciones global:
•	Catacutan: D.C.Catacutan@cgiar.org
•	Girvetz: e.girvetz@cgiar.org 
•	Lundy: m.lundy@cgiar.org
 
Debido a que los correos encontrados son los últimos en entrar a la plataforma, se decide desactivar los siguientes usuarios: 385, 417, 532.

Se verificó los registros actuales del usuario a desactivar y se modificó el ID por el actual donde fuera necesario.
Usuario 385:
•	Modificado user_id a 172 en project_partner_persons.
•	Desactivado crp_users con user_id 385.

Usuario 417:
•	Desactivado crp_users con user_id 417.

Usuario 532:
•	Desactivado crp_users con user_id 532.
