### ISSUE TITLE
Order ahphabetically the PPA Partners in CRP-Admin section

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#852]
Please order alphabetically the list of PPA Partners:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-764f9a57d5a7bba7d2d7818a1c2774c91a6d1f7ed6e1de96d32b4898c15a00a7.png)

**Comment by HermesJim** [comment]
![image](https://cloud.githubusercontent.com/assets/13221179/22212314/37fe0d58-e15e-11e6-9af4-eaf2aa0ee17c.png)
