### ISSUE TITLE
WIKI - Document process for reporting in Pentaho

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#853]
This is technical documentation on how Pentaho is being used to generate summary reports, so others developer can understand and learn how to use it in MARLO.

**Comment by htobon** [comment]
@AndresFVR made a couple of videos that are currently storaged in our Sharepoint:
CCAFS-KDS - Documents\MARLO\2_Technical\2_2_Documentation\2_2_1_Manuals\Pentaho report videos

**Comment by MargaritaRamirez** [comment]
We move this file to D:\CGIAR\CCAFS-KDS - Documents\1_Projects\1_3_MARLO for the OnBoarding technical documentation. 
We will close the issue
