### ISSUE TITLE
To be able to generate a report that shows all funding sources throughout the planning process 

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#857]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-00373ef13593faaa5bd483c2edaf6f0217fab405724d008f831efd9ed676fb0c.png)

**Comment by AndresFVR** [comment]
@htobon I finished the funding sources report, you can find it below

[Funding_Sources_20170125-0846.xlsx](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Funding_Sources_20170125-0846-9ff090f37ff989f465b8d9f370d7cdf367a1ae827a753f67e62fdc5e2e4e0459.xlsx)

**Comment by AndresFVR** [comment]
@htobon I modified the report according to our conversation

A4NH: [Funding_Sources_20170125-1105.xlsx](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Funding_Sources_20170125-1105-fe4b0f5445c6b35e7de05b3ed6a773afcb806a24fcee80361d9303537c4e6dde.xlsx)

**Comment by AndresFVR** [comment]
[Funding_Sources_20170201-1139.xlsx](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Funding_Sources_20170201-1139-0e27d76f9363c4498cdf96bd53149a753523ac68b4902fc9113516716056ffb9.xlsx)

**Comment by AndresFVR** [comment]
[Funding_Sources_20170201-1602.xlsx](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Funding_Sources_20170201-1602-b89951924beeae0582f46f4d595952cc6a6059d03dff01af4e8ba198bc6f13dc.xlsx)
