### ISSUE TITLE
Add Jane Lee as CIAT Contact Point in marlodev environments

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#862]
`Sebas, me confirmas por favor que JaneLee tiene también acceso? Si no es así, serías tan amable de asignárselos como Contact Point de CIAT?
Gracias.`

- [x] MARLO Dev Database  
- [x] MARLO Dev Reporting Database

**Comment by HermesJim** [comment]
Done, the test users are available in the both test platforms.
