### ISSUE TITLE
Priority Issues [January, 24, 2017]

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#863]
- [x]  (COMMUNICATED) MARLO Dev reporting enviroment has some issues (some projects show that marlo is closed)
- [x]  (COMMUNICATED) Add Jane Lee as A CIAT Contact Point en MARLO-CRP Reporting
- [x]  (COMMUNICATED) Amanda email requirements 
- [x]  (COMMUNICATED) Reply Reiner Wassmann message from tawkto
- [x]  Merge Funding sources ([MARLO-CCAFS] Status of Project P325)
- [x] (COMMUNICATED) Issue in activities section, project 2 with Peter ()
- [x] (COMMUNICATED) Hermes:  Email Ou Lin - Remove roles from a couple of People in MARLO.
- [x] (COMMUNICATED) Usuarios David y Emma en MARLO-WLE
- [x] Hermes: Target units must be displayed per CRP in the Impact Pathway section.
- [x] (COMMUNICATED) Christian: Access problem for "Phillips, Michael (WorldFish)"
- [x] Problema con librería de Autenticación LDAP
- [x] (COMMUNICATED) Problema de actividades con Peter Laderach
- [x] Julian Rivera: Listado de proyectos que van en reporting 2016.
- [x] Impact Pathway changes - Alison Rose - Flagship 4
- [x] (COMMUNICATED) Hermes: Mariana Rufino and new account.
- [x] Christian: Change F151 from Bilateral to W3.

**Comment by cgarcia9106** [comment]
Reiner Wassmann connect to taw and i explain 
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-003b58526e1d3263c5583529e20ed7d25abf93d4bbaf0a334431c39eed91390c.png)

**Comment by cgarcia9106** [comment]
MARLO Dev reporting enviroment has some issues (some projects show that marlo is closed)
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-d8c4455776d9069be92453fade08a67c9415f30a3ac24831c8695e05f9f809a6.png)

**Comment by cgarcia9106** [comment]
Issue in activities section, project 2 with Peter ()

Respondi a peter pidiendole que por favor intente de nuevo , se encontro un problema en activites se soluciono y se le restauraron las actividades
