### ISSUE TITLE
Front-end calculate gold data (Only data products)

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#864]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-2a9234a152e17b302f4f745cfc322d103c2d88415cabdd1e331b2f962360605b.png)

   			Yes, but not documented	Yes, and documented	No
quality assurance		25			50		5
data dictionary			25			50		5
tools - data collection		25			50		5

Green (105 - 150)
Yellow (75 - 104)
Red (15 - 74)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-c697b155b32d7e4a9c2625833c214e77f5671f11de1c26795574bb3a77d88a2a.png)
