### ISSUE TITLE
Show "budget by partners" in reporting cycle no able for editing

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#871]

**Comment by sebas932** [comment]
@cgarcia9106 is still pending change in the interceptor

**Comment by htobon** [comment]
Any advance on this? Today is Feb 6 and reporting finishes the 17th!

**Comment by sebas932** [comment]
Done
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-78a8d80e224bd397012ecc40eaf19c891515831e251aed574a05e1fb6c9651bc.png)
