### ISSUE TITLE
Just display the acronym on Funding Sources section

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#877]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-8ed035d6a400c96dadd82fddae6e818189a8a9ed3dbae19c09f67c7fc17dbd9c.png)

**Comment by AndresFVR** [comment]
![image](https://cloud.githubusercontent.com/assets/5505233/22424640/61cf9c0c-e6c5-11e6-8214-748b3fc4edc3.png)

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-afc5e7cf318b393ddc2a47a3948f363bb5f6d1445e086d9114f8cc2f33fd92be.png)
