### ISSUE TITLE
"Compliance check" is only for "data" products

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#879]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-ad4a98fb02cdda6ef42c8ba801d965289cd4e5d8e58008babc3be5a7b36353ac.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-4cff9b8d418a9f0f95be62a758a173b01c179700f6b168af92610c3bf3104ed5.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-284b7fe663f67ac32e5afcd5be25ea99799571bb2d1f90d3f63d9a4073c313c6.png)
