### ISSUE TITLE
Create file directory structure

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#9]

**Comment by htobon** [comment]
@cgarcia9106 May you please include an screenshot of the package structure?

**Comment by cgarcia9106** [comment]
![file structure.PNG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/file%20structure-2bf0c6e65106fb7c92d6746a9ea2197f1a1761bb19c601943be6b8a8c7c315e1.PNG)

**Comment by htobon** [comment]
It seems to me that the project was initialized using java 7. But we decided to use Java 8.
May you please confirm we are using JAVA 8.... and... May you please setup the project so anyone who import it is required to use JavaSE-1.8?
