### ISSUE TITLE
Change "Management Liaison" to "Flagship Leader" for A4NH

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#901]
Not so keen on this "Management Liason" term - why not Flagship Leader? (Also correct spelling of Coordinating Unit)

What do others think?
  HT: A management liaison can be a Regional Program Leader, Flagship Leader or someone from the PMU.
  Pascale: I find the current wording, ie "Management Liaison" (with flagships, PMU, and center in the drop down menu") and "Management liaison contact person" very confusing. I suggest to replace the "Management liaison" field by "Flagship", and the "Management liaison contact person" by "Contact person".
 Pascale Nov 17:let's include this in the User profile discussion.

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-f23c07164b56a53cbb1520b90c365c43f03d78ef3f9a80b83bdd6ee17736e303.png)

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-204424a37627a2855a91d84f9a9cc9fff18a7b079f3ad27736288d3ab5d60e50.png)

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-8ff13ff3e31a614cb051e8d38ef94e00dde9944326e4d0500587a9f990e58143.png)
