### ISSUE TITLE
Pop up window "request new institution or branch" changes

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#904]
Pop up window "request new institution or branch":  
-[ ]   suggest "request creation of new institution" as title; 
-[ ]   found this indication "Please enter the institution as “Partner,” the legal entity. " confusing, suggest removing (especially if we are allowing branches; 
-[ ]   suggest replacing term branch by "national/regional office or branch of an institution"; 

-[ ]   in type, suggest removing Challenge Program and End User and adding "Private sector non research firm" and "Producers' organization", + Donor should be singular (no s); 
-[ ]   nothing happened when I clicked "request add new partner"

**Comment by htobon** [comment]
New Feedback:

Pop up window "request new institution or branch": 
- [ ] suggest "request creation of new institution" as title; 
- [ ] suggest replacing term branch by "national/regional office or branch of an institution"; 
- [ ] please alphabetize countries (it took me forever to find United states, it did not find it even when typing United);
- [ ] **implement changes in types decided by the MARLO family.**

**Comment by carios1usb** [comment]
close #985

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-057a721c175ca17a6c8a05c979e2b4408901fdacd1b12dbf6ff958be4162b038.png)

**Comment by cgarcia9106** [comment]
@htobon  may you please follow up with @HermesJim
