### ISSUE TITLE
Funding source, budget is rounded

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#916]
In the Funding Source entry, the budget automatically rounds to the closest whole dollar when there are "cents" in the amount. Maybe we don't need an option to enter cents then?

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-ff652c7db4cf63338d4c78e4bae7f8de988ebdd3186ca620e071352c87f56f13.png)

**After save** 
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-53918a0fdfd4991dbc9ca7967830cf4dff1bd5307d4c11e1334e58f2f1158c9a.png)

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-b41e05a8fb2f028a5e6036f47da39f958fea4ab0a4949304a554abbcf02520c2.png)
