### ISSUE TITLE
Add Guest user (MARLO super admin)

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#918]

**Comment by HermesJim** [comment]
We working  ( @carios1usb  and me ) in the implementation and the interface of the user management.

this is a 1st version of the section.

![image](https://cloud.githubusercontent.com/assets/13221179/23232367/f79f9e48-f918-11e6-8e20-02e57ee2cfe7.png)

**Comment by sebas932** [comment]
Follow this issue in #971
