### ISSUE TITLE
Disable institution # 133: CGIAR Research Program on Climate Change, Agriculture and Food Security / CCAFS/CRP7

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#926]

**Comment by AndresFVR** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-70d4e863fe1d2341bb553c84633c0a583f704a041fa4cbbe7b91c15c582cc751.png)

**Comment by AndresFVR** [comment]
![Pasted image at 2017_02_22 04_14 PM.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Pasted%20image%20at%202017_02_22%2004_14%20PM-0c043df0ef0b7753722ea74051bbc3b9f8c996e968d4537caa815025fe2cd722.png)

![Pasted image at 2017_02_22 04_20 PM.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Pasted%20image%20at%202017_02_22%2004_20%20PM-cee95c351cb2236054415914ec214162bdc85260ca091e7097eb0028b959acdc.png)

![Pasted image at 2017_02_22 04_24 PM.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Pasted%20image%20at%202017_02_22%2004_24%20PM-0412527e9db023f8b54dc60888aee24cb8ed2e4f88718fd99ea2e1ced501f5a5.png)

**Comment by AndresFVR** [comment]
@htobon The above are the records found for institution 133. What should I do?

**Comment by sebas932** [comment]
@sebas932 please create a report for each project that explain the implications of removing this institution

**Comment by AndresFVR** [comment]
The records of this institutions were moved to CIAT. You can find below the records that were affected.

Relations:
Project Partners: CCAFS-P45, CCAFS-P115, CCAFS-P114, CCAFS-P100
Deliverable leaders: Publication 3020
Project partner locations: CCAFS-P45, CCAFS-P115, CCAFS-P114, CCAFS-P100
Funding sources direct donor: Livestock-FS828
