### ISSUE TITLE
Mejoras en los reportes por solicitud de A4NH

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#931]
Por favor realizar las siguientes mejoras en los reportes que tenemos actualmente en summaries para más tardar el jueves 2 de Marzo.
Como es bastante, sería bueno si alguno de los chicos te puede ayudar con algunos puntos.

1.	Budget Summary by Partners:
a.	Renombrar la columna C a “Managing / PPA Partner”
b.	Incluir una columna después de Flagship(s) que se llame “CoA(s)” y listas todos los Cluster of Activities que están aportando al proyecto (sólo los acrónimos).
c.	Incluir una columna después de Region(s) que se llame “Total Project Budget (USD)” y que calcule el total de presupuesto de dicho proyecto contando todas las ventanas de financiación.
d.	Por favor ocultar la columna “Region(s)” para todos aquellos CRPs que configuraron en la sección “CRP Admin” que no tienen Programas Regionales.
2.	Funding Source Summary – Hoja #2 “Funding Sources Projects”:
a.	Renombrar la columna Lead Partner por Managing / PPA Partner (por favor lo mismo en la primera hoja)
b.	Incluir una columna después de “Projet ID” que se llame “Flagship(s)” y listas todos los Flagships a los que el pryecto contribuye (sólo los acrónimos).
c.	Incluir una columna después de “Flagship(s)” que se llame “CoA(s)” y listas todos los Cluster of Activities que están aportando al proyecto (sólo los acrónimos).
3.	Expected deliverables:
a.	Reemplazar MOG por CoA en la descripción del reporte – ver screenshot
b.	Incluir una columna después de Flagship(s) que se llame “CoA(s)” y listas todos los Cluster of Activities que están aportando al proyecto (sólo los acrónimos).
c.	Por favor ocultar la columna “Region(s)” para todos aquellos CRPs que configuraron en la sección “CRP Admin” que no tienen Programas Regionales.
d.	Incluir una columna antes de “Deliverable title” con el ID del deliverable “Deliverable ID” (ejemplo: D1234)
e.	Agrega un enlace al deliverable en el ID y quítalo en el título.
f.	Incluir una columna después de Status que se llame “Managing / PPA Partner(s) Responsible” que debe contener el/los PPA Partners responsables del deliverable. Por ejemplo, si el responsable es la institución IUCN, entonces se debe listar quién la trajo al proyecto (ver screenshot 1 - ver screenshot 2) 
g.	En las columna “Partner responsible” y “Other responsibles”, por favor listar primero el acrónimo de la institución y después el nombre del contacto.

**Comment by AndresFVR** [comment]
1. Budget Summary by Partners:

A4NH:
[A4NH_BudgetPerPartnersSummary-20170301-1117.xlsx](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/A4NH_BudgetPerPartnersSummary-20170301-1117-bddeb58076e44095fe490177c3f2488e5ebaa29fc548895bfa2319fe3de7c638.xlsx)

CCAFS:[CCAFS_BudgetPerPartnersSummary-20170301-1114 (1).xlsx](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/CCAFS_BudgetPerPartnersSummary-20170301-1114%20%281%29-50df08e001c24cfeac3f69129e14888b19aaffe0a6fbab1b0f28727965d4dee2.xlsx)

**Comment by AndresFVR** [comment]
2. Funding Source Summary
[Funding_Sources_20170301-1150.xlsx](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Funding_Sources_20170301-1150-f0f5240c9cfc41a8436fbb468828e395ff1062af8faa499e623a3481721a3ac8.xlsx)

**Comment by AndresFVR** [comment]
3. Expected deliverables
 
A4NH:[Expected-deliverables-20170301-1541.xlsx](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Expected-deliverables-20170301-1541-e039875cb69ed7f65d7006bea2d9f083495ebf6916e0f44495321155a8d70480.xlsx)



CCAFS:[Expected-deliverables-20170301-1542.xlsx](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Expected-deliverables-20170301-1542-ab09c9882e9f28906e28aaf7d2f3b86804344f343324e6a132915a743fc42598.xlsx)

**Comment by htobon** [comment]
falta 3a.

**Comment by AndresFVR** [comment]
@carios1usb will do so because it is in the interface.

**Comment by carios1usb** [comment]
Done!
