### ISSUE TITLE
Revamp project locations

### ISSUE THREAD

**Issue by carios1usb** [CCAFS/MARLO#932]

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-1ea58f1089fac2a8bcb7289113f53863bc2c32296d83b489528f602197ad0b0f.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-a3d3aa642d5a7c5da63674eab086b50fdfe8a91d48618ec7b7c2f16e04b7eecc.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-b21740613e752f39ffd7b059636951470c18b5c0cbad08584ec8f7b9630f2653.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-6c4357bf6e0d482b6968b9684b513a7b94efe4e2b049def18eeb300d6cffbebb.png)

**Comment by carios1usb** [comment]
@htobon I added "add a new location" button on the map

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-0670004ca91f5ff5949c005f9cf6853be0280c316db49a8bfa759d228df55c84.png)

**Comment by carios1usb** [comment]
@HermesJim is going to check the autosave

**Comment by htobon** [comment]
@sebas932  and @carios1usb, We received a feed back from Amanda. Therefore, there are still more improvements to do on this section. Please work on them first before moving this issue to be reviewed again.

**Comment by carios1usb** [comment]
Hi @htobon , I Made the corrections that Amanda suggested. There is left pending the comments on regions and all the mapping in funding sources

**Comment by carios1usb** [comment]
You can test the interface from my local server.

**Comment by sebas932** [comment]
Follow up in #1009
