### ISSUE TITLE
Custom IDs to Projects, deliverables & activities

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#936]

**Comment by sebas932** [comment]
Issue Statement here 
https://docs.google.com/document/d/1dHcDkL1Lx7KB-dk_105hwfSZGeQHTunEin-9uuInWkU/edit

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-d6e0606a1dc3b93219a363c599c8e9ce86486fde1ea5b57292d9a50c2ca62c06.png)

**Comment by cgarcia9106** [comment]
Only por projects now it's working

**Comment by htobon** [comment]
Let's park this issue for the next release. @sebas932, may you please help on this?

**Comment by htobon** [comment]
Closing this issue. Not a priority now.
