### ISSUE TITLE
DEMO -Show history changes on ftl

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#939]
- [x] Description 
- [x] Partners

**Comment by sebas932** [comment]
Working on history showing changes
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-864945698b49f11585b38541a355463e2fd4f7fbbb3261bc79cbd609bd5eae70.png)

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-2055c9cc050ae79068b3c48b608362b486e005c11493a67d3e5bb1fc461788c0.png)

**Comment by sebas932** [comment]
Improved history changes visualization 

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-6b476e98727b55f990e1df6e34a7663de369d1a59951cd6f227952478fa6466d.png)

**Comment by htobon** [comment]
This is very cool! Hope you may finish it soon. :+1:
