### ISSUE TITLE
The fields Management Liaison and Management Liaison Contact Person have been replaced by Flagship and Flagship Leader 

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#945]
We agreed in Amsterdam not to use the term Management Liaison for CRPs other than CCAFS. Indeed, in the A4NH platform, the fields Management Liaison and Management Liaison Contact Person have been replaced by Flagship and Flagship Leader respectively. This is not the case for the PIM platform. Please update this.

**Comment by sebas932** [comment]
For PIM
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-0b7ab02fdf48fdb8a70779c06d144f0d757dc6bb609fe9ff0f5a8676a411112a.png)
