### ISSUE TITLE
Send information about the automated emails that MARLO has

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#947]
Please send us information about the automated emails that MARLO will send for PIM based on the roles and responsibilities described in the User profiles spreadsheet: list of emails (sent to whom when) and contents of the emails.

**Comment by AndresFVR** [comment]
Emails generated for PIM are listed in the following document: [MARLO-PI M_AutomaticEmails.docx](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/MARLO-PI%20M_AutomaticEmails-fe3e0b4b7aaddc23f738a5a525e0f9e3d61197bbdbaa0d0906c57cd1efcc373c.docx)
