### ISSUE TITLE
Add Permisons to PMU : The PMU can correct/adjust/update information on a continuous basis

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#948]
You mentioned recently that MARLO will not stay open for planning on a continuous basis. It seems to me that if we want MARLO to reflect up to date information we need it to stay open for the PMU to correct/adjust/update information on a continuous basis. 
For instance, to add new funding sources (either newly funded bilateral/W3 grants or additional W1-2 allocations decided at mid-year); correct mistakes, etc. From the Feedback spreadsheet it seems that this concern may be shared by WLE.

**Comment by htobon** [comment]
I do not understand this issue. Please be more explicit.
