### ISSUE TITLE
Modify CRP Parameter Structure

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#949]

**Comment by htobon** [comment]
After looking at the database implementation, we (@sebas932 and @htobon) figured out that the current architecture is not adequate to solve what we would like to accomplish. Therefore, it has to be improved and we propose the following architecture:

![20170502_084513.jpg](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/20170502_084513-8728df8397246e33b5349dbea37c78ebc800a92a17763db86ad450e963754206.jpg)

**Comment by htobon** [comment]
@cgarcia9106, please implement what we are suggesting or please feel free to propose a new architecture.

**Comment by cgarcia9106** [comment]
custom_parameter 
Should have the column of crp_id and not the crp_parameter

Something like this:
![capture](https://cloud.githubusercontent.com/assets/14946768/25620972/a5f6ac66-2f15-11e7-98f4-b5d34b23c854.JPG)

**Comment by cgarcia9106** [comment]
Ignore data types

**Comment by htobon** [comment]
I don't agree. can we discuss in my office? thank you. @sebas932 please join us.

**Comment by htobon** [comment]
After a further discussion, we (@cgarcia9106, @sebas932 and me)  decided to implement the first proposal.

The table "custom_parameters" will be named as "parameters".
The field "custom_parameters.name" will be named as "parameters.key"

**Comment by sebas932** [comment]
We have been working on the parameters structure
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-b32ecf3ff7fb37860798ad49467d8f1a3bf4e12184fbbbaab6fb1a9299fc4562.png)
