### ISSUE TITLE
Timeline information per CRP

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#958]
All CRPs have their own dates for report process.

**Comment by htobon** [comment]
Moving this issue to our next sprint. We need to have this in MARLO before we open it for Project Leaders.

**Comment by htobon** [comment]
Hi @mralmanzar. No, the issue #1019 is different from this one.
Schedules are happening internally with each CRP mostly via email, therefore, we decided to close this issue and not develop this functionality.
