### ISSUE TITLE
Harvest metadata from ILRI Datasets repository

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#960]
Info: http://data.ilri.org/portal/harvestinfo

**Comment by sebas932** [comment]
Implemented ILRI Datasets repository

**Pending:**
 Implement (Is Open Access, Licence)
 Missing from API metadata (Language, handle or DOI, authors ORCID)


![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-07513db1a42105224d1b70aebf054edc151d076928e60779210705c88599c21e.png)

**Comment by htobon** [comment]
@sebas932, can we close this issue?
