### ISSUE TITLE
 Other sections Compare History

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#973]

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-1ad50bdbd4ad24667ae8e1de4e8d24e4976ec606a14ab70306ec7e2041278ebc.png)

**Comment by cgarcia9106** [comment]
Project Outcome P&R

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-3751eb11c0b9885eb89c0aad3d4a2f9f90f8ae8e38b6d8dc3c58d143cdecbb83.png)
Other Contributions

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-6a0387818dcbd16c51d2c7f4617d35cc46eb03d22bbc33d84ef2db4290589a5b.png)
Overview by mogs?

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-c1a54cbd8ef48a57370683e3d1be5de6751c8d85bba2d0d0230a8ddbd6321ee8.png)

Project Activites

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-343b2de20a052a1f3b1ee44ffda4c0d7b39deb1efd408ac1af37ae64d8a250d2.png)
 Leverages

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-8d2153796f588b9505fa4cb81dfea7d51f1bf345bf3276f82ef54054a33e0907.png)

Funding Source

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-13a95b22337be1209f49c120d8b6c62a112b030877d45a3bec6a738e4eaee8df.png)

Impact pahtway outcomes

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-b9a9ae172839bb4d340c0c4f534ff8aa25a562b8575a5d8d583abc63457ba3a2.png)

Cluster of activites

**Comment by cgarcia9106** [comment]
@sebas932 help me

**Comment by sebas932** [comment]
I will check in issue #1028
