### ISSUE TITLE
Annual monitoring partners

### ISSUE THREAD

**Issue by carios1usb** [CCAFS/MARLO#974]

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-78a74412f31f749a0ecc6310c25c98433bad1b66cb0c5a2e7d0bf0835767b713.png)

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-e288af4a88d61932f0bd9d502ed9c145b39d8dfd27606dd30891d6c755c78131.png)

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-77963192660a0e3b1adebdedc3edd7011e84be02b91923e53cd3f8865e46cf19.png)

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-01fafd4f2dded0502d665199f6ce9f9e08e1358e44fbbbbdcef5359e1619a9c9.png)
