### ISSUE TITLE
Sync button - deliverable section

### ISSUE THREAD

**Issue by carios1usb** [CCAFS/MARLO#975]

**Comment by sebas932** [comment]
Working on Deliverable Sync function, its only works with the 9 metadata fields of input text an text area types.

@cgarcia9106, @HermesJim  please help me adding the following to be saved into the database:
DeliverableDissemination =>  private Boolean synced;
DeliverableMetadataElement => private Boolean hide;

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-e7ae5472b7137d9525a3ee857334c91b6331e8217861deb76850756b97e88797.png)

**Comment by sebas932** [comment]
Functionality is completed, still pending to be approved.

![Animation.gif](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Animation-0211b17368c832ec2dd751c4eb7ef066a531e82d38dc2702b6cac4f5ee76f041.gif)

**Comment by sebas932** [comment]
Added Authors to Sync function
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-23b463e931aa2362f4eb082c3c5c2e005032b4f64d6d7b15267e768db25b09da.png)
