### ISSUE TITLE
Improve partner request (System admin)

### ISSUE THREAD

**Issue by carios1usb** [CCAFS/MARLO#979]
- [x] Send email when a partner is added or rejected. 
- [x] Add Funding Source ID to email when is requested from FS 
- [x] Add rejected justification pop up

**Comment by AndresFVR** [comment]
@sebas932 will add a pop up when a request is rejected.

**Comment by AndresFVR** [comment]
Accepted partner email: 
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-14e31e5ed42e8aee0919f3a6b4eea6171d60fdb36c700aeed1aaaf09bf503945.png)
 Rejected partner email: ![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-f51722261782d6901d4989efab6f2c853431affb40cac1690a80aeea5a2ffe16.png)

**Comment by sebas932** [comment]
Improved Partners request interface

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-d741c4f1436e71d83f5f6e9da736af6721413784c4172242188d3caab9d74889.png)

**Comment by sebas932** [comment]
@cgarcia9106  and @sebas932 have been working in a similarity function for catching similar institutions already added in MARLO

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-5d7102b98988f5dee435dd7471ae60fdb403ea58bfd128bd7b67b9b0abae5e7a.png)

**Comment by sebas932** [comment]
@AndresFVR  and @HermesJim is still pending to develop the service for "Rejecting" a partner request. and figure out how to edit a partner request

**Comment by sebas932** [comment]
@htobon this development is already in MARLO Dev for being checked how it works, please let me know if you have any questions.

**Comment by AndresFVR** [comment]
@sebas932 will add validation in edit action.

**Comment by AndresFVR** [comment]
Rejected message was updated as follows: ![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-bd6ec866da3e5cf0a27c98fb4d924832b8b52c3745f197e3dad8514d913add98.png)
