### ISSUE TITLE
Improve the MySQL Architecture to allow a better performance.

### ISSUE THREAD

**Issue by carios1usb** [CCAFS/MARLO#980]

**Comment by AndresFVR** [comment]
Set Up Master Slave Replication in MySQL Servers: Replication enables data from one MySQL database server (the master) to be copied to one or more MySQL database servers (the slaves). Replication is asynchronous by default; slaves do not need to be connected permanently to receive updates from the master. Depending on the configuration, you can replicate all databases, selected databases, or even selected tables within a database.

https://dev.mysql.com/doc/refman/5.7/en/replication.html

**Comment by AndresFVR** [comment]
Test on Davinci 

Setting the Replication Master Configuration: 

Edited the my.cnf file within the [mysqld] section and added the following options

[mysqld]
log-bin=mysql-bin
server-id=1

This to enable binary logging using a log file name prefix of mysql-bin

Created a user for Replication:
mysql> CREATE USER 'replication'@'%.davinciubuntu' IDENTIFIED BY 'slavepass';
mysql> GRANT REPLICATION SLAVE ON *.* TO 'replication'@'%.davinciubuntu';

used SHOW MASTER STATUS to determine the current binary log file name and position.

On the master, released the read lock: mysql> UNLOCK TABLES;

On the slave(localhost) edited the my.ini file within the [mysqld] section and added the following options 

[mysqld]
server-id=2

Set up the slave to communicate with the master:

mysql> CHANGE MASTER TO
    ->     MASTER_HOST='master_host_name',
    ->     MASTER_USER='replication_user_name',
    ->     MASTER_PASSWORD='replication_password',
    ->     MASTER_LOG_FILE='recorded_log_file_name',
    ->     MASTER_LOG_POS=recorded_log_position;

Import master database

Start the slave threads: mysql> START SLAVE;

**Comment by AndresFVR** [comment]
![replication.gif](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/replication-185d608672685b7cace9c79830393a06e08ca7e87a71a357820c02fbcdffa560.gif)

**Comment by AndresFVR** [comment]
MASTER/SLAVE COMMANDS:

- The master creates a thread to send the binary log contents to a slave when the slave connects.
SHOW PROCESSLIST shows you which threads are running.
The SHOW PROCESSLIST statement is very useful if you get the “too many connections” error message and want to find out what is going on. 
 
 mysql> SHOW FULL PROCESSLIST\G;

- When a START SLAVE statement is issued on a slave server, the slave creates an I/O thread, which connects to the master and asks it to send the updates recorded in its binary logs.
  mysql> START SLAVE;

-This statement provides status information on essential parameters of the slave threads.
  mysql> SHOW SLAVE STATUS;

- Stops the slave threads
 mysql> STOP SLAVE;

- RESET SLAVE makes the slave forget its replication position in the master's binary log. This statement is meant to be used for a clean start: It clears the master info and relay log info repositories, deletes all the relay log files, and starts a new relay log file.
 mysql> RESET SLAVE;


Improving Replication Performance:
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-d6b64fb893096555b060b1f6d3aa33d2957bc20e58d8bd271799fafae4336efd.png)
https://dev.mysql.com/doc/refman/5.7/en/replication-solutions-performance.html

**Comment by mralmanzar** [comment]
This architecture was implemented using a Read Replica Database in AWS.
![image](https://user-images.githubusercontent.com/9383649/104021214-66fc1580-518c-11eb-9106-a7c7f0ce5434.png)
