### ISSUE TITLE
Add search function for countries in Partners request popup

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#985]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-2e8c36451aced37a59fcd10caa68fdc7faaad1f246dc783b2bf79138402c8eb0.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-6725a002cbb18800d12f099195a26fb4e982ea51c9bff7e3a5ee7b530d52d936.png)
