### ISSUE TITLE
Mockup for "Custom scopes/regions" in project locations

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#986]

**Comment by carios1usb** [comment]
I created the mockup , view in this link: 
https://docs.google.com/presentation/d/1Der-IyQbAjnChjpd7Gz83HqkhR8gpoxbncd6GXdpW04/edit#slide=id.g215186652c_0_371

**Comment by htobon** [comment]
I have scheduled a meeting for tomorrow to talk with David and then I will go with Pascale and Amanda.
