### ISSUE TITLE
Add new "W1/w2 Co-Financing" budget type & document others budget types

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#990]

**Comment by sebas932** [comment]
Reference #994

**Comment by sebas932** [comment]
I made a proposal of Budgets by partners 

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-10ec3cf2d24539b6d559a290d402a597c7f83a8eec779556fc1b368d5943b4e3.png)

**Comment by htobon** [comment]
This issue will be tackled in the issue #1010.
If we want to implement the natural classification, let's create a new issue.
