### ISSUE TITLE
Validate list of target units in Impact Pathway, hide if is empty

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#991]

**Comment by sebas932** [comment]
Ask to @AndresFVR for reports implications

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-b04deef4e09bad83ad9860a702d83cbb9fc9202485d7e8e50e8f5c2dd5fae45d.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-5d08bb29cc5023b4c6e0ac87d2c6e24405647784e37c57205f1f67bd10fa3b5c.png)

**Comment by htobon** [comment]
Todavía falta.

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-60a753f0c9473d3e92c1622d6dff91080f5bd1de0964352f31e07ff8561e7e44.png)

**Comment by carios1usb** [comment]
@AndresFVR  lo revisará en el reporte @htobon .

**Comment by htobon** [comment]
Gracias @carios1usb y @AndresFVR .

**Comment by AndresFVR** [comment]
Revisado en los reportes, estas variables se encuentran en:

**Planning PDF**:
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-d74f004b05f62261d1840a614d64061b8ccc926ad7fcd0ffa70e24a652e47ff0.png)

**Impact Pathway Contributions Summary Excel**:
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-275b9db68767ee6266b28c668333bbe738e4dda89772b98f086f30cdafbadcbd.png)
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-a92e90f95f977cbfd0dcb31fd3de40ec31fc37e220088777fc5fb0de26fa8e9a.png)

**Comment by carios1usb** [comment]
@cgarcia9106  is going to check the validators
